from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CHAPTER_20241219_EX = Button(
    area=(17, 446, 34, 461),
    color=(169, 178, 207),
    button=(17, 446, 34, 461),
    file="./assets/cn/campaign/CHAPTER_20241219_EX.png",
)
CHAPTER_20241219_PART1 = Button(
    area=(17, 226, 34, 241),
    color=(162, 169, 196),
    button=(17, 226, 34, 241),
    file="./assets/cn/campaign/CHAPTER_20241219_PART1.png",
)
CHAPTER_20241219_PART2 = Button(
    area=(17, 299, 34, 314),
    color=(168, 176, 204),
    button=(17, 299, 34, 314),
    file="./assets/cn/campaign/CHAPTER_20241219_PART2.png",
)
CHAPTER_20241219_SP = Button(
    area=(17, 372, 34, 388),
    color=(163, 172, 201),
    button=(17, 372, 34, 388),
    file="./assets/cn/campaign/CHAPTER_20241219_SP.png",
)
CHAPTER_NEXT = Button(
    area=(1216, 362, 1232, 388),
    color=(121, 150, 198),
    button=(1216, 362, 1232, 388),
    file="./assets/cn/campaign/CHAPTER_NEXT.png",
)
CHAPTER_PREV = Button(
    area=(42, 360, 58, 387),
    color=(105, 133, 169),
    button=(42, 360, 58, 387),
    file="./assets/cn/campaign/CHAPTER_PREV.png",
)
COMMISSION_NOTICE_AT_CAMPAIGN = Button(
    area=(1077, 637, 1083, 643),
    color=(172, 72, 49),
    button=(1077, 637, 1083, 643),
    file="./assets/cn/campaign/COMMISSION_NOTICE_AT_CAMPAIGN.png",
)
EVENT_20201126_DETAIL = Button(
    area=(617, 470, 659, 510),
    color=(188, 152, 166),
    button=(617, 470, 659, 510),
    file="./assets/cn/campaign/EVENT_20201126_DETAIL.png",
)
EVENT_20201126_DETAIL_CHECK = Button(
    area=(1198, 20, 1244, 65),
    color=(176, 138, 121),
    button=(1198, 20, 1244, 65),
    file="./assets/cn/campaign/EVENT_20201126_DETAIL_CHECK.png",
)
EVENT_20201126_DETAIL_WHITE = Button(
    area=(969, 94, 1030, 156),
    color=(178, 148, 165),
    button=(969, 94, 1030, 156),
    file="./assets/cn/campaign/EVENT_20201126_DETAIL_WHITE.png",
)
EVENT_20201126_ENTRANCE = Button(
    area=(927, 599, 1054, 631),
    color=(255, 255, 255),
    button=(927, 599, 1054, 631),
    file="./assets/cn/campaign/EVENT_20201126_ENTRANCE.png",
)
EVENT_20201126_ENTRANCE_TEMP = Button(
    area=(1022, 375, 1100, 398),
    color=(143, 197, 241),
    button=(1022, 375, 1100, 398),
    file="./assets/cn/campaign/EVENT_20201126_ENTRANCE_TEMP.png",
)
EVENT_20201126_PT_ICON = Button(
    area=(1108, 102, 1133, 127),
    color=(231, 121, 159),
    button=(1108, 102, 1133, 127),
    file="./assets/cn/campaign/EVENT_20201126_PT_ICON.png",
)
EVENT_20221124_ENTRANCE = Button(
    area=(1037, 162, 1077, 195),
    color=(207, 168, 148),
    button=(1037, 162, 1077, 195),
    file="./assets/cn/campaign/EVENT_20221124_ENTRANCE.png",
)
EVENT_20221124_PT_ICON = Button(
    area=(1106, 109, 1135, 130),
    color=(151, 116, 139),
    button=(1106, 109, 1135, 130),
    file="./assets/cn/campaign/EVENT_20221124_PT_ICON.png",
)
EVENT_20230817_STORY = Button(
    area=(610, 320, 670, 380),
    color=(183, 180, 190),
    button=(610, 320, 670, 380),
    file="./assets/cn/campaign/EVENT_20230817_STORY.png",
)
EVENT_20250424_PT_ICON = Button(
    area=(1109, 109, 1133, 131),
    color=(182, 173, 150),
    button=(1109, 109, 1133, 131),
    file="./assets/cn/campaign/EVENT_20250424_PT_ICON.png",
)
EVENT_20250724_PT_ICON = Button(
    area=(1102, 106, 1139, 121),
    color=(95, 103, 93),
    button=(1102, 106, 1139, 121),
    file="./assets/cn/campaign/EVENT_20250724_PT_ICON.png",
)
EVENT_20260417_DETAIL = Button(
    area=(618, 251, 658, 290),
    color=(221, 188, 185),
    button=(618, 251, 658, 290),
    file="./assets/cn/campaign/EVENT_20260417_DETAIL.png",
)
EVENT_20260417_DETAIL_CHECK = Button(
    area=(439, 216, 535, 293),
    color=(187, 160, 173),
    button=(439, 216, 535, 293),
    file="./assets/cn/campaign/EVENT_20260417_DETAIL_CHECK.png",
)
EVENT_20260417_DETAIL_WHITE = Button(
    area=(1081, 92, 1141, 153),
    color=(211, 173, 175),
    button=(1081, 92, 1141, 153),
    file="./assets/cn/campaign/EVENT_20260417_DETAIL_WHITE.png",
)
EVENT_20260417_ENTRANCE = Button(
    area=(957, 522, 1091, 573),
    color=(255, 255, 255),
    button=(957, 522, 1091, 573),
    file="./assets/cn/campaign/EVENT_20260417_ENTRANCE.png",
)
EVENT_20260417_PT_ICON = Button(
    area=(1110, 106, 1133, 130),
    color=(119, 177, 213),
    button=(1110, 106, 1133, 130),
    file="./assets/cn/campaign/EVENT_20260417_PT_ICON.png",
)
OCR_COIN = Button(
    area=(815, 23, 922, 51),
    color=(61, 61, 73),
    button=(815, 23, 922, 51),
    file="./assets/cn/campaign/OCR_COIN.png",
)
OCR_EVENT_PT = Button(
    area=(1196, 109, 1280, 131),
    color=(121, 110, 59),
    button=(1196, 109, 1280, 131),
    file="./assets/cn/campaign/OCR_EVENT_PT.png",
)
OCR_OIL = Button(
    area=(614, 23, 714, 51),
    color=(64, 65, 79),
    button=(614, 23, 714, 51),
    file="./assets/cn/campaign/OCR_OIL.png",
)
OCR_OIL_CHECK = Button(
    area=(573, 30, 592, 49),
    color=(82, 82, 82),
    button=(573, 30, 592, 49),
    file="./assets/cn/campaign/OCR_OIL_CHECK.png",
)
SWITCH_1_HARD = Button(
    area=(82, 641, 148, 675),
    color=(233, 141, 128),
    button=(82, 641, 148, 675),
    file="./assets/cn/campaign/SWITCH_1_HARD.png",
)
SWITCH_1_NORMAL = Button(
    area=(80, 641, 148, 675),
    color=(157, 180, 227),
    button=(80, 641, 148, 675),
    file="./assets/cn/campaign/SWITCH_1_NORMAL.png",
)
SWITCH_20241219_COMBAT = Button(
    area=(39, 659, 71, 691),
    color=(133, 96, 49),
    button=(39, 659, 71, 691),
    file="./assets/cn/campaign/SWITCH_20241219_COMBAT.png",
)
SWITCH_20241219_STORY = Button(
    area=(327, 657, 352, 688),
    color=(105, 77, 31),
    button=(327, 657, 352, 688),
    file="./assets/cn/campaign/SWITCH_20241219_STORY.png",
)
SWITCH_2_EX = Button(
    area=(272, 658, 310, 676),
    color=(253, 168, 98),
    button=(272, 658, 310, 676),
    file="./assets/cn/campaign/SWITCH_2_EX.png",
)
SWITCH_2_HARD = Button(
    area=(246, 641, 311, 675),
    color=(233, 140, 127),
    button=(246, 641, 311, 675),
    file="./assets/cn/campaign/SWITCH_2_HARD.png",
)
TEMPLATE_EVENT_20230817_STORY_E1 = Template(file="./assets/cn/campaign/TEMPLATE_EVENT_20230817_STORY_E1.png")
TEMPLATE_EVENT_20230817_STORY_E2 = Template(file="./assets/cn/campaign/TEMPLATE_EVENT_20230817_STORY_E2.png")
