from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BACK = Button(
    area=(30, 26, 86, 82),
    color=(56, 53, 91),
    button=(30, 26, 86, 82),
    file="./assets/cn/minigame/BACK.png",
)
COIN = Button(
    area=(367, 292, 412, 335),
    color=(199, 209, 228),
    button=(367, 292, 412, 335),
    file="./assets/cn/minigame/COIN.png",
)
COIN_HOLDER = Button(
    area=(1093, 24, 1133, 51),
    color=(72, 69, 61),
    button=(1093, 24, 1133, 51),
    file="./assets/cn/minigame/COIN_HOLDER.png",
)
COIN_POPUP = Button(
    area=(881, 179, 912, 209),
    color=(210, 103, 102),
    button=(881, 179, 912, 209),
    file="./assets/cn/minigame/COIN_POPUP.png",
)
GOTO_CHOOSE_GAME = Button(
    area=(1037, 642, 1084, 678),
    color=(189, 179, 185),
    button=(1178, 592, 1204, 670),
    file="./assets/cn/minigame/GOTO_CHOOSE_GAME.png",
)
MINIGAME_SCROLL_AREA = Button(
    area=(1223, 95, 1230, 655),
    color=(190, 190, 195),
    button=(1223, 95, 1230, 655),
    file="./assets/cn/minigame/MINIGAME_SCROLL_AREA.png",
)
NEW_YEAR_CHALLENGE_ADD_COIN = Button(
    area=(509, 635, 575, 668),
    color=(205, 175, 214),
    button=(509, 635, 575, 668),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_ADD_COIN.png",
)
NEW_YEAR_CHALLENGE_BLUE_BUTTON = Button(
    area=(1066, 642, 1121, 697),
    color=(182, 200, 240),
    button=(1066, 642, 1121, 697),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_BLUE_BUTTON.png",
)
NEW_YEAR_CHALLENGE_CHOOSING = Button(
    area=(590, 34, 689, 157),
    color=(128, 136, 155),
    button=(590, 34, 689, 157),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_CHOOSING.png",
)
NEW_YEAR_CHALLENGE_COIN_COST_HOLDER = Button(
    area=(377, 636, 408, 669),
    color=(217, 216, 220),
    button=(377, 636, 408, 669),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_COIN_COST_HOLDER.png",
)
NEW_YEAR_CHALLENGE_DEC_COIN = Button(
    area=(155, 635, 227, 671),
    color=(210, 207, 211),
    button=(155, 635, 227, 671),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_DEC_COIN.png",
)
NEW_YEAR_CHALLENGE_END = Button(
    area=(956, 615, 1061, 664),
    color=(215, 166, 100),
    button=(956, 615, 1061, 664),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_END.png",
)
NEW_YEAR_CHALLENGE_ENTRANCE = Button(
    area=(435, 521, 522, 575),
    color=(232, 225, 230),
    button=(435, 521, 522, 575),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_ENTRANCE.png",
)
NEW_YEAR_CHALLENGE_EXIT = Button(
    area=(24, 11, 123, 98),
    color=(213, 176, 161),
    button=(24, 11, 123, 98),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_EXIT.png",
)
NEW_YEAR_CHALLENGE_FIRST_TIME = Button(
    area=(1212, 342, 1272, 415),
    color=(118, 117, 119),
    button=(1212, 342, 1272, 415),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_FIRST_TIME.png",
)
NEW_YEAR_CHALLENGE_RED_BUTTON = Button(
    area=(1198, 489, 1255, 540),
    color=(241, 202, 196),
    button=(1198, 489, 1255, 540),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_RED_BUTTON.png",
)
NEW_YEAR_CHALLENGE_SAFE_AREA = Button(
    area=(1178, 77, 1258, 157),
    color=(163, 154, 133),
    button=(1178, 77, 1258, 157),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_SAFE_AREA.png",
)
NEW_YEAR_CHALLENGE_SCORE_HOLDER = Button(
    area=(1166, 20, 1259, 54),
    color=(132, 111, 86),
    button=(1166, 20, 1259, 54),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_SCORE_HOLDER.png",
)
NEW_YEAR_CHALLENGE_START = Button(
    area=(462, 418, 508, 495),
    color=(238, 158, 137),
    button=(462, 418, 508, 495),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_START.png",
)
NEW_YEAR_CHALLENGE_STOP_PLAY = Button(
    area=(63, 14, 96, 46),
    color=(141, 131, 181),
    button=(63, 14, 96, 46),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_STOP_PLAY.png",
)
NEW_YEAR_CHALLENGE_TMP_1 = Button(
    area=(263, 317, 308, 324),
    color=(82, 134, 239),
    button=(263, 317, 308, 324),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_TMP_1.png",
)
NEW_YEAR_CHALLENGE_TMP_2 = Button(
    area=(439, 317, 478, 324),
    color=(247, 223, 115),
    button=(439, 317, 478, 324),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_TMP_2.png",
)
NEW_YEAR_CHALLENGE_TMP_3 = Button(
    area=(610, 317, 653, 324),
    color=(255, 150, 124),
    button=(610, 317, 653, 324),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_TMP_3.png",
)
NEW_YEAR_CHALLENGE_TMP_4 = Button(
    area=(784, 318, 823, 323),
    color=(82, 134, 239),
    button=(784, 318, 823, 323),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_TMP_4.png",
)
NEW_YEAR_CHALLENGE_TMP_5 = Button(
    area=(954, 319, 1001, 323),
    color=(247, 223, 115),
    button=(954, 319, 1001, 323),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_TMP_5.png",
)
NEW_YEAR_CHALLENGE_YELLOW_BUTTON = Button(
    area=(1103, 540, 1175, 606),
    color=(247, 233, 181),
    button=(1103, 540, 1175, 606),
    file="./assets/cn/minigame/NEW_YEAR_CHALLENGE_YELLOW_BUTTON.png",
)
TICKET_SHOP = Button(
    area=(244, 629, 285, 679),
    color=(185, 187, 197),
    button=(244, 629, 285, 679),
    file="./assets/cn/minigame/TICKET_SHOP.png",
)
