from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ADD_NEW_STUDENT = Button(
    area=(417, 375, 438, 398),
    color=(81, 91, 106),
    button=(417, 375, 438, 398),
    file="./assets/cn/tactical/ADD_NEW_STUDENT.png",
)
BOOK_EMPTY_POPUP = Button(
    area=(880, 180, 908, 209),
    color=(211, 109, 105),
    button=(880, 180, 908, 209),
    file="./assets/cn/tactical/BOOK_EMPTY_POPUP.png",
)
OCR_SKILL_EXP = Button(
    area=(771, 191, 951, 209),
    color=(72, 82, 83),
    button=(771, 191, 951, 209),
    file="./assets/cn/tactical/OCR_SKILL_EXP.png",
)
RAPID_TRAINING = Button(
    area=(518, 566, 583, 582),
    color=(233, 212, 171),
    button=(518, 566, 583, 582),
    file="./assets/cn/tactical/RAPID_TRAINING.png",
)
REWARD_2 = Button(
    area=(438, 420, 497, 447),
    color=(254, 195, 103),
    button=(438, 420, 497, 447),
    file="./assets/cn/tactical/REWARD_2.png",
)
SKILL_CONFIRM = Button(
    area=(575, 563, 705, 594),
    color=(147, 177, 216),
    button=(575, 563, 705, 594),
    file="./assets/cn/tactical/SKILL_CONFIRM.png",
)
TACTICAL_CLASS_CANCEL = Button(
    area=(818, 591, 990, 647),
    color=(153, 154, 154),
    button=(818, 591, 990, 647),
    file="./assets/cn/tactical/TACTICAL_CLASS_CANCEL.png",
)
TACTICAL_CLASS_START = Button(
    area=(1024, 590, 1197, 648),
    color=(96, 139, 194),
    button=(1024, 590, 1197, 648),
    file="./assets/cn/tactical/TACTICAL_CLASS_START.png",
)
TACTICAL_META = Button(
    area=(571, 553, 710, 597),
    color=(175, 176, 178),
    button=(571, 553, 710, 597),
    file="./assets/cn/tactical/TACTICAL_META.png",
)
