from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BOX_AMOUNT_CONFIRM = Button(
    area=(804, 614, 875, 644),
    color=(144, 173, 211),
    button=(804, 614, 875, 644),
    file="./assets/cn/storage/BOX_AMOUNT_CONFIRM.png",
)
BOX_AMOUNT_OCR = Button(
    area=(591, 298, 688, 326),
    color=(56, 56, 65),
    button=(591, 298, 688, 326),
    file="./assets/cn/storage/BOX_AMOUNT_OCR.png",
)
BOX_USE = Button(
    area=(750, 493, 819, 524),
    color=(153, 183, 219),
    button=(750, 493, 819, 524),
    file="./assets/cn/storage/BOX_USE.png",
)
DISASSEMBLE = Button(
    area=(357, 666, 456, 690),
    color=(191, 192, 192),
    button=(348, 661, 466, 696),
    file="./assets/cn/storage/DISASSEMBLE.png",
)
DISASSEMBLE_CANCEL = Button(
    area=(900, 659, 973, 690),
    color=(186, 186, 187),
    button=(863, 649, 1015, 700),
    file="./assets/cn/storage/DISASSEMBLE_CANCEL.png",
)
DISASSEMBLE_CONFIRM = Button(
    area=(1108, 657, 1183, 690),
    color=(202, 149, 143),
    button=(1067, 650, 1225, 698),
    file="./assets/cn/storage/DISASSEMBLE_CONFIRM.png",
)
DISASSEMBLE_COUNT_OCR = Button(
    area=(612, 662, 687, 695),
    color=(60, 63, 81),
    button=(612, 662, 687, 695),
    file="./assets/cn/storage/DISASSEMBLE_COUNT_OCR.png",
)
DISASSEMBLE_POPUP_CONFIRM = Button(
    area=(746, 564, 815, 594),
    color=(148, 179, 219),
    button=(707, 558, 854, 603),
    file="./assets/cn/storage/DISASSEMBLE_POPUP_CONFIRM.png",
)
EQUIPMENT_EMPTY = Button(
    area=(1127, 353, 1155, 395),
    color=(95, 74, 86),
    button=(1127, 353, 1155, 395),
    file="./assets/cn/storage/EQUIPMENT_EMPTY.png",
)
EQUIPMENT_ENTER = Button(
    area=(1021, 667, 1077, 691),
    color=(222, 187, 122),
    button=(954, 656, 1091, 698),
    file="./assets/cn/storage/EQUIPMENT_ENTER.png",
)
EQUIPMENT_FILTER = Button(
    area=(805, 23, 841, 38),
    color=(155, 171, 210),
    button=(794, 7, 883, 45),
    file="./assets/cn/storage/EQUIPMENT_FILTER.png",
)
EQUIPMENT_FILTER_CONFIRM = Button(
    area=(763, 615, 837, 646),
    color=(140, 172, 211),
    button=(721, 605, 881, 657),
    file="./assets/cn/storage/EQUIPMENT_FILTER_CONFIRM.png",
)
EQUIPMENT_FULL = Button(
    area=(453, 498, 527, 528),
    color=(154, 183, 221),
    button=(413, 487, 569, 538),
    file="./assets/cn/storage/EQUIPMENT_FULL.png",
)
MATERIAL_CHECK = Button(
    area=(258, 664, 305, 687),
    color=(106, 106, 111),
    button=(258, 664, 305, 687),
    file="./assets/cn/storage/MATERIAL_CHECK.png",
)
MATERIAL_ENTER = Button(
    area=(1180, 666, 1237, 691),
    color=(217, 179, 119),
    button=(1114, 656, 1251, 698),
    file="./assets/cn/storage/MATERIAL_ENTER.png",
)
MATERIAL_STABLE_CHECK = Button(
    area=(858, 422, 1231, 631),
    color=(116, 127, 145),
    button=(858, 422, 1231, 631),
    file="./assets/cn/storage/MATERIAL_STABLE_CHECK.png",
)
METERIAL_SCROLL = Button(
    area=(1257, 94, 1263, 585),
    color=(101, 93, 56),
    button=(1257, 94, 1263, 585),
    file="./assets/cn/storage/METERIAL_SCROLL.png",
)
TEMPLATE_BOX_T1 = Template(file="./assets/cn/storage/TEMPLATE_BOX_T1.png")
TEMPLATE_BOX_T2 = Template(file="./assets/cn/storage/TEMPLATE_BOX_T2.png")
TEMPLATE_BOX_T3 = Template(file="./assets/cn/storage/TEMPLATE_BOX_T3.png")
TEMPLATE_BOX_T4 = Template(file="./assets/cn/storage/TEMPLATE_BOX_T4.png")
