from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ACADEMY_EASY = Button(
    area=(201, 290, 243, 311),
    color=(172, 141, 121),
    button=(201, 290, 243, 311),
    file="./assets/cn/coalition/ACADEMY_EASY.png",
)
ACADEMY_EX = Button(
    area=(712, 178, 744, 196),
    color=(151, 200, 191),
    button=(712, 178, 744, 196),
    file="./assets/cn/coalition/ACADEMY_EX.png",
)
ACADEMY_HARD = Button(
    area=(956, 503, 1000, 524),
    color=(169, 137, 118),
    button=(956, 503, 1000, 524),
    file="./assets/cn/coalition/ACADEMY_HARD.png",
)
ACADEMY_MODE_BATTLE = Button(
    area=(105, 654, 182, 675),
    color=(207, 169, 129),
    button=(105, 654, 182, 675),
    file="./assets/cn/coalition/ACADEMY_MODE_BATTLE.png",
)
ACADEMY_MODE_STORY = Button(
    area=(224, 654, 302, 675),
    color=(210, 175, 139),
    button=(224, 654, 302, 675),
    file="./assets/cn/coalition/ACADEMY_MODE_STORY.png",
)
ACADEMY_NORMAL = Button(
    area=(604, 411, 646, 433),
    color=(169, 137, 118),
    button=(604, 411, 646, 433),
    file="./assets/cn/coalition/ACADEMY_NORMAL.png",
)
ACADEMY_PT_OCR = Button(
    area=(1125, 208, 1265, 225),
    color=(124, 105, 88),
    button=(1125, 208, 1265, 225),
    file="./assets/cn/coalition/ACADEMY_PT_OCR.png",
)
ACADEMY_SP = Button(
    area=(333, 580, 362, 597),
    color=(176, 146, 126),
    button=(333, 580, 362, 597),
    file="./assets/cn/coalition/ACADEMY_SP.png",
)
ACADEMY_SWITCH_MULTI = Button(
    area=(1088, 458, 1216, 486),
    color=(234, 184, 61),
    button=(1088, 458, 1216, 486),
    file="./assets/cn/coalition/ACADEMY_SWITCH_MULTI.png",
)
ACADEMY_SWITCH_SINGLE = Button(
    area=(941, 458, 1070, 486),
    color=(232, 182, 60),
    button=(941, 458, 1070, 486),
    file="./assets/cn/coalition/ACADEMY_SWITCH_SINGLE.png",
)
ACEDEMY_FLEET_PREPARATION = Button(
    area=(1025, 537, 1132, 562),
    color=(106, 149, 226),
    button=(1025, 537, 1132, 562),
    file="./assets/cn/coalition/ACEDEMY_FLEET_PREPARATION.png",
)
COALITION_ACADEMY_BACK = Button(
    area=(44, 48, 62, 74),
    color=(162, 188, 194),
    button=(44, 48, 62, 74),
    file="./assets/cn/coalition/COALITION_ACADEMY_BACK.png",
)
COALITION_ACADEMY_CAMPAIGN_CHECK = Button(
    area=(131, 50, 168, 83),
    color=(165, 210, 212),
    button=(131, 50, 168, 83),
    file="./assets/cn/coalition/COALITION_ACADEMY_CAMPAIGN_CHECK.png",
)
COALITION_ACADEMY_GOTO_CAMPAIGN = Button(
    area=(1123, 615, 1159, 651),
    color=(160, 134, 93),
    button=(1123, 615, 1159, 651),
    file="./assets/cn/coalition/COALITION_ACADEMY_GOTO_CAMPAIGN.png",
)
COALITION_ACADEMY_HOME = Button(
    area=(1221, 48, 1244, 73),
    color=(182, 197, 203),
    button=(1221, 48, 1244, 73),
    file="./assets/cn/coalition/COALITION_ACADEMY_HOME.png",
)
COALITION_ACADEMY_MAIN_CHECK = Button(
    area=(132, 57, 163, 92),
    color=(143, 202, 205),
    button=(132, 57, 163, 92),
    file="./assets/cn/coalition/COALITION_ACADEMY_MAIN_CHECK.png",
)
COALITION_REWARD_CONFIRM = Button(
    area=(814, 611, 877, 637),
    color=(155, 186, 227),
    button=(814, 611, 877, 637),
    file="./assets/cn/coalition/COALITION_REWARD_CONFIRM.png",
)
DAL_AREA1 = Button(
    area=(167, 494, 227, 554),
    color=(255, 255, 255),
    button=(167, 494, 227, 554),
    file="./assets/cn/coalition/DAL_AREA1.png",
)
DAL_AREA2 = Button(
    area=(407, 378, 467, 438),
    color=(255, 255, 255),
    button=(407, 378, 467, 438),
    file="./assets/cn/coalition/DAL_AREA2.png",
)
DAL_AREA3 = Button(
    area=(787, 488, 847, 548),
    color=(255, 255, 255),
    button=(787, 488, 847, 548),
    file="./assets/cn/coalition/DAL_AREA3.png",
)
DAL_AREA4 = Button(
    area=(904, 245, 964, 305),
    color=(255, 255, 255),
    button=(904, 245, 964, 305),
    file="./assets/cn/coalition/DAL_AREA4.png",
)
DAL_AREA5 = Button(
    area=(552, 130, 612, 190),
    color=(255, 255, 255),
    button=(552, 130, 612, 190),
    file="./assets/cn/coalition/DAL_AREA5.png",
)
DAL_AREA6 = Button(
    area=(656, 303, 716, 363),
    color=(255, 255, 255),
    button=(656, 303, 716, 363),
    file="./assets/cn/coalition/DAL_AREA6.png",
)
DAL_DIFFICULTY_EXIT = Button(
    area=(1208, 70, 1244, 107),
    color=(122, 158, 172),
    button=(1208, 70, 1244, 107),
    file="./assets/cn/coalition/DAL_DIFFICULTY_EXIT.png",
)
DAL_FLEET_PREPARATION = Button(
    area=(1016, 529, 1100, 550),
    color=(135, 215, 236),
    button=(1016, 529, 1100, 550),
    file="./assets/cn/coalition/DAL_FLEET_PREPARATION.png",
)
DAL_HARD = Button(
    area=(893, 582, 1109, 611),
    color=(255, 255, 255),
    button=(893, 582, 1109, 611),
    file="./assets/cn/coalition/DAL_HARD.png",
)
DAL_NORMAL = Button(
    area=(600, 583, 818, 610),
    color=(255, 255, 255),
    button=(600, 583, 818, 610),
    file="./assets/cn/coalition/DAL_NORMAL.png",
)
DAL_PT_OCR = Button(
    area=(1190, 130, 1274, 161),
    color=(79, 86, 72),
    button=(1190, 130, 1274, 161),
    file="./assets/cn/coalition/DAL_PT_OCR.png",
)
DAL_SWITCH_MULTI = Button(
    area=(1060, 473, 1204, 500),
    color=(225, 225, 225),
    button=(1060, 473, 1204, 500),
    file="./assets/cn/coalition/DAL_SWITCH_MULTI.png",
)
DAL_SWITCH_SINGLE = Button(
    area=(910, 473, 1055, 500),
    color=(223, 223, 223),
    button=(910, 473, 1055, 500),
    file="./assets/cn/coalition/DAL_SWITCH_SINGLE.png",
)
EMPTY_FLAGSHIP = Button(
    area=(247, 237, 277, 267),
    color=(76, 64, 56),
    button=(247, 237, 277, 267),
    file="./assets/cn/coalition/EMPTY_FLAGSHIP.png",
)
EMPTY_VANGUARD = Button(
    area=(515, 237, 545, 267),
    color=(52, 52, 53),
    button=(515, 237, 545, 267),
    file="./assets/cn/coalition/EMPTY_VANGUARD.png",
)
FASHION_COALITION_CHECK = Button(
    area=(102, 19, 177, 51),
    color=(109, 104, 89),
    button=(102, 19, 177, 51),
    file="./assets/cn/coalition/FASHION_COALITION_CHECK.png",
)
FASHION_EASY = Button(
    area=(136, 223, 199, 263),
    color=(225, 199, 197),
    button=(136, 223, 199, 263),
    file="./assets/cn/coalition/FASHION_EASY.png",
)
FASHION_EX = Button(
    area=(844, 246, 923, 301),
    color=(140, 115, 114),
    button=(844, 246, 923, 301),
    file="./assets/cn/coalition/FASHION_EX.png",
)
FASHION_HARD = Button(
    area=(485, 167, 554, 215),
    color=(152, 136, 129),
    button=(485, 167, 554, 215),
    file="./assets/cn/coalition/FASHION_HARD.png",
)
FASHION_MODE_BATTLE = Button(
    area=(152, 635, 213, 669),
    color=(140, 133, 117),
    button=(152, 635, 213, 669),
    file="./assets/cn/coalition/FASHION_MODE_BATTLE.png",
)
FASHION_MODE_STORY = Button(
    area=(154, 629, 220, 666),
    color=(141, 134, 116),
    button=(154, 629, 220, 666),
    file="./assets/cn/coalition/FASHION_MODE_STORY.png",
)
FASHION_NORMAL = Button(
    area=(322, 295, 392, 334),
    color=(219, 196, 198),
    button=(322, 295, 392, 334),
    file="./assets/cn/coalition/FASHION_NORMAL.png",
)
FASHION_PT_OCR = Button(
    area=(881, 658, 937, 674),
    color=(136, 127, 122),
    button=(881, 658, 937, 674),
    file="./assets/cn/coalition/FASHION_PT_OCR.png",
)
FASHION_SP = Button(
    area=(704, 194, 762, 242),
    color=(146, 133, 135),
    button=(704, 194, 762, 242),
    file="./assets/cn/coalition/FASHION_SP.png",
)
FASHION_SWITCH_MULTI = Button(
    area=(1075, 457, 1206, 485),
    color=(233, 183, 63),
    button=(1075, 457, 1206, 485),
    file="./assets/cn/coalition/FASHION_SWITCH_MULTI.png",
)
FASHION_SWITCH_SINGLE = Button(
    area=(929, 457, 1059, 485),
    color=(230, 181, 62),
    button=(929, 457, 1059, 485),
    file="./assets/cn/coalition/FASHION_SWITCH_SINGLE.png",
)
FLEET_NOT_PREPARED = Button(
    area=(1008, 310, 1110, 334),
    color=(106, 106, 112),
    button=(1008, 310, 1110, 334),
    file="./assets/cn/coalition/FLEET_NOT_PREPARED.png",
)
FROSTFALL_COALITION_CHECK = Button(
    area=(118, 14, 227, 39),
    color=(145, 161, 200),
    button=(118, 14, 227, 39),
    file="./assets/cn/coalition/FROSTFALL_COALITION_CHECK.png",
)
FROSTFALL_EX = Button(
    area=(622, 372, 649, 384),
    color=(198, 152, 252),
    button=(622, 372, 649, 384),
    file="./assets/cn/coalition/FROSTFALL_EX.png",
)
FROSTFALL_FLEET_PREPARATION = Button(
    area=(1057, 527, 1155, 548),
    color=(122, 146, 222),
    button=(1057, 527, 1155, 548),
    file="./assets/cn/coalition/FROSTFALL_FLEET_PREPARATION.png",
)
FROSTFALL_MODE_BATTLE = Button(
    area=(71, 608, 137, 653),
    color=(63, 106, 122),
    button=(71, 608, 137, 653),
    file="./assets/cn/coalition/FROSTFALL_MODE_BATTLE.png",
)
FROSTFALL_MODE_STORY = Button(
    area=(73, 610, 134, 652),
    color=(119, 44, 32),
    button=(73, 610, 134, 652),
    file="./assets/cn/coalition/FROSTFALL_MODE_STORY.png",
)
FROSTFALL_OCR_PT = Button(
    area=(1181, 641, 1254, 663),
    color=(93, 100, 106),
    button=(1181, 641, 1254, 663),
    file="./assets/cn/coalition/FROSTFALL_OCR_PT.png",
)
FROSTFALL_SP = Button(
    area=(505, 290, 532, 302),
    color=(183, 128, 253),
    button=(505, 290, 532, 302),
    file="./assets/cn/coalition/FROSTFALL_SP.png",
)
FROSTFALL_SWITCH_MULTI = Button(
    area=(1106, 449, 1237, 478),
    color=(232, 175, 58),
    button=(1106, 449, 1237, 478),
    file="./assets/cn/coalition/FROSTFALL_SWITCH_MULTI.png",
)
FROSTFALL_SWITCH_SINGLE = Button(
    area=(968, 449, 1098, 478),
    color=(230, 173, 57),
    button=(968, 449, 1098, 478),
    file="./assets/cn/coalition/FROSTFALL_SWITCH_SINGLE.png",
)
FROSTFALL_TC1 = Button(
    area=(304, 320, 330, 332),
    color=(204, 162, 254),
    button=(304, 320, 330, 332),
    file="./assets/cn/coalition/FROSTFALL_TC1.png",
)
FROSTFALL_TC2 = Button(
    area=(631, 160, 658, 173),
    color=(186, 136, 252),
    button=(631, 160, 658, 173),
    file="./assets/cn/coalition/FROSTFALL_TC2.png",
)
FROSTFALL_TC3 = Button(
    area=(810, 362, 835, 373),
    color=(197, 153, 255),
    button=(810, 362, 835, 373),
    file="./assets/cn/coalition/FROSTFALL_TC3.png",
)
NEONCITY_COALITION_CHECK = Button(
    area=(230, 36, 276, 82),
    color=(136, 139, 142),
    button=(230, 36, 276, 82),
    file="./assets/cn/coalition/NEONCITY_COALITION_CHECK.png",
)
NEONCITY_EASY = Button(
    area=(255, 252, 308, 270),
    color=(131, 132, 135),
    button=(255, 252, 308, 270),
    file="./assets/cn/coalition/NEONCITY_EASY.png",
)
NEONCITY_EX = Button(
    area=(655, 353, 708, 370),
    color=(151, 150, 151),
    button=(655, 353, 708, 370),
    file="./assets/cn/coalition/NEONCITY_EX.png",
)
NEONCITY_FLEET_PREPARATION = Button(
    area=(1034, 533, 1130, 556),
    color=(107, 137, 239),
    button=(1034, 533, 1130, 556),
    file="./assets/cn/coalition/NEONCITY_FLEET_PREPARATION.png",
)
NEONCITY_HARD = Button(
    area=(924, 549, 977, 567),
    color=(128, 128, 131),
    button=(924, 549, 977, 567),
    file="./assets/cn/coalition/NEONCITY_HARD.png",
)
NEONCITY_MODE_BATTLE = Button(
    area=(8, 627, 86, 671),
    color=(72, 56, 62),
    button=(8, 627, 86, 671),
    file="./assets/cn/coalition/NEONCITY_MODE_BATTLE.png",
)
NEONCITY_MODE_STORY = Button(
    area=(173, 627, 251, 668),
    color=(85, 67, 72),
    button=(173, 627, 251, 668),
    file="./assets/cn/coalition/NEONCITY_MODE_STORY.png",
)
NEONCITY_NORMAL = Button(
    area=(329, 453, 381, 472),
    color=(148, 149, 152),
    button=(329, 453, 381, 472),
    file="./assets/cn/coalition/NEONCITY_NORMAL.png",
)
NEONCITY_PREPARATION_EXIT = Button(
    area=(1190, 52, 1231, 93),
    color=(109, 111, 115),
    button=(1190, 52, 1231, 93),
    file="./assets/cn/coalition/NEONCITY_PREPARATION_EXIT.png",
)
NEONCITY_PT_OCR = Button(
    area=(1179, 166, 1251, 184),
    color=(31, 38, 44),
    button=(1179, 166, 1251, 184),
    file="./assets/cn/coalition/NEONCITY_PT_OCR.png",
)
NEONCITY_SP = Button(
    area=(821, 168, 874, 186),
    color=(144, 143, 143),
    button=(821, 168, 874, 186),
    file="./assets/cn/coalition/NEONCITY_SP.png",
)
NEONCITY_SWITCH_MULTI = Button(
    area=(1087, 458, 1217, 486),
    color=(233, 183, 63),
    button=(1087, 458, 1217, 486),
    file="./assets/cn/coalition/NEONCITY_SWITCH_MULTI.png",
)
NEONCITY_SWITCH_SINGLE = Button(
    area=(940, 458, 1071, 486),
    color=(230, 181, 62),
    button=(940, 458, 1071, 486),
    file="./assets/cn/coalition/NEONCITY_SWITCH_SINGLE.png",
)
NEONCITY_UI_BACK = Button(
    area=(30, 45, 73, 88),
    color=(54, 55, 57),
    button=(30, 45, 73, 88),
    file="./assets/cn/coalition/NEONCITY_UI_BACK.png",
)
NEONCITY_UI_HOME = Button(
    area=(1208, 43, 1251, 86),
    color=(74, 74, 77),
    button=(1208, 43, 1251, 86),
    file="./assets/cn/coalition/NEONCITY_UI_HOME.png",
)
