from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE_PASS_RED_DOT = Button(
    area=(623, 105, 629, 113),
    color=(202, 86, 66),
    button=(623, 105, 629, 113),
    file="./assets/cn/freebies/BATTLE_PASS_RED_DOT.png",
)
BUY_CONFIRM = Button(
    area=(698, 579, 871, 636),
    color=(81, 129, 190),
    button=(698, 579, 871, 636),
    file="./assets/cn/freebies/BUY_CONFIRM.png",
)
DATA_KEY_COLLECT = Button(
    area=(251, 38, 339, 73),
    color=(144, 116, 77),
    button=(251, 38, 339, 73),
    file="./assets/cn/freebies/DATA_KEY_COLLECT.png",
)
DATA_KEY_COLLECTED = Button(
    area=(251, 38, 339, 73),
    color=(102, 103, 103),
    button=(251, 38, 339, 73),
    file="./assets/cn/freebies/DATA_KEY_COLLECTED.png",
)
FREE_SUPPLY_PACK = Button(
    area=(264, 615, 312, 641),
    color=(124, 136, 144),
    button=(234, 302, 348, 396),
    file="./assets/cn/freebies/FREE_SUPPLY_PACK.png",
)
MAIL_BATCH_CLAIM = Button(
    area=(593, 524, 687, 546),
    color=(114, 209, 255),
    button=(593, 524, 687, 546),
    file="./assets/cn/freebies/MAIL_BATCH_CLAIM.png",
)
MAIL_BATCH_DELETE = Button(
    area=(770, 523, 865, 547),
    color=(112, 209, 255),
    button=(770, 523, 865, 547),
    file="./assets/cn/freebies/MAIL_BATCH_DELETE.png",
)
MAIL_ENTER = Button(
    area=(1207, 393, 1253, 429),
    color=(109, 107, 95),
    button=(1207, 393, 1253, 429),
    file="./assets/cn/freebies/MAIL_ENTER.png",
)
MAIL_MANAGE = Button(
    area=(415, 639, 485, 658),
    color=(116, 210, 255),
    button=(415, 639, 485, 658),
    file="./assets/cn/freebies/MAIL_MANAGE.png",
)
MAIL_SELECT_ALL = Button(
    area=(390, 319, 410, 339),
    color=(87, 88, 88),
    button=(390, 319, 410, 339),
    file="./assets/cn/freebies/MAIL_SELECT_ALL.png",
)
MAIL_SELECT_COINS = Button(
    area=(562, 401, 582, 421),
    color=(241, 240, 241),
    button=(562, 401, 582, 421),
    file="./assets/cn/freebies/MAIL_SELECT_COINS.png",
)
MAIL_SELECT_CUBE = Button(
    area=(442, 401, 462, 421),
    color=(241, 241, 241),
    button=(442, 401, 462, 421),
    file="./assets/cn/freebies/MAIL_SELECT_CUBE.png",
)
MAIL_SELECT_GEMS = Button(
    area=(442, 441, 462, 461),
    color=(241, 241, 241),
    button=(442, 441, 462, 461),
    file="./assets/cn/freebies/MAIL_SELECT_GEMS.png",
)
MAIL_SELECT_MERIT = Button(
    area=(802, 401, 822, 421),
    color=(87, 87, 88),
    button=(802, 401, 822, 421),
    file="./assets/cn/freebies/MAIL_SELECT_MERIT.png",
)
MAIL_SELECT_OIL = Button(
    area=(682, 401, 702, 421),
    color=(241, 240, 241),
    button=(682, 401, 702, 421),
    file="./assets/cn/freebies/MAIL_SELECT_OIL.png",
)
MAIL_WHITE_EMPTY = Button(
    area=(178, 375, 266, 400),
    color=(131, 141, 158),
    button=(178, 375, 266, 400),
    file="./assets/cn/freebies/MAIL_WHITE_EMPTY.png",
)
OCR_DATA_KEY = Button(
    area=(133, 39, 250, 72),
    color=(82, 80, 91),
    button=(133, 39, 250, 72),
    file="./assets/cn/freebies/OCR_DATA_KEY.png",
)
PURCHASE_POPUP = Button(
    area=(907, 204, 934, 229),
    color=(176, 130, 110),
    button=(907, 204, 934, 229),
    file="./assets/cn/freebies/PURCHASE_POPUP.png",
)
REWARD_RECEIVE = Button(
    area=(1192, 520, 1255, 536),
    color=(191, 178, 163),
    button=(1192, 520, 1255, 536),
    file="./assets/cn/freebies/REWARD_RECEIVE.png",
)
REWARD_RECEIVE_SP = Button(
    area=(1105, 579, 1184, 597),
    color=(178, 143, 126),
    button=(1105, 579, 1184, 597),
    file="./assets/cn/freebies/REWARD_RECEIVE_SP.png",
)
REWARD_RECEIVE_WHITE = Button(
    area=(1119, 603, 1198, 622),
    color=(255, 211, 156),
    button=(1119, 603, 1198, 622),
    file="./assets/cn/freebies/REWARD_RECEIVE_WHITE.png",
)
