from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ALCHEMIST_MATERIAL_CONFIRM = Button(
    area=(1039, 616, 1078, 636),
    color=(35, 126, 137),
    button=(1039, 616, 1078, 636),
    file="./assets/cn/combat/ALCHEMIST_MATERIAL_CONFIRM.png",
)
AUTOMATION_CONFIRM = Button(
    area=(591, 535, 686, 566),
    color=(144, 177, 218),
    button=(591, 535, 686, 566),
    file="./assets/cn/combat/AUTOMATION_CONFIRM.png",
)
AUTOMATION_CONFIRM_CHECK = Button(
    area=(745, 423, 764, 439),
    color=(181, 85, 82),
    button=(745, 423, 764, 439),
    file="./assets/cn/combat/AUTOMATION_CONFIRM_CHECK.png",
)
AUTOMATION_OFF = Button(
    area=(754, 113, 794, 129),
    color=(119, 71, 70),
    button=(754, 113, 794, 129),
    file="./assets/cn/combat/AUTOMATION_OFF.png",
)
AUTOMATION_ON = Button(
    area=(759, 113, 790, 129),
    color=(22, 112, 81),
    button=(759, 113, 790, 129),
    file="./assets/cn/combat/AUTOMATION_ON.png",
)
AUTOMATION_SWITCH = Button(
    area=(821, 106, 907, 136),
    color=(95, 109, 147),
    button=(821, 106, 907, 136),
    file="./assets/cn/combat/AUTOMATION_SWITCH.png",
)
BATTLE_PREPARATION = Button(
    area=(1062, 612, 1089, 643),
    color=(238, 200, 164),
    button=(1043, 607, 1241, 667),
    file="./assets/cn/combat/BATTLE_PREPARATION.png",
)
BATTLE_PREPARATION_WITH_OVERLAY = Button(
    area=(1058, 622, 1226, 652),
    color=(96, 74, 39),
    button=(1058, 622, 1226, 652),
    file="./assets/cn/combat/BATTLE_PREPARATION_WITH_OVERLAY.png",
)
BATTLE_STATUS_A = Button(
    area=(634, 269, 730, 288),
    color=(235, 229, 111),
    button=(1000, 631, 1055, 689),
    file="./assets/cn/combat/BATTLE_STATUS_A.png",
)
BATTLE_STATUS_B = Button(
    area=(625, 297, 712, 317),
    color=(193, 239, 255),
    button=(999, 630, 1047, 691),
    file="./assets/cn/combat/BATTLE_STATUS_B.png",
)
BATTLE_STATUS_C = Button(
    area=(625, 211, 647, 297),
    color=(199, 208, 198),
    button=(1000, 631, 1055, 689),
    file="./assets/cn/combat/BATTLE_STATUS_C.png",
)
BATTLE_STATUS_D = Button(
    area=(618, 191, 639, 317),
    color=(199, 208, 199),
    button=(1000, 631, 1055, 689),
    file="./assets/cn/combat/BATTLE_STATUS_D.png",
)
BATTLE_STATUS_S = Button(
    area=(643, 297, 722, 317),
    color=(233, 242, 127),
    button=(1000, 631, 1055, 689),
    file="./assets/cn/combat/BATTLE_STATUS_S.png",
)
COMBAT_AUTO = Button(
    area=(136, 572, 167, 605),
    color=(234, 244, 255),
    button=(136, 572, 167, 605),
    file="./assets/cn/combat/COMBAT_AUTO.png",
)
COMBAT_AUTO_133 = Button(
    area=(131, 568, 170, 609),
    color=(234, 244, 255),
    button=(131, 568, 170, 609),
    file="./assets/cn/combat/COMBAT_AUTO_133.png",
)
COMBAT_AUTO_150 = Button(
    area=(129, 567, 172, 611),
    color=(238, 247, 255),
    button=(129, 567, 172, 611),
    file="./assets/cn/combat/COMBAT_AUTO_150.png",
)
COMBAT_AUTO_SWITCH = Button(
    area=(18, 38, 36, 56),
    color=(179, 198, 235),
    button=(18, 38, 36, 56),
    file="./assets/cn/combat/COMBAT_AUTO_SWITCH.png",
)
COMBAT_OIL_LOADING = Button(
    area=(1157, 566, 1214, 594),
    color=(45, 51, 60),
    button=(1157, 566, 1214, 594),
    file="./assets/cn/combat/COMBAT_OIL_LOADING.png",
)
EMERGENCY_REPAIR_AVAILABLE = Button(
    area=(106, 533, 119, 540),
    color=(255, 255, 255),
    button=(97, 512, 141, 557),
    file="./assets/cn/combat/EMERGENCY_REPAIR_AVAILABLE.png",
)
EMERGENCY_REPAIR_CONFIRM = Button(
    area=(669, 418, 842, 475),
    color=(94, 143, 204),
    button=(669, 418, 842, 475),
    file="./assets/cn/combat/EMERGENCY_REPAIR_CONFIRM.png",
)
EXP_INFO_A = Button(
    area=(337, 90, 394, 102),
    color=(235, 228, 110),
    button=(1133, 634, 1262, 650),
    file="./assets/cn/combat/EXP_INFO_A.png",
)
EXP_INFO_B = Button(
    area=(332, 107, 387, 118),
    color=(193, 238, 255),
    button=(1133, 634, 1262, 650),
    file="./assets/cn/combat/EXP_INFO_B.png",
)
EXP_INFO_C = Button(
    area=(332, 56, 345, 107),
    color=(198, 208, 198),
    button=(1133, 634, 1262, 650),
    file="./assets/cn/combat/EXP_INFO_C.png",
)
EXP_INFO_D = Button(
    area=(328, 45, 341, 119),
    color=(199, 208, 199),
    button=(1133, 634, 1262, 650),
    file="./assets/cn/combat/EXP_INFO_D.png",
)
EXP_INFO_S = Button(
    area=(342, 107, 389, 119),
    color=(233, 242, 127),
    button=(1133, 634, 1262, 650),
    file="./assets/cn/combat/EXP_INFO_S.png",
)
GET_ITEMS_1 = Button(
    area=(538, 217, 741, 253),
    color=(160, 192, 248),
    button=(1000, 631, 1055, 689),
    file="./assets/cn/combat/GET_ITEMS_1.png",
)
GET_ITEMS_1_RYZA = Button(
    area=(564, 217, 721, 245),
    color=(176, 199, 243),
    button=(1000, 631, 1055, 689),
    file="./assets/cn/combat/GET_ITEMS_1_RYZA.png",
)
GET_ITEMS_2 = Button(
    area=(538, 146, 742, 182),
    color=(160, 192, 248),
    button=(1000, 631, 1055, 689),
    file="./assets/cn/combat/GET_ITEMS_2.png",
)
GET_ITEMS_3 = Button(
    area=(539, 143, 742, 179),
    color=(161, 193, 248),
    button=(1000, 631, 1055, 689),
    file="./assets/cn/combat/GET_ITEMS_3.png",
)
GET_ITEMS_3_CHECK = Button(
    area=(335, 184, 947, 203),
    color=(84, 95, 109),
    button=(335, 184, 947, 203),
    file="./assets/cn/combat/GET_ITEMS_3_CHECK.png",
)
GET_SHIP = Button(
    area=(1104, 610, 1110, 630),
    color=(255, 255, 255),
    button=(1000, 631, 1055, 689),
    file="./assets/cn/combat/GET_SHIP.png",
)
LOADING_BAR = Button(
    area=(33, 676, 1247, 680),
    color=(172, 205, 232),
    button=(33, 676, 1247, 680),
    file="./assets/cn/combat/LOADING_BAR.png",
)
MAIN_FLEET_POWER_ZERO = Button(
    area=(131, 151, 232, 206),
    color=(63, 79, 98),
    button=(131, 151, 232, 206),
    file="./assets/cn/combat/MAIN_FLEET_POWER_ZERO.png",
)
MOVE_DOWN = Button(
    area=(148, 647, 155, 669),
    color=(21, 28, 57),
    button=(148, 647, 155, 669),
    file="./assets/cn/combat/MOVE_DOWN.png",
)
MOVE_LEFT_DOWN = Button(
    area=(67, 668, 112, 707),
    color=(65, 80, 100),
    button=(67, 668, 112, 707),
    file="./assets/cn/combat/MOVE_LEFT_DOWN.png",
)
MOVE_LEFT_UP = Button(
    area=(101, 539, 136, 574),
    color=(255, 255, 255),
    button=(101, 539, 136, 574),
    file="./assets/cn/combat/MOVE_LEFT_UP.png",
)
NEW_SHIP = Button(
    area=(206, 87, 213, 93),
    color=(235, 171, 60),
    button=(206, 87, 213, 93),
    file="./assets/cn/combat/NEW_SHIP.png",
)
OPTS_INFO_D = Button(
    area=(602, 151, 703, 179),
    color=(157, 115, 123),
    button=(583, 605, 677, 628),
    file="./assets/cn/combat/OPTS_INFO_D.png",
)
QUIT_RECONFIRM = Button(
    area=(749, 501, 828, 540),
    color=(207, 140, 133),
    button=(749, 501, 828, 540),
    file="./assets/cn/combat/QUIT_RECONFIRM.png",
)
READY_AIR_RAID = Button(
    area=(887, 618, 907, 628),
    color=(255, 255, 255),
    button=(887, 618, 907, 628),
    file="./assets/cn/combat/READY_AIR_RAID.png",
)
READY_TORPEDO = Button(
    area=(1038, 611, 1046, 619),
    color=(255, 255, 255),
    button=(1038, 611, 1046, 619),
    file="./assets/cn/combat/READY_TORPEDO.png",
)
SUBMARINE_AVAILABLE_CHECK_1 = Button(
    area=(707, 660, 712, 665),
    color=(255, 255, 255),
    button=(707, 660, 712, 665),
    file="./assets/cn/combat/SUBMARINE_AVAILABLE_CHECK_1.png",
)
SUBMARINE_AVAILABLE_CHECK_2 = Button(
    area=(790, 631, 795, 641),
    color=(255, 255, 255),
    button=(790, 631, 795, 641),
    file="./assets/cn/combat/SUBMARINE_AVAILABLE_CHECK_2.png",
)
SUBMARINE_CALLED = Button(
    area=(737, 608, 750, 626),
    color=(132, 134, 132),
    button=(737, 608, 750, 626),
    file="./assets/cn/combat/SUBMARINE_CALLED.png",
)
SUBMARINE_READY = Button(
    area=(737, 608, 752, 625),
    color=(255, 251, 255),
    button=(737, 608, 752, 625),
    file="./assets/cn/combat/SUBMARINE_READY.png",
)
