from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

AIR_STRIKE_CANCEL = Button(
    area=(887, 644, 948, 676),
    color=(193, 141, 135),
    button=(887, 644, 948, 676),
    file="./assets/cn/handler/AIR_STRIKE_CANCEL.png",
)
AIR_STRIKE_CONFIRM = Button(
    area=(1100, 644, 1161, 675),
    color=(129, 161, 199),
    button=(1100, 644, 1161, 675),
    file="./assets/cn/handler/AIR_STRIKE_CONFIRM.png",
)
AIR_STRIKE_ENTER = Button(
    area=(1194, 456, 1249, 530),
    color=(123, 124, 131),
    button=(1194, 456, 1249, 530),
    file="./assets/cn/handler/AIR_STRIKE_ENTER.png",
)
ANDROID_NO_RESPOND = Button(
    area=(341, 433, 391, 472),
    color=(217, 237, 235),
    button=(341, 433, 391, 472),
    file="./assets/cn/handler/ANDROID_NO_RESPOND.png",
)
AUTO_SEARCH_MAP_OPTION_OFF = Button(
    area=(1205, 549, 1275, 566),
    color=(196, 169, 169),
    button=(1205, 549, 1275, 566),
    file="./assets/cn/handler/AUTO_SEARCH_MAP_OPTION_OFF.png",
)
AUTO_SEARCH_MAP_OPTION_ON = Button(
    area=(1205, 549, 1275, 566),
    color=(149, 176, 193),
    button=(1205, 549, 1275, 566),
    file="./assets/cn/handler/AUTO_SEARCH_MAP_OPTION_ON.png",
)
AUTO_SEARCH_MENU_CONTINUE = Button(
    area=(789, 610, 903, 638),
    color=(147, 182, 224),
    button=(773, 598, 919, 646),
    file="./assets/cn/handler/AUTO_SEARCH_MENU_CONTINUE.png",
)
AUTO_SEARCH_MENU_EXIT = Button(
    area=(419, 609, 475, 637),
    color=(198, 199, 201),
    button=(373, 598, 520, 647),
    file="./assets/cn/handler/AUTO_SEARCH_MENU_EXIT.png",
)
AUTO_SEARCH_OFF = Button(
    area=(867, 588, 883, 604),
    color=(94, 92, 94),
    button=(867, 588, 883, 604),
    file="./assets/cn/handler/AUTO_SEARCH_OFF.png",
)
AUTO_SEARCH_OFF2 = Button(
    area=(867, 588, 883, 604),
    color=(90, 89, 92),
    button=(867, 588, 883, 604),
    file="./assets/cn/handler/AUTO_SEARCH_OFF2.png",
)
AUTO_SEARCH_OFF3 = Button(
    area=(865, 587, 881, 603),
    color=(108, 112, 115),
    button=(865, 587, 881, 603),
    file="./assets/cn/handler/AUTO_SEARCH_OFF3.png",
)
AUTO_SEARCH_OFF4 = Button(
    area=(865, 587, 881, 603),
    color=(105, 110, 114),
    button=(865, 587, 881, 603),
    file="./assets/cn/handler/AUTO_SEARCH_OFF4.png",
)
AUTO_SEARCH_ON = Button(
    area=(867, 588, 883, 604),
    color=(140, 167, 120),
    button=(867, 588, 883, 604),
    file="./assets/cn/handler/AUTO_SEARCH_ON.png",
)
AUTO_SEARCH_ON2 = Button(
    area=(867, 588, 883, 604),
    color=(139, 168, 112),
    button=(867, 588, 883, 604),
    file="./assets/cn/handler/AUTO_SEARCH_ON2.png",
)
AUTO_SEARCH_ON3 = Button(
    area=(865, 587, 881, 603),
    color=(141, 168, 125),
    button=(865, 587, 881, 603),
    file="./assets/cn/handler/AUTO_SEARCH_ON3.png",
)
AUTO_SEARCH_ON4 = Button(
    area=(867, 588, 883, 604),
    color=(138, 166, 123),
    button=(867, 588, 883, 604),
    file="./assets/cn/handler/AUTO_SEARCH_ON4.png",
)
AUTO_SEARCH_SET_ALL = Button(
    area=(832, 207, 851, 226),
    color=(32, 32, 38),
    button=(832, 207, 851, 226),
    file="./assets/cn/handler/AUTO_SEARCH_SET_ALL.png",
)
AUTO_SEARCH_SET_BOSS = Button(
    area=(635, 207, 653, 226),
    color=(30, 30, 33),
    button=(635, 207, 653, 226),
    file="./assets/cn/handler/AUTO_SEARCH_SET_BOSS.png",
)
AUTO_SEARCH_SET_MOB = Button(
    area=(496, 207, 515, 226),
    color=(69, 96, 51),
    button=(496, 207, 515, 226),
    file="./assets/cn/handler/AUTO_SEARCH_SET_MOB.png",
)
AUTO_SEARCH_SET_STANDBY = Button(
    area=(932, 207, 950, 226),
    color=(30, 30, 37),
    button=(932, 207, 950, 226),
    file="./assets/cn/handler/AUTO_SEARCH_SET_STANDBY.png",
)
AUTO_SEARCH_SET_SUB_AUTO = Button(
    area=(578, 457, 597, 476),
    color=(69, 96, 52),
    button=(578, 457, 597, 476),
    file="./assets/cn/handler/AUTO_SEARCH_SET_SUB_AUTO.png",
)
AUTO_SEARCH_SET_SUB_STANDBY = Button(
    area=(894, 457, 913, 476),
    color=(32, 31, 34),
    button=(894, 457, 913, 476),
    file="./assets/cn/handler/AUTO_SEARCH_SET_SUB_STANDBY.png",
)
AVATAR_EXPIRED = Button(
    area=(641, 567, 713, 598),
    color=(154, 184, 222),
    button=(641, 567, 713, 598),
    file="./assets/cn/handler/AVATAR_EXPIRED.png",
)
BATTLE_PASS_NEW_SEASON = Button(
    area=(942, 529, 962, 550),
    color=(134, 137, 140),
    button=(942, 529, 962, 550),
    file="./assets/cn/handler/BATTLE_PASS_NEW_SEASON.png",
)
BATTLE_PASS_NOTICE = Button(
    area=(554, 483, 726, 540),
    color=(107, 152, 207),
    button=(863, 173, 929, 217),
    file="./assets/cn/handler/BATTLE_PASS_NOTICE.png",
)
BOOK_BOX_AUTO = Button(
    area=(737, 614, 756, 631),
    color=(67, 74, 82),
    button=(737, 614, 756, 631),
    file="./assets/cn/handler/BOOK_BOX_AUTO.png",
)
BOOK_BOX_PREP = Button(
    area=(922, 600, 940, 617),
    color=(88, 122, 68),
    button=(922, 600, 940, 617),
    file="./assets/cn/handler/BOOK_BOX_PREP.png",
)
BOOK_CHECK_AUTO = Button(
    area=(600, 599, 648, 635),
    color=(144, 128, 138),
    button=(600, 599, 648, 635),
    file="./assets/cn/handler/BOOK_CHECK_AUTO.png",
)
BOOK_CHECK_PREP = Button(
    area=(735, 588, 761, 618),
    color=(148, 134, 83),
    button=(735, 588, 761, 618),
    file="./assets/cn/handler/BOOK_CHECK_PREP.png",
)
BOOK_POPUP_CHECK = Button(
    area=(420, 304, 475, 354),
    color=(152, 137, 83),
    button=(420, 304, 475, 354),
    file="./assets/cn/handler/BOOK_POPUP_CHECK.png",
)
FAST_FORWARD_OFF = Button(
    area=(982, 587, 1022, 605),
    color=(251, 251, 251),
    button=(982, 587, 1022, 605),
    file="./assets/cn/handler/FAST_FORWARD_OFF.png",
)
FAST_FORWARD_ON = Button(
    area=(1024, 587, 1064, 605),
    color=(251, 251, 251),
    button=(1024, 587, 1064, 605),
    file="./assets/cn/handler/FAST_FORWARD_ON.png",
)
FLEET_LOCKED = Button(
    area=(1185, 501, 1192, 519),
    color=(59, 100, 110),
    button=(1185, 501, 1192, 519),
    file="./assets/cn/handler/FLEET_LOCKED.png",
)
FLEET_UNLOCKED = Button(
    area=(1185, 492, 1192, 525),
    color=(84, 74, 98),
    button=(1185, 492, 1192, 525),
    file="./assets/cn/handler/FLEET_UNLOCKED.png",
)
FORMATION_1 = Button(
    area=(1108, 446, 1170, 477),
    color=(79, 82, 92),
    button=(1108, 415, 1170, 477),
    file="./assets/cn/handler/FORMATION_1.png",
)
FORMATION_2 = Button(
    area=(1108, 446, 1170, 477),
    color=(81, 83, 92),
    button=(1108, 415, 1170, 477),
    file="./assets/cn/handler/FORMATION_2.png",
)
FORMATION_3 = Button(
    area=(1108, 446, 1170, 477),
    color=(79, 82, 91),
    button=(1108, 415, 1170, 477),
    file="./assets/cn/handler/FORMATION_3.png",
)
FORMATION_LOCATION = Button(
    area=(145, 115, 437, 159),
    color=(103, 118, 118),
    button=(145, 115, 437, 159),
    file="./assets/cn/handler/FORMATION_LOCATION.png",
)
GAME_TIPS = Button(
    area=(1009, 586, 1028, 614),
    color=(85, 84, 85),
    button=(924, 653, 943, 672),
    file="./assets/cn/handler/GAME_TIPS.png",
)
GAME_TIPS3 = Button(
    area=(1008, 586, 1028, 614),
    color=(105, 104, 105),
    button=(1008, 586, 1028, 614),
    file="./assets/cn/handler/GAME_TIPS3.png",
)
GAME_TIPS4 = Button(
    area=(1008, 587, 1028, 614),
    color=(106, 105, 106),
    button=(1008, 587, 1028, 614),
    file="./assets/cn/handler/GAME_TIPS4.png",
)
GET_AMMO = Button(
    area=(792, 315, 794, 333),
    color=(251, 250, 255),
    button=(792, 315, 794, 333),
    file="./assets/cn/handler/GET_AMMO.png",
)
GET_ITEMS_SHIP_1 = Button(
    area=(563, 193, 720, 219),
    color=(179, 201, 243),
    button=(563, 193, 720, 219),
    file="./assets/cn/handler/GET_ITEMS_SHIP_1.png",
)
GET_MISSION = Button(
    area=(604, 495, 676, 525),
    color=(151, 181, 221),
    button=(604, 495, 676, 525),
    file="./assets/cn/handler/GET_MISSION.png",
)
GET_SKIN = Button(
    area=(990, 550, 1022, 565),
    color=(113, 114, 124),
    button=(990, 550, 1022, 565),
    file="./assets/cn/handler/GET_SKIN.png",
)
GUILD_POPUP_CANCEL = Button(
    area=(422, 449, 623, 486),
    color=(127, 125, 127),
    button=(422, 449, 623, 486),
    file="./assets/cn/handler/GUILD_POPUP_CANCEL.png",
)
GUILD_POPUP_CONFIRM = Button(
    area=(655, 450, 856, 487),
    color=(90, 121, 217),
    button=(655, 450, 856, 487),
    file="./assets/cn/handler/GUILD_POPUP_CONFIRM.png",
)
INFO_BAR_1 = Button(
    area=(202, 297, 1078, 299),
    color=(107, 158, 255),
    button=(202, 297, 1078, 299),
    file="./assets/cn/handler/INFO_BAR_1.png",
)
INFO_BAR_2 = Button(
    area=(202, 241, 1078, 243),
    color=(107, 158, 255),
    button=(202, 241, 1078, 243),
    file="./assets/cn/handler/INFO_BAR_2.png",
)
INFO_BAR_3 = Button(
    area=(202, 185, 1078, 187),
    color=(107, 158, 255),
    button=(202, 185, 1078, 187),
    file="./assets/cn/handler/INFO_BAR_3.png",
)
INFO_BAR_AREA = Button(
    area=(200, 173, 1080, 348),
    color=(71, 85, 102),
    button=(200, 173, 1080, 348),
    file="./assets/cn/handler/INFO_BAR_AREA.png",
)
INFO_BAR_DETECT = Button(
    area=(194, 299, 1086, 348),
    color=(48, 53, 65),
    button=(194, 299, 1086, 348),
    file="./assets/cn/handler/INFO_BAR_DETECT.png",
)
IN_MAP = Button(
    area=(749, 654, 921, 707),
    color=(213, 124, 124),
    button=(749, 654, 921, 707),
    file="./assets/cn/handler/IN_MAP.png",
)
IN_STAGE = Button(
    area=(122, 16, 172, 39),
    color=(149, 167, 207),
    button=(122, 16, 172, 39),
    file="./assets/cn/handler/IN_STAGE.png",
)
LOGIN_ANNOUNCE = Button(
    area=(1160, 45, 1227, 90),
    color=(174, 61, 56),
    button=(1160, 61, 1190, 90),
    file="./assets/cn/handler/LOGIN_ANNOUNCE.png",
)
LOGIN_ANNOUNCE_2 = Button(
    area=(1193, 83, 1215, 105),
    color=(158, 170, 175),
    button=(1171, 83, 1193, 105),
    file="./assets/cn/handler/LOGIN_ANNOUNCE_2.png",
)
LOGIN_CHECK = Button(
    area=(1214, 653, 1268, 709),
    color=(203, 215, 230),
    button=(416, 294, 534, 400),
    file="./assets/cn/handler/LOGIN_CHECK.png",
)
LOGIN_GAME_UPDATE = Button(
    area=(700, 471, 873, 529),
    color=(238, 170, 78),
    button=(700, 471, 873, 529),
    file="./assets/cn/handler/LOGIN_GAME_UPDATE.png",
)
LOGIN_RETURN_INFO = Button(
    area=(960, 123, 1158, 333),
    color=(170, 185, 166),
    button=(960, 123, 1158, 333),
    file="./assets/cn/handler/LOGIN_RETURN_INFO.png",
)
LOGIN_RETURN_SIGN = Button(
    area=(1, 7, 104, 47),
    color=(158, 214, 229),
    button=(1, 7, 104, 47),
    file="./assets/cn/handler/LOGIN_RETURN_SIGN.png",
)
MAINTENANCE_ANNOUNCE = Button(
    area=(923, 141, 990, 186),
    color=(207, 95, 91),
    button=(923, 141, 990, 186),
    file="./assets/cn/handler/MAINTENANCE_ANNOUNCE.png",
)
MANJUU_AREA = Button(
    area=(520, 240, 760, 400),
    color=(255, 255, 255),
    button=(520, 240, 760, 400),
    file="./assets/cn/handler/MANJUU_AREA.png",
)
MAP_AIR_RAID = Button(
    area=(350, 447, 1280, 472),
    color=(154, 43, 46),
    button=(350, 447, 1280, 472),
    file="./assets/cn/handler/MAP_AIR_RAID.png",
)
MAP_AIR_STRIKE = Button(
    area=(351, 453, 1280, 477),
    color=(170, 57, 63),
    button=(351, 453, 1280, 477),
    file="./assets/cn/handler/MAP_AIR_STRIKE.png",
)
MAP_AMBUSH = Button(
    area=(261, 433, 1280, 449),
    color=(161, 41, 43),
    button=(261, 433, 1280, 449),
    file="./assets/cn/handler/MAP_AMBUSH.png",
)
MAP_AMBUSH_ATTACK = Button(
    area=(804, 457, 876, 488),
    color=(139, 168, 210),
    button=(755, 446, 925, 501),
    file="./assets/cn/handler/MAP_AMBUSH_ATTACK.png",
)
MAP_AMBUSH_EVADE = Button(
    area=(1029, 457, 1101, 487),
    color=(199, 195, 196),
    button=(979, 444, 1152, 502),
    file="./assets/cn/handler/MAP_AMBUSH_EVADE.png",
)
MAP_BUFF = Button(
    area=(145, 115, 437, 159),
    color=(103, 118, 118),
    button=(145, 115, 437, 159),
    file="./assets/cn/handler/MAP_BUFF.png",
)
MAP_CLEAR_PERCENTAGE = Button(
    area=(626, 185, 970, 190),
    color=(245, 213, 88),
    button=(626, 185, 970, 190),
    file="./assets/cn/handler/MAP_CLEAR_PERCENTAGE.png",
)
MAP_ENEMY_SEARCHING = Button(
    area=(617, 359, 651, 373),
    color=(237, 163, 159),
    button=(617, 359, 651, 373),
    file="./assets/cn/handler/MAP_ENEMY_SEARCHING.png",
)
MAP_GREEN = Button(
    area=(242, 268, 321, 286),
    color=(171, 209, 145),
    button=(242, 268, 321, 286),
    file="./assets/cn/handler/MAP_GREEN.png",
)
MAP_STAR_1 = Button(
    area=(234, 365, 265, 394),
    color=(80, 69, 45),
    button=(234, 365, 265, 394),
    file="./assets/cn/handler/MAP_STAR_1.png",
)
MAP_STAR_2 = Button(
    area=(521, 365, 551, 394),
    color=(81, 69, 44),
    button=(521, 365, 551, 394),
    file="./assets/cn/handler/MAP_STAR_2.png",
)
MAP_STAR_3 = Button(
    area=(807, 365, 838, 394),
    color=(80, 68, 46),
    button=(807, 365, 838, 394),
    file="./assets/cn/handler/MAP_STAR_3.png",
)
MAP_WALK_OUT_OF_STEP = Button(
    area=(654, 312, 704, 335),
    color=(109, 113, 120),
    button=(654, 312, 704, 335),
    file="./assets/cn/handler/MAP_WALK_OUT_OF_STEP.png",
)
MAP_WALK_SPEEDUP = Button(
    area=(1025, 406, 1055, 436),
    color=(62, 97, 72),
    button=(1025, 406, 1055, 436),
    file="./assets/cn/handler/MAP_WALK_SPEEDUP.png",
)
MISSION_POPUP_ACK = Button(
    area=(432, 493, 543, 533),
    color=(181, 182, 184),
    button=(432, 493, 543, 533),
    file="./assets/cn/handler/MISSION_POPUP_ACK.png",
)
MISSION_POPUP_GO = Button(
    area=(719, 493, 861, 534),
    color=(125, 164, 214),
    button=(719, 493, 861, 534),
    file="./assets/cn/handler/MISSION_POPUP_GO.png",
)
MOB_MOVE_CANCEL = Button(
    area=(1162, 646, 1220, 674),
    color=(224, 176, 173),
    button=(1162, 646, 1220, 674),
    file="./assets/cn/handler/MOB_MOVE_CANCEL.png",
)
MOB_MOVE_ENTER = Button(
    area=(1102, 504, 1157, 578),
    color=(122, 124, 131),
    button=(1102, 504, 1157, 578),
    file="./assets/cn/handler/MOB_MOVE_ENTER.png",
)
MONTHLY_PASS_NOTICE = Button(
    area=(554, 505, 726, 561),
    color=(109, 153, 208),
    button=(872, 152, 939, 196),
    file="./assets/cn/handler/MONTHLY_PASS_NOTICE.png",
)
MYSTERY_ITEM = Button(
    area=(589, 294, 691, 427),
    color=(144, 127, 83),
    button=(588, 478, 698, 496),
    file="./assets/cn/handler/MYSTERY_ITEM.png",
)
POPUP_CANCEL = Button(
    area=(453, 506, 525, 536),
    color=(196, 198, 199),
    button=(453, 506, 525, 536),
    file="./assets/cn/handler/POPUP_CANCEL.png",
)
POPUP_CONFIRM = Button(
    area=(754, 502, 825, 532),
    color=(153, 183, 222),
    button=(754, 502, 825, 532),
    file="./assets/cn/handler/POPUP_CONFIRM.png",
)
STORY_CLOSE = Button(
    area=(1227, 28, 1252, 53),
    color=(87, 90, 104),
    button=(1227, 28, 1252, 53),
    file="./assets/cn/handler/STORY_CLOSE.png",
)
STORY_LETTERS_ONLY = Button(
    area=(1159, 26, 1264, 52),
    color=(123, 128, 141),
    button=(1159, 26, 1264, 52),
    file="./assets/cn/handler/STORY_LETTERS_ONLY.png",
)
STORY_LETTER_BLACK = Button(
    area=(1145, 585, 1280, 720),
    color=(16, 20, 16),
    button=(1145, 585, 1280, 720),
    file="./assets/cn/handler/STORY_LETTER_BLACK.png",
)
STORY_SKIP = Button(
    area=(1216, 676, 1258, 708),
    color=(148, 159, 178),
    button=(1178, 25, 1196, 54),
    file="./assets/cn/handler/STORY_SKIP.png",
)
STORY_SKIP_2 = Button(
    area=(1181, 26, 1225, 40),
    color=(173, 172, 181),
    button=(1181, 26, 1225, 40),
    file="./assets/cn/handler/STORY_SKIP_2.png",
)
STORY_SKIP_3 = Button(
    area=(28, 23, 55, 50),
    color=(192, 199, 209),
    button=(28, 23, 55, 50),
    file="./assets/cn/handler/STORY_SKIP_3.png",
)
STRATEGY_OPEN = Button(
    area=(1198, 411, 1269, 471),
    color=(81, 85, 101),
    button=(1198, 411, 1269, 471),
    file="./assets/cn/handler/STRATEGY_OPEN.png",
)
STRATEGY_OPENED = Button(
    area=(1176, 366, 1275, 393),
    color=(128, 155, 218),
    button=(968, 403, 994, 488),
    file="./assets/cn/handler/STRATEGY_OPENED.png",
)
SUBMARINE_HUNT_OFF = Button(
    area=(1200, 415, 1262, 477),
    color=(125, 127, 132),
    button=(1200, 415, 1262, 477),
    file="./assets/cn/handler/SUBMARINE_HUNT_OFF.png",
)
SUBMARINE_HUNT_ON = Button(
    area=(1200, 415, 1262, 477),
    color=(124, 125, 132),
    button=(1200, 415, 1262, 477),
    file="./assets/cn/handler/SUBMARINE_HUNT_ON.png",
)
SUBMARINE_MOVE_CANCEL = Button(
    area=(891, 647, 1005, 673),
    color=(219, 172, 167),
    button=(891, 647, 1005, 673),
    file="./assets/cn/handler/SUBMARINE_MOVE_CANCEL.png",
)
SUBMARINE_MOVE_CONFIRM = Button(
    area=(1103, 646, 1218, 674),
    color=(157, 185, 222),
    button=(1103, 646, 1218, 674),
    file="./assets/cn/handler/SUBMARINE_MOVE_CONFIRM.png",
)
SUBMARINE_MOVE_ENTER = Button(
    area=(1109, 511, 1169, 571),
    color=(106, 107, 114),
    button=(1109, 511, 1169, 571),
    file="./assets/cn/handler/SUBMARINE_MOVE_ENTER.png",
)
SUBMARINE_VIEW_OFF = Button(
    area=(1140, 435, 1170, 468),
    color=(156, 156, 158),
    button=(1140, 435, 1170, 468),
    file="./assets/cn/handler/SUBMARINE_VIEW_OFF.png",
)
SUBMARINE_VIEW_ON = Button(
    area=(1140, 435, 1170, 468),
    color=(177, 178, 179),
    button=(1140, 435, 1170, 468),
    file="./assets/cn/handler/SUBMARINE_VIEW_ON.png",
)
TEMPLATE_MANJUU = Template(file="./assets/cn/handler/TEMPLATE_MANJUU.png")
USER_AGREEMENT_CONFIRM = Button(
    area=(709, 526, 742, 542),
    color=(151, 216, 243),
    button=(709, 526, 742, 542),
    file="./assets/cn/handler/USER_AGREEMENT_CONFIRM.png",
)
USE_DATA_KEY = Button(
    area=(688, 316, 781, 338),
    color=(165, 154, 99),
    button=(688, 316, 781, 338),
    file="./assets/cn/handler/USE_DATA_KEY.png",
)
USE_DATA_KEY_NOTIFIED = Button(
    area=(690, 185, 713, 207),
    color=(34, 49, 75),
    button=(690, 185, 713, 207),
    file="./assets/cn/handler/USE_DATA_KEY_NOTIFIED.png",
)
VOTE_CANCEL = Button(
    area=(404, 483, 576, 539),
    color=(167, 169, 171),
    button=(404, 483, 576, 539),
    file="./assets/cn/handler/VOTE_CANCEL.png",
)
