from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DORM_BUY_FOOD_CHECK = Button(
    area=(607, 427, 675, 459),
    color=(184, 182, 182),
    button=(607, 427, 675, 459),
    file="./assets/cn/dorm/DORM_BUY_FOOD_CHECK.png",
)
DORM_BUY_FOOD_CONFIRM = Button(
    area=(751, 499, 792, 520),
    color=(255, 238, 186),
    button=(751, 499, 792, 520),
    file="./assets/cn/dorm/DORM_BUY_FOOD_CONFIRM.png",
)
DORM_BUY_FOOD_ENTER = Button(
    area=(866, 375, 888, 398),
    color=(119, 110, 71),
    button=(866, 375, 888, 398),
    file="./assets/cn/dorm/DORM_BUY_FOOD_ENTER.png",
)
DORM_FEED_CHECK = Button(
    area=(162, 342, 274, 370),
    color=(182, 179, 171),
    button=(162, 342, 274, 370),
    file="./assets/cn/dorm/DORM_FEED_CHECK.png",
)
DORM_FEED_ENTER = Button(
    area=(254, 581, 300, 605),
    color=(204, 192, 177),
    button=(254, 581, 300, 605),
    file="./assets/cn/dorm/DORM_FEED_ENTER.png",
)
DORM_FURNITURE_BUY_ALL = Button(
    area=(818, 621, 1072, 677),
    color=(249, 202, 66),
    button=(818, 621, 1072, 677),
    file="./assets/cn/dorm/DORM_FURNITURE_BUY_ALL.png",
)
DORM_FURNITURE_BUY_CONFIRM = Button(
    area=(644, 464, 972, 517),
    color=(251, 204, 66),
    button=(644, 464, 972, 517),
    file="./assets/cn/dorm/DORM_FURNITURE_BUY_CONFIRM.png",
)
DORM_FURNITURE_BUY_SET = Button(
    area=(505, 621, 759, 677),
    color=(248, 202, 66),
    button=(505, 621, 759, 677),
    file="./assets/cn/dorm/DORM_FURNITURE_BUY_SET.png",
)
DORM_FURNITURE_CONFIRM = Button(
    area=(614, 476, 667, 503),
    color=(226, 155, 84),
    button=(614, 476, 667, 503),
    file="./assets/cn/dorm/DORM_FURNITURE_CONFIRM.png",
)
DORM_FURNITURE_COUNTDOWN = Button(
    area=(422, 244, 437, 259),
    color=(222, 222, 224),
    button=(422, 244, 437, 259),
    file="./assets/cn/dorm/DORM_FURNITURE_COUNTDOWN.png",
)
DORM_FURNITURE_DETAILS_ENTER = Button(
    area=(1003, 444, 1259, 496),
    color=(252, 204, 66),
    button=(1003, 444, 1259, 496),
    file="./assets/cn/dorm/DORM_FURNITURE_DETAILS_ENTER.png",
)
DORM_FURNITURE_DETAILS_QUIT = Button(
    area=(100, 121, 114, 141),
    color=(255, 224, 131),
    button=(100, 121, 114, 141),
    file="./assets/cn/dorm/DORM_FURNITURE_DETAILS_QUIT.png",
)
DORM_FURNITURE_SHOP_ENTER = Button(
    area=(1067, 604, 1120, 650),
    color=(255, 226, 130),
    button=(1067, 604, 1120, 650),
    file="./assets/cn/dorm/DORM_FURNITURE_SHOP_ENTER.png",
)
DORM_FURNITURE_SHOP_FIRST = Button(
    area=(241, 565, 271, 572),
    color=(247, 213, 129),
    button=(241, 565, 271, 572),
    file="./assets/cn/dorm/DORM_FURNITURE_SHOP_FIRST.png",
)
DORM_FURNITURE_SHOP_FIRST_SELECTED = Button(
    area=(239, 519, 273, 525),
    color=(242, 205, 114),
    button=(239, 519, 273, 525),
    file="./assets/cn/dorm/DORM_FURNITURE_SHOP_FIRST_SELECTED.png",
)
DORM_FURNITURE_SHOP_QUIT = Button(
    area=(38, 34, 58, 63),
    color=(255, 241, 195),
    button=(38, 34, 58, 63),
    file="./assets/cn/dorm/DORM_FURNITURE_SHOP_QUIT.png",
)
DORM_MANAGE = Button(
    area=(949, 600, 1005, 659),
    color=(255, 245, 213),
    button=(949, 600, 1005, 659),
    file="./assets/cn/dorm/DORM_MANAGE.png",
)
DORM_MANAGE_CHECK = Button(
    area=(1128, 116, 1150, 135),
    color=(173, 147, 77),
    button=(1128, 116, 1150, 135),
    file="./assets/cn/dorm/DORM_MANAGE_CHECK.png",
)
DORM_QUICK_COLLECT = Button(
    area=(1191, 497, 1251, 519),
    color=(243, 194, 138),
    button=(1191, 497, 1251, 519),
    file="./assets/cn/dorm/DORM_QUICK_COLLECT.png",
)
DORM_RED_DOT = Button(
    area=(528, 339, 543, 356),
    color=(214, 126, 114),
    button=(528, 339, 543, 356),
    file="./assets/cn/dorm/DORM_RED_DOT.png",
)
FOOD_MINUS = Button(
    area=(532, 370, 554, 397),
    color=(246, 246, 247),
    button=(532, 370, 554, 397),
    file="./assets/cn/dorm/FOOD_MINUS.png",
)
FOOD_PLUS = Button(
    area=(807, 370, 826, 397),
    color=(248, 248, 248),
    button=(807, 370, 826, 397),
    file="./assets/cn/dorm/FOOD_PLUS.png",
)
OCR_DORM_BUY_FOOD_AMOUNT = Button(
    area=(653, 374, 706, 395),
    color=(203, 203, 204),
    button=(653, 374, 706, 395),
    file="./assets/cn/dorm/OCR_DORM_BUY_FOOD_AMOUNT.png",
)
OCR_DORM_FILL = Button(
    area=(813, 271, 987, 296),
    color=(222, 213, 193),
    button=(813, 271, 987, 296),
    file="./assets/cn/dorm/OCR_DORM_FILL.png",
)
OCR_DORM_FURNITURE_COIN = Button(
    area=(897, 20, 988, 49),
    color=(203, 197, 194),
    button=(897, 20, 988, 49),
    file="./assets/cn/dorm/OCR_DORM_FURNITURE_COIN.png",
)
OCR_DORM_FURNITURE_PRICE = Button(
    area=(819, 417, 896, 442),
    color=(227, 223, 220),
    button=(819, 417, 896, 442),
    file="./assets/cn/dorm/OCR_DORM_FURNITURE_PRICE.png",
)
OCR_DORM_SLOT = Button(
    area=(112, 662, 155, 694),
    color=(217, 217, 217),
    button=(112, 662, 155, 694),
    file="./assets/cn/dorm/OCR_DORM_SLOT.png",
)
