# docker build -f deploy/docker/Dockerfile.cn -t hgjazhgj/alas:latest .
# docker run -v ${PWD}:/app/AzurLaneAutoScript -p 22267:22267 --name alas -it --rm hgjazhgj/alas

FROM python:3.14.6-slim

WORKDIR /app/AzurLaneAutoScript

COPY pyproject.toml .python-version ./

# Use Aliyun Debian mirror.
RUN echo "\
deb https://mirrors.aliyun.com/debian/ trixie main non-free contrib\n\
deb-src https://mirrors.aliyun.com/debian/ trixie main non-free contrib\n\
deb https://mirrors.aliyun.com/debian-security/ trixie-security main\n\
deb-src https://mirrors.aliyun.com/debian-security/ trixie-security main\n\
deb https://mirrors.aliyun.com/debian/ trixie-updates main non-free contrib\n\
deb-src https://mirrors.aliyun.com/debian/ trixie-updates main non-free contrib" \
> /etc/apt/sources.list \
 && apt update \
 && apt install -y git adb libgomp1 openssh-client \
 && apt install -y build-essential pkg-config \
 && apt install -y libavformat-dev libavcodec-dev libavdevice-dev \
 && apt install -y libavutil-dev libswscale-dev libswresample-dev libavfilter-dev \
 && git config --global --add safe.directory '*' \
 && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
 && echo 'Asia/Shanghai' > /etc/timezone \
 && pip install uv \
 && uv sync --python 3.14.6 --index-url https://pypi.tuna.tsinghua.edu.cn/simple \
 && rm -rf ~/.cache/pip ~/.cache/uv

CMD uv run python gui.py
