import sys
from pathlib import Path

import pytest
from PIL import Image

from dev_tools import button_extract
from dev_tools.button_extract import (
    AssetExtractionError,
    AssetExtractor,
    ImageExtractor,
    collect_asset_issues,
    collect_generated_asset_issues,
    validate_assets,
)


def _write_image(path: Path, size: tuple[int, int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    Image.new("RGB", size).save(path)


def _write_generated_assets(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# This file was automatically generated by dev_tools/button_extract.py.\n" + body,
        encoding="utf-8",
    )


def test_asset_validation_aggregates_wrong_resolutions_and_dangling_overrides(tmp_path: Path) -> None:
    first = tmp_path / "first"
    second = tmp_path / "second"
    _write_image(first / "GOOD.png", (1280, 720))
    _write_image(first / "BAD.png", (640, 360))
    _write_image(first / "TEMPLATE_CROPPED.png", (20, 20))
    _write_image(first / "ORPHAN.AREA.png", (1280, 720))
    _write_image(first / "1_IGNORED.png", (20, 20))
    (first / "BROKEN.png").write_bytes(b"not an image")
    _write_image(second / "ALSO_BAD.gif", (100, 100))

    issues = collect_asset_issues(tmp_path)

    assert issues == tuple(sorted(issues))
    assert len(issues) == 4
    assert [Path(issue.file).name for issue in issues] == [
        "BAD.png",
        "BROKEN.png",
        "ORPHAN.AREA.png",
        "ALSO_BAD.gif",
    ]
    assert "wrong resolution: (640, 360)" in issues[0].reason
    assert issues[1].reason.startswith("unreadable image:")
    assert issues[2].reason == "dangling AREA override: base image does not exist"
    assert "wrong resolution: (100, 100)" in issues[3].reason

    with pytest.raises(AssetExtractionError) as exc_info:
        validate_assets(tmp_path)

    assert exc_info.value.issues == issues
    message = str(exc_info.value)
    assert "BAD.png" in message
    assert "BROKEN.png" in message
    assert "ORPHAN.AREA.png" in message
    assert "ALSO_BAD.gif" in message


def test_generated_asset_scan_accepts_string_and_server_mapping_without_importing_module(tmp_path: Path) -> None:
    module_folder = tmp_path / "module"
    first = tmp_path / "assets" / "cn" / "demo" / "FIRST.png"
    second = tmp_path / "assets" / "cn" / "demo" / "SECOND.gif"
    _write_image(first, (1280, 720))
    _write_image(second, (20, 20))
    _write_generated_assets(
        module_folder / "demo" / "assets.py",
        """
import asset_module_that_must_not_be_imported
raise RuntimeError("asset module was imported")

FIRST = Button(file="./assets/cn/demo/FIRST.png")
SECOND = Template(file={"cn": "./assets/cn/demo/SECOND.gif"})
""",
    )
    sys.modules.pop("asset_module_that_must_not_be_imported", None)

    issues = collect_generated_asset_issues(module_folder, repository_root=tmp_path)

    assert issues == ()
    assert "asset_module_that_must_not_be_imported" not in sys.modules


def test_generated_asset_scan_reports_all_missing_string_and_mapping_references(tmp_path: Path) -> None:
    module_folder = tmp_path / "module"
    _write_generated_assets(
        module_folder / "demo" / "assets.py",
        """
FIRST = Button(file="./assets/cn/demo/MISSING.png")
SECOND = Template(file={
    "cn": "./assets/cn/demo/ALSO_MISSING.gif",
    "en": "./assets/cn/demo/MISSING_TOO.png",
})
""",
    )

    issues = collect_generated_asset_issues(module_folder, repository_root=tmp_path)

    assert len(issues) == 3
    assert all("assets.py:" in issue.file for issue in issues)
    assert {Path(issue.reason.removeprefix("missing generated resource reference: ")).name for issue in issues} == {
        "MISSING.png",
        "ALSO_MISSING.gif",
        "MISSING_TOO.png",
    }


def test_image_extractor_rejects_wrong_resolution_directly(tmp_path: Path) -> None:
    file = tmp_path / "BAD.png"
    _write_image(file, (20, 10))

    with pytest.raises(AssetExtractionError, match=r"wrong resolution: \(20, 10\)"):
        ImageExtractor.extract(file)


def test_asset_extractor_validates_all_modules_before_starting_workers(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    assets_folder = tmp_path / "assets"
    _write_image(assets_folder / "cn" / "bad_module" / "BAD.png", (10, 10))
    process_map_calls: list[tuple[object, list[str]]] = []
    monkeypatch.setattr(button_extract.AzurLaneConfig, "ASSETS_FOLDER", assets_folder.as_posix())
    monkeypatch.setattr(button_extract, "MODULE_FOLDER", (tmp_path / "module").as_posix())
    monkeypatch.setattr(
        button_extract,
        "process_map",
        lambda worker, modules: process_map_calls.append((worker, modules)),
    )

    with pytest.raises(AssetExtractionError, match=r"BAD\.png"):
        AssetExtractor()

    assert process_map_calls == []


def test_asset_extractor_scans_generated_references_after_workers(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    assets_folder = tmp_path / "assets"
    module_folder = tmp_path / "module"
    _write_image(assets_folder / "cn" / "demo" / "GOOD.png", (1280, 720))
    _write_generated_assets(
        module_folder / "demo" / "assets.py",
        'GOOD = Button(file="./assets/cn/demo/MISSING.png")\n',
    )
    process_map_calls: list[list[str]] = []
    monkeypatch.setattr(button_extract.AzurLaneConfig, "ASSETS_FOLDER", assets_folder.as_posix())
    monkeypatch.setattr(button_extract, "MODULE_FOLDER", module_folder.as_posix())
    monkeypatch.setattr(button_extract, "process_map", lambda _worker, modules: process_map_calls.append(modules))

    with pytest.raises(AssetExtractionError, match="missing generated resource reference"):
        AssetExtractor()

    assert process_map_calls == [["demo"]]
