from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DETAIL_BLUEPRINT = Button(
    area=(330, 447, 500, 525),
    color=(158, 176, 184),
    button=(330, 447, 500, 525),
    file="./assets/cn/research/DETAIL_BLUEPRINT.png",
)
DETAIL_COST = Button(
    area=(869, 396, 1043, 474),
    color=(170, 168, 131),
    button=(869, 396, 1043, 474),
    file="./assets/cn/research/DETAIL_COST.png",
)
DETAIL_GENRE_B = Button(
    area=(323, 110, 418, 133),
    color=(222, 131, 106),
    button=(323, 110, 418, 133),
    file="./assets/cn/research/DETAIL_GENRE_B.png",
)
DETAIL_GENRE_C = Button(
    area=(323, 110, 418, 133),
    color=(214, 140, 128),
    button=(323, 110, 418, 133),
    file="./assets/cn/research/DETAIL_GENRE_C.png",
)
DETAIL_GENRE_D = Button(
    area=(323, 110, 418, 133),
    color=(216, 136, 123),
    button=(323, 110, 418, 133),
    file="./assets/cn/research/DETAIL_GENRE_D.png",
)
DETAIL_GENRE_E = Button(
    area=(323, 110, 418, 133),
    color=(116, 125, 220),
    button=(323, 110, 418, 133),
    file="./assets/cn/research/DETAIL_GENRE_E.png",
)
DETAIL_GENRE_G = Button(
    area=(323, 110, 418, 133),
    color=(215, 135, 122),
    button=(323, 110, 418, 133),
    file="./assets/cn/research/DETAIL_GENRE_G.png",
)
DETAIL_GENRE_H_0 = Button(
    area=(323, 110, 418, 133),
    color=(217, 141, 128),
    button=(323, 110, 418, 133),
    file="./assets/cn/research/DETAIL_GENRE_H_0.png",
)
DETAIL_GENRE_H_1 = Button(
    area=(323, 110, 418, 133),
    color=(107, 119, 215),
    button=(323, 110, 418, 133),
    file="./assets/cn/research/DETAIL_GENRE_H_1.png",
)
DETAIL_GENRE_Q = Button(
    area=(323, 110, 418, 133),
    color=(118, 126, 220),
    button=(323, 110, 418, 133),
    file="./assets/cn/research/DETAIL_GENRE_Q.png",
)
DETAIL_GENRE_T = Button(
    area=(323, 110, 418, 133),
    color=(113, 122, 219),
    button=(323, 110, 418, 133),
    file="./assets/cn/research/DETAIL_GENRE_T.png",
)
DETAIL_ITEMS_ODD = Button(
    area=(408, 447, 422, 525),
    color=(145, 169, 164),
    button=(408, 447, 422, 525),
    file="./assets/cn/research/DETAIL_ITEMS_ODD.png",
)
DETAIL_NEXT = Button(
    area=(1236, 347, 1257, 374),
    color=(98, 148, 165),
    button=(1236, 347, 1257, 374),
    file="./assets/cn/research/DETAIL_NEXT.png",
)
DURATION_DETAIL = Button(
    area=(788, 274, 913, 319),
    color=(102, 112, 132),
    button=(788, 274, 913, 319),
    file="./assets/cn/research/DURATION_DETAIL.png",
)
ENTRANCE_1 = Button(
    area=(104, 186, 250, 289),
    color=(144, 163, 208),
    button=(104, 186, 250, 289),
    file="./assets/cn/research/ENTRANCE_1.png",
)
ENTRANCE_2 = Button(
    area=(322, 159, 491, 276),
    color=(80, 153, 218),
    button=(322, 159, 491, 276),
    file="./assets/cn/research/ENTRANCE_2.png",
)
ENTRANCE_3 = Button(
    area=(540, 135, 732, 265),
    color=(80, 153, 218),
    button=(540, 135, 732, 265),
    file="./assets/cn/research/ENTRANCE_3.png",
)
ENTRANCE_4 = Button(
    area=(782, 159, 951, 275),
    color=(80, 153, 218),
    button=(782, 159, 951, 275),
    file="./assets/cn/research/ENTRANCE_4.png",
)
ENTRANCE_5 = Button(
    area=(1025, 186, 1169, 287),
    color=(80, 153, 218),
    button=(1025, 186, 1169, 287),
    file="./assets/cn/research/ENTRANCE_5.png",
)
GET_ITEMS_RESEARCH_SAVE = Button(
    area=(357, 643, 497, 701),
    color=(54, 65, 83),
    button=(357, 643, 497, 701),
    file="./assets/cn/research/GET_ITEMS_RESEARCH_SAVE.png",
)
ITEMS_3_SWIPE = Button(
    area=(693, 219, 715, 503),
    color=(78, 70, 55),
    button=(693, 219, 715, 503),
    file="./assets/cn/research/ITEMS_3_SWIPE.png",
)
OCR_RESEARCH_1 = Button(
    area=(78, 277, 249, 330),
    color=(139, 160, 196),
    button=(78, 277, 249, 330),
    file="./assets/cn/research/OCR_RESEARCH_1.png",
)
OCR_RESEARCH_2 = Button(
    area=(292, 263, 490, 325),
    color=(122, 153, 201),
    button=(292, 263, 490, 325),
    file="./assets/cn/research/OCR_RESEARCH_2.png",
)
OCR_RESEARCH_3 = Button(
    area=(505, 249, 730, 319),
    color=(204, 180, 143),
    button=(505, 249, 730, 319),
    file="./assets/cn/research/OCR_RESEARCH_3.png",
)
OCR_RESEARCH_4 = Button(
    area=(752, 263, 950, 325),
    color=(122, 155, 203),
    button=(752, 263, 950, 325),
    file="./assets/cn/research/OCR_RESEARCH_4.png",
)
OCR_RESEARCH_5 = Button(
    area=(998, 276, 1169, 329),
    color=(124, 156, 204),
    button=(998, 276, 1169, 329),
    file="./assets/cn/research/OCR_RESEARCH_5.png",
)
QUEUE_CHECK = Button(
    area=(118, 16, 227, 39),
    color=(149, 166, 205),
    button=(118, 16, 227, 39),
    file="./assets/cn/research/QUEUE_CHECK.png",
)
QUEUE_CLAIM_REWARD = Button(
    area=(1230, 275, 1272, 420),
    color=(249, 182, 121),
    button=(1230, 275, 1272, 420),
    file="./assets/cn/research/QUEUE_CLAIM_REWARD.png",
)
QUEUE_REMAIN = Button(
    area=(156, 605, 272, 637),
    color=(193, 212, 240),
    button=(156, 605, 272, 637),
    file="./assets/cn/research/QUEUE_REMAIN.png",
)
RESEARCH_COST_CHECKER = Button(
    area=(809, 365, 972, 386),
    color=(105, 114, 128),
    button=(809, 365, 972, 386),
    file="./assets/cn/research/RESEARCH_COST_CHECKER.png",
)
RESEARCH_DETAIL_QUIT = Button(
    area=(695, 656, 784, 707),
    color=(50, 57, 74),
    button=(695, 656, 784, 707),
    file="./assets/cn/research/RESEARCH_DETAIL_QUIT.png",
)
RESEARCH_FINISHED = Button(
    area=(384, 547, 502, 585),
    color=(233, 163, 69),
    button=(384, 547, 502, 585),
    file="./assets/cn/research/RESEARCH_FINISHED.png",
)
RESEARCH_GOTO_QUEUE = Button(
    area=(4, 227, 51, 255),
    color=(49, 53, 82),
    button=(4, 227, 51, 255),
    file="./assets/cn/research/RESEARCH_GOTO_QUEUE.png",
)
RESEARCH_LAB = Button(
    area=(55, 518, 186, 559),
    color=(113, 142, 174),
    button=(55, 518, 186, 559),
    file="./assets/cn/research/RESEARCH_LAB.png",
)
RESEARCH_LAB_DURATION_REMAIN = Button(
    area=(379, 583, 504, 614),
    color=(158, 157, 158),
    button=(379, 583, 504, 614),
    file="./assets/cn/research/RESEARCH_LAB_DURATION_REMAIN.png",
)
RESEARCH_PENDING = Button(
    area=(227, 589, 269, 607),
    color=(108, 163, 168),
    button=(227, 589, 269, 607),
    file="./assets/cn/research/RESEARCH_PENDING.png",
)
RESEARCH_QUEUE_ADD = Button(
    area=(541, 570, 654, 595),
    color=(164, 203, 237),
    button=(517, 560, 678, 603),
    file="./assets/cn/research/RESEARCH_QUEUE_ADD.png",
)
RESEARCH_RUNNING = Button(
    area=(313, 556, 362, 619),
    color=(124, 126, 131),
    button=(313, 556, 362, 619),
    file="./assets/cn/research/RESEARCH_RUNNING.png",
)
RESEARCH_START = Button(
    area=(445, 569, 568, 597),
    color=(173, 211, 242),
    button=(445, 569, 568, 597),
    file="./assets/cn/research/RESEARCH_START.png",
)
RESEARCH_STOP = Button(
    area=(329, 561, 485, 602),
    color=(228, 138, 117),
    button=(329, 561, 485, 602),
    file="./assets/cn/research/RESEARCH_STOP.png",
)
RESEARCH_UNAVAILABLE = Button(
    area=(509, 569, 568, 597),
    color=(185, 191, 194),
    button=(509, 569, 568, 597),
    file="./assets/cn/research/RESEARCH_UNAVAILABLE.png",
)
RESET_AVAILABLE = Button(
    area=(1153, 662, 1227, 679),
    color=(101, 118, 152),
    button=(1153, 662, 1227, 679),
    file="./assets/cn/research/RESET_AVAILABLE.png",
)
SERIES_1 = Button(
    area=(86, 154, 113, 173),
    color=(197, 108, 91),
    button=(86, 154, 113, 173),
    file="./assets/cn/research/SERIES_1.png",
)
SERIES_2 = Button(
    area=(301, 122, 332, 144),
    color=(199, 112, 96),
    button=(301, 122, 332, 144),
    file="./assets/cn/research/SERIES_2.png",
)
SERIES_3 = Button(
    area=(516, 89, 551, 114),
    color=(75, 98, 210),
    button=(516, 89, 551, 114),
    file="./assets/cn/research/SERIES_3.png",
)
SERIES_4 = Button(
    area=(761, 122, 792, 144),
    color=(199, 114, 102),
    button=(761, 122, 792, 144),
    file="./assets/cn/research/SERIES_4.png",
)
SERIES_5 = Button(
    area=(1006, 154, 1033, 173),
    color=(203, 127, 114),
    button=(1006, 154, 1033, 173),
    file="./assets/cn/research/SERIES_5.png",
)
SERIES_DETAIL = Button(
    area=(301, 102, 335, 127),
    color=(217, 141, 124),
    button=(301, 102, 335, 127),
    file="./assets/cn/research/SERIES_DETAIL.png",
)
STABLE_CHECKER = Button(
    area=(776, 324, 1245, 622),
    color=(124, 142, 164),
    button=(776, 324, 1245, 622),
    file="./assets/cn/research/STABLE_CHECKER.png",
)
STABLE_CHECKER_CENTER = Button(
    area=(506, 524, 770, 684),
    color=(155, 154, 156),
    button=(506, 524, 770, 684),
    file="./assets/cn/research/STABLE_CHECKER_CENTER.png",
)
STATUS_1 = Button(
    area=(111, 541, 117, 547),
    color=(132, 166, 222),
    button=(111, 541, 117, 547),
    file="./assets/cn/research/STATUS_1.png",
)
STATUS_2 = Button(
    area=(330, 570, 336, 576),
    color=(115, 166, 222),
    button=(330, 570, 336, 576),
    file="./assets/cn/research/STATUS_2.png",
)
STATUS_3 = Button(
    area=(549, 598, 556, 605),
    color=(115, 166, 222),
    button=(549, 598, 556, 605),
    file="./assets/cn/research/STATUS_3.png",
)
STATUS_4 = Button(
    area=(790, 570, 796, 576),
    color=(115, 166, 222),
    button=(790, 570, 796, 576),
    file="./assets/cn/research/STATUS_4.png",
)
STATUS_5 = Button(
    area=(1031, 541, 1037, 547),
    color=(115, 166, 222),
    button=(1031, 541, 1037, 547),
    file="./assets/cn/research/STATUS_5.png",
)
TEMPLATE_DETAIL = Template(file="./assets/cn/research/TEMPLATE_DETAIL.png")
TEMPLATE_RUNNING = Template(file="./assets/cn/research/TEMPLATE_RUNNING.png")
TEMPLATE_S1 = Template(file="./assets/cn/research/TEMPLATE_S1.png")
TEMPLATE_S2 = Template(file="./assets/cn/research/TEMPLATE_S2.png")
TEMPLATE_S3 = Template(file="./assets/cn/research/TEMPLATE_S3.png")
TEMPLATE_S4 = Template(file="./assets/cn/research/TEMPLATE_S4.png")
TEMPLATE_S4_2 = Template(file="./assets/cn/research/TEMPLATE_S4_2.png")
TEMPLATE_S5 = Template(file="./assets/cn/research/TEMPLATE_S5.png")
TEMPLATE_S6 = Template(file="./assets/cn/research/TEMPLATE_S6.png")
TEMPLATE_S7 = Template(file="./assets/cn/research/TEMPLATE_S7.png")
TEMPLATE_S8 = Template(file="./assets/cn/research/TEMPLATE_S8.png")
TEMPLATE_WAITING = Template(file="./assets/cn/research/TEMPLATE_WAITING.png")
