# 此文件由 dev_tools/research_extractor.py 自动生成。
# 不要手动修改。

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from module.research.types import ResearchProjectData


LIST_RESEARCH_PROJECT: list[ResearchProjectData] = [
    {
        "name": "C-153-MI",
        "series": 1,
        "time": 21600,
    },
    {
        "name": "C-185-MI",
        "series": 1,
        "time": 28800,
    },
    {
        "name": "B-622-MI",
        "series": 1,
        "time": 14400,
    },
    {
        "name": "B-636-MI",
        "series": 1,
        "time": 14400,
    },
    {
        "name": "B-654-MI",
        "series": 1,
        "time": 14400,
    },
    {
        "name": "B-682-MI",
        "series": 1,
        "time": 14400,
    },
    {
        "name": "B-235-MI",
        "series": 1,
        "time": 14400,
    },
    {
        "name": "B-268-MI",
        "series": 1,
        "time": 14400,
    },
    {
        "name": "B-128-MI",
        "series": 1,
        "time": 14400,
    },
    {
        "name": "B-164-MI",
        "series": 1,
        "time": 14400,
    },
    {
        "name": "T-018-MI",
        "series": 1,
        "time": 10800,
    },
    {
        "name": "T-384-MI",
        "series": 1,
        "time": 14400,
    },
    {
        "name": "T-249-MI",
        "series": 1,
        "time": 21600,
    },
    {
        "name": "E-031-MI",
        "series": 1,
        "time": 7200,
        "equipment_amount": 8,
    },
    {
        "name": "E-315-MI",
        "series": 1,
        "time": 7200,
        "equipment_amount": 15,
    },
    {
        "name": "E-131-MI",
        "series": 1,
        "time": 21600,
    },
    {
        "name": "E-159-MI",
        "series": 1,
        "time": 21600,
    },
    {
        "name": "E-174-MI",
        "series": 1,
        "time": 21600,
    },
    {
        "name": "E-192-MI",
        "series": 1,
        "time": 21600,
    },
    {
        "name": "E-118-MI",
        "series": 1,
        "time": 21600,
    },
    {
        "name": "E-144-MI",
        "series": 1,
        "time": 21600,
    },
    {
        "name": "G-412-MI",
        "series": 1,
        "time": 5400,
        "need_coin": True,
    },
    {
        "name": "G-236-MI",
        "series": 1,
        "time": 9000,
        "need_coin": True,
    },
    {
        "name": "G-531-MI",
        "series": 1,
        "time": 14400,
        "need_coin": True,
    },
    {
        "name": "D-718-MI",
        "series": 1,
        "time": 9000,
        "need_coin": True,
        "ship": "neptune",
        "ship_rarity": "pry",
    },
    {
        "name": "D-731-MI",
        "series": 1,
        "time": 9000,
        "need_coin": True,
        "ship": "monarch",
        "ship_rarity": "pry",
    },
    {
        "name": "D-744-MI",
        "series": 1,
        "time": 9000,
        "need_coin": True,
        "ship": "ibuki",
        "ship_rarity": "pry",
    },
    {
        "name": "D-759-MI",
        "series": 1,
        "time": 9000,
        "need_coin": True,
        "ship": "izumo",
        "ship_rarity": "pry",
    },
    {
        "name": "D-774-MI",
        "series": 1,
        "time": 9000,
        "need_coin": True,
        "ship": "roon",
        "ship_rarity": "pry",
    },
    {
        "name": "D-792-MI",
        "series": 1,
        "time": 9000,
        "need_coin": True,
        "ship": "saintlouis",
        "ship_rarity": "pry",
    },
    {
        "name": "D-318-MI",
        "series": 1,
        "time": 18000,
        "need_coin": True,
        "ship": "neptune",
        "ship_rarity": "pry",
    },
    {
        "name": "D-331-MI",
        "series": 1,
        "time": 18000,
        "need_coin": True,
        "ship": "monarch",
        "ship_rarity": "pry",
    },
    {
        "name": "D-344-MI",
        "series": 1,
        "time": 18000,
        "need_coin": True,
        "ship": "ibuki",
        "ship_rarity": "pry",
    },
    {
        "name": "D-359-MI",
        "series": 1,
        "time": 18000,
        "need_coin": True,
        "ship": "izumo",
        "ship_rarity": "pry",
    },
    {
        "name": "D-374-MI",
        "series": 1,
        "time": 18000,
        "need_coin": True,
        "ship": "roon",
        "ship_rarity": "pry",
    },
    {
        "name": "D-392-MI",
        "series": 1,
        "time": 18000,
        "need_coin": True,
        "ship": "saintlouis",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-302-MI",
        "series": 1,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-310-MI",
        "series": 1,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-351-MI",
        "series": 1,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-368-MI",
        "series": 1,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-389-MI",
        "series": 1,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-202-MI",
        "series": 1,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-210-MI",
        "series": 1,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-251-MI",
        "series": 1,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-268-MI",
        "series": 1,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-289-MI",
        "series": 1,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-002-MI",
        "series": 1,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-010-MI",
        "series": 1,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-051-MI",
        "series": 1,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-068-MI",
        "series": 1,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-089-MI",
        "series": 1,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "H-387-MI",
        "series": 1,
        "time": 3600,
        "need_cube": True,
    },
    {
        "name": "H-339-MI",
        "series": 1,
        "time": 7200,
        "need_cube": True,
    },
    {
        "name": "C-153-MI",
        "series": 2,
        "time": 21600,
    },
    {
        "name": "C-185-MI",
        "series": 2,
        "time": 28800,
    },
    {
        "name": "B-622-MI",
        "series": 2,
        "time": 14400,
    },
    {
        "name": "B-636-MI",
        "series": 2,
        "time": 14400,
    },
    {
        "name": "B-654-MI",
        "series": 2,
        "time": 14400,
    },
    {
        "name": "B-682-MI",
        "series": 2,
        "time": 14400,
    },
    {
        "name": "B-235-MI",
        "series": 2,
        "time": 14400,
    },
    {
        "name": "B-268-MI",
        "series": 2,
        "time": 14400,
    },
    {
        "name": "B-128-MI",
        "series": 2,
        "time": 14400,
    },
    {
        "name": "B-164-MI",
        "series": 2,
        "time": 14400,
    },
    {
        "name": "T-018-MI",
        "series": 2,
        "time": 10800,
    },
    {
        "name": "T-384-MI",
        "series": 2,
        "time": 14400,
    },
    {
        "name": "T-249-MI",
        "series": 2,
        "time": 21600,
    },
    {
        "name": "E-031-MI",
        "series": 2,
        "time": 7200,
        "equipment_amount": 8,
    },
    {
        "name": "E-315-MI",
        "series": 2,
        "time": 7200,
        "equipment_amount": 15,
    },
    {
        "name": "E-179-MI",
        "series": 2,
        "time": 21600,
    },
    {
        "name": "E-105-MI",
        "series": 2,
        "time": 21600,
    },
    {
        "name": "E-146-MI",
        "series": 2,
        "time": 21600,
    },
    {
        "name": "E-157-MI",
        "series": 2,
        "time": 21600,
    },
    {
        "name": "E-194-MI",
        "series": 2,
        "time": 21600,
    },
    {
        "name": "G-412-MI",
        "series": 2,
        "time": 5400,
        "need_coin": True,
    },
    {
        "name": "G-236-MI",
        "series": 2,
        "time": 9000,
        "need_coin": True,
    },
    {
        "name": "G-531-MI",
        "series": 2,
        "time": 14400,
        "need_coin": True,
    },
    {
        "name": "D-705-MI",
        "series": 2,
        "time": 9000,
        "need_coin": True,
        "ship": "seattle",
        "ship_rarity": "pry",
    },
    {
        "name": "D-712-MI",
        "series": 2,
        "time": 9000,
        "need_coin": True,
        "ship": "georgia",
        "ship_rarity": "pry",
    },
    {
        "name": "D-746-MI",
        "series": 2,
        "time": 9000,
        "need_coin": True,
        "ship": "kitakaze",
        "ship_rarity": "pry",
    },
    {
        "name": "D-757-MI",
        "series": 2,
        "time": 9000,
        "need_coin": True,
        "ship": "azuma",
        "ship_rarity": "dr",
    },
    {
        "name": "D-779-MI",
        "series": 2,
        "time": 9000,
        "need_coin": True,
        "ship": "friedrich",
        "ship_rarity": "dr",
    },
    {
        "name": "D-794-MI",
        "series": 2,
        "time": 9000,
        "need_coin": True,
        "ship": "gascogne",
        "ship_rarity": "pry",
    },
    {
        "name": "D-305-MI",
        "series": 2,
        "time": 18000,
        "need_coin": True,
        "ship": "seattle",
        "ship_rarity": "pry",
    },
    {
        "name": "D-312-MI",
        "series": 2,
        "time": 18000,
        "need_coin": True,
        "ship": "georgia",
        "ship_rarity": "pry",
    },
    {
        "name": "D-346-MI",
        "series": 2,
        "time": 18000,
        "need_coin": True,
        "ship": "kitakaze",
        "ship_rarity": "pry",
    },
    {
        "name": "D-357-MI",
        "series": 2,
        "time": 18000,
        "need_coin": True,
        "ship": "azuma",
        "ship_rarity": "dr",
    },
    {
        "name": "D-379-MI",
        "series": 2,
        "time": 18000,
        "need_coin": True,
        "ship": "friedrich",
        "ship_rarity": "dr",
    },
    {
        "name": "D-394-MI",
        "series": 2,
        "time": 18000,
        "need_coin": True,
        "ship": "gascogne",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-302-MI",
        "series": 2,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-310-MI",
        "series": 2,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-351-MI",
        "series": 2,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-368-MI",
        "series": 2,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-389-MI",
        "series": 2,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-202-MI",
        "series": 2,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-210-MI",
        "series": 2,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-251-MI",
        "series": 2,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-268-MI",
        "series": 2,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-289-MI",
        "series": 2,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-002-MI",
        "series": 2,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-010-MI",
        "series": 2,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-051-MI",
        "series": 2,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-068-MI",
        "series": 2,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-089-MI",
        "series": 2,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "H-387-MI",
        "series": 2,
        "time": 3600,
        "need_cube": True,
    },
    {
        "name": "H-339-MI",
        "series": 2,
        "time": 7200,
        "need_cube": True,
    },
    {
        "name": "C-153-MI",
        "series": 3,
        "time": 21600,
    },
    {
        "name": "C-185-MI",
        "series": 3,
        "time": 28800,
    },
    {
        "name": "B-622-MI",
        "series": 3,
        "time": 14400,
    },
    {
        "name": "B-636-MI",
        "series": 3,
        "time": 14400,
    },
    {
        "name": "B-654-MI",
        "series": 3,
        "time": 14400,
    },
    {
        "name": "B-682-MI",
        "series": 3,
        "time": 14400,
    },
    {
        "name": "B-235-MI",
        "series": 3,
        "time": 14400,
    },
    {
        "name": "B-268-MI",
        "series": 3,
        "time": 14400,
    },
    {
        "name": "B-128-MI",
        "series": 3,
        "time": 14400,
    },
    {
        "name": "B-164-MI",
        "series": 3,
        "time": 14400,
    },
    {
        "name": "T-018-MI",
        "series": 3,
        "time": 10800,
    },
    {
        "name": "T-384-MI",
        "series": 3,
        "time": 14400,
    },
    {
        "name": "T-249-MI",
        "series": 3,
        "time": 21600,
    },
    {
        "name": "E-031-MI",
        "series": 3,
        "time": 7200,
        "equipment_amount": 8,
    },
    {
        "name": "E-315-MI",
        "series": 3,
        "time": 7200,
        "equipment_amount": 15,
    },
    {
        "name": "E-121-MI",
        "series": 3,
        "time": 21600,
    },
    {
        "name": "E-123-MI",
        "series": 3,
        "time": 21600,
    },
    {
        "name": "E-124-MI",
        "series": 3,
        "time": 21600,
    },
    {
        "name": "E-177-MI",
        "series": 3,
        "time": 21600,
    },
    {
        "name": "E-195-MI",
        "series": 3,
        "time": 21600,
    },
    {
        "name": "G-412-MI",
        "series": 3,
        "time": 5400,
        "need_coin": True,
    },
    {
        "name": "G-236-MI",
        "series": 3,
        "time": 9000,
        "need_coin": True,
    },
    {
        "name": "G-531-MI",
        "series": 3,
        "time": 14400,
        "need_coin": True,
    },
    {
        "name": "D-721-MI",
        "series": 3,
        "time": 9000,
        "need_coin": True,
        "ship": "cheshire",
        "ship_rarity": "pry",
    },
    {
        "name": "D-722-MI",
        "series": 3,
        "time": 9000,
        "need_coin": True,
        "ship": "drake",
        "ship_rarity": "dr",
    },
    {
        "name": "D-772-MI",
        "series": 3,
        "time": 9000,
        "need_coin": True,
        "ship": "mainz",
        "ship_rarity": "pry",
    },
    {
        "name": "D-777-MI",
        "series": 3,
        "time": 9000,
        "need_coin": True,
        "ship": "odin",
        "ship_rarity": "pry",
    },
    {
        "name": "D-795-MI",
        "series": 3,
        "time": 9000,
        "need_coin": True,
        "ship": "champagne",
        "ship_rarity": "pry",
    },
    {
        "name": "D-321-MI",
        "series": 3,
        "time": 18000,
        "need_coin": True,
        "ship": "cheshire",
        "ship_rarity": "pry",
    },
    {
        "name": "D-322-MI",
        "series": 3,
        "time": 18000,
        "need_coin": True,
        "ship": "drake",
        "ship_rarity": "dr",
    },
    {
        "name": "D-372-MI",
        "series": 3,
        "time": 18000,
        "need_coin": True,
        "ship": "mainz",
        "ship_rarity": "pry",
    },
    {
        "name": "D-377-MI",
        "series": 3,
        "time": 18000,
        "need_coin": True,
        "ship": "odin",
        "ship_rarity": "pry",
    },
    {
        "name": "D-395-MI",
        "series": 3,
        "time": 18000,
        "need_coin": True,
        "ship": "champagne",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-302-MI",
        "series": 3,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-310-MI",
        "series": 3,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-351-MI",
        "series": 3,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-368-MI",
        "series": 3,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-389-MI",
        "series": 3,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-202-MI",
        "series": 3,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-210-MI",
        "series": 3,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-251-MI",
        "series": 3,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-268-MI",
        "series": 3,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-289-MI",
        "series": 3,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-002-MI",
        "series": 3,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-010-MI",
        "series": 3,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-051-MI",
        "series": 3,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-068-MI",
        "series": 3,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-089-MI",
        "series": 3,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "H-387-MI",
        "series": 3,
        "time": 3600,
        "need_cube": True,
    },
    {
        "name": "H-339-MI",
        "series": 3,
        "time": 7200,
        "need_cube": True,
    },
    {
        "name": "C-153-MI",
        "series": 4,
        "time": 21600,
    },
    {
        "name": "C-185-MI",
        "series": 4,
        "time": 28800,
    },
    {
        "name": "B-622-MI",
        "series": 4,
        "time": 14400,
    },
    {
        "name": "B-636-MI",
        "series": 4,
        "time": 14400,
    },
    {
        "name": "B-654-MI",
        "series": 4,
        "time": 14400,
    },
    {
        "name": "B-682-MI",
        "series": 4,
        "time": 14400,
    },
    {
        "name": "B-235-MI",
        "series": 4,
        "time": 14400,
    },
    {
        "name": "B-268-MI",
        "series": 4,
        "time": 14400,
    },
    {
        "name": "B-128-MI",
        "series": 4,
        "time": 14400,
    },
    {
        "name": "B-164-MI",
        "series": 4,
        "time": 14400,
    },
    {
        "name": "T-018-MI",
        "series": 4,
        "time": 10800,
    },
    {
        "name": "T-384-MI",
        "series": 4,
        "time": 14400,
    },
    {
        "name": "T-249-MI",
        "series": 4,
        "time": 21600,
    },
    {
        "name": "E-031-MI",
        "series": 4,
        "time": 7200,
        "equipment_amount": 8,
    },
    {
        "name": "E-315-MI",
        "series": 4,
        "time": 7200,
        "equipment_amount": 15,
    },
    {
        "name": "E-175-MI",
        "series": 4,
        "time": 21600,
    },
    {
        "name": "E-182-MI",
        "series": 4,
        "time": 21600,
    },
    {
        "name": "E-168-MI",
        "series": 4,
        "time": 21600,
    },
    {
        "name": "E-108-MI",
        "series": 4,
        "time": 21600,
    },
    {
        "name": "E-163-MI",
        "series": 4,
        "time": 21600,
    },
    {
        "name": "G-412-MI",
        "series": 4,
        "time": 5400,
        "need_coin": True,
    },
    {
        "name": "G-236-MI",
        "series": 4,
        "time": 9000,
        "need_coin": True,
    },
    {
        "name": "G-531-MI",
        "series": 4,
        "time": 14400,
        "need_coin": True,
    },
    {
        "name": "D-708-MI",
        "series": 4,
        "time": 9000,
        "need_coin": True,
        "ship": "anchorage",
        "ship_rarity": "pry",
    },
    {
        "name": "D-763-MI",
        "series": 4,
        "time": 9000,
        "need_coin": True,
        "ship": "hakuryu",
        "ship_rarity": "dr",
    },
    {
        "name": "D-775-MI",
        "series": 4,
        "time": 9000,
        "need_coin": True,
        "ship": "agir",
        "ship_rarity": "dr",
    },
    {
        "name": "D-782-MI",
        "series": 4,
        "time": 9000,
        "need_coin": True,
        "ship": "august",
        "ship_rarity": "pry",
    },
    {
        "name": "D-768-MI",
        "series": 4,
        "time": 9000,
        "need_coin": True,
        "ship": "marcopolo",
        "ship_rarity": "pry",
    },
    {
        "name": "D-308-MI",
        "series": 4,
        "time": 18000,
        "need_coin": True,
        "ship": "anchorage",
        "ship_rarity": "pry",
    },
    {
        "name": "D-363-MI",
        "series": 4,
        "time": 18000,
        "need_coin": True,
        "ship": "hakuryu",
        "ship_rarity": "dr",
    },
    {
        "name": "D-375-MI",
        "series": 4,
        "time": 18000,
        "need_coin": True,
        "ship": "agir",
        "ship_rarity": "dr",
    },
    {
        "name": "D-382-MI",
        "series": 4,
        "time": 18000,
        "need_coin": True,
        "ship": "august",
        "ship_rarity": "pry",
    },
    {
        "name": "D-368-MI",
        "series": 4,
        "time": 18000,
        "need_coin": True,
        "ship": "marcopolo",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-302-MI",
        "series": 4,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-310-MI",
        "series": 4,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-351-MI",
        "series": 4,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-368-MI",
        "series": 4,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-389-MI",
        "series": 4,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-202-MI",
        "series": 4,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-210-MI",
        "series": 4,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-251-MI",
        "series": 4,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-268-MI",
        "series": 4,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-289-MI",
        "series": 4,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-002-MI",
        "series": 4,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-010-MI",
        "series": 4,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-051-MI",
        "series": 4,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-068-MI",
        "series": 4,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-089-MI",
        "series": 4,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "H-387-MI",
        "series": 4,
        "time": 3600,
        "need_cube": True,
    },
    {
        "name": "H-339-MI",
        "series": 4,
        "time": 7200,
        "need_cube": True,
    },
    {
        "name": "C-153-MI",
        "series": 5,
        "time": 21600,
    },
    {
        "name": "C-185-MI",
        "series": 5,
        "time": 28800,
    },
    {
        "name": "B-622-MI",
        "series": 5,
        "time": 14400,
    },
    {
        "name": "B-636-MI",
        "series": 5,
        "time": 14400,
    },
    {
        "name": "B-654-MI",
        "series": 5,
        "time": 14400,
    },
    {
        "name": "B-682-MI",
        "series": 5,
        "time": 14400,
    },
    {
        "name": "B-235-MI",
        "series": 5,
        "time": 14400,
    },
    {
        "name": "B-268-MI",
        "series": 5,
        "time": 14400,
    },
    {
        "name": "B-128-MI",
        "series": 5,
        "time": 14400,
    },
    {
        "name": "B-164-MI",
        "series": 5,
        "time": 14400,
    },
    {
        "name": "T-018-MI",
        "series": 5,
        "time": 10800,
    },
    {
        "name": "T-384-MI",
        "series": 5,
        "time": 14400,
    },
    {
        "name": "T-249-MI",
        "series": 5,
        "time": 21600,
    },
    {
        "name": "E-031-MI",
        "series": 5,
        "time": 7200,
        "equipment_amount": 8,
    },
    {
        "name": "E-315-MI",
        "series": 5,
        "time": 7200,
        "equipment_amount": 15,
    },
    {
        "name": "E-193-MI",
        "series": 5,
        "time": 21600,
    },
    {
        "name": "E-178-MI",
        "series": 5,
        "time": 21600,
    },
    {
        "name": "E-186-MI",
        "series": 5,
        "time": 21600,
    },
    {
        "name": "E-188-MI",
        "series": 5,
        "time": 21600,
    },
    {
        "name": "E-189-MI",
        "series": 5,
        "time": 21600,
    },
    {
        "name": "G-412-MI",
        "series": 5,
        "time": 5400,
        "need_coin": True,
    },
    {
        "name": "G-236-MI",
        "series": 5,
        "time": 9000,
        "need_coin": True,
    },
    {
        "name": "G-531-MI",
        "series": 5,
        "time": 14400,
        "need_coin": True,
    },
    {
        "name": "D-719-MI",
        "series": 5,
        "time": 9000,
        "need_coin": True,
        "ship": "plymouth",
        "ship_rarity": "dr",
    },
    {
        "name": "D-778-MI",
        "series": 5,
        "time": 9000,
        "need_coin": True,
        "ship": "rupprecht",
        "ship_rarity": "pry",
    },
    {
        "name": "D-786-MI",
        "series": 5,
        "time": 9000,
        "need_coin": True,
        "ship": "harbin",
        "ship_rarity": "pry",
    },
    {
        "name": "D-788-MI",
        "series": 5,
        "time": 9000,
        "need_coin": True,
        "ship": "chkalov",
        "ship_rarity": "pry",
    },
    {
        "name": "D-793-MI",
        "series": 5,
        "time": 9000,
        "need_coin": True,
        "ship": "brest",
        "ship_rarity": "dr",
    },
    {
        "name": "D-319-MI",
        "series": 5,
        "time": 18000,
        "need_coin": True,
        "ship": "plymouth",
        "ship_rarity": "dr",
    },
    {
        "name": "D-378-MI",
        "series": 5,
        "time": 18000,
        "need_coin": True,
        "ship": "rupprecht",
        "ship_rarity": "pry",
    },
    {
        "name": "D-386-MI",
        "series": 5,
        "time": 18000,
        "need_coin": True,
        "ship": "harbin",
        "ship_rarity": "pry",
    },
    {
        "name": "D-388-MI",
        "series": 5,
        "time": 18000,
        "need_coin": True,
        "ship": "chkalov",
        "ship_rarity": "pry",
    },
    {
        "name": "D-393-MI",
        "series": 5,
        "time": 18000,
        "need_coin": True,
        "ship": "brest",
        "ship_rarity": "dr",
    },
    {
        "name": "Q-302-MI",
        "series": 5,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-310-MI",
        "series": 5,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-351-MI",
        "series": 5,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-368-MI",
        "series": 5,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-389-MI",
        "series": 5,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-202-MI",
        "series": 5,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-210-MI",
        "series": 5,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-251-MI",
        "series": 5,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-268-MI",
        "series": 5,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-289-MI",
        "series": 5,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-002-MI",
        "series": 5,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-010-MI",
        "series": 5,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-051-MI",
        "series": 5,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-068-MI",
        "series": 5,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-089-MI",
        "series": 5,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "H-387-MI",
        "series": 5,
        "time": 3600,
        "need_cube": True,
    },
    {
        "name": "H-339-MI",
        "series": 5,
        "time": 7200,
        "need_cube": True,
    },
    {
        "name": "C-153-MI",
        "series": 6,
        "time": 21600,
    },
    {
        "name": "C-185-MI",
        "series": 6,
        "time": 28800,
    },
    {
        "name": "B-622-MI",
        "series": 6,
        "time": 14400,
    },
    {
        "name": "B-636-MI",
        "series": 6,
        "time": 14400,
    },
    {
        "name": "B-654-MI",
        "series": 6,
        "time": 14400,
    },
    {
        "name": "B-682-MI",
        "series": 6,
        "time": 14400,
    },
    {
        "name": "B-235-MI",
        "series": 6,
        "time": 14400,
    },
    {
        "name": "B-268-MI",
        "series": 6,
        "time": 14400,
    },
    {
        "name": "B-128-MI",
        "series": 6,
        "time": 14400,
    },
    {
        "name": "B-164-MI",
        "series": 6,
        "time": 14400,
    },
    {
        "name": "T-018-MI",
        "series": 6,
        "time": 10800,
    },
    {
        "name": "T-384-MI",
        "series": 6,
        "time": 14400,
    },
    {
        "name": "T-249-MI",
        "series": 6,
        "time": 21600,
    },
    {
        "name": "E-031-MI",
        "series": 6,
        "time": 7200,
        "equipment_amount": 8,
    },
    {
        "name": "E-315-MI",
        "series": 6,
        "time": 7200,
        "equipment_amount": 15,
    },
    {
        "name": "E-113-MI",
        "series": 6,
        "time": 21600,
    },
    {
        "name": "E-139-MI",
        "series": 6,
        "time": 21600,
    },
    {
        "name": "E-171-MI",
        "series": 6,
        "time": 21600,
    },
    {
        "name": "E-196-MI",
        "series": 6,
        "time": 21600,
    },
    {
        "name": "E-184-MI",
        "series": 6,
        "time": 21600,
    },
    {
        "name": "G-412-MI",
        "series": 6,
        "time": 5400,
        "need_coin": True,
    },
    {
        "name": "G-236-MI",
        "series": 6,
        "time": 9000,
        "need_coin": True,
    },
    {
        "name": "G-531-MI",
        "series": 6,
        "time": 14400,
        "need_coin": True,
    },
    {
        "name": "D-783-MI",
        "series": 6,
        "time": 9000,
        "need_coin": True,
        "ship": "hindenburg",
        "ship_rarity": "dr",
    },
    {
        "name": "D-713-MI",
        "series": 6,
        "time": 9000,
        "need_coin": True,
        "ship": "kearsarge",
        "ship_rarity": "dr",
    },
    {
        "name": "D-739-MI",
        "series": 6,
        "time": 9000,
        "need_coin": True,
        "ship": "shimanto",
        "ship_rarity": "pry",
    },
    {
        "name": "D-771-MI",
        "series": 6,
        "time": 9000,
        "need_coin": True,
        "ship": "schultz",
        "ship_rarity": "pry",
    },
    {
        "name": "D-796-MI",
        "series": 6,
        "time": 9000,
        "need_coin": True,
        "ship": "flandre",
        "ship_rarity": "pry",
    },
    {
        "name": "D-383-MI",
        "series": 6,
        "time": 18000,
        "need_coin": True,
        "ship": "hindenburg",
        "ship_rarity": "dr",
    },
    {
        "name": "D-313-MI",
        "series": 6,
        "time": 18000,
        "need_coin": True,
        "ship": "kearsarge",
        "ship_rarity": "dr",
    },
    {
        "name": "D-339-MI",
        "series": 6,
        "time": 18000,
        "need_coin": True,
        "ship": "shimanto",
        "ship_rarity": "pry",
    },
    {
        "name": "D-371-MI",
        "series": 6,
        "time": 18000,
        "need_coin": True,
        "ship": "schultz",
        "ship_rarity": "pry",
    },
    {
        "name": "D-396-MI",
        "series": 6,
        "time": 18000,
        "need_coin": True,
        "ship": "flandre",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-302-MI",
        "series": 6,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-310-MI",
        "series": 6,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-351-MI",
        "series": 6,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-368-MI",
        "series": 6,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-389-MI",
        "series": 6,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-202-MI",
        "series": 6,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-210-MI",
        "series": 6,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-251-MI",
        "series": 6,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-268-MI",
        "series": 6,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-289-MI",
        "series": 6,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-002-MI",
        "series": 6,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-010-MI",
        "series": 6,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-051-MI",
        "series": 6,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-068-MI",
        "series": 6,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-089-MI",
        "series": 6,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "H-387-MI",
        "series": 6,
        "time": 3600,
        "need_cube": True,
    },
    {
        "name": "H-339-MI",
        "series": 6,
        "time": 7200,
        "need_cube": True,
    },
    {
        "name": "C-153-MI",
        "series": 7,
        "time": 21600,
    },
    {
        "name": "C-185-MI",
        "series": 7,
        "time": 28800,
    },
    {
        "name": "B-622-MI",
        "series": 7,
        "time": 14400,
    },
    {
        "name": "B-636-MI",
        "series": 7,
        "time": 14400,
    },
    {
        "name": "B-654-MI",
        "series": 7,
        "time": 14400,
    },
    {
        "name": "B-682-MI",
        "series": 7,
        "time": 14400,
    },
    {
        "name": "B-235-MI",
        "series": 7,
        "time": 14400,
    },
    {
        "name": "B-268-MI",
        "series": 7,
        "time": 14400,
    },
    {
        "name": "B-128-MI",
        "series": 7,
        "time": 14400,
    },
    {
        "name": "B-164-MI",
        "series": 7,
        "time": 14400,
    },
    {
        "name": "T-018-MI",
        "series": 7,
        "time": 10800,
    },
    {
        "name": "T-384-MI",
        "series": 7,
        "time": 14400,
    },
    {
        "name": "T-249-MI",
        "series": 7,
        "time": 21600,
    },
    {
        "name": "E-031-MI",
        "series": 7,
        "time": 7200,
        "equipment_amount": 8,
    },
    {
        "name": "E-315-MI",
        "series": 7,
        "time": 7200,
        "equipment_amount": 15,
    },
    {
        "name": "E-191-MI",
        "series": 7,
        "time": 21600,
    },
    {
        "name": "E-166-MI",
        "series": 7,
        "time": 21600,
    },
    {
        "name": "E-167-MI",
        "series": 7,
        "time": 21600,
    },
    {
        "name": "E-13-MI",
        "series": 7,
        "time": 21600,
    },
    {
        "name": "E-158-MI",
        "series": 7,
        "time": 21600,
    },
    {
        "name": "G-412-MI",
        "series": 7,
        "time": 5400,
        "need_coin": True,
    },
    {
        "name": "G-236-MI",
        "series": 7,
        "time": 9000,
        "need_coin": True,
    },
    {
        "name": "G-531-MI",
        "series": 7,
        "time": 14400,
        "need_coin": True,
    },
    {
        "name": "D-703-MI",
        "series": 7,
        "time": 9000,
        "need_coin": True,
        "ship": "halford",
        "ship_rarity": "pry",
    },
    {
        "name": "D-758-MI",
        "series": 7,
        "time": 9000,
        "need_coin": True,
        "ship": "daisen",
        "ship_rarity": "pry",
    },
    {
        "name": "D-766-MI",
        "series": 7,
        "time": 9000,
        "need_coin": True,
        "ship": "napoli",
        "ship_rarity": "dr",
    },
    {
        "name": "D-790-MI",
        "series": 7,
        "time": 9000,
        "need_coin": True,
        "ship": "nakhimov",
        "ship_rarity": "dr",
    },
    {
        "name": "D-797-MI",
        "series": 7,
        "time": 9000,
        "need_coin": True,
        "ship": "bayard",
        "ship_rarity": "pry",
    },
    {
        "name": "D-303-MI",
        "series": 7,
        "time": 18000,
        "need_coin": True,
        "ship": "halford",
        "ship_rarity": "pry",
    },
    {
        "name": "D-358-MI",
        "series": 7,
        "time": 18000,
        "need_coin": True,
        "ship": "daisen",
        "ship_rarity": "pry",
    },
    {
        "name": "D-366-MI",
        "series": 7,
        "time": 18000,
        "need_coin": True,
        "ship": "napoli",
        "ship_rarity": "dr",
    },
    {
        "name": "D-390-MI",
        "series": 7,
        "time": 18000,
        "need_coin": True,
        "ship": "nakhimov",
        "ship_rarity": "dr",
    },
    {
        "name": "D-397-MI",
        "series": 7,
        "time": 18000,
        "need_coin": True,
        "ship": "bayard",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-302-MI",
        "series": 7,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-310-MI",
        "series": 7,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-351-MI",
        "series": 7,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-368-MI",
        "series": 7,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-389-MI",
        "series": 7,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-202-MI",
        "series": 7,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-210-MI",
        "series": 7,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-251-MI",
        "series": 7,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-268-MI",
        "series": 7,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-289-MI",
        "series": 7,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-002-MI",
        "series": 7,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-010-MI",
        "series": 7,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-051-MI",
        "series": 7,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-068-MI",
        "series": 7,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-089-MI",
        "series": 7,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "H-387-MI",
        "series": 7,
        "time": 3600,
        "need_cube": True,
    },
    {
        "name": "H-339-MI",
        "series": 7,
        "time": 7200,
        "need_cube": True,
    },
    {
        "name": "C-153-MI",
        "series": 8,
        "time": 21600,
    },
    {
        "name": "C-185-MI",
        "series": 8,
        "time": 28800,
    },
    {
        "name": "B-622-MI",
        "series": 8,
        "time": 14400,
    },
    {
        "name": "B-636-MI",
        "series": 8,
        "time": 14400,
    },
    {
        "name": "B-654-MI",
        "series": 8,
        "time": 14400,
    },
    {
        "name": "B-682-MI",
        "series": 8,
        "time": 14400,
    },
    {
        "name": "B-235-MI",
        "series": 8,
        "time": 14400,
    },
    {
        "name": "B-268-MI",
        "series": 8,
        "time": 14400,
    },
    {
        "name": "B-128-MI",
        "series": 8,
        "time": 14400,
    },
    {
        "name": "B-164-MI",
        "series": 8,
        "time": 14400,
    },
    {
        "name": "T-018-MI",
        "series": 8,
        "time": 10800,
    },
    {
        "name": "T-384-MI",
        "series": 8,
        "time": 14400,
    },
    {
        "name": "T-249-MI",
        "series": 8,
        "time": 21600,
    },
    {
        "name": "E-031-MI",
        "series": 8,
        "time": 7200,
        "equipment_amount": 8,
    },
    {
        "name": "E-315-MI",
        "series": 8,
        "time": 7200,
        "equipment_amount": 15,
    },
    {
        "name": "G-412-MI",
        "series": 8,
        "time": 5400,
        "need_coin": True,
    },
    {
        "name": "G-236-MI",
        "series": 8,
        "time": 9000,
        "need_coin": True,
    },
    {
        "name": "G-531-MI",
        "series": 8,
        "time": 14400,
        "need_coin": True,
    },
    {
        "name": "D-780-MI",
        "series": 8,
        "time": 9000,
        "need_coin": True,
        "ship": "mecklenburg",
        "ship_rarity": "dr",
    },
    {
        "name": "D-736-MI",
        "series": 8,
        "time": 9000,
        "need_coin": True,
        "ship": "goudenleeuw",
        "ship_rarity": "dr",
    },
    {
        "name": "D-787-MI",
        "series": 8,
        "time": 9000,
        "need_coin": True,
        "ship": "dmitri",
        "ship_rarity": "pry",
    },
    {
        "name": "D-711-MI",
        "series": 8,
        "time": 9000,
        "need_coin": True,
        "ship": "kansas",
        "ship_rarity": "pry",
    },
    {
        "name": "D-764-MI",
        "series": 8,
        "time": 9000,
        "need_coin": True,
        "ship": "vittorio",
        "ship_rarity": "pry",
    },
    {
        "name": "D-380-MI",
        "series": 8,
        "time": 18000,
        "need_coin": True,
        "ship": "mecklenburg",
        "ship_rarity": "dr",
    },
    {
        "name": "D-336-MI",
        "series": 8,
        "time": 18000,
        "need_coin": True,
        "ship": "goudenleeuw",
        "ship_rarity": "dr",
    },
    {
        "name": "D-387-MI",
        "series": 8,
        "time": 18000,
        "need_coin": True,
        "ship": "dmitri",
        "ship_rarity": "pry",
    },
    {
        "name": "D-311-MI",
        "series": 8,
        "time": 18000,
        "need_coin": True,
        "ship": "kansas",
        "ship_rarity": "pry",
    },
    {
        "name": "D-364-MI",
        "series": 8,
        "time": 18000,
        "need_coin": True,
        "ship": "vittorio",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-302-MI",
        "series": 8,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-310-MI",
        "series": 8,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-351-MI",
        "series": 8,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-368-MI",
        "series": 8,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-389-MI",
        "series": 8,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-202-MI",
        "series": 8,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-210-MI",
        "series": 8,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-251-MI",
        "series": 8,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-268-MI",
        "series": 8,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-289-MI",
        "series": 8,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-002-MI",
        "series": 8,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-010-MI",
        "series": 8,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-051-MI",
        "series": 8,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-068-MI",
        "series": 8,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-089-MI",
        "series": 8,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "H-387-MI",
        "series": 8,
        "time": 3600,
        "need_cube": True,
    },
    {
        "name": "H-339-MI",
        "series": 8,
        "time": 7200,
        "need_cube": True,
    },
    {
        "name": "C-038-RF",
        "series": 1,
        "time": 43200,
    },
    {
        "name": "B-351-RF",
        "series": 1,
        "time": 14400,
    },
    {
        "name": "B-397-RF",
        "series": 1,
        "time": 14400,
    },
    {
        "name": "D-418-RF",
        "series": 1,
        "time": 28800,
        "need_coin": True,
        "ship": "neptune",
        "ship_rarity": "pry",
    },
    {
        "name": "D-431-RF",
        "series": 1,
        "time": 28800,
        "need_coin": True,
        "ship": "monarch",
        "ship_rarity": "pry",
    },
    {
        "name": "D-444-RF",
        "series": 1,
        "time": 28800,
        "need_coin": True,
        "ship": "ibuki",
        "ship_rarity": "pry",
    },
    {
        "name": "D-459-RF",
        "series": 1,
        "time": 28800,
        "need_coin": True,
        "ship": "izumo",
        "ship_rarity": "pry",
    },
    {
        "name": "D-474-RF",
        "series": 1,
        "time": 28800,
        "need_coin": True,
        "ship": "roon",
        "ship_rarity": "pry",
    },
    {
        "name": "D-492-RF",
        "series": 1,
        "time": 28800,
        "need_coin": True,
        "ship": "saintlouis",
        "ship_rarity": "pry",
    },
    {
        "name": "H-207-RF",
        "series": 1,
        "time": 14400,
        "need_cube": True,
    },
    {
        "name": "D-018-UL",
        "series": 1,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "neptune",
        "ship_rarity": "pry",
    },
    {
        "name": "D-031-UL",
        "series": 1,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "monarch",
        "ship_rarity": "pry",
    },
    {
        "name": "D-044-UL",
        "series": 1,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "ibuki",
        "ship_rarity": "pry",
    },
    {
        "name": "D-059-UL",
        "series": 1,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "izumo",
        "ship_rarity": "pry",
    },
    {
        "name": "D-074-UL",
        "series": 1,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "roon",
        "ship_rarity": "pry",
    },
    {
        "name": "D-092-UL",
        "series": 1,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "saintlouis",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-002-UL",
        "series": 1,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-010-UL",
        "series": 1,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-051-UL",
        "series": 1,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-068-UL",
        "series": 1,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-089-UL",
        "series": 1,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "H-085-UL",
        "series": 1,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
    },
    {
        "name": "E-831-MI",
        "series": 1,
        "time": 7200,
    },
    {
        "name": "E-859-MI",
        "series": 1,
        "time": 7200,
    },
    {
        "name": "E-874-MI",
        "series": 1,
        "time": 7200,
    },
    {
        "name": "E-892-MI",
        "series": 1,
        "time": 7200,
    },
    {
        "name": "E-818-MI",
        "series": 1,
        "time": 7200,
    },
    {
        "name": "E-844-MI",
        "series": 1,
        "time": 7200,
    },
    {
        "name": "C-038-RF",
        "series": 2,
        "time": 43200,
    },
    {
        "name": "B-351-RF",
        "series": 2,
        "time": 14400,
    },
    {
        "name": "B-397-RF",
        "series": 2,
        "time": 14400,
    },
    {
        "name": "D-405-RF",
        "series": 2,
        "time": 28800,
        "need_coin": True,
        "ship": "seattle",
        "ship_rarity": "pry",
    },
    {
        "name": "D-412-RF",
        "series": 2,
        "time": 28800,
        "need_coin": True,
        "ship": "georgia",
        "ship_rarity": "pry",
    },
    {
        "name": "D-446-RF",
        "series": 2,
        "time": 28800,
        "need_coin": True,
        "ship": "kitakaze",
        "ship_rarity": "pry",
    },
    {
        "name": "D-457-RF",
        "series": 2,
        "time": 28800,
        "need_coin": True,
        "ship": "azuma",
        "ship_rarity": "dr",
    },
    {
        "name": "D-479-RF",
        "series": 2,
        "time": 28800,
        "need_coin": True,
        "ship": "friedrich",
        "ship_rarity": "dr",
    },
    {
        "name": "D-494-RF",
        "series": 2,
        "time": 28800,
        "need_coin": True,
        "ship": "gascogne",
        "ship_rarity": "pry",
    },
    {
        "name": "H-207-RF",
        "series": 2,
        "time": 14400,
        "need_cube": True,
    },
    {
        "name": "D-005-UL",
        "series": 2,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "seattle",
        "ship_rarity": "pry",
    },
    {
        "name": "D-012-UL",
        "series": 2,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "georgia",
        "ship_rarity": "pry",
    },
    {
        "name": "D-046-UL",
        "series": 2,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "kitakaze",
        "ship_rarity": "pry",
    },
    {
        "name": "D-057-UL",
        "series": 2,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "azuma",
        "ship_rarity": "dr",
    },
    {
        "name": "D-079-UL",
        "series": 2,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "friedrich",
        "ship_rarity": "dr",
    },
    {
        "name": "D-094-UL",
        "series": 2,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "gascogne",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-002-UL",
        "series": 2,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-010-UL",
        "series": 2,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-051-UL",
        "series": 2,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-068-UL",
        "series": 2,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-089-UL",
        "series": 2,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "H-022-UL",
        "series": 2,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
    },
    {
        "name": "E-879-MI",
        "series": 2,
        "time": 7200,
    },
    {
        "name": "E-805-MI",
        "series": 2,
        "time": 7200,
    },
    {
        "name": "E-846-MI",
        "series": 2,
        "time": 7200,
    },
    {
        "name": "E-857-MI",
        "series": 2,
        "time": 7200,
    },
    {
        "name": "E-894-MI",
        "series": 2,
        "time": 7200,
    },
    {
        "name": "C-038-RF",
        "series": 3,
        "time": 43200,
    },
    {
        "name": "B-351-RF",
        "series": 3,
        "time": 14400,
    },
    {
        "name": "B-397-RF",
        "series": 3,
        "time": 14400,
    },
    {
        "name": "D-421-RF",
        "series": 3,
        "time": 28800,
        "need_coin": True,
        "ship": "cheshire",
        "ship_rarity": "pry",
    },
    {
        "name": "D-422-RF",
        "series": 3,
        "time": 28800,
        "need_coin": True,
        "ship": "drake",
        "ship_rarity": "dr",
    },
    {
        "name": "D-472-RF",
        "series": 3,
        "time": 28800,
        "need_coin": True,
        "ship": "mainz",
        "ship_rarity": "pry",
    },
    {
        "name": "D-477-RF",
        "series": 3,
        "time": 28800,
        "need_coin": True,
        "ship": "odin",
        "ship_rarity": "pry",
    },
    {
        "name": "D-495-RF",
        "series": 3,
        "time": 28800,
        "need_coin": True,
        "ship": "champagne",
        "ship_rarity": "pry",
    },
    {
        "name": "H-207-RF",
        "series": 3,
        "time": 14400,
        "need_cube": True,
    },
    {
        "name": "D-021-UL",
        "series": 3,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "cheshire",
        "ship_rarity": "pry",
    },
    {
        "name": "D-022-UL",
        "series": 3,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "drake",
        "ship_rarity": "dr",
    },
    {
        "name": "D-072-UL",
        "series": 3,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "mainz",
        "ship_rarity": "pry",
    },
    {
        "name": "D-077-UL",
        "series": 3,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "odin",
        "ship_rarity": "pry",
    },
    {
        "name": "D-095-UL",
        "series": 3,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "champagne",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-002-UL",
        "series": 3,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-010-UL",
        "series": 3,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-051-UL",
        "series": 3,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-068-UL",
        "series": 3,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-089-UL",
        "series": 3,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "H-060-UL",
        "series": 3,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
    },
    {
        "name": "E-821-MI",
        "series": 3,
        "time": 7200,
    },
    {
        "name": "E-823-MI",
        "series": 3,
        "time": 7200,
    },
    {
        "name": "E-824-MI",
        "series": 3,
        "time": 7200,
    },
    {
        "name": "E-877-MI",
        "series": 3,
        "time": 7200,
    },
    {
        "name": "E-895-MI",
        "series": 3,
        "time": 7200,
    },
    {
        "name": "C-038-RF",
        "series": 4,
        "time": 43200,
    },
    {
        "name": "B-351-RF",
        "series": 4,
        "time": 14400,
    },
    {
        "name": "B-397-RF",
        "series": 4,
        "time": 14400,
    },
    {
        "name": "D-408-RF",
        "series": 4,
        "time": 28800,
        "need_coin": True,
        "ship": "anchorage",
        "ship_rarity": "pry",
    },
    {
        "name": "D-463-RF",
        "series": 4,
        "time": 28800,
        "need_coin": True,
        "ship": "hakuryu",
        "ship_rarity": "dr",
    },
    {
        "name": "D-475-RF",
        "series": 4,
        "time": 28800,
        "need_coin": True,
        "ship": "agir",
        "ship_rarity": "dr",
    },
    {
        "name": "D-482-RF",
        "series": 4,
        "time": 28800,
        "need_coin": True,
        "ship": "august",
        "ship_rarity": "pry",
    },
    {
        "name": "D-468-RF",
        "series": 4,
        "time": 28800,
        "need_coin": True,
        "ship": "marcopolo",
        "ship_rarity": "pry",
    },
    {
        "name": "H-207-RF",
        "series": 4,
        "time": 14400,
        "need_cube": True,
    },
    {
        "name": "D-008-UL",
        "series": 4,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "anchorage",
        "ship_rarity": "pry",
    },
    {
        "name": "D-063-UL",
        "series": 4,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "hakuryu",
        "ship_rarity": "dr",
    },
    {
        "name": "D-075-UL",
        "series": 4,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "agir",
        "ship_rarity": "dr",
    },
    {
        "name": "D-082-UL",
        "series": 4,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "august",
        "ship_rarity": "pry",
    },
    {
        "name": "D-068-UL",
        "series": 4,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "marcopolo",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-002-UL",
        "series": 4,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-010-UL",
        "series": 4,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-051-UL",
        "series": 4,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-068-UL",
        "series": 4,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-089-UL",
        "series": 4,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "H-063-UL",
        "series": 4,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
    },
    {
        "name": "E-875-MI",
        "series": 4,
        "time": 7200,
    },
    {
        "name": "E-882-MI",
        "series": 4,
        "time": 7200,
    },
    {
        "name": "E-868-MI",
        "series": 4,
        "time": 7200,
    },
    {
        "name": "E-808-MI",
        "series": 4,
        "time": 7200,
    },
    {
        "name": "E-863-MI",
        "series": 4,
        "time": 7200,
    },
    {
        "name": "C-038-RF",
        "series": 5,
        "time": 43200,
    },
    {
        "name": "B-351-RF",
        "series": 5,
        "time": 14400,
    },
    {
        "name": "B-397-RF",
        "series": 5,
        "time": 14400,
    },
    {
        "name": "D-419-RF",
        "series": 5,
        "time": 28800,
        "need_coin": True,
        "ship": "plymouth",
        "ship_rarity": "dr",
    },
    {
        "name": "D-478-RF",
        "series": 5,
        "time": 28800,
        "need_coin": True,
        "ship": "rupprecht",
        "ship_rarity": "pry",
    },
    {
        "name": "D-486-RF",
        "series": 5,
        "time": 28800,
        "need_coin": True,
        "ship": "harbin",
        "ship_rarity": "pry",
    },
    {
        "name": "D-488-RF",
        "series": 5,
        "time": 28800,
        "need_coin": True,
        "ship": "chkalov",
        "ship_rarity": "pry",
    },
    {
        "name": "D-493-RF",
        "series": 5,
        "time": 28800,
        "need_coin": True,
        "ship": "brest",
        "ship_rarity": "dr",
    },
    {
        "name": "H-207-RF",
        "series": 5,
        "time": 14400,
        "need_cube": True,
    },
    {
        "name": "D-019-UL",
        "series": 5,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "plymouth",
        "ship_rarity": "dr",
    },
    {
        "name": "D-078-UL",
        "series": 5,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "rupprecht",
        "ship_rarity": "pry",
    },
    {
        "name": "D-086-UL",
        "series": 5,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "harbin",
        "ship_rarity": "pry",
    },
    {
        "name": "D-088-UL",
        "series": 5,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "chkalov",
        "ship_rarity": "pry",
    },
    {
        "name": "D-093-UL",
        "series": 5,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "brest",
        "ship_rarity": "dr",
    },
    {
        "name": "Q-002-UL",
        "series": 5,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-010-UL",
        "series": 5,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-051-UL",
        "series": 5,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-068-UL",
        "series": 5,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-089-UL",
        "series": 5,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "H-063-UL",
        "series": 5,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
    },
    {
        "name": "E-893-MI",
        "series": 5,
        "time": 7200,
    },
    {
        "name": "E-878-MI",
        "series": 5,
        "time": 7200,
    },
    {
        "name": "E-886-MI",
        "series": 5,
        "time": 7200,
    },
    {
        "name": "C-038-RF",
        "series": 6,
        "time": 43200,
    },
    {
        "name": "B-351-RF",
        "series": 6,
        "time": 14400,
    },
    {
        "name": "B-397-RF",
        "series": 6,
        "time": 14400,
    },
    {
        "name": "D-483-RF",
        "series": 6,
        "time": 28800,
        "need_coin": True,
        "ship": "hindenburg",
        "ship_rarity": "dr",
    },
    {
        "name": "D-413-RF",
        "series": 6,
        "time": 28800,
        "need_coin": True,
        "ship": "kearsarge",
        "ship_rarity": "dr",
    },
    {
        "name": "D-439-RF",
        "series": 6,
        "time": 28800,
        "need_coin": True,
        "ship": "shimanto",
        "ship_rarity": "pry",
    },
    {
        "name": "D-471-RF",
        "series": 6,
        "time": 28800,
        "need_coin": True,
        "ship": "schultz",
        "ship_rarity": "pry",
    },
    {
        "name": "D-496-RF",
        "series": 6,
        "time": 28800,
        "need_coin": True,
        "ship": "flandre",
        "ship_rarity": "pry",
    },
    {
        "name": "H-207-RF",
        "series": 6,
        "time": 14400,
        "need_cube": True,
    },
    {
        "name": "D-083-UL",
        "series": 6,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "hindenburg",
        "ship_rarity": "dr",
    },
    {
        "name": "D-013-UL",
        "series": 6,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "kearsarge",
        "ship_rarity": "dr",
    },
    {
        "name": "D-039-UL",
        "series": 6,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "shimanto",
        "ship_rarity": "pry",
    },
    {
        "name": "D-071-UL",
        "series": 6,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "schultz",
        "ship_rarity": "pry",
    },
    {
        "name": "D-096-UL",
        "series": 6,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "flandre",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-002-UL",
        "series": 6,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-010-UL",
        "series": 6,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-051-UL",
        "series": 6,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-068-UL",
        "series": 6,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-089-UL",
        "series": 6,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "H-063-UL",
        "series": 6,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
    },
    {
        "name": "E-813-MI",
        "series": 6,
        "time": 7200,
    },
    {
        "name": "E-839-MI",
        "series": 6,
        "time": 7200,
    },
    {
        "name": "E-871-MI",
        "series": 6,
        "time": 7200,
    },
    {
        "name": "E-896-MI",
        "series": 6,
        "time": 7200,
    },
    {
        "name": "E-884-MI",
        "series": 6,
        "time": 7200,
    },
    {
        "name": "C-038-RF",
        "series": 7,
        "time": 43200,
    },
    {
        "name": "B-351-RF",
        "series": 7,
        "time": 14400,
    },
    {
        "name": "B-397-RF",
        "series": 7,
        "time": 14400,
    },
    {
        "name": "D-403-RF",
        "series": 7,
        "time": 28800,
        "need_coin": True,
        "ship": "halford",
        "ship_rarity": "pry",
    },
    {
        "name": "D-458-RF",
        "series": 7,
        "time": 28800,
        "need_coin": True,
        "ship": "daisen",
        "ship_rarity": "pry",
    },
    {
        "name": "D-466-RF",
        "series": 7,
        "time": 28800,
        "need_coin": True,
        "ship": "napoli",
        "ship_rarity": "dr",
    },
    {
        "name": "D-490-RF",
        "series": 7,
        "time": 28800,
        "need_coin": True,
        "ship": "nakhimov",
        "ship_rarity": "dr",
    },
    {
        "name": "D-497-RF",
        "series": 7,
        "time": 28800,
        "need_coin": True,
        "ship": "bayard",
        "ship_rarity": "pry",
    },
    {
        "name": "H-207-RF",
        "series": 7,
        "time": 14400,
        "need_cube": True,
    },
    {
        "name": "D-003-UL",
        "series": 7,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "halford",
        "ship_rarity": "pry",
    },
    {
        "name": "D-058-UL",
        "series": 7,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "daisen",
        "ship_rarity": "pry",
    },
    {
        "name": "D-066-UL",
        "series": 7,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "napoli",
        "ship_rarity": "dr",
    },
    {
        "name": "D-090-UL",
        "series": 7,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "nakhimov",
        "ship_rarity": "dr",
    },
    {
        "name": "D-097-UL",
        "series": 7,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "bayard",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-002-UL",
        "series": 7,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-010-UL",
        "series": 7,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-051-UL",
        "series": 7,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-068-UL",
        "series": 7,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-089-UL",
        "series": 7,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "H-063-UL",
        "series": 7,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
    },
    {
        "name": "E-866-MI",
        "series": 7,
        "time": 7200,
    },
    {
        "name": "E-867-MI",
        "series": 7,
        "time": 7200,
    },
    {
        "name": "E-83-MI",
        "series": 7,
        "time": 7200,
    },
    {
        "name": "E-858-MI",
        "series": 7,
        "time": 7200,
    },
    {
        "name": "C-038-RF",
        "series": 8,
        "time": 43200,
    },
    {
        "name": "B-351-RF",
        "series": 8,
        "time": 14400,
    },
    {
        "name": "B-397-RF",
        "series": 8,
        "time": 14400,
    },
    {
        "name": "D-480-RF",
        "series": 8,
        "time": 28800,
        "need_coin": True,
        "ship": "mecklenburg",
        "ship_rarity": "dr",
    },
    {
        "name": "D-436-RF",
        "series": 8,
        "time": 28800,
        "need_coin": True,
        "ship": "goudenleeuw",
        "ship_rarity": "dr",
    },
    {
        "name": "D-487-RF",
        "series": 8,
        "time": 28800,
        "need_coin": True,
        "ship": "dmitri",
        "ship_rarity": "pry",
    },
    {
        "name": "D-411-RF",
        "series": 8,
        "time": 28800,
        "need_coin": True,
        "ship": "kansas",
        "ship_rarity": "pry",
    },
    {
        "name": "D-464-RF",
        "series": 8,
        "time": 28800,
        "need_coin": True,
        "ship": "vittorio",
        "ship_rarity": "pry",
    },
    {
        "name": "H-207-RF",
        "series": 8,
        "time": 14400,
        "need_cube": True,
    },
    {
        "name": "D-080-UL",
        "series": 8,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "mecklenburg",
        "ship_rarity": "dr",
    },
    {
        "name": "D-036-UL",
        "series": 8,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "goudenleeuw",
        "ship_rarity": "dr",
    },
    {
        "name": "D-087-UL",
        "series": 8,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "dmitri",
        "ship_rarity": "pry",
    },
    {
        "name": "D-011-UL",
        "series": 8,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "kansas",
        "ship_rarity": "pry",
    },
    {
        "name": "D-064-UL",
        "series": 8,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "vittorio",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-002-UL",
        "series": 8,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-010-UL",
        "series": 8,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-051-UL",
        "series": 8,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-068-UL",
        "series": 8,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-089-UL",
        "series": 8,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "H-063-UL",
        "series": 8,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
    },
    {
        "name": "E-180-MI",
        "series": 8,
        "time": 21600,
    },
    {
        "name": "E-136-MI",
        "series": 8,
        "time": 21600,
    },
    {
        "name": "E-111-MI",
        "series": 8,
        "time": 21600,
    },
    {
        "name": "E-164-MI",
        "series": 8,
        "time": 21600,
    },
    {
        "name": "E-187-MI",
        "series": 8,
        "time": 21600,
    },
    {
        "name": "C-153-MI",
        "series": 9,
        "time": 21600,
    },
    {
        "name": "C-185-MI",
        "series": 9,
        "time": 28800,
    },
    {
        "name": "B-622-MI",
        "series": 9,
        "time": 14400,
    },
    {
        "name": "B-636-MI",
        "series": 9,
        "time": 14400,
    },
    {
        "name": "B-654-MI",
        "series": 9,
        "time": 14400,
    },
    {
        "name": "B-682-MI",
        "series": 9,
        "time": 14400,
    },
    {
        "name": "B-235-MI",
        "series": 9,
        "time": 14400,
    },
    {
        "name": "B-268-MI",
        "series": 9,
        "time": 14400,
    },
    {
        "name": "B-128-MI",
        "series": 9,
        "time": 14400,
    },
    {
        "name": "B-164-MI",
        "series": 9,
        "time": 14400,
    },
    {
        "name": "T-018-MI",
        "series": 9,
        "time": 10800,
    },
    {
        "name": "T-384-MI",
        "series": 9,
        "time": 14400,
    },
    {
        "name": "T-249-MI",
        "series": 9,
        "time": 21600,
    },
    {
        "name": "E-031-MI",
        "series": 9,
        "time": 7200,
        "equipment_amount": 8,
    },
    {
        "name": "E-315-MI",
        "series": 9,
        "time": 7200,
        "equipment_amount": 15,
    },
    {
        "name": "G-412-MI",
        "series": 9,
        "time": 5400,
        "need_coin": True,
    },
    {
        "name": "G-236-MI",
        "series": 9,
        "time": 9000,
        "need_coin": True,
    },
    {
        "name": "G-531-MI",
        "series": 9,
        "time": 14400,
        "need_coin": True,
    },
    {
        "name": "D-737-MI",
        "series": 9,
        "time": 9000,
        "need_coin": True,
        "ship": "valparaiso",
        "ship_rarity": "dr",
    },
    {
        "name": "D-781-MI",
        "series": 9,
        "time": 9000,
        "need_coin": True,
        "ship": "maximmelmann",
        "ship_rarity": "dr",
    },
    {
        "name": "D-732-MI",
        "series": 9,
        "time": 9000,
        "need_coin": True,
        "ship": "duncan",
        "ship_rarity": "pry",
    },
    {
        "name": "D-740-MI",
        "series": 9,
        "time": 9000,
        "need_coin": True,
        "ship": "takahashi",
        "ship_rarity": "pry",
    },
    {
        "name": "D-747-MI",
        "series": 9,
        "time": 9000,
        "need_coin": True,
        "ship": "orage",
        "ship_rarity": "pry",
    },
    {
        "name": "D-337-MI",
        "series": 9,
        "time": 18000,
        "need_coin": True,
        "ship": "valparaiso",
        "ship_rarity": "dr",
    },
    {
        "name": "D-381-MI",
        "series": 9,
        "time": 18000,
        "need_coin": True,
        "ship": "maximmelmann",
        "ship_rarity": "dr",
    },
    {
        "name": "D-332-MI",
        "series": 9,
        "time": 18000,
        "need_coin": True,
        "ship": "duncan",
        "ship_rarity": "pry",
    },
    {
        "name": "D-340-MI",
        "series": 9,
        "time": 18000,
        "need_coin": True,
        "ship": "takahashi",
        "ship_rarity": "pry",
    },
    {
        "name": "D-347-MI",
        "series": 9,
        "time": 18000,
        "need_coin": True,
        "ship": "orage",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-302-MI",
        "series": 9,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-310-MI",
        "series": 9,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-351-MI",
        "series": 9,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-368-MI",
        "series": 9,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-389-MI",
        "series": 9,
        "time": 3600,
        "need_part": True,
    },
    {
        "name": "Q-202-MI",
        "series": 9,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-210-MI",
        "series": 9,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-251-MI",
        "series": 9,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-268-MI",
        "series": 9,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-289-MI",
        "series": 9,
        "time": 7200,
        "need_part": True,
    },
    {
        "name": "Q-002-MI",
        "series": 9,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-010-MI",
        "series": 9,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-051-MI",
        "series": 9,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-068-MI",
        "series": 9,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "Q-089-MI",
        "series": 9,
        "time": 14400,
        "need_part": True,
    },
    {
        "name": "H-387-MI",
        "series": 9,
        "time": 3600,
        "need_cube": True,
    },
    {
        "name": "H-339-MI",
        "series": 9,
        "time": 7200,
        "need_cube": True,
    },
    {
        "name": "E-880-MI",
        "series": 8,
        "time": 7200,
    },
    {
        "name": "E-836-MI",
        "series": 8,
        "time": 7200,
    },
    {
        "name": "E-811-MI",
        "series": 8,
        "time": 7200,
    },
    {
        "name": "E-864-MI",
        "series": 8,
        "time": 7200,
    },
    {
        "name": "E-887-MI",
        "series": 8,
        "time": 7200,
    },
    {
        "name": "C-038-RF",
        "series": 9,
        "time": 43200,
    },
    {
        "name": "B-351-RF",
        "series": 9,
        "time": 14400,
    },
    {
        "name": "B-397-RF",
        "series": 9,
        "time": 14400,
    },
    {
        "name": "D-437-RF",
        "series": 9,
        "time": 28800,
        "need_coin": True,
        "ship": "valparaiso",
        "ship_rarity": "dr",
    },
    {
        "name": "D-481-RF",
        "series": 9,
        "time": 28800,
        "need_coin": True,
        "ship": "maximmelmann",
        "ship_rarity": "dr",
    },
    {
        "name": "D-432-RF",
        "series": 9,
        "time": 28800,
        "need_coin": True,
        "ship": "duncan",
        "ship_rarity": "pry",
    },
    {
        "name": "D-440-RF",
        "series": 9,
        "time": 28800,
        "need_coin": True,
        "ship": "takahashi",
        "ship_rarity": "pry",
    },
    {
        "name": "D-447-RF",
        "series": 9,
        "time": 28800,
        "need_coin": True,
        "ship": "orage",
        "ship_rarity": "pry",
    },
    {
        "name": "H-207-RF",
        "series": 9,
        "time": 14400,
        "need_cube": True,
    },
    {
        "name": "D-037-UL",
        "series": 9,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "valparaiso",
        "ship_rarity": "dr",
    },
    {
        "name": "D-081-UL",
        "series": 9,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "maximmelmann",
        "ship_rarity": "dr",
    },
    {
        "name": "D-032-UL",
        "series": 9,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "duncan",
        "ship_rarity": "pry",
    },
    {
        "name": "D-040-UL",
        "series": 9,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "takahashi",
        "ship_rarity": "pry",
    },
    {
        "name": "D-047-UL",
        "series": 9,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
        "ship": "orage",
        "ship_rarity": "pry",
    },
    {
        "name": "Q-002-UL",
        "series": 9,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-010-UL",
        "series": 9,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-051-UL",
        "series": 9,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-068-UL",
        "series": 9,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "Q-089-UL",
        "series": 9,
        "time": 1800,
        "need_coin": True,
        "need_part": True,
    },
    {
        "name": "H-063-UL",
        "series": 9,
        "time": 1800,
        "need_coin": True,
        "need_cube": True,
    },
]
