from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BACK_ARROW_WHITE = Button(
    area=(54, 30, 69, 53),
    color=(199, 199, 199),
    button=(54, 30, 69, 53),
    file="./assets/cn/ui_white/BACK_ARROW_WHITE.png",
)
GOTO_MAIN_WHITE = Button(
    area=(1211, 24, 1239, 47),
    color=(151, 151, 152),
    button=(1211, 24, 1239, 47),
    file="./assets/cn/ui_white/GOTO_MAIN_WHITE.png",
)
MAIL_CHECK = Button(
    area=(141, 21, 181, 41),
    color=(101, 109, 122),
    button=(141, 21, 181, 41),
    file="./assets/cn/ui_white/MAIL_CHECK.png",
)
MAIL_ENTER_WHITE = Button(
    area=(1018, 22, 1087, 52),
    color=(194, 187, 190),
    button=(1018, 22, 1087, 52),
    file="./assets/cn/ui_white/MAIL_ENTER_WHITE.png",
)
MAIN_GOTO_BUILD_WHITE = Button(
    area=(959, 657, 1103, 703),
    color=(229, 216, 216),
    button=(959, 657, 1103, 703),
    file="./assets/cn/ui_white/MAIN_GOTO_BUILD_WHITE.png",
)
MAIN_GOTO_CAMPAIGN_WHITE = Button(
    area=(1132, 529, 1187, 557),
    color=(152, 161, 161),
    button=(1124, 437, 1260, 579),
    file="./assets/cn/ui_white/MAIN_GOTO_CAMPAIGN_WHITE.png",
)
MAIN_GOTO_DOCK_WHITE = Button(
    area=(176, 656, 322, 703),
    color=(226, 226, 230),
    button=(176, 656, 322, 703),
    file="./assets/cn/ui_white/MAIN_GOTO_DOCK_WHITE.png",
)
MAIN_GOTO_DORMMENU_WHITE = Button(
    area=(490, 656, 634, 702),
    color=(206, 205, 209),
    button=(490, 656, 634, 702),
    file="./assets/cn/ui_white/MAIN_GOTO_DORMMENU_WHITE.png",
)
MAIN_GOTO_EVENT_LIST_WHITE = Button(
    area=(1181, 83, 1260, 160),
    color=(147, 155, 186),
    button=(1181, 83, 1260, 160),
    file="./assets/cn/ui_white/MAIN_GOTO_EVENT_LIST_WHITE.png",
)
MAIN_GOTO_FLEET_WHITE = Button(
    area=(1025, 437, 1097, 579),
    color=(230, 229, 231),
    button=(1025, 437, 1097, 579),
    file="./assets/cn/ui_white/MAIN_GOTO_FLEET_WHITE.png",
)
MAIN_GOTO_GUILD_WHITE = Button(
    area=(1116, 656, 1261, 703),
    color=(213, 206, 209),
    button=(1116, 656, 1261, 703),
    file="./assets/cn/ui_white/MAIN_GOTO_GUILD_WHITE.png",
)
MAIN_GOTO_MEMORIES_WHITE = Button(
    area=(1125, 546, 1195, 579),
    color=(255, 152, 191),
    button=(1125, 546, 1195, 579),
    file="./assets/cn/ui_white/MAIN_GOTO_MEMORIES_WHITE.png",
)
MAIN_GOTO_MISSION_WHITE = Button(
    area=(802, 656, 949, 704),
    color=(219, 213, 214),
    button=(802, 656, 949, 704),
    file="./assets/cn/ui_white/MAIN_GOTO_MISSION_WHITE.png",
)
MAIN_GOTO_RAID_WHITE = Button(
    area=(1071, 83, 1151, 159),
    color=(105, 95, 94),
    button=(1071, 83, 1151, 159),
    file="./assets/cn/ui_white/MAIN_GOTO_RAID_WHITE.png",
)
MAIN_GOTO_RESHMENU_WHITE = Button(
    area=(646, 656, 793, 703),
    color=(216, 213, 217),
    button=(646, 656, 793, 703),
    file="./assets/cn/ui_white/MAIN_GOTO_RESHMENU_WHITE.png",
)
MAIN_GOTO_REWARD_WHITE = Button(
    area=(11, 209, 30, 259),
    color=(73, 84, 122),
    button=(11, 209, 30, 259),
    file="./assets/cn/ui_white/MAIN_GOTO_REWARD_WHITE.png",
)
MAIN_GOTO_SHOP_WHITE = Button(
    area=(18, 656, 164, 703),
    color=(221, 214, 212),
    button=(18, 656, 164, 703),
    file="./assets/cn/ui_white/MAIN_GOTO_SHOP_WHITE.png",
)
MAIN_GOTO_STORAGE_WHITE = Button(
    area=(331, 656, 478, 703),
    color=(212, 214, 219),
    button=(331, 656, 478, 703),
    file="./assets/cn/ui_white/MAIN_GOTO_STORAGE_WHITE.png",
)
MAIN_TAB_SWITCH_WHITE = Button(
    area=(966, 548, 999, 582),
    color=(89, 93, 108),
    button=(966, 548, 999, 582),
    file="./assets/cn/ui_white/MAIN_TAB_SWITCH_WHITE.png",
)
MISSION_NOTICE_WHITE = Button(
    area=(923, 657, 947, 671),
    color=(227, 168, 159),
    button=(923, 657, 947, 671),
    file="./assets/cn/ui_white/MISSION_NOTICE_WHITE.png",
)
POPUP_CANCEL_WHITE = Button(
    area=(487, 491, 531, 513),
    color=(214, 214, 214),
    button=(487, 491, 531, 513),
    file="./assets/cn/ui_white/POPUP_CANCEL_WHITE.png",
)
POPUP_CONFIRM_WHITE = Button(
    area=(746, 494, 791, 515),
    color=(133, 216, 255),
    button=(746, 494, 791, 515),
    file="./assets/cn/ui_white/POPUP_CONFIRM_WHITE.png",
)
POPUP_CONFIRM_WHITE_BATTLEPASS = Button(
    area=(744, 490, 795, 513),
    color=(119, 211, 255),
    button=(744, 490, 795, 513),
    file="./assets/cn/ui_white/POPUP_CONFIRM_WHITE_BATTLEPASS.png",
)
POPUP_SINGLE_WHITE = Button(
    area=(623, 493, 668, 515),
    color=(131, 215, 255),
    button=(623, 493, 668, 515),
    file="./assets/cn/ui_white/POPUP_SINGLE_WHITE.png",
)
REWARD_1_WHITE = Button(
    area=(437, 278, 496, 296),
    color=(255, 193, 97),
    button=(437, 278, 496, 296),
    file="./assets/cn/ui_white/REWARD_1_WHITE.png",
)
REWARD_2_WHITE = Button(
    area=(436, 419, 497, 448),
    color=(255, 192, 94),
    button=(436, 419, 497, 448),
    file="./assets/cn/ui_white/REWARD_2_WHITE.png",
)
REWARD_GOTO_COMMISSION_WHITE = Button(
    area=(440, 278, 494, 296),
    color=(107, 209, 255),
    button=(440, 278, 494, 296),
    file="./assets/cn/ui_white/REWARD_GOTO_COMMISSION_WHITE.png",
)
REWARD_GOTO_TACTICAL_WHITE = Button(
    area=(442, 421, 492, 447),
    color=(114, 211, 255),
    button=(442, 421, 492, 447),
    file="./assets/cn/ui_white/REWARD_GOTO_TACTICAL_WHITE.png",
)
