from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COMMON_SHIP_FILTER_DISABLE = Button(
    area=(714, 13, 757, 41),
    color=(127, 143, 183),
    button=(714, 13, 757, 41),
    file="./assets/cn/retire/COMMON_SHIP_FILTER_DISABLE.png",
)
COMMON_SHIP_FILTER_ENABLE = Button(
    area=(713, 12, 758, 41),
    color=(214, 174, 130),
    button=(713, 12, 758, 41),
    file="./assets/cn/retire/COMMON_SHIP_FILTER_ENABLE.png",
)
DOCK_AMOUNT = Button(
    area=(473, 17, 611, 41),
    color=(71, 74, 78),
    button=(473, 17, 611, 41),
    file="./assets/cn/retire/DOCK_AMOUNT.png",
)
DOCK_CHECK = Button(
    area=(121, 14, 175, 39),
    color=(156, 171, 207),
    button=(121, 14, 175, 39),
    file="./assets/cn/retire/DOCK_CHECK.png",
)
DOCK_EMPTY = Button(
    area=(95, 347, 388, 378),
    color=(160, 154, 159),
    button=(95, 347, 388, 378),
    file="./assets/cn/retire/DOCK_EMPTY.png",
)
DOCK_FILTER = Button(
    area=(1099, 5, 1193, 48),
    color=(70, 87, 127),
    button=(1099, 5, 1193, 48),
    file="./assets/cn/retire/DOCK_FILTER.png",
)
DOCK_FILTER_CONFIRM = Button(
    area=(714, 613, 886, 671),
    color=(86, 133, 192),
    button=(714, 613, 886, 671),
    file="./assets/cn/retire/DOCK_FILTER_CONFIRM.png",
)
DOCK_FIRST_NPC = Button(
    area=(96, 111, 123, 123),
    color=(184, 150, 150),
    button=(96, 111, 123, 123),
    file="./assets/cn/retire/DOCK_FIRST_NPC.png",
)
DOCK_SCROLL = Button(
    area=(1239, 76, 1248, 641),
    color=(47, 46, 37),
    button=(1239, 76, 1248, 641),
    file="./assets/cn/retire/DOCK_SCROLL.png",
)
DOCK_SELECTED = Button(
    area=(582, 662, 647, 685),
    color=(75, 75, 83),
    button=(582, 662, 647, 685),
    file="./assets/cn/retire/DOCK_SELECTED.png",
)
EMPTY_ENHANCE_SLOT_PLUS = Button(
    area=(737, 402, 773, 437),
    color=(46, 46, 46),
    button=(737, 402, 773, 437),
    file="./assets/cn/retire/EMPTY_ENHANCE_SLOT_PLUS.png",
)
ENHANCE_CONFIRM = Button(
    area=(1126, 602, 1256, 645),
    color=(203, 149, 81),
    button=(1126, 602, 1256, 645),
    file="./assets/cn/retire/ENHANCE_CONFIRM.png",
)
ENHANCE_FILLED = Button(
    area=(728, 440, 781, 454),
    color=(156, 138, 127),
    button=(728, 440, 781, 454),
    file="./assets/cn/retire/ENHANCE_FILLED.png",
)
ENHANCE_RECOMMEND = Button(
    area=(959, 602, 1089, 645),
    color=(87, 134, 194),
    button=(959, 602, 1089, 645),
    file="./assets/cn/retire/ENHANCE_RECOMMEND.png",
)
ENHANCE_RELOAD = Button(
    area=(898, 277, 1164, 291),
    color=(251, 231, 94),
    button=(898, 277, 1164, 291),
    file="./assets/cn/retire/ENHANCE_RELOAD.png",
)
EQUIP_CONFIRM = Button(
    area=(1012, 587, 1083, 617),
    color=(152, 182, 219),
    button=(1012, 587, 1083, 617),
    file="./assets/cn/retire/EQUIP_CONFIRM.png",
)
EQUIP_CONFIRM_2 = Button(
    area=(770, 554, 843, 584),
    color=(150, 181, 218),
    button=(770, 554, 843, 584),
    file="./assets/cn/retire/EQUIP_CONFIRM_2.png",
)
GET_ITEMS_1_RETIREMENT_SAVE = Button(
    area=(1031, 656, 1063, 688),
    color=(49, 44, 54),
    button=(1031, 656, 1063, 688),
    file="./assets/cn/retire/GET_ITEMS_1_RETIREMENT_SAVE.png",
)
IN_RETIREMENT_CHECK = Button(
    area=(854, 641, 1027, 698),
    color=(184, 99, 89),
    button=(854, 641, 1027, 698),
    file="./assets/cn/retire/IN_RETIREMENT_CHECK.png",
)
ONE_CLICK_RETIREMENT = Button(
    area=(639, 641, 811, 698),
    color=(94, 138, 194),
    button=(639, 641, 811, 698),
    file="./assets/cn/retire/ONE_CLICK_RETIREMENT.png",
)
RETIRE_APPEAR_1 = Button(
    area=(404, 501, 477, 532),
    color=(153, 183, 221),
    button=(404, 501, 477, 532),
    file="./assets/cn/retire/RETIRE_APPEAR_1.png",
)
RETIRE_APPEAR_2 = Button(
    area=(604, 501, 677, 533),
    color=(146, 178, 219),
    button=(604, 501, 677, 533),
    file="./assets/cn/retire/RETIRE_APPEAR_2.png",
)
RETIRE_APPEAR_3 = Button(
    area=(804, 501, 876, 533),
    color=(148, 179, 219),
    button=(804, 501, 876, 533),
    file="./assets/cn/retire/RETIRE_APPEAR_3.png",
)
RETIRE_COIN = Button(
    area=(307, 638, 351, 661),
    color=(150, 158, 165),
    button=(307, 638, 351, 661),
    file="./assets/cn/retire/RETIRE_COIN.png",
)
RETIRE_CONFIRM_SCROLL_AREA = Button(
    area=(1092, 114, 1095, 592),
    color=(255, 255, 255),
    button=(1092, 114, 1095, 592),
    file="./assets/cn/retire/RETIRE_CONFIRM_SCROLL_AREA.png",
)
RETIRE_SETTING_1 = Button(
    area=(818, 259, 847, 290),
    color=(102, 122, 147),
    button=(818, 259, 847, 290),
    file="./assets/cn/retire/RETIRE_SETTING_1.png",
)
RETIRE_SETTING_2 = Button(
    area=(746, 316, 775, 346),
    color=(104, 124, 149),
    button=(746, 316, 775, 346),
    file="./assets/cn/retire/RETIRE_SETTING_2.png",
)
RETIRE_SETTING_3 = Button(
    area=(894, 372, 923, 404),
    color=(101, 120, 145),
    button=(894, 372, 923, 404),
    file="./assets/cn/retire/RETIRE_SETTING_3.png",
)
RETIRE_SETTING_4 = Button(
    area=(970, 471, 997, 498),
    color=(104, 125, 151),
    button=(970, 471, 997, 498),
    file="./assets/cn/retire/RETIRE_SETTING_4.png",
)
RETIRE_SETTING_5_ALL = Button(
    area=(969, 567, 997, 595),
    color=(66, 75, 92),
    button=(969, 567, 997, 595),
    file="./assets/cn/retire/RETIRE_SETTING_5_ALL.png",
)
RETIRE_SETTING_5_PRESERVE = Button(
    area=(863, 567, 890, 595),
    color=(103, 123, 149),
    button=(863, 567, 890, 595),
    file="./assets/cn/retire/RETIRE_SETTING_5_PRESERVE.png",
)
RETIRE_SETTING_ENTER = Button(
    area=(20, 501, 50, 531),
    color=(181, 181, 182),
    button=(20, 501, 50, 531),
    file="./assets/cn/retire/RETIRE_SETTING_ENTER.png",
)
RETIRE_SETTING_QUIT = Button(
    area=(986, 140, 1016, 169),
    color=(224, 118, 113),
    button=(986, 140, 1016, 169),
    file="./assets/cn/retire/RETIRE_SETTING_QUIT.png",
)
SHIP_CONFIRM = Button(
    area=(1069, 641, 1241, 698),
    color=(84, 131, 190),
    button=(1069, 641, 1241, 698),
    file="./assets/cn/retire/SHIP_CONFIRM.png",
)
SHIP_CONFIRM_2 = Button(
    area=(928, 617, 1100, 674),
    color=(95, 143, 203),
    button=(928, 617, 1100, 674),
    file="./assets/cn/retire/SHIP_CONFIRM_2.png",
)
SHIP_DETAIL_CHECK = Button(
    area=(121, 15, 230, 40),
    color=(152, 168, 206),
    button=(121, 15, 230, 40),
    file="./assets/cn/retire/SHIP_DETAIL_CHECK.png",
)
SORTING_CLICK = Button(
    area=(1004, 14, 1096, 42),
    color=(49, 54, 67),
    button=(1004, 14, 1096, 42),
    file="./assets/cn/retire/SORTING_CLICK.png",
)
SORT_ASC = Button(
    area=(1014, 22, 1019, 26),
    color=(189, 207, 231),
    button=(1014, 22, 1019, 26),
    file="./assets/cn/retire/SORT_ASC.png",
)
SORT_DESC = Button(
    area=(1014, 29, 1019, 33),
    color=(189, 207, 231),
    button=(1014, 29, 1019, 33),
    file="./assets/cn/retire/SORT_DESC.png",
)
SR_SSR_CONFIRM = Button(
    area=(757, 480, 829, 511),
    color=(150, 181, 221),
    button=(757, 480, 829, 511),
    file="./assets/cn/retire/SR_SSR_CONFIRM.png",
)
TEMPLATE_AULICK = Template(file="./assets/cn/retire/TEMPLATE_AULICK.png")
TEMPLATE_BOGUE = Template(file="./assets/cn/retire/TEMPLATE_BOGUE.png")
TEMPLATE_CASSIN_1 = Template(file="./assets/cn/retire/TEMPLATE_CASSIN_1.png")
TEMPLATE_CASSIN_2 = Template(file="./assets/cn/retire/TEMPLATE_CASSIN_2.png")
TEMPLATE_DOWNES_1 = Template(file="./assets/cn/retire/TEMPLATE_DOWNES_1.png")
TEMPLATE_DOWNES_2 = Template(file="./assets/cn/retire/TEMPLATE_DOWNES_2.png")
TEMPLATE_FLEET_1 = Template(file="./assets/cn/retire/TEMPLATE_FLEET_1.png")
TEMPLATE_FLEET_2 = Template(file="./assets/cn/retire/TEMPLATE_FLEET_2.png")
TEMPLATE_FLEET_3 = Template(file="./assets/cn/retire/TEMPLATE_FLEET_3.png")
TEMPLATE_FLEET_4 = Template(file="./assets/cn/retire/TEMPLATE_FLEET_4.png")
TEMPLATE_FLEET_5 = Template(file="./assets/cn/retire/TEMPLATE_FLEET_5.png")
TEMPLATE_FLEET_6 = Template(file="./assets/cn/retire/TEMPLATE_FLEET_6.png")
TEMPLATE_FOOTE = Template(file="./assets/cn/retire/TEMPLATE_FOOTE.png")
TEMPLATE_HERMES = Template(file="./assets/cn/retire/TEMPLATE_HERMES.png")
TEMPLATE_IN_BATTLE = Template(file="./assets/cn/retire/TEMPLATE_IN_BATTLE.png")
TEMPLATE_IN_COMMISSION = Template(file="./assets/cn/retire/TEMPLATE_IN_COMMISSION.png")
TEMPLATE_IN_EVENT_FLEET = Template(file="./assets/cn/retire/TEMPLATE_IN_EVENT_FLEET.png")
TEMPLATE_LANGLEY = Template(file="./assets/cn/retire/TEMPLATE_LANGLEY.png")
TEMPLATE_RANGER = Template(file="./assets/cn/retire/TEMPLATE_RANGER.png")
