from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

AMOUNT_MAX = Button(
    area=(762, 314, 830, 342),
    color=(104, 145, 209),
    button=(762, 314, 830, 342),
    file="./assets/cn/shop/AMOUNT_MAX.png",
)
AMOUNT_MINUS = Button(
    area=(549, 311, 582, 345),
    color=(82, 129, 194),
    button=(549, 311, 582, 345),
    file="./assets/cn/shop/AMOUNT_MINUS.png",
)
AMOUNT_PLUS = Button(
    area=(696, 312, 732, 345),
    color=(88, 133, 199),
    button=(696, 312, 732, 345),
    file="./assets/cn/shop/AMOUNT_PLUS.png",
)
MEDAL_SHOP_SCROLL_AREA_250814 = Button(
    area=(1063, 201, 1064, 623),
    color=(128, 143, 153),
    button=(1063, 201, 1064, 623),
    file="./assets/cn/shop/MEDAL_SHOP_SCROLL_AREA_250814.png",
)
NAV_GENERAL = Button(
    area=(52, 436, 127, 457),
    color=(126, 178, 207),
    button=(52, 436, 127, 457),
    file="./assets/cn/shop/NAV_GENERAL.png",
)
NAV_MONTHLY = Button(
    area=(52, 486, 127, 508),
    color=(127, 178, 207),
    button=(52, 486, 127, 508),
    file="./assets/cn/shop/NAV_MONTHLY.png",
)
SELECT_MINUS = Button(
    area=(562, 201, 588, 227),
    color=(86, 70, 70),
    button=(562, 201, 588, 227),
    file="./assets/cn/shop/SELECT_MINUS.png",
)
SELECT_PLUS = Button(
    area=(674, 201, 700, 227),
    color=(97, 70, 70),
    button=(674, 201, 700, 227),
    file="./assets/cn/shop/SELECT_PLUS.png",
)
SHOP_AMOUNT = Button(
    area=(600, 313, 680, 344),
    color=(38, 38, 46),
    button=(600, 313, 680, 344),
    file="./assets/cn/shop/SHOP_AMOUNT.png",
)
SHOP_BUY_CONFIRM = Button(
    area=(703, 483, 876, 540),
    color=(94, 142, 203),
    button=(703, 483, 876, 540),
    file="./assets/cn/shop/SHOP_BUY_CONFIRM.png",
)
SHOP_BUY_CONFIRM_AMOUNT = Button(
    area=(756, 622, 827, 653),
    color=(137, 168, 209),
    button=(756, 622, 827, 653),
    file="./assets/cn/shop/SHOP_BUY_CONFIRM_AMOUNT.png",
)
SHOP_BUY_CONFIRM_MISTAKE = Button(
    area=(590, 300, 612, 318),
    color=(154, 79, 103),
    button=(590, 300, 612, 318),
    file="./assets/cn/shop/SHOP_BUY_CONFIRM_MISTAKE.png",
)
SHOP_BUY_CONFIRM_SELECT = Button(
    area=(604, 642, 676, 671),
    color=(236, 191, 130),
    button=(604, 642, 676, 671),
    file="./assets/cn/shop/SHOP_BUY_CONFIRM_SELECT.png",
)
SHOP_CLICK_SAFE_AREA = Button(
    area=(1051, 137, 1218, 179),
    color=(150, 181, 163),
    button=(1051, 137, 1218, 179),
    file="./assets/cn/shop/SHOP_CLICK_SAFE_AREA.png",
)
SHOP_GEMS = Button(
    area=(1035, 23, 1133, 51),
    color=(55, 56, 53),
    button=(1035, 23, 1133, 51),
    file="./assets/cn/shop/SHOP_GEMS.png",
)
SHOP_GOLD_COINS = Button(
    area=(815, 23, 922, 51),
    color=(61, 61, 73),
    button=(815, 23, 922, 51),
    file="./assets/cn/shop/SHOP_GOLD_COINS.png",
)
SHOP_OCR_BALANCE = Button(
    area=(972, 164, 1052, 189),
    color=(193, 204, 210),
    button=(972, 164, 1052, 189),
    file="./assets/cn/shop/SHOP_OCR_BALANCE.png",
)
SHOP_OCR_OIL = Button(
    area=(700, 23, 785, 47),
    color=(150, 185, 194),
    button=(700, 23, 785, 47),
    file="./assets/cn/shop/SHOP_OCR_OIL.png",
)
SHOP_OCR_OIL_CHECK = Button(
    area=(666, 30, 682, 43),
    color=(73, 73, 73),
    button=(666, 30, 682, 43),
    file="./assets/cn/shop/SHOP_OCR_OIL_CHECK.png",
)
SHOP_REFRESH = Button(
    area=(1001, 653, 1070, 690),
    color=(65, 150, 212),
    button=(1001, 653, 1070, 690),
    file="./assets/cn/shop/SHOP_REFRESH.png",
)
SHOP_REFRESH_CHECK = Button(
    area=(1024, 660, 1048, 684),
    color=(131, 170, 197),
    button=(1024, 660, 1048, 684),
    file="./assets/cn/shop/SHOP_REFRESH_CHECK.png",
)
SHOP_SELECT_PR1 = Button(
    area=(182, 212, 308, 339),
    color=(157, 158, 143),
    button=(182, 212, 308, 339),
    file="./assets/cn/shop/SHOP_SELECT_PR1.png",
)
SHOP_SELECT_PR2 = Button(
    area=(182, 212, 310, 340),
    color=(160, 159, 145),
    button=(182, 212, 310, 340),
    file="./assets/cn/shop/SHOP_SELECT_PR2.png",
)
SHOP_SELECT_PR3 = Button(
    area=(180, 212, 309, 340),
    color=(156, 156, 142),
    button=(180, 212, 309, 340),
    file="./assets/cn/shop/SHOP_SELECT_PR3.png",
)
SHOP_SELECT_STOCK = Button(
    area=(1070, 152, 1126, 178),
    color=(76, 88, 90),
    button=(1070, 152, 1126, 178),
    file="./assets/cn/shop/SHOP_SELECT_STOCK.png",
)
SHOP_VOUCHER = Button(
    area=(1115, 123, 1261, 158),
    color=(90, 96, 110),
    button=(1115, 123, 1261, 158),
    file="./assets/cn/shop/SHOP_VOUCHER.png",
)
TAB_CORE_LIMITED = Button(
    area=(303, 99, 340, 118),
    color=(154, 161, 166),
    button=(303, 99, 340, 118),
    file="./assets/cn/shop/TAB_CORE_LIMITED.png",
)
TAB_CORE_MONTHLY = Button(
    area=(533, 100, 570, 118),
    color=(154, 161, 166),
    button=(533, 100, 570, 118),
    file="./assets/cn/shop/TAB_CORE_MONTHLY.png",
)
TAB_GENERAL = Button(
    area=(259, 98, 300, 118),
    color=(175, 182, 186),
    button=(259, 98, 300, 118),
    file="./assets/cn/shop/TAB_GENERAL.png",
)
TAB_GUILD = Button(
    area=(627, 98, 668, 118),
    color=(160, 167, 172),
    button=(627, 98, 668, 118),
    file="./assets/cn/shop/TAB_GUILD.png",
)
TAB_MEDAL = Button(
    area=(742, 99, 783, 118),
    color=(151, 159, 163),
    button=(742, 99, 783, 118),
    file="./assets/cn/shop/TAB_MEDAL.png",
)
TAB_MERIT = Button(
    area=(443, 98, 484, 118),
    color=(157, 164, 169),
    button=(443, 98, 484, 118),
    file="./assets/cn/shop/TAB_MERIT.png",
)
TAB_META = Button(
    area=(804, 99, 860, 117),
    color=(172, 179, 183),
    button=(804, 99, 860, 117),
    file="./assets/cn/shop/TAB_META.png",
)
TAB_PRIZE = Button(
    area=(995, 98, 1037, 118),
    color=(162, 168, 173),
    button=(995, 98, 1037, 118),
    file="./assets/cn/shop/TAB_PRIZE.png",
)
TAB_PROTOTYPE = Button(
    area=(973, 98, 1013, 118),
    color=(154, 161, 165),
    button=(973, 98, 1013, 118),
    file="./assets/cn/shop/TAB_PROTOTYPE.png",
)
VOUCHER_SHOP_SCROLL_AREA = Button(
    area=(1257, 184, 1263, 647),
    color=(255, 255, 255),
    button=(1257, 184, 1263, 647),
    file="./assets/cn/shop/VOUCHER_SHOP_SCROLL_AREA.png",
)
