from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

OCR_SIGNAL = Button(
    area=(1189, 510, 1215, 542),
    color=(93, 101, 116),
    button=(1189, 510, 1215, 542),
    file="./assets/cn/sos/OCR_SIGNAL.png",
)
SIGNAL_LIST_CHECK = Button(
    area=(351, 164, 482, 198),
    color=(155, 174, 211),
    button=(351, 164, 482, 198),
    file="./assets/cn/sos/SIGNAL_LIST_CHECK.png",
)
SIGNAL_SEARCH_CLOSE = Button(
    area=(896, 157, 939, 194),
    color=(205, 95, 87),
    button=(896, 157, 939, 194),
    file="./assets/cn/sos/SIGNAL_SEARCH_CLOSE.png",
)
SIGNAL_SEARCH_ENTER = Button(
    area=(1175, 499, 1230, 554),
    color=(72, 81, 98),
    button=(1175, 499, 1230, 554),
    file="./assets/cn/sos/SIGNAL_SEARCH_ENTER.png",
)
SOS_SCROLL_AREA = Button(
    area=(935, 257, 941, 516),
    color=(120, 133, 146),
    button=(935, 257, 941, 516),
    file="./assets/cn/sos/SOS_SCROLL_AREA.png",
)
TEMPLATE_SIGNAL_CONFIRM = Template(file="./assets/cn/sos/TEMPLATE_SIGNAL_CONFIRM.png")
TEMPLATE_SIGNAL_GOTO = Template(file="./assets/cn/sos/TEMPLATE_SIGNAL_GOTO.png")
TEMPLATE_SIGNAL_SEARCH = Template(file="./assets/cn/sos/TEMPLATE_SIGNAL_SEARCH.png")
