schema_version: 1
id: event_20240725_cn
kind: event
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2024-07-25'
  name_cn: 幻梦间奏曲
  order: 1850
- opened_on: '2025-02-27'
  name_cn: null
  order: 2100
stages:
- id: ht1
  source: stages/ht1.yaml
  runtime_profile: profile_5a0d5fabd6df603f
- id: ht2
  source: stages/ht2.yaml
  runtime_profile: profile_5a0d5fabd6df603f
- id: ht3
  source: stages/ht3.yaml
  runtime_profile: profile_5a0d5fabd6df603f
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_5a0d5fabd6df603f
- id: t1
  source: stages/t1.yaml
  runtime_profile: profile_5a0d5fabd6df603f
- id: t2
  source: stages/t2.yaml
  runtime_profile: profile_5a0d5fabd6df603f
- id: t3
  source: stages/t3.yaml
  runtime_profile: profile_5a0d5fabd6df603f
policy:
  aliases:
    a1: t1
    a2: t2
    a3: t3
    c1: ht1
    c2: ht2
    c3: ht3
    y.sp: sp
    ysp: sp
  progressions:
    ht1: ht2
    ht2: ht3
    ht3: null
    t1: t2
    t2: t3
    t3: null
