schema_version: 1
id: event_20251023_cn
kind: event
activity:
  kind: event_story
  profile: sp
releases:
- opened_on: '2025-10-23'
  name_cn: 飓风与自由群岛
  order: 2340
- opened_on: '2025-12-11'
  name_cn: null
  order: 2410
stages:
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_0b42f64686054d41
- id: t1
  source: stages/t1.yaml
  runtime_profile: profile_1f30e7e2b84859c0
- id: t2
  source: stages/t2.yaml
  runtime_profile: profile_1f30e7e2b84859c0
- id: t3
  source: stages/t3.yaml
  runtime_profile: profile_1f30e7e2b84859c0
- id: t4
  source: stages/t4.yaml
  runtime_profile: profile_1f30e7e2b84859c0
- id: t5
  source: stages/t5.yaml
  runtime_profile: profile_1f30e7e2b84859c0
- id: t6
  source: stages/t6.yaml
  runtime_profile: profile_c9a495d2baa0c11e
policy:
  aliases:
    a1: t1
    a2: t2
    a3: t3
    a4: t4
    a5: t5
    a6: t6
    b1: t4
    b2: t5
    b3: t6
    sp1: t1
    sp2: t2
    sp3: t3
    sp4: t4
    sp5: t5
    sp6: t6
  progressions:
    t1: t2
    t2: t3
    t3: t4
    t4: t5
    t5: t6
    t6: null
