schema_version: 1
id: event_20220324_cn
kind: event
ui_profile: campaign_v1
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2022-03-24'
  name_cn: 虚像构筑之塔
  order: 930
- opened_on: '2022-08-18'
  name_cn: null
  order: 1080
- opened_on: '2024-03-14'
  name_cn: 复刻虚像构筑之塔
  order: 1690
- opened_on: '2024-08-29'
  name_cn: null
  order: 1900
stages:
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_4362779e466f63c7
- id: sp1
  source: stages/sp1.yaml
  runtime_profile: profile_0f46874512014eda
- id: sp2
  source: stages/sp2.yaml
  runtime_profile: profile_0f46874512014eda
- id: sp3
  source: stages/sp3.yaml
  runtime_profile: profile_0f46874512014eda
- id: sp4
  source: stages/sp4.yaml
  runtime_profile: profile_0f46874512014eda
policy:
  aliases:
    esp: sp
  progressions:
    sp1: sp2
    sp2: sp3
    sp3: sp4
    sp4: null
