schema_version: 1
id: event_20250814_cn
kind: event
ui_profile: campaign_v1
activity:
  kind: event_story
  profile: rpg_status
releases:
- opened_on: '2025-08-14'
  name_cn: 奇渊下的秘密
  order: 2270
- opened_on: '2025-08-28'
  name_cn: null
  order: 2290
stages:
- id: ht1
  source: stages/ht1.yaml
  runtime_profile: profile_6324c265c07d0cfc
- id: ht2
  source: stages/ht2.yaml
  runtime_profile: profile_da7184ef3b279a22
- id: ht3
  source: stages/ht3.yaml
  runtime_profile: profile_6324c265c07d0cfc
- id: ht4
  source: stages/ht4.yaml
  runtime_profile: profile_6324c265c07d0cfc
- id: ht5
  source: stages/ht5.yaml
  runtime_profile: profile_6324c265c07d0cfc
- id: ht6
  source: stages/ht6.yaml
  runtime_profile: profile_6324c265c07d0cfc
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_6324c265c07d0cfc
- id: t1
  source: stages/t1.yaml
  runtime_profile: profile_6324c265c07d0cfc
- id: t2
  source: stages/t2.yaml
  runtime_profile: profile_da7184ef3b279a22
- id: t3
  source: stages/t3.yaml
  runtime_profile: profile_6324c265c07d0cfc
- id: t4
  source: stages/t4.yaml
  runtime_profile: profile_6324c265c07d0cfc
- id: t5
  source: stages/t5.yaml
  runtime_profile: profile_6324c265c07d0cfc
- id: t6
  source: stages/t6.yaml
  runtime_profile: profile_6324c265c07d0cfc
policy:
  aliases:
    a1: t1
    a2: t2
    a3: t3
    a4: t4
    a5: t5
    a6: t6
    b1: t4
    b2: t5
    b3: t6
    c1: ht1
    c2: ht2
    c3: ht3
    d1: ht4
    d2: ht5
    d3: ht6
    sp1: t1
    sp2: t2
    sp3: t3
    sp4: t4
    sp5: t5
    sp6: t6
  progressions:
    ht1: ht2
    ht2: ht3
    ht3: ht4
    ht4: ht5
    ht5: ht6
    ht6: null
    t1: t2
    t2: t3
    t3: t4
    t4: t5
    t5: t6
    t6: null
