schema_version: 1
id: event_20230223_cn
kind: event
ui_profile: campaign_v1
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2023-02-23'
  name_cn: 湮烬尘墟
  order: 1260
- opened_on: '2024-02-29'
  name_cn: null
  order: 1660
- opened_on: '2025-03-20'
  name_cn: 复刻湮烬尘墟
  order: 2110
- opened_on: '2026-06-25'
  name_cn: null
  order: 2660
stages:
- id: a1
  source: stages/a1.yaml
  runtime_profile: core
- id: a2
  source: stages/a2.yaml
  runtime_profile: core
- id: a3
  source: stages/a3.yaml
  runtime_profile: core
- id: b1
  source: stages/b1.yaml
  runtime_profile: profile_72498bef23a030f8
- id: b2
  source: stages/b2.yaml
  runtime_profile: profile_72498bef23a030f8
- id: b3
  source: stages/b3.yaml
  runtime_profile: profile_72498bef23a030f8
- id: c1
  source: stages/c1.yaml
  runtime_profile: core
- id: c2
  source: stages/c2.yaml
  runtime_profile: core
- id: c3
  source: stages/c3.yaml
  runtime_profile: core
- id: d1
  source: stages/d1.yaml
  runtime_profile: profile_72498bef23a030f8
- id: d2
  source: stages/d2.yaml
  runtime_profile: profile_72498bef23a030f8
- id: d3
  source: stages/d3.yaml
  runtime_profile: profile_72498bef23a030f8
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_c369a937792b50e6
policy:
  aliases:
    ht1: c1
    ht2: c2
    ht3: c3
    ht4: d1
    ht5: d2
    ht6: d3
    t1: a1
    t2: a2
    t3: a3
    t4: b1
    t5: b2
    t6: b3
  progressions:
    a1: a2
    a2: a3
    a3: b1
    b1: b2
    b2: b3
    b3: null
    c1: c2
    c2: c3
    c3: null
    d1: d2
    d2: d3
    d3: null
