schema_version: 1
id: event_20220915_cn
kind: event
ui_profile: campaign_v1
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2022-09-15'
  name_cn: 紫绛槿岚
  order: 1110
- opened_on: '2023-09-14'
  name_cn: null
  order: 1480
- opened_on: '2024-11-14'
  name_cn: 复刻紫绛槿岚
  order: 1970
- opened_on: '2026-04-16'
  name_cn: null
  order: 2550
stages:
- id: a1
  source: stages/a1.yaml
  runtime_profile: profile_65d5968eec7a5c1a
- id: a2
  source: stages/a2.yaml
  runtime_profile: profile_65d5968eec7a5c1a
- id: a3
  source: stages/a3.yaml
  runtime_profile: profile_65d5968eec7a5c1a
- id: b1
  source: stages/b1.yaml
  runtime_profile: profile_9df006311733c781
- id: b2
  source: stages/b2.yaml
  runtime_profile: profile_9df006311733c781
- id: b3
  source: stages/b3.yaml
  runtime_profile: profile_9df006311733c781
- id: c1
  source: stages/c1.yaml
  runtime_profile: profile_499a96deab13a7c9
- id: c2
  source: stages/c2.yaml
  runtime_profile: profile_499a96deab13a7c9
- id: c3
  source: stages/c3.yaml
  runtime_profile: profile_499a96deab13a7c9
- id: d1
  source: stages/d1.yaml
  runtime_profile: profile_f2e3f60dc1901d11
- id: d2
  source: stages/d2.yaml
  runtime_profile: profile_f2e3f60dc1901d11
- id: d3
  source: stages/d3.yaml
  runtime_profile: profile_f2e3f60dc1901d11
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_f2e3f60dc1901d11
policy:
  aliases:
    ht1: c1
    ht2: c2
    ht3: c3
    ht4: d1
    ht5: d2
    ht6: d3
    t1: a1
    t2: a2
    t3: a3
    t4: b1
    t5: b2
    t6: b3
  progressions:
    a1: a2
    a2: a3
    a3: b1
    b1: b2
    b2: b3
    b3: null
    c1: c2
    c2: c3
    c3: null
    d1: d2
    d2: d3
    d3: null
