schema_version: 1
id: event_20200917_cn
kind: event
ui_profile: campaign_v1
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2020-09-17'
  name_cn: 蝶海梦花
  order: 580
- opened_on: '2021-09-23'
  name_cn: null
  order: 780
- opened_on: '2022-07-14'
  name_cn: 复刻蝶海梦花
  order: 1050
- opened_on: '2023-07-27'
  name_cn: null
  order: 1420
stages:
- id: ht1
  source: stages/ht1.yaml
  runtime_profile: profile_c24c6ed26c0858eb
- id: ht2
  source: stages/ht2.yaml
  runtime_profile: profile_c24c6ed26c0858eb
- id: ht3
  source: stages/ht3.yaml
  runtime_profile: profile_c24c6ed26c0858eb
- id: ht4
  source: stages/ht4.yaml
  runtime_profile: profile_c24c6ed26c0858eb
- id: ht5
  source: stages/ht5.yaml
  runtime_profile: profile_c24c6ed26c0858eb
- id: ht6
  source: stages/ht6.yaml
  runtime_profile: profile_c24c6ed26c0858eb
- id: hts1
  source: stages/hts1.yaml
  runtime_profile: profile_58c284dbe8eed4d9
- id: hts2
  source: stages/hts2.yaml
  runtime_profile: profile_58c284dbe8eed4d9
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_eb434849c0170f07
- id: t1
  source: stages/t1.yaml
  runtime_profile: profile_c24c6ed26c0858eb
- id: t2
  source: stages/t2.yaml
  runtime_profile: profile_7d9cf3a525694257
- id: t3
  source: stages/t3.yaml
  runtime_profile: profile_7d9cf3a525694257
- id: t4
  source: stages/t4.yaml
  runtime_profile: profile_7d9cf3a525694257
- id: t5
  source: stages/t5.yaml
  runtime_profile: profile_7d9cf3a525694257
- id: t6
  source: stages/t6.yaml
  runtime_profile: profile_c24c6ed26c0858eb
- id: ts1
  source: stages/ts1.yaml
  runtime_profile: profile_58c284dbe8eed4d9
- id: ts2
  source: stages/ts2.yaml
  runtime_profile: profile_58c284dbe8eed4d9
policy:
  aliases:
    a1: t1
    a2: t2
    a3: t3
    b1: t4
    b2: t5
    b3: t6
    c1: ht1
    c2: ht2
    c3: ht3
    d1: ht4
    d2: ht5
    d3: ht6
  progressions:
    ht1: ht2
    ht2: ht3
    ht3: null
    ht4: hts2
    ht5: ht6
    ht6: null
    hts1: ht1
    hts2: ht5
    t1: t2
    t2: t3
    t3: t4
    t4: ts2
    t5: t6
    t6: null
    ts1: t1
    ts2: t5
