schema_version: 1
id: event_20230803_cn
kind: event
ui_profile: campaign_v1
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2023-08-03'
  name_cn: 奏响鸢尾之歌
  order: 1440
- opened_on: '2024-01-11'
  name_cn: null
  order: 1620
- opened_on: '2025-11-06'
  name_cn: 复刻奏响鸢尾之歌
  order: 2350
stages:
- id: sp1
  source: stages/sp1.yaml
  runtime_profile: profile_da74332c40a63a58
- id: sp2
  source: stages/sp2.yaml
  runtime_profile: profile_da74332c40a63a58
- id: sp3
  source: stages/sp3.yaml
  runtime_profile: profile_1701342bbe4bda32
policy:
  progressions:
    sp1: sp2
    sp2: sp3
    sp3: null
