schema_version: 1
id: event_20220526_cn
kind: event
ui_profile: campaign_v1
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2022-05-26'
  name_cn: 泠誓光庭
  order: 980
- opened_on: '2023-05-25'
  name_cn: null
  order: 1340
- opened_on: '2024-07-18'
  name_cn: 复刻泠誓光庭
  order: 1840
- opened_on: '2026-01-22'
  name_cn: null
  order: 2460
stages:
- id: a1
  source: stages/a1.yaml
  runtime_profile: profile_0d46c5fa22613b0c
- id: a2
  source: stages/a2.yaml
  runtime_profile: profile_6cd78dc7421fd44f
- id: a3
  source: stages/a3.yaml
  runtime_profile: profile_39ae84b0d0009d8b
- id: b1
  source: stages/b1.yaml
  runtime_profile: profile_348f85b822ad7da0
- id: b2
  source: stages/b2.yaml
  runtime_profile: profile_173764790f75baed
- id: b3
  source: stages/b3.yaml
  runtime_profile: profile_820814de5087eff9
- id: c1
  source: stages/c1.yaml
  runtime_profile: profile_66b49cd06dd3a1fd
- id: c2
  source: stages/c2.yaml
  runtime_profile: profile_a1c97c434cfa77fd
- id: c3
  source: stages/c3.yaml
  runtime_profile: profile_39ae84b0d0009d8b
- id: d1
  source: stages/d1.yaml
  runtime_profile: profile_5e42938edd1ea950
- id: d2
  source: stages/d2.yaml
  runtime_profile: profile_173764790f75baed
- id: d3
  source: stages/d3.yaml
  runtime_profile: profile_820814de5087eff9
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_9a341a980476b2dd
policy:
  aliases:
    ht1: c1
    ht2: c2
    ht3: c3
    ht4: d1
    ht5: d2
    ht6: d3
    t1: a1
    t2: a2
    t3: a3
    t4: b1
    t5: b2
    t6: b3
  progressions:
    a1: a2
    a2: a3
    a3: b1
    b1: b2
    b2: b3
    b3: null
    c1: c2
    c2: c3
    c3: null
    d1: d2
    d2: d3
    d3: null
