schema_version: 1
id: event_20231026_cn
kind: event
ui_profile: campaign_v1
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2023-10-26'
  name_cn: 飓风与青春之泉
  order: 1520
- opened_on: '2024-06-27'
  name_cn: null
  order: 1810
stages:
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_e8748747e2bceb40
- id: t1
  source: stages/t1.yaml
  runtime_profile: profile_a63de9c7479d5ed2
- id: t2
  source: stages/t2.yaml
  runtime_profile: profile_99e951ebd1ec5b43
- id: t3
  source: stages/t3.yaml
  runtime_profile: profile_a63de9c7479d5ed2
- id: t4
  source: stages/t4.yaml
  runtime_profile: profile_a63de9c7479d5ed2
- id: t5
  source: stages/t5.yaml
  runtime_profile: profile_99e951ebd1ec5b43
- id: t6
  source: stages/t6.yaml
  runtime_profile: profile_4dcc61386391f722
policy:
  aliases:
    a1: t1
    a2: t2
    a3: t3
    a4: t4
    a5: t5
    a6: t6
    b1: t4
    b2: t5
    b3: t6
    sp1: t1
    sp2: t2
    sp3: t3
    sp4: t4
    sp5: t5
    sp6: t6
  progressions:
    t1: t2
    t2: t3
    t3: t4
    t4: t5
    t5: t6
    t6: null
