schema_version: 1
id: event_20241024_cn
kind: event
ui_profile: campaign_v1
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2024-10-24'
  name_cn: 飓风与沉眠之海
  order: 1950
- opened_on: '2025-04-10'
  name_cn: null
  order: 2130
stages:
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_d4805cf726705a91
- id: t1
  source: stages/t1.yaml
  runtime_profile: profile_f427c46478edd040
- id: t2
  source: stages/t2.yaml
  runtime_profile: profile_f427c46478edd040
- id: t3
  source: stages/t3.yaml
  runtime_profile: profile_50e7c89d7aad6725
- id: t4
  source: stages/t4.yaml
  runtime_profile: profile_aaa899e8f0b3c7b8
- id: t5
  source: stages/t5.yaml
  runtime_profile: profile_327e88d495a33724
- id: t6
  source: stages/t6.yaml
  runtime_profile: profile_5a442e0716334207
policy:
  aliases:
    a1: t1
    a2: t2
    a3: t3
    a4: t4
    a5: t5
    a6: t6
    b1: t4
    b2: t5
    b3: t6
    sp1: t1
    sp2: t2
    sp3: t3
    sp4: t4
    sp5: t5
    sp6: t6
  progressions:
    t1: t2
    t2: t3
    t3: t4
    t4: t5
    t5: t6
    t6: null
