schema_version: 1
id: event_20200507_cn
kind: event
ui_profile: campaign_v1
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2020-05-07'
  name_cn: 夜幕下的归途
  order: 510
stages:
- id: sp1
  source: stages/sp1.yaml
  runtime_profile: profile_caa93564589ec25b
- id: sp2
  source: stages/sp2.yaml
  runtime_profile: profile_caa93564589ec25b
- id: sp3
  source: stages/sp3.yaml
  runtime_profile: profile_642ff9392f02b170
policy:
  progressions:
    sp1: sp2
    sp2: sp3
    sp3: null
