schema_version: 1
id: event_20201126_cn
kind: event
ui_profile: campaign_v1
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2020-11-26'
  name_cn: 假日航线
  order: 620
- opened_on: '2023-04-27'
  name_cn: 假日航线
  order: 1330
- opened_on: '2026-04-17'
  name_cn: 复刻假日航线
  order: 2570
- opened_on: '2026-04-17'
  name_cn: null
  order: 2600
stages:
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_39c05cd00db42fb9
- id: sp1
  source: stages/sp1.yaml
  runtime_profile: profile_e89842104e739d9e
- id: sp2
  source: stages/sp2.yaml
  runtime_profile: profile_e89842104e739d9e
- id: sp3
  source: stages/sp3.yaml
  runtime_profile: profile_e89842104e739d9e
- id: sp4
  source: stages/sp4.yaml
  runtime_profile: profile_e89842104e739d9e
policy:
  aliases:
    vsp: sp
  progressions:
    sp1: sp2
    sp2: sp3
    sp3: sp4
    sp4: null
