schema_version: 1
id: event_20210722_cn
kind: event
ui_profile: campaign_v1
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2021-07-22'
  name_cn: 响彻碧海的偶像歌
  order: 720
- opened_on: '2021-08-26'
  name_cn: null
  order: 760
stages:
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_573e0a49db6277b4
- id: sp1
  source: stages/sp1.yaml
  runtime_profile: profile_573e0a49db6277b4
- id: sp2
  source: stages/sp2.yaml
  runtime_profile: profile_573e0a49db6277b4
- id: sp3
  source: stages/sp3.yaml
  runtime_profile: profile_573e0a49db6277b4
- id: sp4
  source: stages/sp4.yaml
  runtime_profile: profile_51e54e8a44737454
policy:
  aliases:
    vsp: sp
  progressions:
    sp1: sp2
    sp2: sp3
    sp3: sp4
    sp4: null
