schema_version: 1
id: event_20220818_cn
kind: event
activity:
  kind: event_story
  profile: standard
releases:
- opened_on: '2022-08-18'
  name_cn: 远汇点作战
  order: 1090
- opened_on: '2023-07-13'
  name_cn: null
  order: 1400
- opened_on: '2025-02-06'
  name_cn: 复刻远汇点作战
  order: 2070
- opened_on: '2026-05-28'
  name_cn: null
  order: 2630
stages:
- id: sp
  source: stages/sp.yaml
  runtime_profile: profile_e202cb19f542a215
- id: sp1
  source: stages/sp1.yaml
  runtime_profile: profile_c76faa5c9c1e8d71
- id: sp2
  source: stages/sp2.yaml
  runtime_profile: profile_c76faa5c9c1e8d71
- id: sp3
  source: stages/sp3.yaml
  runtime_profile: profile_c76faa5c9c1e8d71
- id: sp4
  source: stages/sp4.yaml
  runtime_profile: profile_c76faa5c9c1e8d71
policy:
  aliases:
    esp: sp
  progressions:
    sp1: sp2
    sp2: sp3
    sp3: sp4
    sp4: null
