schema_version: 1
id: war_archives_20211111_cn
kind: war_archives
war_archives:
  profile: the_flame_touched_dagger
releases:
- opened_on: '2024-06-13'
  name_cn: 杰诺瓦的焰火
  order: 320
stages:
- id: sp1
  source: stages/sp1.yaml
  runtime_profile: profile_536216ef5130ae21
- id: sp2
  source: stages/sp2.yaml
  runtime_profile: profile_536216ef5130ae21
- id: sp3
  source: stages/sp3.yaml
  runtime_profile: profile_536216ef5130ae21
policy:
  progressions:
    sp1: sp2
    sp2: sp3
    sp3: null
