schema_version: 1
id: war_archives_20191010_cn
kind: war_archives
war_archives:
  profile: encircling_graf_spee
releases:
- opened_on: '2018-01-19'
  name_cn: 围剿斯佩伯爵
  order: 60
stages:
- id: sp1
  source: stages/sp1.yaml
  runtime_profile: profile_e8b9f9cf244a5223
- id: sp2
  source: stages/sp2.yaml
  runtime_profile: profile_e8b9f9cf244a5223
- id: sp3
  source: stages/sp3.yaml
  runtime_profile: profile_e8b9f9cf244a5223
policy:
  progressions:
    sp1: sp2
    sp2: sp3
    sp3: null
