schema_version: 1
id: war_archives_20220414_cn
kind: war_archives
ui_profile: campaign_v1
war_archives:
  profile: aurora_noctis
releases:
- opened_on: '2023-05-11'
  name_cn: 永夜幻光
  order: 250
stages:
- id: a1
  source: stages/a1.yaml
  runtime_profile: profile_86e560c3ac181abb
- id: a2
  source: stages/a2.yaml
  runtime_profile: profile_86e560c3ac181abb
- id: a3
  source: stages/a3.yaml
  runtime_profile: profile_86e560c3ac181abb
- id: b1
  source: stages/b1.yaml
  runtime_profile: profile_86e560c3ac181abb
- id: b2
  source: stages/b2.yaml
  runtime_profile: profile_86e560c3ac181abb
- id: b3
  source: stages/b3.yaml
  runtime_profile: profile_be8877c78a313635
- id: c1
  source: stages/c1.yaml
  runtime_profile: profile_86e560c3ac181abb
- id: c2
  source: stages/c2.yaml
  runtime_profile: profile_86e560c3ac181abb
- id: c3
  source: stages/c3.yaml
  runtime_profile: profile_86e560c3ac181abb
- id: d1
  source: stages/d1.yaml
  runtime_profile: profile_86e560c3ac181abb
- id: d2
  source: stages/d2.yaml
  runtime_profile: profile_86e560c3ac181abb
- id: d3
  source: stages/d3.yaml
  runtime_profile: profile_be8877c78a313635
policy:
  aliases:
    ht1: c1
    ht2: c2
    ht3: c3
    ht4: d1
    ht5: d2
    ht6: d3
    t1: a1
    t2: a2
    t3: a3
    t4: b1
    t5: b2
    t6: b3
  progressions:
    a1: a2
    a2: a3
    a3: b1
    b1: b2
    b2: b3
    b3: null
    c1: c2
    c2: c3
    c3: null
    d1: d2
    d2: d3
    d3: null
