schema_version: 1
id: war_archives_20230803_cn
kind: war_archives
ui_profile: campaign_v1
war_archives:
  profile: anthem_of_remembrance
releases:
- opened_on: '2026-05-07'
  name_cn: 奏响鸢尾之歌
  order: 460
stages:
- id: sp1
  source: stages/sp1.yaml
  runtime_profile: profile_225de2051e0a712e
- id: sp2
  source: stages/sp2.yaml
  runtime_profile: profile_225de2051e0a712e
- id: sp3
  source: stages/sp3.yaml
  runtime_profile: profile_26563882edf99082
policy:
  progressions:
    sp1: sp2
    sp2: sp3
    sp3: null
