schema_version: 1
id: war_archives_20190911_cn
kind: war_archives
war_archives:
  profile: empyreal_tragicomedy
releases:
- opened_on: '2022-01-13'
  name_cn: 神圣的悲喜剧
  order: 150
stages:
- id: a1
  source: stages/a1.yaml
  runtime_profile: profile_edf6bdefb41f8111
- id: a2
  source: stages/a2.yaml
  runtime_profile: profile_2c1d105e47cf96db
- id: a3
  source: stages/a3.yaml
  runtime_profile: profile_2c1d105e47cf96db
- id: as1
  source: stages/as1.yaml
  runtime_profile: profile_e8b9f9cf244a5223
- id: as2
  source: stages/as2.yaml
  runtime_profile: profile_e8b9f9cf244a5223
- id: b1
  source: stages/b1.yaml
  runtime_profile: profile_1e94a06ed5c6b795
- id: b2
  source: stages/b2.yaml
  runtime_profile: profile_1e94a06ed5c6b795
- id: b3
  source: stages/b3.yaml
  runtime_profile: profile_1e94a06ed5c6b795
- id: c1
  source: stages/c1.yaml
  runtime_profile: profile_edf6bdefb41f8111
- id: c2
  source: stages/c2.yaml
  runtime_profile: profile_2c1d105e47cf96db
- id: c3
  source: stages/c3.yaml
  runtime_profile: profile_2c1d105e47cf96db
- id: cs1
  source: stages/cs1.yaml
  runtime_profile: profile_edf6bdefb41f8111
- id: cs2
  source: stages/cs2.yaml
  runtime_profile: profile_edf6bdefb41f8111
- id: d1
  source: stages/d1.yaml
  runtime_profile: profile_1e94a06ed5c6b795
- id: d2
  source: stages/d2.yaml
  runtime_profile: profile_1e94a06ed5c6b795
- id: d3
  source: stages/d3.yaml
  runtime_profile: profile_ca7c4a1d471776a8
policy:
  aliases:
    ht1: c1
    ht2: c2
    ht3: c3
    ht4: d1
    ht5: d2
    ht6: d3
    t1: a1
    t2: a2
    t3: a3
    t4: b1
    t5: b2
    t6: b3
  progressions:
    a1: a2
    a2: a3
    a3: b1
    as1: a2
    as2: a3
    b1: b2
    b2: b3
    b3: null
    c1: cs1
    c2: cs2
    c3: null
    cs1: c2
    cs2: c3
    d1: d2
    d2: d3
    d3: null
