schema_version: 1
id: war_archives_20180607_cn
kind: war_archives
war_archives:
  profile: ink_stained_steel_sakura
releases:
- opened_on: '2018-06-07'
  name_cn: 墨染的钢铁之花
  order: 80
stages:
- id: a1
  source: stages/a1.yaml
  runtime_profile: profile_a392c6a154516da7
- id: a2
  source: stages/a2.yaml
  runtime_profile: profile_a392c6a154516da7
- id: a3
  source: stages/a3.yaml
  runtime_profile: profile_a392c6a154516da7
- id: a4
  source: stages/a4.yaml
  runtime_profile: profile_a392c6a154516da7
- id: b1
  source: stages/b1.yaml
  runtime_profile: profile_a392c6a154516da7
- id: b2
  source: stages/b2.yaml
  runtime_profile: profile_45fe869e211d785c
- id: c1
  source: stages/c1.yaml
  runtime_profile: profile_45fe869e211d785c
- id: c2
  source: stages/c2.yaml
  runtime_profile: profile_45fe869e211d785c
- id: c3
  source: stages/c3.yaml
  runtime_profile: profile_45fe869e211d785c
- id: c4
  source: stages/c4.yaml
  runtime_profile: profile_45fe869e211d785c
- id: d1
  source: stages/d1.yaml
  runtime_profile: profile_45d4106a4e442b1b
- id: d2
  source: stages/d2.yaml
  runtime_profile: profile_45d4106a4e442b1b
policy:
  aliases:
    ht1: c1
    ht2: c2
    ht3: c3
    ht4: d1
    ht5: d2
    t1: a1
    t2: a2
    t3: a3
    t4: b1
    t5: b2
  progressions:
    a1: a2
    a2: a3
    a3: b1
    b1: b2
    b2: null
    c1: c2
    c2: c3
    c3: null
    d1: d2
    d2: null
