# Translations web gui
# This will insert to `config/i18n/{lang}.json`, under key `Gui`

Aside:
  Install:
  Home:
  Develop:
  Performance:
  Setting:
  AddAlas:

Button:
  Start:
  Stop:
  ScrollON:
  ScrollOFF:
  ClearLog:
  Setting:

Toast:
  ConfigSaved:
  AlasIsRunning:

Status:
  Running:
  Inactive:
  Warning:

MenuAlas:
  Overview:
  Log:

MenuDevelop:
  HomePage:
  Remote:
  Utils:

Overview:
  Scheduler:
  Log:
  Running:
  Pending:
  Waiting:
  NoTask:

AddAlas:
  PopupTitle:
  NewName:
  CopyFrom:
  Confirm:
  FileExist:
  InvalidChar:
  InvalidPrefixTemplate:
  Manage:

AppManage:
  PageTitle:
  TitleNew:
  NewName:
  CopyFrom:
  NameExist:
  InvalidChar:
  InvalidPrefixTemplate:
  Back:
  New:
  Import:
  Export:
  Delete:
  OverrideWarning:
  ImportSuccess:
  NewSuccess:
  Name:
  Mod:
  Actions:

Remote:
  Running:
  NotRunning:
  NotEnable:
  EntryPoint:
  ConfigureHint:
  SSHNotInstall:

Text:
  InvalidFeedBack:
  Clear:
  EnterPassword:
  ChooseFile:
