# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Alas:
      groups:
        - Emulator
        - Error
        - Optimization
    General:
      groups:
        - Retirement
        - OneClickRetire
        - Enhance
        - OldRetire
    Restart:
      groups:
        - Scheduler

# ==================== Farm ====================

Farm:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Main:
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    Main2:
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    Main3:
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    GemsFarming:
      groups:
        - Scheduler
        - GemsFarming
        - EquipmentCode
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion

# ==================== Event ====================

Event:
  menu: 'collapse'
  page: 'setting'
  tasks:
    EventGeneral:
      groups:
        - EventGeneral
        - TaskBalancer
    Event:
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    Event2:
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    Raid:
      groups:
        - Scheduler
        - Raid
        - Campaign
        - StopCondition
        - Emotion
    Hospital:
      groups:
        - Scheduler
        - Hospital
        - StopCondition
        - Emotion
    Coalition:
      groups:
        - Scheduler
        - Campaign
        - Coalition
        - StopCondition
        - Emotion
    MaritimeEscort:
      groups:
        - Scheduler
        - MaritimeEscort
    WarArchives:
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority


# ==================== EventDaily ====================

EventDaily:
  menu: 'collapse'
  page: 'setting'
  tasks:
    EventA:
      groups:
        - Scheduler
        - EventDaily
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    EventB:
      groups:
        - Scheduler
        - EventDaily
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    EventC:
      groups:
        - Scheduler
        - EventDaily
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    EventD:
      groups:
        - Scheduler
        - EventDaily
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    EventSp:
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    RaidDaily:
      groups:
        - Scheduler
        - RaidDaily
        - Campaign
        - StopCondition
        - Emotion
    CoalitionSp:
      groups:
        - Scheduler
        - Campaign
        - Coalition
        - StopCondition
        - Emotion

# ==================== Reward ====================

Reward:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Commission:
      groups:
        - Scheduler
        - Commission
    Tactical:
      groups:
        - Scheduler
        - Tactical
        - ControlExpOverflow
        - AddNewStudent
    Research:
      groups:
        - Scheduler
        - Research
    Dorm:
      groups:
        - Scheduler
        - Dorm
        - BuyFurniture
    Meowfficer:
      groups:
        - Scheduler
        - Meowfficer
        - MeowfficerTrain
    Guild:
      groups:
        - Scheduler
        - GuildLogistics
        - GuildOperation
    Reward:
      groups:
        - Scheduler
        - Reward
    Awaken:
      groups:
        - Scheduler
        - Awaken

# ==================== DailyMission ====================

DailyMission:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Daily:
      groups:
        - Scheduler
        - Daily
    Hard:
      groups:
        - Scheduler
        - Hard
    Exercise:
      groups:
        - Scheduler
        - Exercise
    ShopFrequent:
      groups:
        - Scheduler
        - GeneralShop
    ShopOnce:
      groups:
        - Scheduler
        - GuildShop
        - MedalShop2
        - MeritShop
        - CoreShop
    Shipyard:
      groups:
        - Scheduler
        - ShipyardDr
        - Shipyard
    Gacha:
      groups:
        - Scheduler
        - Gacha
    Freebies:
      groups:
        - Scheduler
        - BattlePass
        - DataKey
        - Mail
        - SupplyPack
    Minigame:
      groups:
        - Scheduler
    PrivateQuarters:
      groups:
        - Scheduler
        - PrivateQuarters

# ==================== Opsi ====================

Opsi:
  menu: 'collapse'
  page: 'setting'
  tasks:
    OpsiGeneral:
      groups:
        - OpsiGeneral
    OpsiAshBeacon:
      groups:
        - Scheduler
        - OpsiAshBeacon
    OpsiAshAssist:
      groups:
        - Scheduler
        - OpsiAshAssist
    OpsiExplore:
      groups:
        - Scheduler
        - OpsiExplore
        - OpsiFleet
    OpsiShop:
      groups:
        - Scheduler
        - OpsiShop
    OpsiVoucher:
      groups:
        - Scheduler
        - OpsiVoucher
    OpsiDaily:
      groups:
        - Scheduler
        - OpsiDaily
        - OpsiFleet
    OpsiObscure:
      groups:
        - Scheduler
        - OpsiObscure
        - OpsiFleet
    OpsiAbyssal:
      groups:
        - Scheduler
        - OpsiAbyssal
        - OpsiFleetFilter
    OpsiArchive:
      groups:
        - Scheduler
        - OpsiFleet
    OpsiStronghold:
      groups:
        - Scheduler
        - OpsiStronghold
        - OpsiFleetFilter
    OpsiMonthBoss:
      groups:
        - Scheduler
        - OpsiMonthBoss
        - OpsiFleetFilter
    OpsiMeowfficerFarming:
      groups:
        - Scheduler
        - OpsiMeowfficerFarming
        - OpsiFleet
    OpsiHazard1Leveling:
      groups:
        - Scheduler
        - OpsiHazard1Leveling
        - OpsiFleet
    OpsiCrossMonth:
      groups:
        - Scheduler

# ==================== Tool ====================

Tool:
  menu: 'collapse'
  page: 'tool'
  tasks:
    Daemon:
      groups:
        - Daemon
    OpsiDaemon:
      groups:
        - OpsiDaemon
    EventStory:
      groups:
        - EventStory
    Benchmark:
      groups:
        - Benchmark
    AzurLaneUncensored:
      groups: []
    GameManager:
      groups:
        - GameManager
