# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Alas:
      groups:
        - Emulator
        - Error
        - Optimization
    General:
      groups:
        - Retirement
        - OneClickRetire
        - Enhance
        - OldRetire
    Restart:
      command: restart
      groups:
        - Scheduler

# ==================== Farm ====================

Farm:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Main:
      command: main
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    Main2:
      command: main2
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    Main3:
      command: main3
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    GemsFarming:
      command: gems_farming
      groups:
        - Scheduler
        - GemsFarming
        - Campaign
        - StopCondition
        - Fleet

# ==================== Event ====================

Event:
  menu: 'collapse'
  page: 'setting'
  tasks:
    EventGeneral:
      groups:
        - EventGeneral
        - TaskBalancer
    Event:
      command: event
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    Event2:
      command: event2
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    Raid:
      command: raid
      groups:
        - Scheduler
        - Raid
        - Campaign
        - StopCondition
        - Emotion
    Hospital:
      command: hospital
      groups:
        - Scheduler
        - Hospital
        - StopCondition
        - Emotion
    Coalition:
      command: coalition
      groups:
        - Scheduler
        - Campaign
        - Coalition
        - StopCondition
        - Emotion
    MaritimeEscort:
      command: maritime_escort
      groups:
        - Scheduler
        - MaritimeEscort
    WarArchives:
      command: war_archives
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority


# ==================== EventDaily ====================

EventDaily:
  menu: 'collapse'
  page: 'setting'
  tasks:
    EventA:
      command: event_a
      groups:
        - Scheduler
        - EventDaily
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    EventB:
      command: event_b
      groups:
        - Scheduler
        - EventDaily
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    EventC:
      command: event_c
      groups:
        - Scheduler
        - EventDaily
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    EventD:
      command: event_d
      groups:
        - Scheduler
        - EventDaily
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    EventSp:
      command: event_sp
      groups:
        - Scheduler
        - Campaign
        - StopCondition
        - Fleet
        - Submarine
        - Emotion
        - HpControl
        - EnemyPriority
    RaidDaily:
      command: raid_daily
      groups:
        - Scheduler
        - RaidDaily
        - Campaign
        - StopCondition
        - Emotion
    CoalitionSp:
      command: coalition_sp
      groups:
        - Scheduler
        - Campaign
        - Coalition
        - StopCondition
        - Emotion

# ==================== Reward ====================

Reward:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Commission:
      command: commission
      groups:
        - Scheduler
        - Commission
    Tactical:
      command: tactical
      groups:
        - Scheduler
        - Tactical
        - ControlExpOverflow
        - AddNewStudent
    Research:
      command: research
      groups:
        - Scheduler
        - Research
    Dorm:
      command: dorm
      groups:
        - Scheduler
        - Dorm
        - BuyFurniture
    Meowfficer:
      command: meowfficer
      groups:
        - Scheduler
        - Meowfficer
        - MeowfficerTrain
    Guild:
      command: guild
      groups:
        - Scheduler
        - GuildLogistics
        - GuildOperation
    Reward:
      command: reward
      groups:
        - Scheduler
        - Reward
    Awaken:
      command: awaken
      groups:
        - Scheduler
        - Awaken

# ==================== DailyMission ====================

DailyMission:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Daily:
      command: daily
      groups:
        - Scheduler
        - Daily
    Hard:
      command: hard
      groups:
        - Scheduler
        - Hard
    Exercise:
      command: exercise
      groups:
        - Scheduler
        - Exercise
    ShopFrequent:
      command: shop_frequent
      groups:
        - Scheduler
        - GeneralShop
    ShopOnce:
      command: shop_once
      groups:
        - Scheduler
        - GuildShop
        - MedalShop2
        - MeritShop
        - CoreShop
    Shipyard:
      command: shipyard
      groups:
        - Scheduler
        - ShipyardDr
        - Shipyard
    Gacha:
      command: gacha
      groups:
        - Scheduler
        - Gacha
    Freebies:
      command: freebies
      groups:
        - Scheduler
        - BattlePass
        - DataKey
        - Mail
        - SupplyPack
    Minigame:
      command: minigame
      groups:
        - Scheduler
    PrivateQuarters:
      command: private_quarters
      groups:
        - Scheduler
        - PrivateQuarters

# ==================== Opsi ====================

Opsi:
  menu: 'collapse'
  page: 'setting'
  tasks:
    OpsiGeneral:
      groups:
        - OpsiGeneral
    OpsiAshBeacon:
      command: opsi_ash_beacon
      groups:
        - Scheduler
        - OpsiAshBeacon
    OpsiAshAssist:
      command: opsi_ash_assist
      groups:
        - Scheduler
        - OpsiAshAssist
    OpsiExplore:
      command: opsi_explore
      groups:
        - Scheduler
        - OpsiExplore
        - OpsiFleet
    OpsiShop:
      command: opsi_shop
      groups:
        - Scheduler
        - OpsiShop
    OpsiVoucher:
      command: opsi_voucher
      groups:
        - Scheduler
        - OpsiVoucher
    OpsiDaily:
      command: opsi_daily
      groups:
        - Scheduler
        - OpsiDaily
        - OpsiFleet
    OpsiObscure:
      command: opsi_obscure
      groups:
        - Scheduler
        - OpsiObscure
        - OpsiFleet
    OpsiAbyssal:
      command: opsi_abyssal
      groups:
        - Scheduler
        - OpsiAbyssal
        - OpsiFleetFilter
    OpsiArchive:
      command: opsi_archive
      groups:
        - Scheduler
        - OpsiFleet
    OpsiStronghold:
      command: opsi_stronghold
      groups:
        - Scheduler
        - OpsiStronghold
        - OpsiFleetFilter
    OpsiMonthBoss:
      command: opsi_month_boss
      groups:
        - Scheduler
        - OpsiMonthBoss
        - OpsiFleetFilter
    OpsiMeowfficerFarming:
      command: opsi_meowfficer_farming
      groups:
        - Scheduler
        - OpsiMeowfficerFarming
        - OpsiFleet
    OpsiHazard1Leveling:
      command: opsi_hazard1_leveling
      groups:
        - Scheduler
        - OpsiHazard1Leveling
        - OpsiFleet
    OpsiCrossMonth:
      command: opsi_cross_month
      groups:
        - Scheduler

# ==================== Tool ====================

Tool:
  menu: 'collapse'
  page: 'tool'
  tasks:
    Daemon:
      command: daemon
      groups:
        - Daemon
    OpsiDaemon:
      command: opsi_daemon
      groups:
        - OpsiDaemon
    EventStory:
      command: event_story
      groups:
        - EventStory
    Benchmark:
      command: benchmark
      groups:
        - Benchmark
    AzurLaneUncensored:
      command: azur_lane_uncensored
      groups: []
    GameManager:
      command: game_manager
      groups:
        - GameManager
