from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

PRIVATE_QUARTERS_DAILY_COUNT = Button(
    area=(107, 129, 154, 154),
    color=(99, 102, 106),
    button=(107, 129, 154, 154),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_DAILY_COUNT.png",
)
PRIVATE_QUARTERS_INTERACT = Button(
    area=(832, 446, 857, 471),
    color=(167, 165, 167),
    button=(832, 446, 1107, 471),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_INTERACT.png",
)
PRIVATE_QUARTERS_INTERACT_CHECK = Button(
    area=(1223, 653, 1245, 675),
    color=(196, 192, 187),
    button=(1223, 653, 1245, 675),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_INTERACT_CHECK.png",
)
PRIVATE_QUARTERS_LOADING_CHECK = Button(
    area=(582, 376, 702, 391),
    color=(200, 232, 255),
    button=(582, 376, 702, 391),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_LOADING_CHECK.png",
)
PRIVATE_QUARTERS_PAGE_LEFT = Button(
    area=(27, 332, 39, 356),
    color=(246, 248, 249),
    button=(27, 332, 39, 356),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_PAGE_LEFT.png",
)
PRIVATE_QUARTERS_PAGE_LOCALE_BEACH = Button(
    area=(24, 504, 99, 527),
    color=(198, 198, 198),
    button=(24, 504, 99, 527),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_PAGE_LOCALE_BEACH.png",
)
PRIVATE_QUARTERS_PAGE_LOCALE_LOFT = Button(
    area=(23, 502, 99, 528),
    color=(206, 206, 207),
    button=(23, 502, 99, 528),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_PAGE_LOCALE_LOFT.png",
)
PRIVATE_QUARTERS_PAGE_LOCALE_VILLA = Button(
    area=(42, 508, 80, 523),
    color=(162, 162, 162),
    button=(42, 508, 80, 523),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_PAGE_LOCALE_VILLA.png",
)
PRIVATE_QUARTERS_PAGE_RIGHT = Button(
    area=(1241, 332, 1253, 356),
    color=(248, 248, 249),
    button=(1241, 332, 1253, 356),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_PAGE_RIGHT.png",
)
PRIVATE_QUARTERS_ROOM_BACK = Button(
    area=(28, 40, 43, 60),
    color=(185, 184, 186),
    button=(16, 31, 139, 69),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_ROOM_BACK.png",
)
PRIVATE_QUARTERS_ROOM_CHECK = Button(
    area=(1218, 651, 1238, 666),
    color=(68, 98, 113),
    button=(1218, 651, 1238, 666),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_ROOM_CHECK.png",
)
PRIVATE_QUARTERS_ROOM_SAFE_CLICK_AREA = Button(
    area=(950, 95, 1275, 595),
    color=(255, 255, 255),
    button=(950, 95, 1275, 595),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_ROOM_SAFE_CLICK_AREA.png",
)
PRIVATE_QUARTERS_ROOM_TARGET_CHECK_1 = Button(
    area=(721, 17, 781, 37),
    color=(206, 202, 201),
    button=(721, 17, 781, 37),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_ROOM_TARGET_CHECK_1.png",
)
PRIVATE_QUARTERS_ROOM_TARGET_CHECK_2 = Button(
    area=(667, 71, 717, 86),
    color=(222, 213, 198),
    button=(667, 71, 717, 86),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_ROOM_TARGET_CHECK_2.png",
)
PRIVATE_QUARTERS_ROOM_TARGET_CHECK_3 = Button(
    area=(709, 185, 754, 200),
    color=(213, 206, 198),
    button=(709, 185, 754, 200),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_ROOM_TARGET_CHECK_3.png",
)
PRIVATE_QUARTERS_ROOM_TARGET_CLICK_AREA = Button(
    area=(504, 266, 784, 625),
    color=(255, 255, 255),
    button=(504, 266, 784, 625),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_ROOM_TARGET_CLICK_AREA.png",
)
PRIVATE_QUARTERS_ROOM_TARGET_INTIMACY_MAX = Button(
    area=(1157, 40, 1197, 60),
    color=(173, 161, 155),
    button=(1157, 40, 1197, 60),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_ROOM_TARGET_INTIMACY_MAX.png",
)
PRIVATE_QUARTERS_SHIP_AEGIR = Button(
    area=(512, 526, 569, 568),
    color=(209, 191, 188),
    button=(512, 526, 569, 568),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHIP_AEGIR.png",
)
PRIVATE_QUARTERS_SHIP_ANCHORAGE = Button(
    area=(713, 246, 778, 311),
    color=(214, 184, 176),
    button=(713, 246, 778, 311),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHIP_ANCHORAGE.png",
)
PRIVATE_QUARTERS_SHIP_NAKHIMOV = Button(
    area=(944, 373, 994, 431),
    color=(181, 184, 166),
    button=(944, 373, 994, 431),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHIP_NAKHIMOV.png",
)
PRIVATE_QUARTERS_SHIP_NEW_JERSEY = Button(
    area=(973, 307, 1023, 347),
    color=(149, 141, 173),
    button=(973, 307, 1023, 347),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHIP_NEW_JERSEY.png",
)
PRIVATE_QUARTERS_SHIP_NOSHIRO = Button(
    area=(965, 289, 1027, 362),
    color=(143, 120, 127),
    button=(965, 289, 1027, 362),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHIP_NOSHIRO.png",
)
PRIVATE_QUARTERS_SHIP_SIRIUS = Button(
    area=(908, 411, 966, 478),
    color=(219, 207, 214),
    button=(908, 411, 966, 478),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHIP_SIRIUS.png",
)
PRIVATE_QUARTERS_SHIP_TAIHOU = Button(
    area=(814, 190, 856, 232),
    color=(134, 111, 109),
    button=(814, 190, 856, 232),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHIP_TAIHOU.png",
)
PRIVATE_QUARTERS_SHOP_AMOUNT_MAX = Button(
    area=(848, 504, 888, 524),
    color=(227, 231, 235),
    button=(848, 504, 888, 524),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHOP_AMOUNT_MAX.png",
)
PRIVATE_QUARTERS_SHOP_BACK = Button(
    area=(40, 35, 60, 55),
    color=(202, 202, 202),
    button=(35, 30, 95, 60),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHOP_BACK.png",
)
PRIVATE_QUARTERS_SHOP_CHECK = Button(
    area=(124, 18, 218, 48),
    color=(86, 92, 98),
    button=(124, 18, 218, 48),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHOP_CHECK.png",
)
PRIVATE_QUARTERS_SHOP_CONFIRM_AMOUNT = Button(
    area=(790, 574, 842, 601),
    color=(94, 195, 252),
    button=(651, 566, 981, 611),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHOP_CONFIRM_AMOUNT.png",
)
PRIVATE_QUARTERS_SHOP_ENTER = Button(
    area=(1028, 641, 1078, 691),
    color=(243, 227, 213),
    button=(1028, 641, 1078, 691),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHOP_ENTER.png",
)
PRIVATE_QUARTERS_SHOP_GEMS = Button(
    area=(1142, 25, 1227, 49),
    color=(168, 179, 162),
    button=(1142, 25, 1227, 49),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHOP_GEMS.png",
)
PRIVATE_QUARTERS_SHOP_GOLD_COINS = Button(
    area=(963, 25, 1055, 47),
    color=(186, 197, 204),
    button=(963, 25, 1055, 47),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHOP_GOLD_COINS.png",
)
PRIVATE_QUARTERS_SHOP_WEEKLY_CAKES_GET = Button(
    area=(591, 339, 688, 420),
    color=(192, 180, 172),
    button=(591, 339, 688, 420),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHOP_WEEKLY_CAKES_GET.png",
)
PRIVATE_QUARTERS_SHOP_WEEKLY_ROSES_CHECK = Button(
    area=(968, 489, 1028, 539),
    color=(131, 109, 120),
    button=(968, 489, 1028, 539),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHOP_WEEKLY_ROSES_CHECK.png",
)
PRIVATE_QUARTERS_SHOP_WEEKLY_ROSES_GET = Button(
    area=(598, 335, 683, 420),
    color=(151, 130, 137),
    button=(598, 335, 683, 420),
    file="./assets/cn/private_quarters/PRIVATE_QUARTERS_SHOP_WEEKLY_ROSES_GET.png",
)
