from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

PAUSE = Button(
    area=(1158, 40, 1199, 58),
    color=(189, 190, 202),
    button=(1157, 34, 1241, 61),
    file="./assets/cn/combat_ui/PAUSE.png",
)
PAUSE_Ancient = Button(
    area=(1228, 36, 1245, 55),
    color=(172, 161, 144),
    button=(1228, 36, 1245, 55),
    file="./assets/cn/combat_ui/PAUSE_Ancient.png",
)
PAUSE_AzureCore = Button(
    area=(1220, 36, 1237, 55),
    color=(149, 133, 118),
    button=(1220, 36, 1237, 55),
    file="./assets/cn/combat_ui/PAUSE_AzureCore.png",
)
PAUSE_Christmas = Button(
    area=(1234, 35, 1250, 56),
    color=(158, 181, 210),
    button=(1234, 35, 1250, 56),
    file="./assets/cn/combat_ui/PAUSE_Christmas.png",
)
PAUSE_Cyber = Button(
    area=(1231, 32, 1253, 59),
    color=(40, 140, 157),
    button=(1231, 32, 1253, 59),
    file="./assets/cn/combat_ui/PAUSE_Cyber.png",
)
PAUSE_DOUBLE_CHECK = Button(
    area=(1226, 35, 1231, 60),
    color=(96, 104, 136),
    button=(1226, 35, 1231, 60),
    file="./assets/cn/combat_ui/PAUSE_DOUBLE_CHECK.png",
)
PAUSE_Devil = Button(
    area=(1233, 35, 1250, 57),
    color=(193, 98, 108),
    button=(1233, 35, 1250, 57),
    file="./assets/cn/combat_ui/PAUSE_Devil.png",
)
PAUSE_ElvenVine = Button(
    area=(1229, 32, 1253, 55),
    color=(152, 189, 166),
    button=(1229, 32, 1253, 55),
    file="./assets/cn/combat_ui/PAUSE_ElvenVine.png",
)
PAUSE_GildedReverie = Button(
    area=(1225, 34, 1245, 50),
    color=(166, 154, 127),
    button=(1225, 34, 1245, 50),
    file="./assets/cn/combat_ui/PAUSE_GildedReverie.png",
)
PAUSE_HolyLight = Button(
    area=(1233, 35, 1250, 57),
    color=(54, 40, 27),
    button=(1233, 35, 1250, 57),
    file="./assets/cn/combat_ui/PAUSE_HolyLight.png",
)
PAUSE_Iridescent_Fantasy = Button(
    area=(1232, 33, 1252, 57),
    color=(124, 139, 190),
    button=(1232, 33, 1252, 57),
    file="./assets/cn/combat_ui/PAUSE_Iridescent_Fantasy.png",
)
PAUSE_MaidCafe = Button(
    area=(1230, 35, 1248, 54),
    color=(159, 145, 139),
    button=(1230, 35, 1248, 54),
    file="./assets/cn/combat_ui/PAUSE_MaidCafe.png",
)
PAUSE_Neon = Button(
    area=(1228, 32, 1250, 59),
    color=(106, 137, 80),
    button=(1228, 32, 1250, 59),
    file="./assets/cn/combat_ui/PAUSE_Neon.png",
)
PAUSE_New = Button(
    area=(1231, 29, 1253, 56),
    color=(156, 158, 166),
    button=(1231, 29, 1253, 56),
    file="./assets/cn/combat_ui/PAUSE_New.png",
)
PAUSE_Ninja = Button(
    area=(1230, 37, 1246, 53),
    color=(135, 109, 92),
    button=(1230, 37, 1246, 53),
    file="./assets/cn/combat_ui/PAUSE_Ninja.png",
)
PAUSE_Nurse = Button(
    area=(1236, 33, 1251, 50),
    color=(200, 206, 209),
    button=(1236, 33, 1251, 50),
    file="./assets/cn/combat_ui/PAUSE_Nurse.png",
)
PAUSE_Pharaoh = Button(
    area=(1229, 55, 1259, 62),
    color=(164, 119, 78),
    button=(1229, 55, 1259, 62),
    file="./assets/cn/combat_ui/PAUSE_Pharaoh.png",
)
PAUSE_Seaside = Button(
    area=(1214, 31, 1239, 59),
    color=(172, 196, 212),
    button=(1214, 31, 1239, 59),
    file="./assets/cn/combat_ui/PAUSE_Seaside.png",
)
PAUSE_ShadowPuppetry = Button(
    area=(1216, 37, 1234, 55),
    color=(139, 112, 72),
    button=(1216, 37, 1234, 55),
    file="./assets/cn/combat_ui/PAUSE_ShadowPuppetry.png",
)
PAUSE_SpringInn = Button(
    area=(1212, 37, 1235, 61),
    color=(201, 91, 78),
    button=(1212, 37, 1235, 61),
    file="./assets/cn/combat_ui/PAUSE_SpringInn.png",
)
PAUSE_Star = Button(
    area=(1234, 36, 1250, 57),
    color=(169, 179, 179),
    button=(1234, 36, 1250, 57),
    file="./assets/cn/combat_ui/PAUSE_Star.png",
)
QUIT = Button(
    area=(420, 490, 593, 548),
    color=(199, 122, 114),
    button=(420, 490, 593, 548),
    file="./assets/cn/combat_ui/QUIT.png",
)
QUIT_Christmas = Button(
    area=(400, 506, 477, 525),
    color=(195, 139, 166),
    button=(400, 506, 477, 525),
    file="./assets/cn/combat_ui/QUIT_Christmas.png",
)
QUIT_Cyber = Button(
    area=(393, 506, 470, 524),
    color=(255, 198, 190),
    button=(393, 506, 470, 524),
    file="./assets/cn/combat_ui/QUIT_Cyber.png",
)
QUIT_GildedReverie = Button(
    area=(422, 553, 500, 572),
    color=(122, 128, 167),
    button=(422, 553, 500, 572),
    file="./assets/cn/combat_ui/QUIT_GildedReverie.png",
)
QUIT_Iridescent_Fantasy = Button(
    area=(391, 522, 464, 540),
    color=(121, 73, 79),
    button=(391, 522, 464, 540),
    file="./assets/cn/combat_ui/QUIT_Iridescent_Fantasy.png",
)
QUIT_MaidCafe = Button(
    area=(423, 549, 501, 568),
    color=(168, 142, 133),
    button=(423, 549, 501, 568),
    file="./assets/cn/combat_ui/QUIT_MaidCafe.png",
)
QUIT_New = Button(
    area=(394, 506, 467, 524),
    color=(255, 180, 171),
    button=(394, 506, 467, 524),
    file="./assets/cn/combat_ui/QUIT_New.png",
)
QUIT_Ninja = Button(
    area=(398, 509, 477, 528),
    color=(148, 138, 134),
    button=(398, 509, 477, 528),
    file="./assets/cn/combat_ui/QUIT_Ninja.png",
)
QUIT_Nurse = Button(
    area=(400, 507, 477, 525),
    color=(254, 193, 170),
    button=(400, 507, 477, 525),
    file="./assets/cn/combat_ui/QUIT_Nurse.png",
)
QUIT_Pharaoh = Button(
    area=(400, 507, 477, 525),
    color=(204, 132, 108),
    button=(400, 507, 477, 525),
    file="./assets/cn/combat_ui/QUIT_Pharaoh.png",
)
QUIT_Seaside = Button(
    area=(398, 509, 476, 528),
    color=(247, 208, 188),
    button=(398, 509, 476, 528),
    file="./assets/cn/combat_ui/QUIT_Seaside.png",
)
QUIT_SpringInn = Button(
    area=(396, 559, 478, 584),
    color=(145, 88, 80),
    button=(396, 559, 478, 584),
    file="./assets/cn/combat_ui/QUIT_SpringInn.png",
)
