from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

FLEET_1 = Button(
    area=(183, 643, 211, 672),
    color=(96, 156, 239),
    button=(183, 643, 211, 672),
    file="./assets/cn/os/FLEET_1.png",
)
FLEET_2 = Button(
    area=(183, 643, 211, 671),
    color=(96, 157, 240),
    button=(183, 643, 211, 671),
    file="./assets/cn/os/FLEET_2.png",
)
FLEET_3 = Button(
    area=(183, 643, 212, 673),
    color=(100, 159, 240),
    button=(183, 643, 212, 673),
    file="./assets/cn/os/FLEET_3.png",
)
FLEET_4 = Button(
    area=(185, 646, 210, 672),
    color=(175, 205, 248),
    button=(185, 646, 210, 672),
    file="./assets/cn/os/FLEET_4.png",
)
FLEET_BAR = Button(
    area=(145, 414, 345, 616),
    color=(152, 171, 192),
    button=(145, 414, 345, 616),
    file="./assets/cn/os/FLEET_BAR.png",
)
FLEET_CHOOSE = Button(
    area=(270, 636, 345, 699),
    color=(112, 189, 245),
    button=(270, 636, 345, 699),
    file="./assets/cn/os/FLEET_CHOOSE.png",
)
FLEET_EMP_DEBUFF = Button(
    area=(137, 144, 175, 167),
    color=(180, 167, 191),
    button=(137, 144, 175, 167),
    file="./assets/cn/os/FLEET_EMP_DEBUFF.png",
)
GLOBE_GOTO_MAP = Button(
    area=(37, 29, 83, 75),
    color=(112, 119, 157),
    button=(37, 29, 83, 75),
    file="./assets/cn/os/GLOBE_GOTO_MAP.png",
)
MAP_EXIT = Button(
    area=(1147, 637, 1280, 699),
    color=(47, 35, 42),
    button=(1147, 637, 1280, 699),
    file="./assets/cn/os/MAP_EXIT.png",
)
MAP_GOTO_GLOBE = Button(
    area=(1069, 641, 1260, 695),
    color=(212, 140, 140),
    button=(1069, 641, 1260, 695),
    file="./assets/cn/os/MAP_GOTO_GLOBE.png",
)
MAP_GOTO_GLOBE_FOG = Button(
    area=(1074, 644, 1114, 691),
    color=(50, 34, 32),
    button=(1074, 644, 1114, 691),
    file="./assets/cn/os/MAP_GOTO_GLOBE_FOG.png",
)
MAP_NAME = Button(
    area=(120, 9, 400, 41),
    color=(60, 66, 77),
    button=(120, 9, 400, 41),
    file="./assets/cn/os/MAP_NAME.png",
)
MEOWFFICER_SEARCHING = Button(
    area=(172, 606, 220, 619),
    color=(67, 131, 149),
    button=(172, 606, 220, 619),
    file="./assets/cn/os/MEOWFFICER_SEARCHING.png",
)
MEOWFFICER_SEARCHING_PERCENTAGE = Button(
    area=(144, 621, 223, 623),
    color=(52, 167, 190),
    button=(144, 621, 223, 623),
    file="./assets/cn/os/MEOWFFICER_SEARCHING_PERCENTAGE.png",
)
SELECT_ABYSSAL = Button(
    area=(89, 251, 167, 269),
    color=(107, 110, 112),
    button=(89, 251, 167, 269),
    file="./assets/cn/os/SELECT_ABYSSAL.png",
)
SELECT_ARCHIVE = Button(
    area=(89, 251, 167, 269),
    color=(110, 111, 114),
    button=(89, 251, 167, 269),
    file="./assets/cn/os/SELECT_ARCHIVE.png",
)
SELECT_DANGEROUS = Button(
    area=(89, 318, 167, 336),
    color=(115, 121, 121),
    button=(89, 318, 167, 336),
    file="./assets/cn/os/SELECT_DANGEROUS.png",
)
SELECT_OBSCURE = Button(
    area=(89, 251, 167, 269),
    color=(109, 111, 114),
    button=(89, 251, 167, 269),
    file="./assets/cn/os/SELECT_OBSCURE.png",
)
SELECT_SAFE = Button(
    area=(89, 251, 167, 269),
    color=(89, 94, 94),
    button=(89, 251, 167, 269),
    file="./assets/cn/os/SELECT_SAFE.png",
)
SELECT_STRONGHOLD = Button(
    area=(89, 251, 166, 269),
    color=(113, 114, 118),
    button=(89, 251, 166, 269),
    file="./assets/cn/os/SELECT_STRONGHOLD.png",
)
STRONGHOLD_PERCENTAGE = Button(
    area=(293, 125, 340, 143),
    color=(132, 135, 146),
    button=(293, 125, 340, 143),
    file="./assets/cn/os/STRONGHOLD_PERCENTAGE.png",
)
TEMPLATE_EMPTY_HP = Template(file="./assets/cn/os/TEMPLATE_EMPTY_HP.png")
TEMPLATE_ExplorationReward = Template(file="./assets/cn/os/TEMPLATE_ExplorationReward.png")
TEMPLATE_FleetMechanism = Template(file="./assets/cn/os/TEMPLATE_FleetMechanism.png")
TEMPLATE_LoggingTower = Template(file="./assets/cn/os/TEMPLATE_LoggingTower.png")
TEMPLATE_LoggingTowerUpper = Template(file="./assets/cn/os/TEMPLATE_LoggingTowerUpper.png")
TEMPLATE_ScanningDevice = Template(file="./assets/cn/os/TEMPLATE_ScanningDevice.png")
TEMPLATE_ScanningDeviceUpper = Template(file="./assets/cn/os/TEMPLATE_ScanningDeviceUpper.png")
ZONE_ABYSSAL = Button(
    area=(85, 302, 171, 322),
    color=(171, 143, 147),
    button=(85, 302, 171, 322),
    file="./assets/cn/os/ZONE_ABYSSAL.png",
)
ZONE_ARCHIVE = Button(
    area=(85, 301, 171, 322),
    color=(131, 137, 181),
    button=(85, 301, 171, 322),
    file="./assets/cn/os/ZONE_ARCHIVE.png",
)
ZONE_DANGEROUS = Button(
    area=(87, 310, 171, 322),
    color=(153, 177, 197),
    button=(87, 310, 171, 322),
    file="./assets/cn/os/ZONE_DANGEROUS.png",
)
ZONE_ENTRANCE = Button(
    area=(395, 276, 545, 320),
    color=(107, 158, 227),
    button=(395, 276, 545, 320),
    file="./assets/cn/os/ZONE_ENTRANCE.png",
)
ZONE_LOCKED = Button(
    area=(400, 277, 432, 318),
    color=(101, 103, 102),
    button=(400, 277, 432, 318),
    file="./assets/cn/os/ZONE_LOCKED.png",
)
ZONE_OBSCURE = Button(
    area=(85, 302, 172, 322),
    color=(142, 147, 186),
    button=(85, 302, 172, 322),
    file="./assets/cn/os/ZONE_OBSCURE.png",
)
ZONE_PINNED = Button(
    area=(503, 419, 514, 430),
    color=(224, 239, 250),
    button=(503, 419, 514, 430),
    file="./assets/cn/os/ZONE_PINNED.png",
)
ZONE_SAFE = Button(
    area=(85, 301, 172, 322),
    color=(131, 180, 184),
    button=(85, 301, 172, 322),
    file="./assets/cn/os/ZONE_SAFE.png",
)
ZONE_STRONGHOLD = Button(
    area=(85, 301, 171, 322),
    color=(154, 114, 123),
    button=(85, 301, 171, 322),
    file="./assets/cn/os/ZONE_STRONGHOLD.png",
)
ZONE_SWITCH = Button(
    area=(94, 336, 165, 354),
    color=(101, 106, 109),
    button=(94, 336, 165, 354),
    file="./assets/cn/os/ZONE_SWITCH.png",
)
