from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BUILD_CUBE_COUNT = Button(
    area=(853, 104, 938, 138),
    color=(59, 62, 73),
    button=(853, 104, 938, 138),
    file="./assets/cn/gacha/BUILD_CUBE_COUNT.png",
)
BUILD_FINISH_ORDERS = Button(
    area=(1117, 95, 1265, 146),
    color=(182, 142, 84),
    button=(1117, 95, 1265, 146),
    file="./assets/cn/gacha/BUILD_FINISH_ORDERS.png",
)
BUILD_FINISH_RESULTS = Button(
    area=(540, 193, 740, 229),
    color=(163, 193, 248),
    button=(540, 193, 740, 229),
    file="./assets/cn/gacha/BUILD_FINISH_RESULTS.png",
)
BUILD_MINUS = Button(
    area=(569, 253, 613, 295),
    color=(80, 131, 200),
    button=(569, 253, 613, 295),
    file="./assets/cn/gacha/BUILD_MINUS.png",
)
BUILD_PLUS = Button(
    area=(748, 253, 792, 295),
    color=(85, 135, 203),
    button=(748, 253, 792, 295),
    file="./assets/cn/gacha/BUILD_PLUS.png",
)
BUILD_QUEUE_EMPTY = Button(
    area=(639, 362, 700, 409),
    color=(157, 151, 152),
    button=(639, 362, 700, 409),
    file="./assets/cn/gacha/BUILD_QUEUE_EMPTY.png",
)
BUILD_SUBMIT_COUNT = Button(
    area=(628, 260, 739, 288),
    color=(72, 79, 92),
    button=(628, 260, 739, 288),
    file="./assets/cn/gacha/BUILD_SUBMIT_COUNT.png",
)
BUILD_SUBMIT_ORDERS = Button(
    area=(1032, 603, 1223, 657),
    color=(236, 186, 112),
    button=(1032, 603, 1223, 657),
    file="./assets/cn/gacha/BUILD_SUBMIT_ORDERS.png",
)
BUILD_SUBMIT_WW_COUNT = Button(
    area=(628, 260, 739, 288),
    color=(72, 79, 92),
    button=(628, 260, 739, 288),
    file="./assets/cn/gacha/BUILD_SUBMIT_WW_COUNT.png",
)
BUILD_SUBMIT_WW_ORDERS = Button(
    area=(495, 570, 705, 625),
    color=(231, 217, 91),
    button=(495, 570, 705, 625),
    file="./assets/cn/gacha/BUILD_SUBMIT_WW_ORDERS.png",
)
BUILD_TICKET_CHECK = Button(
    area=(640, 110, 677, 131),
    color=(56, 107, 211),
    button=(640, 110, 677, 131),
    file="./assets/cn/gacha/BUILD_TICKET_CHECK.png",
)
BUILD_TICKET_COUNT = Button(
    area=(681, 105, 788, 138),
    color=(47, 50, 62),
    button=(681, 105, 788, 138),
    file="./assets/cn/gacha/BUILD_TICKET_COUNT.png",
)
BUILD_WW_CHECK = Button(
    area=(620, 624, 763, 655),
    color=(129, 137, 152),
    button=(620, 624, 763, 655),
    file="./assets/cn/gacha/BUILD_WW_CHECK.png",
)
SHOP_MEDAL_CHECK = Button(
    area=(573, 102, 604, 145),
    color=(93, 102, 118),
    button=(573, 102, 604, 145),
    file="./assets/cn/gacha/SHOP_MEDAL_CHECK.png",
)
