from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ATTACKER_HP_AREA = Button(
    area=(271, 43, 586, 58),
    color=(239, 51, 15),
    button=(271, 43, 586, 58),
    file="./assets/cn/exercise/ATTACKER_HP_AREA.png",
)
ATTACKER_HP_AREA_New = Button(
    area=(266, 40, 592, 49),
    color=(232, 82, 45),
    button=(266, 40, 592, 49),
    file="./assets/cn/exercise/ATTACKER_HP_AREA_New.png",
)
CLICK_SAFE_AREA = Button(
    area=(1215, 637, 1260, 686),
    color=(253, 180, 75),
    button=(1215, 637, 1260, 686),
    file="./assets/cn/exercise/CLICK_SAFE_AREA.png",
)
DEFENDER_HP_AREA = Button(
    area=(691, 43, 1004, 58),
    color=(239, 51, 15),
    button=(691, 43, 1004, 58),
    file="./assets/cn/exercise/DEFENDER_HP_AREA.png",
)
DEFENDER_HP_AREA_New = Button(
    area=(692, 40, 1019, 49),
    color=(231, 80, 45),
    button=(692, 40, 1019, 49),
    file="./assets/cn/exercise/DEFENDER_HP_AREA_New.png",
)
EQUIP_EDIT_ACTIVE = Button(
    area=(51, 608, 245, 668),
    color=(191, 159, 109),
    button=(51, 608, 245, 668),
    file="./assets/cn/exercise/EQUIP_EDIT_ACTIVE.png",
)
EQUIP_EDIT_INACTIVE = Button(
    area=(51, 608, 246, 667),
    color=(89, 112, 158),
    button=(51, 608, 246, 667),
    file="./assets/cn/exercise/EQUIP_EDIT_INACTIVE.png",
)
EQUIP_ENTER = Button(
    area=(432, 283, 442, 293),
    color=(207, 206, 206),
    button=(432, 283, 442, 293),
    file="./assets/cn/exercise/EQUIP_ENTER.png",
)
EXERCISE_PREPARATION = Button(
    area=(543, 539, 741, 599),
    color=(235, 186, 114),
    button=(543, 539, 741, 599),
    file="./assets/cn/exercise/EXERCISE_PREPARATION.png",
)
NEW_OPPONENT = Button(
    area=(1065, 340, 1204, 382),
    color=(129, 166, 220),
    button=(1065, 340, 1204, 382),
    file="./assets/cn/exercise/NEW_OPPONENT.png",
)
OCR_EXERCISE_REMAIN = Button(
    area=(1153, 140, 1178, 165),
    color=(96, 132, 113),
    button=(1153, 140, 1178, 165),
    file="./assets/cn/exercise/OCR_EXERCISE_REMAIN.png",
)
OCR_PERIOD_REMAIN = Button(
    area=(1089, 105, 1209, 129),
    color=(125, 133, 169),
    button=(1089, 105, 1209, 129),
    file="./assets/cn/exercise/OCR_PERIOD_REMAIN.png",
)
OPPONENT_1 = Button(
    area=(104, 77, 316, 381),
    color=(101, 117, 136),
    button=(104, 77, 316, 381),
    file="./assets/cn/exercise/OPPONENT_1.png",
)
OPPONENT_2 = Button(
    area=(348, 77, 560, 381),
    color=(105, 123, 149),
    button=(348, 77, 560, 381),
    file="./assets/cn/exercise/OPPONENT_2.png",
)
OPPONENT_3 = Button(
    area=(592, 77, 804, 381),
    color=(106, 131, 158),
    button=(592, 77, 804, 381),
    file="./assets/cn/exercise/OPPONENT_3.png",
)
OPPONENT_4 = Button(
    area=(836, 77, 1048, 381),
    color=(103, 118, 141),
    button=(836, 77, 1048, 381),
    file="./assets/cn/exercise/OPPONENT_4.png",
)
