from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ACADEMY_CHECK = Button(
    area=(121, 14, 175, 39),
    color=(147, 163, 200),
    button=(121, 14, 175, 39),
    file="./assets/cn/ui/ACADEMY_CHECK.png",
)
ACADEMY_GOTO_GAME_ROOM = Button(
    area=(1074, 340, 1103, 374),
    color=(208, 185, 150),
    button=(1074, 340, 1103, 374),
    file="./assets/cn/ui/ACADEMY_GOTO_GAME_ROOM.png",
)
ACADEMY_GOTO_MUNITIONS = Button(
    area=(1046, 188, 1137, 210),
    color=(133, 135, 165),
    button=(1046, 188, 1137, 210),
    file="./assets/cn/ui/ACADEMY_GOTO_MUNITIONS.png",
)
BACK_ARROW = Button(
    area=(33, 44, 47, 64),
    color=(112, 118, 152),
    button=(33, 31, 81, 78),
    file="./assets/cn/ui/BACK_ARROW.png",
)
BATTLE_PASS_CHECK = Button(
    area=(701, 674, 723, 699),
    color=(129, 130, 134),
    button=(701, 674, 723, 699),
    file="./assets/cn/ui/BATTLE_PASS_CHECK.png",
)
BUILD_CHECK = Button(
    area=(121, 15, 175, 40),
    color=(163, 179, 215),
    button=(121, 15, 175, 40),
    file="./assets/cn/ui/BUILD_CHECK.png",
)
CAMPAIGN_CHECK = Button(
    area=(173, 78, 194, 98),
    color=(165, 182, 221),
    button=(173, 78, 194, 98),
    file="./assets/cn/ui/CAMPAIGN_CHECK.png",
)
CAMPAIGN_GOTO_DAILY = Button(
    area=(804, 648, 892, 703),
    color=(189, 145, 78),
    button=(804, 648, 892, 703),
    file="./assets/cn/ui/CAMPAIGN_GOTO_DAILY.png",
)
CAMPAIGN_GOTO_EVENT = Button(
    area=(173, 78, 194, 98),
    color=(165, 182, 221),
    button=(1178, 171, 1230, 223),
    file="./assets/cn/ui/CAMPAIGN_GOTO_EVENT.png",
)
CAMPAIGN_GOTO_EXERCISE = Button(
    area=(1166, 648, 1248, 703),
    color=(177, 136, 69),
    button=(1166, 648, 1248, 703),
    file="./assets/cn/ui/CAMPAIGN_GOTO_EXERCISE.png",
)
CAMPAIGN_GOTO_WAR_ARCHIVES = Button(
    area=(187, 651, 237, 690),
    color=(132, 155, 200),
    button=(187, 651, 237, 690),
    file="./assets/cn/ui/CAMPAIGN_GOTO_WAR_ARCHIVES.png",
)
CAMPAIGN_MENU_CHECK = Button(
    area=(355, 439, 501, 506),
    color=(103, 106, 113),
    button=(355, 439, 501, 506),
    file="./assets/cn/ui/CAMPAIGN_MENU_CHECK.png",
)
CAMPAIGN_MENU_GOTO_CAMPAIGN = Button(
    area=(355, 439, 501, 506),
    color=(103, 106, 113),
    button=(197, 147, 502, 507),
    file="./assets/cn/ui/CAMPAIGN_MENU_GOTO_CAMPAIGN.png",
)
CAMPAIGN_MENU_GOTO_DAILY = Button(
    area=(686, 586, 788, 638),
    color=(62, 66, 67),
    button=(686, 586, 788, 638),
    file="./assets/cn/ui/CAMPAIGN_MENU_GOTO_DAILY.png",
)
CAMPAIGN_MENU_GOTO_EVENT = Button(
    area=(355, 439, 501, 506),
    color=(103, 106, 113),
    button=(544, 120, 966, 325),
    file="./assets/cn/ui/CAMPAIGN_MENU_GOTO_EVENT.png",
)
CAMPAIGN_MENU_GOTO_EXERCISE = Button(
    area=(1011, 586, 1106, 638),
    color=(45, 49, 51),
    button=(1011, 586, 1106, 638),
    file="./assets/cn/ui/CAMPAIGN_MENU_GOTO_EXERCISE.png",
)
CAMPAIGN_MENU_GOTO_OS = Button(
    area=(355, 439, 501, 506),
    color=(103, 106, 113),
    button=(543, 345, 967, 552),
    file="./assets/cn/ui/CAMPAIGN_MENU_GOTO_OS.png",
)
CAMPAIGN_MENU_GOTO_WAR_ARCHIVES = Button(
    area=(210, 586, 310, 638),
    color=(62, 65, 66),
    button=(210, 586, 310, 638),
    file="./assets/cn/ui/CAMPAIGN_MENU_GOTO_WAR_ARCHIVES.png",
)
CAMPAIGN_MENU_NO_EVENT = Button(
    area=(681, 204, 831, 233),
    color=(65, 75, 84),
    button=(681, 204, 831, 233),
    file="./assets/cn/ui/CAMPAIGN_MENU_NO_EVENT.png",
)
CHANNEL_CHECK = Button(
    area=(785, 661, 824, 699),
    color=(88, 90, 89),
    button=(785, 661, 824, 699),
    file="./assets/cn/ui/CHANNEL_CHECK.png",
)
COMMISSION_CHECK = Button(
    area=(122, 16, 175, 39),
    color=(157, 173, 210),
    button=(122, 16, 175, 39),
    file="./assets/cn/ui/COMMISSION_CHECK.png",
)
DAILY_CHECK = Button(
    area=(23, 656, 67, 698),
    color=(84, 139, 210),
    button=(23, 656, 67, 698),
    file="./assets/cn/ui/DAILY_CHECK.png",
)
DORMMENU_CHECK = Button(
    area=(261, 487, 334, 587),
    color=(181, 172, 178),
    button=(261, 487, 334, 587),
    file="./assets/cn/ui/DORMMENU_CHECK.png",
)
DORMMENU_GOTO_ACADEMY = Button(
    area=(261, 487, 334, 587),
    color=(181, 172, 178),
    button=(261, 487, 334, 587),
    file="./assets/cn/ui/DORMMENU_GOTO_ACADEMY.png",
)
DORMMENU_GOTO_DORM = Button(
    area=(408, 494, 541, 587),
    color=(167, 148, 137),
    button=(408, 494, 541, 587),
    file="./assets/cn/ui/DORMMENU_GOTO_DORM.png",
)
DORMMENU_GOTO_MAIN = Button(
    area=(261, 487, 334, 587),
    color=(181, 172, 178),
    button=(150, 153, 437, 279),
    file="./assets/cn/ui/DORMMENU_GOTO_MAIN.png",
)
DORMMENU_GOTO_MEOWFFICER = Button(
    area=(634, 512, 749, 569),
    color=(144, 153, 176),
    button=(634, 512, 749, 569),
    file="./assets/cn/ui/DORMMENU_GOTO_MEOWFFICER.png",
)
DORMMENU_GOTO_PRIVATE_QUARTERS = Button(
    area=(998, 581, 1148, 601),
    color=(140, 140, 139),
    button=(1010, 336, 1140, 596),
    file="./assets/cn/ui/DORMMENU_GOTO_PRIVATE_QUARTERS.png",
)
DORM_CHECK = Button(
    area=(949, 600, 1005, 654),
    color=(255, 244, 209),
    button=(949, 600, 1005, 654),
    file="./assets/cn/ui/DORM_CHECK.png",
)
DORM_FEED_CANCEL = Button(
    area=(494, 510, 547, 536),
    color=(196, 161, 109),
    button=(494, 510, 547, 536),
    file="./assets/cn/ui/DORM_FEED_CANCEL.png",
)
DORM_GOTO_MAIN = Button(
    area=(40, 30, 62, 60),
    color=(255, 226, 133),
    button=(40, 30, 62, 60),
    file="./assets/cn/ui/DORM_GOTO_MAIN.png",
)
DORM_INFO = Button(
    area=(1071, 609, 1142, 640),
    color=(155, 182, 220),
    button=(1071, 609, 1142, 640),
    file="./assets/cn/ui/DORM_INFO.png",
)
DORM_TROPHY_CONFIRM = Button(
    area=(590, 473, 690, 508),
    color=(245, 167, 88),
    button=(590, 473, 690, 508),
    file="./assets/cn/ui/DORM_TROPHY_CONFIRM.png",
)
EVENT_CHECK = Button(
    area=(123, 63, 206, 109),
    color=(88, 104, 138),
    button=(123, 63, 206, 109),
    file="./assets/cn/ui/EVENT_CHECK.png",
)
EVENT_LIST_CHECK = Button(
    area=(123, 15, 232, 39),
    color=(151, 166, 206),
    button=(123, 15, 232, 39),
    file="./assets/cn/ui/EVENT_LIST_CHECK.png",
)
EXERCISE_CHECK = Button(
    area=(1065, 340, 1204, 382),
    color=(129, 166, 220),
    button=(1065, 340, 1204, 382),
    file="./assets/cn/ui/EXERCISE_CHECK.png",
)
FLEET_CHECK = Button(
    area=(1044, 641, 1243, 702),
    color=(237, 186, 112),
    button=(1044, 641, 1243, 702),
    file="./assets/cn/ui/FLEET_CHECK.png",
)
GAME_ROOM_CHECK = Button(
    area=(983, 17, 1022, 53),
    color=(164, 183, 216),
    button=(983, 17, 1022, 53),
    file="./assets/cn/ui/GAME_ROOM_CHECK.png",
)
GAME_ROOM_GOTO_MAIN = Button(
    area=(1210, 16, 1247, 51),
    color=(95, 88, 126),
    button=(1210, 16, 1247, 51),
    file="./assets/cn/ui/GAME_ROOM_GOTO_MAIN.png",
)
GOTO_MAIN = Button(
    area=(1230, 17, 1253, 45),
    color=(112, 132, 159),
    button=(1228, 18, 1255, 49),
    file="./assets/cn/ui/GOTO_MAIN.png",
)
GUILD_CHECK = Button(
    area=(121, 15, 199, 39),
    color=(145, 159, 195),
    button=(121, 15, 199, 39),
    file="./assets/cn/ui/GUILD_CHECK.png",
)
IDLE = Button(
    area=(864, 672, 873, 688),
    color=(158, 159, 167),
    button=(864, 672, 873, 688),
    file="./assets/cn/ui/IDLE.png",
)
IDLE_2 = Button(
    area=(864, 672, 873, 688),
    color=(173, 178, 186),
    button=(864, 672, 873, 688),
    file="./assets/cn/ui/IDLE_2.png",
)
IDLE_3 = Button(
    area=(864, 672, 873, 688),
    color=(185, 183, 182),
    button=(864, 672, 873, 688),
    file="./assets/cn/ui/IDLE_3.png",
)
MAIN_GOTO_BUILD = Button(
    area=(958, 665, 1113, 714),
    color=(129, 83, 76),
    button=(958, 665, 1113, 714),
    file="./assets/cn/ui/MAIN_GOTO_BUILD.png",
)
MAIN_GOTO_CAMPAIGN = Button(
    area=(1029, 304, 1102, 342),
    color=(240, 213, 157),
    button=(1021, 292, 1160, 432),
    file="./assets/cn/ui/MAIN_GOTO_CAMPAIGN.png",
)
MAIN_GOTO_DOCK = Button(
    area=(172, 668, 326, 715),
    color=(72, 90, 122),
    button=(172, 668, 326, 715),
    file="./assets/cn/ui/MAIN_GOTO_DOCK.png",
)
MAIN_GOTO_DORMMENU = Button(
    area=(1029, 304, 1102, 342),
    color=(240, 213, 157),
    button=(488, 667, 638, 712),
    file="./assets/cn/ui/MAIN_GOTO_DORMMENU.png",
)
MAIN_GOTO_EVENT_LIST = Button(
    area=(607, 141, 657, 191),
    color=(216, 187, 187),
    button=(607, 141, 657, 191),
    file="./assets/cn/ui/MAIN_GOTO_EVENT_LIST.png",
)
MAIN_GOTO_FLEET = Button(
    area=(859, 372, 936, 410),
    color=(187, 216, 248),
    button=(749, 364, 992, 430),
    file="./assets/cn/ui/MAIN_GOTO_FLEET.png",
)
MAIN_GOTO_GUILD = Button(
    area=(1116, 666, 1241, 713),
    color=(81, 99, 133),
    button=(1116, 666, 1241, 713),
    file="./assets/cn/ui/MAIN_GOTO_GUILD.png",
)
MAIN_GOTO_MISSION = Button(
    area=(816, 666, 932, 713),
    color=(93, 110, 140),
    button=(816, 666, 932, 713),
    file="./assets/cn/ui/MAIN_GOTO_MISSION.png",
)
MAIN_GOTO_RAID = Button(
    area=(1029, 304, 1102, 342),
    color=(240, 213, 157),
    button=(610, 264, 654, 305),
    file="./assets/cn/ui/MAIN_GOTO_RAID.png",
)
MAIN_GOTO_RESHMENU = Button(
    area=(1029, 304, 1102, 342),
    color=(240, 213, 157),
    button=(644, 666, 798, 713),
    file="./assets/cn/ui/MAIN_GOTO_RESHMENU.png",
)
MAIN_GOTO_REWARD = Button(
    area=(11, 139, 30, 189),
    color=(69, 81, 115),
    button=(11, 139, 30, 189),
    file="./assets/cn/ui/MAIN_GOTO_REWARD.png",
)
MAIN_GOTO_SHOP = Button(
    area=(11, 662, 165, 713),
    color=(149, 119, 77),
    button=(11, 662, 165, 713),
    file="./assets/cn/ui/MAIN_GOTO_SHOP.png",
)
MAIN_GOTO_STORAGE = Button(
    area=(340, 673, 473, 710),
    color=(95, 109, 143),
    button=(340, 673, 473, 710),
    file="./assets/cn/ui/MAIN_GOTO_STORAGE.png",
)
MEOWFFICER_CHECK = Button(
    area=(142, 16, 212, 38),
    color=(180, 175, 175),
    button=(142, 16, 212, 38),
    file="./assets/cn/ui/MEOWFFICER_CHECK.png",
)
MEOWFFICER_GOTO_DORMMENU = Button(
    area=(24, 7, 49, 45),
    color=(248, 222, 158),
    button=(24, 7, 49, 45),
    file="./assets/cn/ui/MEOWFFICER_GOTO_DORMMENU.png",
)
MEOWFFICER_INFO = Button(
    area=(1090, 603, 1241, 650),
    color=(243, 214, 92),
    button=(1090, 603, 1241, 650),
    file="./assets/cn/ui/MEOWFFICER_INFO.png",
)
META_CHECK = Button(
    area=(120, 14, 209, 35),
    color=(159, 143, 144),
    button=(120, 14, 209, 35),
    file="./assets/cn/ui/META_CHECK.png",
)
MISSION_CHECK = Button(
    area=(120, 15, 173, 40),
    color=(141, 156, 194),
    button=(120, 15, 173, 40),
    file="./assets/cn/ui/MISSION_CHECK.png",
)
MUNITIONS_CHECK = Button(
    area=(60, 361, 104, 395),
    color=(115, 191, 235),
    button=(60, 361, 104, 395),
    file="./assets/cn/ui/MUNITIONS_CHECK.png",
)
OS_CHECK = Button(
    area=(613, 17, 627, 34),
    color=(58, 117, 146),
    button=(613, 17, 627, 34),
    file="./assets/cn/ui/OS_CHECK.png",
)
PLAYER_CHECK = Button(
    area=(28, 668, 139, 688),
    color=(237, 204, 127),
    button=(28, 668, 139, 688),
    file="./assets/cn/ui/PLAYER_CHECK.png",
)
PQ_GOTO_MAIN = Button(
    area=(1107, 19, 1143, 51),
    color=(199, 199, 199),
    button=(1107, 19, 1143, 51),
    file="./assets/cn/ui/PQ_GOTO_MAIN.png",
)
PRIVATE_QUARTERS_CHECK = Button(
    area=(123, 18, 218, 47),
    color=(106, 109, 113),
    button=(123, 18, 218, 47),
    file="./assets/cn/ui/PRIVATE_QUARTERS_CHECK.png",
)
RAID_CHECK = Button(
    area=(107, 13, 216, 38),
    color=(129, 131, 129),
    button=(107, 13, 216, 38),
    file="./assets/cn/ui/RAID_CHECK.png",
)
RESEARCH_CHECK = Button(
    area=(118, 15, 170, 39),
    color=(165, 179, 215),
    button=(118, 15, 170, 39),
    file="./assets/cn/ui/RESEARCH_CHECK.png",
)
RESHMENU_CHECK = Button(
    area=(121, 15, 174, 39),
    color=(156, 171, 209),
    button=(121, 15, 174, 39),
    file="./assets/cn/ui/RESHMENU_CHECK.png",
)
RESHMENU_GOTO_META = Button(
    area=(1076, 254, 1155, 334),
    color=(144, 156, 183),
    button=(1076, 254, 1155, 334),
    file="./assets/cn/ui/RESHMENU_GOTO_META.png",
)
RESHMENU_GOTO_RESEARCH = Button(
    area=(308, 268, 466, 422),
    color=(132, 147, 184),
    button=(308, 268, 466, 422),
    file="./assets/cn/ui/RESHMENU_GOTO_RESEARCH.png",
)
RESHMENU_GOTO_SHIPYARD = Button(
    area=(567, 275, 731, 397),
    color=(113, 126, 162),
    button=(567, 275, 731, 397),
    file="./assets/cn/ui/RESHMENU_GOTO_SHIPYARD.png",
)
REWARD_CHECK = Button(
    area=(219, 107, 267, 158),
    color=(143, 116, 123),
    button=(219, 107, 267, 158),
    file="./assets/cn/ui/REWARD_CHECK.png",
)
REWARD_GOTO_BATTLE_PASS = Button(
    area=(580, 117, 620, 155),
    color=(92, 113, 139),
    button=(580, 117, 620, 155),
    file="./assets/cn/ui/REWARD_GOTO_BATTLE_PASS.png",
)
REWARD_GOTO_COMMISSION = Button(
    area=(432, 279, 500, 296),
    color=(102, 205, 254),
    button=(432, 279, 500, 296),
    file="./assets/cn/ui/REWARD_GOTO_COMMISSION.png",
)
REWARD_GOTO_MAIN = Button(
    area=(219, 107, 267, 158),
    color=(143, 116, 123),
    button=(787, 602, 867, 642),
    file="./assets/cn/ui/REWARD_GOTO_MAIN.png",
)
REWARD_GOTO_TACTICAL = Button(
    area=(435, 420, 498, 448),
    color=(101, 204, 254),
    button=(435, 420, 498, 448),
    file="./assets/cn/ui/REWARD_GOTO_TACTICAL.png",
)
SHIPYARD_CHECK = Button(
    area=(9, 131, 82, 148),
    color=(159, 180, 229),
    button=(9, 131, 82, 148),
    file="./assets/cn/ui/SHIPYARD_CHECK.png",
)
SHOP_BACK_ARROW = Button(
    area=(43, 35, 57, 56),
    color=(191, 191, 191),
    button=(43, 35, 57, 56),
    file="./assets/cn/ui/SHOP_BACK_ARROW.png",
)
SHOP_CHECK = Button(
    area=(149, 23, 192, 44),
    color=(107, 114, 125),
    button=(149, 23, 192, 44),
    file="./assets/cn/ui/SHOP_CHECK.png",
)
SHOP_GOTO_MUNITIONS = Button(
    area=(840, 560, 999, 600),
    color=(122, 87, 75),
    button=(840, 560, 999, 600),
    file="./assets/cn/ui/SHOP_GOTO_MUNITIONS.png",
)
SHOP_GOTO_SUPPLY_PACK = Button(
    area=(1044, 321, 1094, 366),
    color=(198, 155, 150),
    button=(902, 105, 1211, 490),
    file="./assets/cn/ui/SHOP_GOTO_SUPPLY_PACK.png",
)
SP_CHECK = Button(
    area=(123, 63, 206, 109),
    color=(95, 110, 145),
    button=(123, 63, 206, 109),
    file="./assets/cn/ui/SP_CHECK.png",
)
STORAGE_CHECK = Button(
    area=(120, 14, 175, 40),
    color=(137, 151, 188),
    button=(120, 14, 175, 40),
    file="./assets/cn/ui/STORAGE_CHECK.png",
)
SUPPLY_PACK_CHECK = Button(
    area=(60, 232, 104, 265),
    color=(120, 193, 236),
    button=(60, 232, 104, 265),
    file="./assets/cn/ui/SUPPLY_PACK_CHECK.png",
)
TACTICAL_CHECK = Button(
    area=(122, 14, 231, 38),
    color=(145, 161, 200),
    button=(122, 14, 231, 38),
    file="./assets/cn/ui/TACTICAL_CHECK.png",
)
WAR_ARCHIVES_CHECK = Button(
    area=(95, 41, 114, 70),
    color=(137, 177, 208),
    button=(95, 41, 114, 70),
    file="./assets/cn/ui/WAR_ARCHIVES_CHECK.png",
)
WAR_ARCHIVES_GOTO_CAMPAIGN_MENU = Button(
    area=(95, 41, 114, 70),
    color=(137, 177, 208),
    button=(14, 312, 69, 467),
    file="./assets/cn/ui/WAR_ARCHIVES_GOTO_CAMPAIGN_MENU.png",
)
