from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

FLEET_1_ADVICE = Button(
    area=(1030, 207, 1074, 227),
    color=(243, 222, 179),
    button=(1030, 207, 1074, 227),
    file="./assets/cn/map/FLEET_1_ADVICE.png",
)
FLEET_1_BAR = Button(
    area=(1012, 269, 1183, 515),
    color=(177, 170, 154),
    button=(1012, 269, 1183, 515),
    file="./assets/cn/map/FLEET_1_BAR.png",
)
FLEET_1_CHOOSE = Button(
    area=(1021, 192, 1083, 251),
    color=(201, 162, 104),
    button=(1021, 192, 1083, 251),
    file="./assets/cn/map/FLEET_1_CHOOSE.png",
)
FLEET_1_CLEAR = Button(
    area=(1117, 207, 1162, 228),
    color=(204, 205, 205),
    button=(1117, 207, 1162, 228),
    file="./assets/cn/map/FLEET_1_CLEAR.png",
)
FLEET_1_HARD_SATIESFIED = Button(
    area=(211, 142, 364, 186),
    color=(61, 42, 37),
    button=(211, 142, 364, 186),
    file="./assets/cn/map/FLEET_1_HARD_SATIESFIED.png",
)
FLEET_1_IN_USE = Button(
    area=(391, 177, 474, 260),
    color=(198, 188, 179),
    button=(391, 177, 474, 260),
    file="./assets/cn/map/FLEET_1_IN_USE.png",
)
FLEET_2_ADVICE = Button(
    area=(1030, 321, 1074, 341),
    color=(243, 222, 179),
    button=(1030, 321, 1074, 341),
    file="./assets/cn/map/FLEET_2_ADVICE.png",
)
FLEET_2_BAR = Button(
    area=(1012, 383, 1183, 628),
    color=(177, 169, 153),
    button=(1012, 383, 1183, 628),
    file="./assets/cn/map/FLEET_2_BAR.png",
)
FLEET_2_CHOOSE = Button(
    area=(1022, 306, 1083, 365),
    color=(202, 163, 104),
    button=(1022, 306, 1083, 365),
    file="./assets/cn/map/FLEET_2_CHOOSE.png",
)
FLEET_2_CLEAR = Button(
    area=(1117, 321, 1162, 341),
    color=(205, 206, 205),
    button=(1117, 321, 1162, 341),
    file="./assets/cn/map/FLEET_2_CLEAR.png",
)
FLEET_2_HARD_SATIESFIED = Button(
    area=(208, 372, 361, 401),
    color=(75, 54, 43),
    button=(208, 372, 361, 401),
    file="./assets/cn/map/FLEET_2_HARD_SATIESFIED.png",
)
FLEET_2_IN_USE = Button(
    area=(391, 351, 475, 374),
    color=(182, 165, 200),
    button=(391, 351, 475, 374),
    file="./assets/cn/map/FLEET_2_IN_USE.png",
)
FLEET_2_IN_USE_W15 = Button(
    area=(390, 290, 475, 319),
    color=(128, 131, 147),
    button=(390, 290, 475, 319),
    file="./assets/cn/map/FLEET_2_IN_USE_W15.png",
)
FLEET_NUM_1 = Button(
    area=(213, 76, 224, 101),
    color=(51, 143, 186),
    button=(213, 76, 224, 101),
    file="./assets/cn/map/FLEET_NUM_1.png",
)
FLEET_NUM_2 = Button(
    area=(212, 75, 226, 101),
    color=(52, 150, 194),
    button=(212, 75, 226, 101),
    file="./assets/cn/map/FLEET_NUM_2.png",
)
FLEET_PREPARATION = Button(
    area=(1013, 558, 1141, 588),
    color=(242, 211, 160),
    button=(980, 549, 1181, 612),
    file="./assets/cn/map/FLEET_PREPARATION.png",
)
FLEET_PREPARATION_CHECK = Button(
    area=(1146, 107, 1174, 136),
    color=(180, 98, 111),
    button=(1146, 107, 1174, 136),
    file="./assets/cn/map/FLEET_PREPARATION_CHECK.png",
)
FLEET_SUPPORT_EMPTY = Button(
    area=(454, 470, 538, 540),
    color=(47, 54, 77),
    button=(454, 470, 538, 540),
    file="./assets/cn/map/FLEET_SUPPORT_EMPTY.png",
)
MAP_CAT_ATTACK = Button(
    area=(1237, 103, 1252, 153),
    color=(43, 45, 52),
    button=(1148, 653, 1262, 705),
    file="./assets/cn/map/MAP_CAT_ATTACK.png",
)
MAP_CAT_ATTACK_MIRROR = Button(
    area=(147, 145, 187, 157),
    color=(214, 191, 99),
    button=(147, 145, 187, 157),
    file="./assets/cn/map/MAP_CAT_ATTACK_MIRROR.png",
)
MAP_MODE_SWITCH_HARD = Button(
    area=(341, 580, 374, 617),
    color=(234, 179, 179),
    button=(341, 580, 374, 617),
    file="./assets/cn/map/MAP_MODE_SWITCH_HARD.png",
)
MAP_MODE_SWITCH_HARD2 = Button(
    area=(340, 579, 372, 615),
    color=(255, 174, 85),
    button=(340, 579, 372, 615),
    file="./assets/cn/map/MAP_MODE_SWITCH_HARD2.png",
)
MAP_MODE_SWITCH_HARD3 = Button(
    area=(340, 579, 372, 615),
    color=(254, 169, 89),
    button=(340, 579, 372, 615),
    file="./assets/cn/map/MAP_MODE_SWITCH_HARD3.png",
)
MAP_MODE_SWITCH_HARD4 = Button(
    area=(340, 579, 372, 615),
    color=(252, 159, 98),
    button=(340, 579, 372, 615),
    file="./assets/cn/map/MAP_MODE_SWITCH_HARD4.png",
)
MAP_MODE_SWITCH_HARD5 = Button(
    area=(340, 579, 372, 615),
    color=(249, 168, 106),
    button=(340, 579, 372, 615),
    file="./assets/cn/map/MAP_MODE_SWITCH_HARD5.png",
)
MAP_MODE_SWITCH_HARD6 = Button(
    area=(340, 579, 372, 615),
    color=(253, 176, 90),
    button=(340, 579, 372, 615),
    file="./assets/cn/map/MAP_MODE_SWITCH_HARD6.png",
)
MAP_MODE_SWITCH_NORMAL = Button(
    area=(214, 584, 255, 615),
    color=(185, 201, 236),
    button=(214, 584, 255, 615),
    file="./assets/cn/map/MAP_MODE_SWITCH_NORMAL.png",
)
MAP_OFFENSIVE = Button(
    area=(1148, 653, 1262, 705),
    color=(234, 180, 108),
    button=(1148, 653, 1262, 705),
    file="./assets/cn/map/MAP_OFFENSIVE.png",
)
MAP_PREPARATION = Button(
    area=(854, 488, 1052, 548),
    color=(236, 186, 115),
    button=(854, 488, 1052, 548),
    file="./assets/cn/map/MAP_PREPARATION.png",
)
MAP_PREPARATION_CANCEL = Button(
    area=(234, 12, 278, 47),
    color=(45, 46, 69),
    button=(234, 12, 278, 47),
    file="./assets/cn/map/MAP_PREPARATION_CANCEL.png",
)
SUBMARINE_ADVICE = Button(
    area=(1030, 457, 1074, 477),
    color=(243, 222, 179),
    button=(1030, 457, 1074, 477),
    file="./assets/cn/map/SUBMARINE_ADVICE.png",
)
SUBMARINE_BAR = Button(
    area=(1012, 519, 1183, 597),
    color=(200, 184, 147),
    button=(1012, 519, 1183, 597),
    file="./assets/cn/map/SUBMARINE_BAR.png",
)
SUBMARINE_CHOOSE = Button(
    area=(1022, 443, 1082, 501),
    color=(202, 162, 104),
    button=(1022, 443, 1082, 501),
    file="./assets/cn/map/SUBMARINE_CHOOSE.png",
)
SUBMARINE_CLEAR = Button(
    area=(1117, 457, 1162, 478),
    color=(204, 205, 204),
    button=(1117, 457, 1162, 478),
    file="./assets/cn/map/SUBMARINE_CLEAR.png",
)
SUBMARINE_HARD_SATIESFIED = Button(
    area=(211, 514, 375, 539),
    color=(59, 57, 58),
    button=(211, 514, 375, 539),
    file="./assets/cn/map/SUBMARINE_HARD_SATIESFIED.png",
)
SUBMARINE_IN_USE = Button(
    area=(454, 427, 537, 510),
    color=(99, 98, 116),
    button=(454, 427, 537, 510),
    file="./assets/cn/map/SUBMARINE_IN_USE.png",
)
SWITCH_OVER = Button(
    area=(947, 654, 1118, 706),
    color=(144, 158, 198),
    button=(947, 654, 1118, 706),
    file="./assets/cn/map/SWITCH_OVER.png",
)
WITHDRAW = Button(
    area=(749, 654, 921, 707),
    color=(213, 124, 124),
    button=(749, 654, 921, 707),
    file="./assets/cn/map/WITHDRAW.png",
)
