from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE_PREPARATION = Button(
    area=(1031, 624, 1228, 682),
    color=(216, 159, 83),
    button=(1031, 624, 1228, 682),
    file="./assets/cn/os_combat/BATTLE_PREPARATION.png",
)
SIREN_PREPARATION = Button(
    area=(1043, 638, 1240, 698),
    color=(136, 94, 111),
    button=(1043, 638, 1240, 698),
    file="./assets/cn/os_combat/SIREN_PREPARATION.png",
)
