from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COIN = Button(
    area=(279, 48, 308, 73),
    color=(228, 175, 73),
    button=(279, 48, 308, 73),
    file="./assets/cn/reward/COIN.png",
)
EXP = Button(
    area=(449, 31, 477, 49),
    color=(145, 158, 176),
    button=(449, 31, 477, 49),
    file="./assets/cn/reward/EXP.png",
)
MISSION_EMPTY = Button(
    area=(158, 347, 220, 378),
    color=(156, 160, 172),
    button=(158, 347, 220, 378),
    file="./assets/cn/reward/MISSION_EMPTY.png",
)
MISSION_MULTI = Button(
    area=(1041, 8, 1101, 39),
    color=(226, 192, 142),
    button=(1041, 8, 1101, 39),
    file="./assets/cn/reward/MISSION_MULTI.png",
)
MISSION_NOTICE = Button(
    area=(940, 670, 945, 681),
    color=(183, 83, 66),
    button=(940, 670, 945, 681),
    file="./assets/cn/reward/MISSION_NOTICE.png",
)
MISSION_SINGLE = Button(
    area=(1096, 133, 1128, 163),
    color=(167, 200, 237),
    button=(1096, 133, 1128, 163),
    file="./assets/cn/reward/MISSION_SINGLE.png",
)
MISSION_UNFINISH = Button(
    area=(1095, 122, 1126, 154),
    color=(191, 198, 213),
    button=(1095, 122, 1126, 154),
    file="./assets/cn/reward/MISSION_UNFINISH.png",
)
MISSION_WEEKLY_RED_DOT = Button(
    area=(25, 500, 103, 531),
    color=(74, 58, 62),
    button=(25, 500, 103, 531),
    file="./assets/cn/reward/MISSION_WEEKLY_RED_DOT.png",
)
OIL = Button(
    area=(114, 65, 152, 78),
    color=(75, 77, 80),
    button=(114, 65, 152, 78),
    file="./assets/cn/reward/OIL.png",
)
