from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

COMMISSION_ADVICE = Button(
    area=(871, 322, 999, 383),
    color=(230, 177, 116),
    button=(871, 322, 999, 383),
    file="./assets/cn/commission/COMMISSION_ADVICE.png",
)
COMMISSION_DAILY = Button(
    area=(35, 132, 67, 186),
    color=(208, 172, 118),
    button=(35, 132, 67, 186),
    file="./assets/cn/commission/COMMISSION_DAILY.png",
)
COMMISSION_HAS_PENDING = Button(
    area=(320, 288, 380, 338),
    color=(121, 113, 152),
    button=(320, 288, 380, 338),
    file="./assets/cn/commission/COMMISSION_HAS_PENDING.png",
)
COMMISSION_SCROLL_AREA = Button(
    area=(1254, 77, 1261, 676),
    color=(213, 183, 66),
    button=(1254, 77, 1261, 676),
    file="./assets/cn/commission/COMMISSION_SCROLL_AREA.png",
)
COMMISSION_START = Button(
    area=(1028, 322, 1156, 383),
    color=(229, 175, 113),
    button=(1028, 322, 1156, 383),
    file="./assets/cn/commission/COMMISSION_START.png",
)
COMMISSION_URGENT = Button(
    area=(35, 231, 68, 281),
    color=(215, 188, 124),
    button=(35, 231, 68, 281),
    file="./assets/cn/commission/COMMISSION_URGENT.png",
)
EXP_INFO_S_REWARD = Button(
    area=(498, 140, 557, 154),
    color=(233, 241, 127),
    button=(498, 140, 557, 154),
    file="./assets/cn/commission/EXP_INFO_S_REWARD.png",
)
OIL_MAXED = Button(
    area=(428, 310, 534, 335),
    color=(106, 103, 110),
    button=(428, 310, 534, 335),
    file="./assets/cn/commission/OIL_MAXED.png",
)
REWARD_1 = Button(
    area=(420, 277, 518, 295),
    color=(254, 186, 80),
    button=(420, 277, 518, 295),
    file="./assets/cn/commission/REWARD_1.png",
)
REWARD_SAVE_CLICK = Button(
    area=(415, 184, 496, 214),
    color=(152, 150, 168),
    button=(415, 184, 496, 214),
    file="./assets/cn/commission/REWARD_SAVE_CLICK.png",
)
