dictionary_cn = {
    "major_comm": ["自主训练", "对抗演习", "科研任务", "工具整备", "战术课程", "货物运输"],
    "daily_resource": ["日常资源开发"],
    "daily_chip": ["高阶战术研发"],
    "extra_drill": ["航行训练", "防卫巡逻", "海域浮标检查作业"],
    "extra_part": ["委托"],
    "extra_cube": ["演习"],
    "extra_oil": ["油田"],
    "extra_book": ["商船护卫"],
    "urgent_drill": ["运输部队", "侦查部队", "主力部队", "精锐部队"],
    "urgent_part": ["维拉", "伊", "多伦瓦", "恐班纳", "马内", "萌"],
    "urgent_book": ["土豪尔", "姆波罗", "马拉基", "卡波罗", "玛丽", "特林"],
    "urgent_box": ["装备", "物资"],
    "urgent_cube": ["解救", "敌袭"],
    "urgent_gem": ["要员", "度假", "巡视"],
    "urgent_ship": ["观舰"],
}
