from pathlib import Path
from typing import TYPE_CHECKING

import imageio
import numpy as np
from tqdm.contrib.concurrent import process_map

from module.base.utils import get_bbox, get_color, image_size, load_image
from module.config.config_manual import ManualConfig as AzurLaneConfig
from module.logger import logger

if TYPE_CHECKING:
    from module.base.type_alias import FilePath, ImageArray

type Bounds = tuple[int, int, int, int]
type MeanColor = tuple[int, int, int]
type Extraction = tuple[Bounds, MeanColor]

MODULE_FOLDER = "./module"
BUTTON_FILE = "assets.py"
HEADER_EXP = """
# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.
"""
HEADER_EXP = [*HEADER_EXP.strip().split("\n"), ""]


class ImageExtractor:
    def __init__(self, module: str, file: FilePath) -> None:
        path = Path(file)
        self.module = module
        self.name = path.stem
        self.ext = path.suffix
        self.area: dict[str, Bounds] = {}
        self.color: dict[str, MeanColor] = {}
        self.button: dict[str, Bounds] = {}
        self.file: dict[str, str] = {}
        self.load()

    def get_file(self, genre: str = "") -> str:
        for ext in [".png", ".gif"]:
            file = f"{self.name}.{genre}{ext}" if genre else f"{self.name}{ext}"
            file = (Path(AzurLaneConfig.ASSETS_FOLDER) / "cn" / self.module / file).as_posix()
            if Path(file).exists():
                return file

        ext = ".png"
        file = f"{self.name}.{genre}{ext}" if genre else f"{self.name}{ext}"
        return (Path(AzurLaneConfig.ASSETS_FOLDER) / "cn" / self.module / file).as_posix()

    @staticmethod
    def extract(file: FilePath) -> Extraction:
        if Path(file).suffix == ".gif":
            # GIF 按钮使用第一帧。
            frames = imageio.mimread(Path(file))
            if not frames:
                message = f"GIF contains no frames: {file}"
                raise ValueError(message)
            first: ImageArray = np.asarray(frames[0], dtype=np.uint8)
            first = first[:, :, :3] if len(first.shape) == 3 else first
            bbox, mean = ImageExtractor._extract(first, file)
            for frame in frames[1:]:
                image: ImageArray = np.asarray(frame, dtype=np.uint8)
                image = image[:, :, :3] if len(image.shape) == 3 else image
                new_bbox, _new_mean = ImageExtractor._extract(image, file)
                if bbox != new_bbox:
                    logger.warning(f"{file} has multiple different bbox, this will cause unexpected behaviour")
            return bbox, mean
        image = load_image(file)
        return ImageExtractor._extract(image, file)

    @staticmethod
    def _extract(image: ImageArray, file: FilePath) -> Extraction:
        size = image_size(image)
        if size != (1280, 720):
            logger.warning(f"{file} has wrong resolution: {size}")
        bbox = get_bbox(image)
        mean = get_color(image=image, area=bbox)
        rounded = np.rint(mean).astype(int)
        return bbox, (int(rounded[0]), int(rounded[1]), int(rounded[2]))

    def load(self) -> None:
        file = self.get_file()
        if Path(file).exists():
            area, color = self.extract(file)
            button = area
            override = self.get_file("AREA")
            if Path(override).exists():
                area, _ = self.extract(override)
            override = self.get_file("COLOR")
            if Path(override).exists():
                _, color = self.extract(override)
            override = self.get_file("BUTTON")
            if Path(override).exists():
                button, _ = self.extract(override)

            self.area["cn"] = area
            self.color["cn"] = color
            self.button["cn"] = button
            self.file["cn"] = file
        else:
            raise FileNotFoundError(file)

    @property
    def expression(self) -> str:
        return f"{self.name} = Button(area={self.area}, color={self.color}, button={self.button}, file={self.file})"


class TemplateExtractor(ImageExtractor):
    @staticmethod
    def extract(file: FilePath) -> Extraction:
        image = load_image(file)
        bbox = get_bbox(image)
        mean = get_color(image=image, area=bbox)
        rounded = np.rint(mean).astype(int)
        return bbox, (int(rounded[0]), int(rounded[1]), int(rounded[2]))

    @property
    def expression(self) -> str:
        return f"{self.name} = Template(file={self.file})"


class ModuleExtractor:
    def __init__(self, name: str) -> None:
        self.name = name
        self.folder = (Path(AzurLaneConfig.ASSETS_FOLDER) / "cn" / name).as_posix()

    @staticmethod
    def split(file: FilePath) -> tuple[str, str, str]:
        path = Path(file)
        name = Path(path.stem)
        return name.stem, name.suffix, path.suffix

    @staticmethod
    def is_base_image(file: FilePath) -> bool:
        _, sub, _ = ModuleExtractor.split(file)
        return sub == ""

    @property
    def expression(self) -> list[str]:
        exp = []
        for path in Path(self.folder).iterdir():
            file = path.name
            if file[0].isdigit():
                continue
            if file.startswith("TEMPLATE_"):
                exp.append(TemplateExtractor(module=self.name, file=file).expression)
                continue
            if self.is_base_image(file):
                exp.append(ImageExtractor(module=self.name, file=file).expression)
                continue

        exp.sort()

        logger.info(f"Module: {self.name}({len(exp)})")
        imports = []
        if any("Button(" in row for row in exp):
            imports.append("from module.base.button import Button")
        if any("Template(" in row for row in exp):
            imports.append("from module.base.template import Template")
        return [*imports, "", *HEADER_EXP, *exp]

    def write(self) -> None:
        folder = Path(MODULE_FOLDER) / self.name
        if not folder.exists():
            folder.mkdir()
        with (folder / BUTTON_FILE).open("w", newline="") as f:
            f.writelines(f"{text}\n" for text in self.expression)


def worker(module: str) -> None:
    me = ModuleExtractor(name=module)
    me.write()


class AssetExtractor:
    """从国区资源生成 `assets.py`。

    资源名必须大写；数字前缀会被忽略，`TEMPLATE_` 前缀生成 `Template`，其余生成 `Button`；
    `.AREA`、`.COLOR`、`.BUTTON` 后缀分别覆盖对应字段。
    """

    def __init__(self) -> None:
        logger.info("Assets extract")

        assets_folder = Path(AzurLaneConfig.ASSETS_FOLDER) / "cn"
        modules = [path.name for path in assets_folder.iterdir() if path.is_dir()]

        process_map(worker, modules)


if __name__ == "__main__":
    ae = AssetExtractor()
