import ast
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

import imageio
import numpy as np
from PIL import Image
from tqdm.contrib.concurrent import process_map

from module.base.utils import get_bbox, get_color, image_size, load_image
from module.config.config_manual import ManualConfig as AzurLaneConfig
from module.logger import logger

if TYPE_CHECKING:
    from module.base.type_alias import FilePath, ImageArray

type Bounds = tuple[int, int, int, int]
type MeanColor = tuple[int, int, int]
type Extraction = tuple[Bounds, MeanColor]

MODULE_FOLDER = "./module"
BUTTON_FILE = "assets.py"
EXPECTED_BUTTON_RESOLUTION = (1280, 720)
IMAGE_EXTENSIONS = frozenset({".gif", ".png"})
OVERRIDE_SUFFIXES = frozenset({".AREA", ".BUTTON", ".COLOR"})
GENERATED_MARKER = "This file was automatically generated by dev_tools/button_extract.py."
HEADER_EXP = """
# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.
"""
HEADER_EXP = [*HEADER_EXP.strip().split("\n"), ""]


@dataclass(frozen=True, slots=True, order=True)
class AssetIssue:
    file: str
    reason: str


class AssetExtractionError(ValueError):
    def __init__(self, issues: tuple[AssetIssue, ...]) -> None:
        self.issues = tuple(sorted(issues))
        details = "\n".join(f"- {issue.file}: {issue.reason}" for issue in self.issues)
        message = f"Asset extraction validation failed with {len(self.issues)} issue(s):\n{details}"
        super().__init__(message)


def _split_asset_file(file: FilePath) -> tuple[str, str, str]:
    path = Path(file)
    name = Path(path.stem)
    return name.stem, name.suffix, path.suffix


def _wrong_resolution_issue(file: FilePath, size: tuple[int, int]) -> AssetIssue:
    return AssetIssue(
        file=Path(file).as_posix(),
        reason=f"wrong resolution: {size}, expected {EXPECTED_BUTTON_RESOLUTION}",
    )


def _require_button_resolution(file: FilePath, size: tuple[int, int]) -> None:
    if size != EXPECTED_BUTTON_RESOLUTION:
        raise AssetExtractionError((_wrong_resolution_issue(file, size),))


def collect_asset_issues(assets_folder: Path) -> tuple[AssetIssue, ...]:
    issues: list[AssetIssue] = []
    modules = sorted(path for path in assets_folder.iterdir() if path.is_dir())
    for module in modules:
        for file in sorted(module.iterdir()):
            if not file.is_file() or file.suffix not in IMAGE_EXTENSIONS or file.name[0].isdigit():
                continue

            name, override_suffix, _extension = _split_asset_file(file)
            if override_suffix in OVERRIDE_SUFFIXES:
                base_exists = any((module / f"{name}{extension}").exists() for extension in IMAGE_EXTENSIONS)
                if not base_exists:
                    issues.append(
                        AssetIssue(
                            file=file.as_posix(),
                            reason=f"dangling {override_suffix[1:]} override: base image does not exist",
                        )
                    )

            is_button_image = not file.name.startswith("TEMPLATE_") and (
                override_suffix == "" or override_suffix in OVERRIDE_SUFFIXES
            )
            if is_button_image:
                try:
                    with Image.open(file) as image:
                        size = image.size
                except OSError as error:
                    issues.append(
                        AssetIssue(
                            file=file.as_posix(),
                            reason=f"unreadable image: {type(error).__name__}: {error}",
                        )
                    )
                    continue
                if size != EXPECTED_BUTTON_RESOLUTION:
                    issues.append(_wrong_resolution_issue(file, size))

    return tuple(sorted(issues))


def validate_assets(assets_folder: Path) -> None:
    issues = collect_asset_issues(assets_folder)
    if issues:
        raise AssetExtractionError(issues)


def _literal_file_reference(value: ast.expr) -> str | None:
    if isinstance(value, ast.Constant) and isinstance(value.value, str):
        return value.value
    return None


def collect_generated_asset_issues(module_folder: Path, *, repository_root: Path) -> tuple[AssetIssue, ...]:
    """Validate generated file references without importing asset modules."""
    issues: list[AssetIssue] = []
    for assets_file in sorted(module_folder.rglob(BUTTON_FILE)):
        source = assets_file.read_text(encoding="utf-8")
        if GENERATED_MARKER not in source:
            continue
        tree = ast.parse(source, filename=str(assets_file))
        for node in ast.walk(tree):
            if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Name):
                continue
            if node.func.id not in {"Button", "Template"}:
                continue
            file_keyword = next((keyword for keyword in node.keywords if keyword.arg == "file"), None)
            if file_keyword is None:
                continue
            reference = _literal_file_reference(file_keyword.value)
            if reference is None:
                issues.append(
                    AssetIssue(
                        file=f"{assets_file.as_posix()}:{node.lineno}",
                        reason="generated resource file must be a string literal",
                    )
                )
                continue
            referenced_file = Path(reference)
            if not referenced_file.is_absolute():
                referenced_file = repository_root / referenced_file
            if not referenced_file.is_file():
                issues.append(
                    AssetIssue(
                        file=f"{assets_file.as_posix()}:{node.lineno}",
                        reason=f"missing generated resource reference: {reference}",
                    )
                )
    return tuple(sorted(issues))


def _generated_path(path: Path) -> str:
    value = path.as_posix()
    return value if path.is_absolute() else f"./{value}"


class ImageExtractor:
    def __init__(self, module: str, file: FilePath) -> None:
        path = Path(file)
        self.module = module
        self.name = path.stem
        self.area, self.color, self.button, self.file = self.load()

    def get_file(self, genre: str = "") -> str:
        for ext in [".png", ".gif"]:
            file = f"{self.name}.{genre}{ext}" if genre else f"{self.name}{ext}"
            file = _generated_path(Path(AzurLaneConfig.ASSETS_FOLDER) / "cn" / self.module / file)
            if Path(file).exists():
                return file

        ext = ".png"
        file = f"{self.name}.{genre}{ext}" if genre else f"{self.name}{ext}"
        return _generated_path(Path(AzurLaneConfig.ASSETS_FOLDER) / "cn" / self.module / file)

    @staticmethod
    def extract(file: FilePath) -> Extraction:
        if Path(file).suffix == ".gif":
            # GIF 按钮使用第一帧。
            frames = imageio.mimread(Path(file))
            if not frames:
                message = f"GIF contains no frames: {file}"
                raise ValueError(message)
            first: ImageArray = np.asarray(frames[0], dtype=np.uint8)
            first = first[:, :, :3] if len(first.shape) == 3 else first
            bbox, mean = ImageExtractor._extract(first, file)
            for frame in frames[1:]:
                image: ImageArray = np.asarray(frame, dtype=np.uint8)
                image = image[:, :, :3] if len(image.shape) == 3 else image
                new_bbox, _new_mean = ImageExtractor._extract(image, file)
                if bbox != new_bbox:
                    logger.warning(f"{file} has multiple different bbox, this will cause unexpected behaviour")
            return bbox, mean
        image = load_image(file)
        return ImageExtractor._extract(image, file)

    @staticmethod
    def _extract(image: ImageArray, file: FilePath) -> Extraction:
        size = image_size(image)
        _require_button_resolution(file, size)
        bbox = get_bbox(image)
        mean = get_color(image=image, area=bbox)
        rounded = np.rint(mean).astype(int)
        return bbox, (int(rounded[0]), int(rounded[1]), int(rounded[2]))

    def load(self) -> tuple[Bounds, MeanColor, Bounds, str]:
        file = self.get_file()
        if Path(file).exists():
            area, color = self.extract(file)
            button = area
            override = self.get_file("AREA")
            if Path(override).exists():
                area, _ = self.extract(override)
            override = self.get_file("COLOR")
            if Path(override).exists():
                _, color = self.extract(override)
            override = self.get_file("BUTTON")
            if Path(override).exists():
                button, _ = self.extract(override)

            return area, color, button, file
        raise FileNotFoundError(file)

    @property
    def expression(self) -> str:
        return (
            f"{self.name} = Button(area={self.area!r}, color={self.color!r}, "
            f"button={self.button!r}, file={self.file!r},)"
        )


class TemplateExtractor(ImageExtractor):
    @staticmethod
    def extract(file: FilePath) -> Extraction:
        image = load_image(file)
        bbox = get_bbox(image)
        mean = get_color(image=image, area=bbox)
        rounded = np.rint(mean).astype(int)
        return bbox, (int(rounded[0]), int(rounded[1]), int(rounded[2]))

    @property
    def expression(self) -> str:
        return f"{self.name} = Template(file={self.file!r})"


class ModuleExtractor:
    def __init__(self, name: str) -> None:
        self.name = name
        self.folder = (Path(AzurLaneConfig.ASSETS_FOLDER) / "cn" / name).as_posix()

    @staticmethod
    def split(file: FilePath) -> tuple[str, str, str]:
        return _split_asset_file(file)

    @staticmethod
    def is_base_image(file: FilePath) -> bool:
        _, sub, _ = ModuleExtractor.split(file)
        return sub == ""

    @property
    def expression(self) -> list[str]:
        exp = []
        for path in Path(self.folder).iterdir():
            file = path.name
            if file[0].isdigit():
                continue
            if file.startswith("TEMPLATE_"):
                exp.append(TemplateExtractor(module=self.name, file=file).expression)
                continue
            if self.is_base_image(file):
                exp.append(ImageExtractor(module=self.name, file=file).expression)
                continue

        exp.sort()

        logger.info(f"Module: {self.name}({len(exp)})")
        imports = []
        if any("Button(" in row for row in exp):
            imports.append("from module.base.button import Button")
        if any("Template(" in row for row in exp):
            imports.append("from module.base.template import Template")
        return [*imports, "", *HEADER_EXP, *exp]

    def write(self) -> None:
        folder = Path(MODULE_FOLDER) / self.name
        if not folder.exists():
            folder.mkdir()
        with (folder / BUTTON_FILE).open("w", newline="") as f:
            f.writelines(f"{text}\n" for text in self.expression)


def worker(module: str) -> None:
    me = ModuleExtractor(name=module)
    me.write()


class AssetExtractor:
    """从国区资源生成 `assets.py`。

    资源名必须大写；数字前缀会被忽略，`TEMPLATE_` 前缀生成 `Template`，其余生成 `Button`；
    `.AREA`、`.COLOR`、`.BUTTON` 后缀分别覆盖对应字段。
    """

    def __init__(self) -> None:
        logger.info("Assets extract")

        assets_folder = Path(AzurLaneConfig.ASSETS_FOLDER) / "cn"
        modules = sorted(path.name for path in assets_folder.iterdir() if path.is_dir())

        issues = collect_asset_issues(assets_folder)
        if not issues:
            process_map(worker, modules)
        generated_issues = collect_generated_asset_issues(Path(MODULE_FOLDER), repository_root=Path())
        issues = tuple(sorted((*issues, *generated_issues)))
        if issues:
            raise AssetExtractionError(issues)


if __name__ == "__main__":
    ae = AssetExtractor()
