from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

EMPTY_SHIP_R = Button(
    area=(192, 359, 268, 435),
    color=(144, 144, 144),
    button=(192, 359, 268, 435),
    file="./assets/cn/equipment/EMPTY_SHIP_R.png",
)
EQUIPMENT_CLOSE = Button(
    area=(1139, 87, 1231, 111),
    color=(215, 149, 69),
    button=(1139, 87, 1231, 111),
    file="./assets/cn/equipment/EQUIPMENT_CLOSE.png",
)
EQUIPMENT_CODE_CLEAR = Button(
    area=(999, 477, 1121, 519),
    color=(142, 146, 151),
    button=(999, 477, 1121, 519),
    file="./assets/cn/equipment/EQUIPMENT_CODE_CLEAR.png",
)
EQUIPMENT_CODE_CONFIRM = Button(
    area=(999, 544, 1122, 586),
    color=(81, 137, 202),
    button=(999, 544, 1122, 586),
    file="./assets/cn/equipment/EQUIPMENT_CODE_CONFIRM.png",
)
EQUIPMENT_CODE_ENTER = Button(
    area=(875, 667, 1004, 707),
    color=(80, 129, 188),
    button=(875, 667, 1004, 707),
    file="./assets/cn/equipment/EQUIPMENT_CODE_ENTER.png",
)
EQUIPMENT_CODE_ENTRANCE = Button(
    area=(936, 88, 1028, 111),
    color=(94, 148, 208),
    button=(936, 88, 1028, 111),
    file="./assets/cn/equipment/EQUIPMENT_CODE_ENTRANCE.png",
)
EQUIPMENT_CODE_EQUIP_0 = Button(
    area=(324, 356, 407, 439),
    color=(44, 65, 88),
    button=(324, 356, 407, 439),
    file="./assets/cn/equipment/EQUIPMENT_CODE_EQUIP_0.png",
)
EQUIPMENT_CODE_EQUIP_1 = Button(
    area=(424, 356, 507, 439),
    color=(43, 65, 88),
    button=(424, 356, 507, 439),
    file="./assets/cn/equipment/EQUIPMENT_CODE_EQUIP_1.png",
)
EQUIPMENT_CODE_EQUIP_2 = Button(
    area=(524, 356, 607, 439),
    color=(43, 66, 89),
    button=(524, 356, 607, 439),
    file="./assets/cn/equipment/EQUIPMENT_CODE_EQUIP_2.png",
)
EQUIPMENT_CODE_EQUIP_3 = Button(
    area=(624, 356, 707, 439),
    color=(40, 62, 87),
    button=(624, 356, 707, 439),
    file="./assets/cn/equipment/EQUIPMENT_CODE_EQUIP_3.png",
)
EQUIPMENT_CODE_EQUIP_4 = Button(
    area=(724, 356, 807, 439),
    color=(40, 63, 87),
    button=(724, 356, 807, 439),
    file="./assets/cn/equipment/EQUIPMENT_CODE_EQUIP_4.png",
)
EQUIPMENT_CODE_EQUIP_5 = Button(
    area=(823, 355, 916, 440),
    color=(55, 79, 104),
    button=(823, 355, 916, 440),
    file="./assets/cn/equipment/EQUIPMENT_CODE_EQUIP_5.png",
)
EQUIPMENT_CODE_EQUIP_5_LOCKED = Button(
    area=(823, 355, 916, 440),
    color=(65, 84, 107),
    button=(823, 355, 916, 440),
    file="./assets/cn/equipment/EQUIPMENT_CODE_EQUIP_5_LOCKED.png",
)
EQUIPMENT_CODE_EXPORT = Button(
    area=(1000, 200, 1121, 241),
    color=(81, 138, 203),
    button=(1000, 200, 1121, 241),
    file="./assets/cn/equipment/EQUIPMENT_CODE_EXPORT.png",
)
EQUIPMENT_CODE_PAGE_CHECK = Button(
    area=(1000, 113, 1050, 160),
    color=(102, 122, 154),
    button=(1000, 113, 1050, 160),
    file="./assets/cn/equipment/EQUIPMENT_CODE_PAGE_CHECK.png",
)
EQUIPMENT_CODE_TEXTBOX = Button(
    area=(446, 668, 834, 706),
    color=(45, 47, 60),
    button=(446, 668, 834, 706),
    file="./assets/cn/equipment/EQUIPMENT_CODE_TEXTBOX.png",
)
EQUIPMENT_OPEN = Button(
    area=(1166, 91, 1203, 110),
    color=(128, 178, 223),
    button=(1166, 91, 1203, 110),
    file="./assets/cn/equipment/EQUIPMENT_OPEN.png",
)
EQUIPMENT_SCROLL_BOTTOM = Button(
    area=(1256, 575, 1264, 583),
    color=(244, 209, 66),
    button=(1256, 575, 1264, 583),
    file="./assets/cn/equipment/EQUIPMENT_SCROLL_BOTTOM.png",
)
EQUIPPING_OFF = Button(
    area=(25, 565, 60, 589),
    color=(94, 101, 104),
    button=(25, 565, 60, 589),
    file="./assets/cn/equipment/EQUIPPING_OFF.png",
)
EQUIPPING_ON = Button(
    area=(26, 510, 57, 584),
    color=(97, 115, 156),
    button=(26, 510, 57, 584),
    file="./assets/cn/equipment/EQUIPPING_ON.png",
)
EQUIP_1 = Button(
    area=(1211, 274, 1230, 315),
    color=(133, 181, 222),
    button=(1211, 274, 1230, 315),
    file="./assets/cn/equipment/EQUIP_1.png",
)
EQUIP_2 = Button(
    area=(1211, 374, 1230, 416),
    color=(130, 179, 220),
    button=(1211, 374, 1230, 416),
    file="./assets/cn/equipment/EQUIP_2.png",
)
EQUIP_3 = Button(
    area=(1211, 475, 1230, 517),
    color=(130, 179, 220),
    button=(1211, 475, 1230, 517),
    file="./assets/cn/equipment/EQUIP_3.png",
)
EQUIP_CONFIRM = Button(
    area=(792, 623, 959, 677),
    color=(222, 154, 59),
    button=(792, 623, 959, 677),
    file="./assets/cn/equipment/EQUIP_CONFIRM.png",
)
EQUIP_OFF = Button(
    area=(907, 565, 1037, 610),
    color=(112, 153, 216),
    button=(907, 565, 1037, 610),
    file="./assets/cn/equipment/EQUIP_OFF.png",
)
EQUIP_SAVE = Button(
    area=(355, 312, 452, 433),
    color=(170, 156, 122),
    button=(355, 312, 452, 433),
    file="./assets/cn/equipment/EQUIP_SAVE.png",
)
EQUIP_SCROLL = Button(
    area=(1254, 86, 1266, 588),
    color=(141, 130, 77),
    button=(1254, 86, 1266, 588),
    file="./assets/cn/equipment/EQUIP_SCROLL.png",
)
EQUIP_TAKE_ON_0 = Button(
    area=(871, 151, 955, 244),
    color=(116, 113, 116),
    button=(871, 151, 955, 244),
    file="./assets/cn/equipment/EQUIP_TAKE_ON_0.png",
)
EQUIP_TAKE_ON_1 = Button(
    area=(907, 338, 991, 431),
    color=(122, 122, 135),
    button=(907, 338, 991, 431),
    file="./assets/cn/equipment/EQUIP_TAKE_ON_1.png",
)
EQUIP_TAKE_ON_2 = Button(
    area=(866, 511, 950, 604),
    color=(117, 118, 127),
    button=(866, 511, 950, 604),
    file="./assets/cn/equipment/EQUIP_TAKE_ON_2.png",
)
EQUIP_TAKE_ON_3 = Button(
    area=(129, 252, 213, 345),
    color=(105, 108, 115),
    button=(129, 252, 213, 345),
    file="./assets/cn/equipment/EQUIP_TAKE_ON_3.png",
)
EQUIP_TAKE_ON_4 = Button(
    area=(128, 432, 212, 525),
    color=(109, 111, 120),
    button=(128, 432, 212, 525),
    file="./assets/cn/equipment/EQUIP_TAKE_ON_4.png",
)
FLEET_1_BACKLINE_1 = Button(
    area=(412, 195, 456, 239),
    color=(76, 67, 66),
    button=(412, 195, 456, 239),
    file="./assets/cn/equipment/FLEET_1_BACKLINE_1.png",
)
FLEET_1_BACKLINE_3 = Button(
    area=(616, 195, 659, 238),
    color=(62, 62, 67),
    button=(616, 195, 659, 238),
    file="./assets/cn/equipment/FLEET_1_BACKLINE_3.png",
)
FLEET_1_VANGUARD_1 = Button(
    area=(728, 195, 770, 237),
    color=(54, 57, 63),
    button=(728, 195, 770, 237),
    file="./assets/cn/equipment/FLEET_1_VANGUARD_1.png",
)
FLEET_1_VANGUARD_3 = Button(
    area=(932, 195, 974, 237),
    color=(53, 55, 62),
    button=(932, 195, 974, 237),
    file="./assets/cn/equipment/FLEET_1_VANGUARD_3.png",
)
FLEET_2_BACKLINE_1 = Button(
    area=(412, 309, 455, 352),
    color=(73, 64, 63),
    button=(412, 309, 455, 352),
    file="./assets/cn/equipment/FLEET_2_BACKLINE_1.png",
)
FLEET_2_BACKLINE_3 = Button(
    area=(616, 309, 659, 352),
    color=(51, 52, 57),
    button=(616, 309, 659, 352),
    file="./assets/cn/equipment/FLEET_2_BACKLINE_3.png",
)
FLEET_2_VANGUARD_1 = Button(
    area=(729, 310, 770, 351),
    color=(52, 54, 61),
    button=(729, 310, 770, 351),
    file="./assets/cn/equipment/FLEET_2_VANGUARD_1.png",
)
FLEET_2_VANGUARD_3 = Button(
    area=(932, 309, 974, 351),
    color=(51, 54, 62),
    button=(932, 309, 974, 351),
    file="./assets/cn/equipment/FLEET_2_VANGUARD_3.png",
)
FLEET_DETAIL = Button(
    area=(906, 644, 1008, 699),
    color=(166, 170, 188),
    button=(906, 644, 1008, 699),
    file="./assets/cn/equipment/FLEET_DETAIL.png",
)
FLEET_DETAIL_CHECK = Button(
    area=(915, 647, 980, 679),
    color=(234, 195, 154),
    button=(915, 647, 980, 679),
    file="./assets/cn/equipment/FLEET_DETAIL_CHECK.png",
)
FLEET_DETAIL_ENTER = Button(
    area=(729, 314, 802, 438),
    color=(154, 149, 147),
    button=(729, 314, 802, 438),
    file="./assets/cn/equipment/FLEET_DETAIL_ENTER.png",
)
FLEET_DETAIL_ENTER_FLAGSHIP = Button(
    area=(103, 327, 176, 437),
    color=(141, 135, 138),
    button=(103, 327, 176, 437),
    file="./assets/cn/equipment/FLEET_DETAIL_ENTER_FLAGSHIP.png",
)
FLEET_ENTER = Button(
    area=(502, 474, 517, 489),
    color=(165, 193, 232),
    button=(502, 474, 517, 489),
    file="./assets/cn/equipment/FLEET_ENTER.png",
)
FLEET_ENTER_FLAGSHIP = Button(
    area=(577, 277, 605, 291),
    color=(219, 196, 174),
    button=(577, 277, 605, 291),
    file="./assets/cn/equipment/FLEET_ENTER_FLAGSHIP.png",
)
FLEET_NEXT = Button(
    area=(1234, 327, 1254, 356),
    color=(72, 93, 125),
    button=(1234, 327, 1254, 356),
    file="./assets/cn/equipment/FLEET_NEXT.png",
)
FLEET_PREV = Button(
    area=(26, 327, 46, 356),
    color=(72, 93, 125),
    button=(26, 327, 46, 356),
    file="./assets/cn/equipment/FLEET_PREV.png",
)
OCR_FLEET_INDEX = Button(
    area=(957, 113, 987, 163),
    color=(36, 54, 86),
    button=(957, 113, 987, 163),
    file="./assets/cn/equipment/OCR_FLEET_INDEX.png",
)
SHIP_INFO_EQUIPMENT_CHECK = Button(
    area=(1173, 654, 1216, 686),
    color=(216, 166, 94),
    button=(1173, 654, 1216, 686),
    file="./assets/cn/equipment/SHIP_INFO_EQUIPMENT_CHECK.png",
)
SWIPE_AREA = Button(
    area=(220, 167, 580, 527),
    color=(165, 172, 194),
    button=(220, 167, 580, 527),
    file="./assets/cn/equipment/SWIPE_AREA.png",
)
SWIPE_CHECK = Button(
    area=(190, 353, 610, 455),
    color=(171, 180, 198),
    button=(190, 353, 610, 455),
    file="./assets/cn/equipment/SWIPE_CHECK.png",
)
UPGRADE_ENTER = Button(
    area=(759, 624, 919, 674),
    color=(228, 159, 66),
    button=(759, 624, 919, 674),
    file="./assets/cn/equipment/UPGRADE_ENTER.png",
)
UPGRADE_ENTER_CHECK = Button(
    area=(825, 528, 859, 559),
    color=(163, 138, 71),
    button=(825, 528, 859, 559),
    file="./assets/cn/equipment/UPGRADE_ENTER_CHECK.png",
)
UPGRADE_QUIT = Button(
    area=(125, 81, 312, 639),
    color=(70, 72, 80),
    button=(125, 81, 312, 639),
    file="./assets/cn/equipment/UPGRADE_QUIT.png",
)
