from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

OCR_DATA_KEY_CAMPAIGN = Button(
    area=(1188, 107, 1272, 131),
    color=(104, 101, 107),
    button=(1188, 107, 1272, 131),
    file="./assets/cn/war_archives/OCR_DATA_KEY_CAMPAIGN.png",
)
TEMPLATE_ABYSSAL_REFRAIN = Template(file="./assets/cn/war_archives/TEMPLATE_ABYSSAL_REFRAIN.png")
TEMPLATE_ANTHEM_OF_REMEMBRANCE = Template(file="./assets/cn/war_archives/TEMPLATE_ANTHEM_OF_REMEMBRANCE.png")
TEMPLATE_AQUILIFERS_BALLADE = Template(file="./assets/cn/war_archives/TEMPLATE_AQUILIFERS_BALLADE.png")
TEMPLATE_ASHEN_SIMULACRUM = Template(file="./assets/cn/war_archives/TEMPLATE_ASHEN_SIMULACRUM.png")
TEMPLATE_AURORA_NOCTIS = Template(file="./assets/cn/war_archives/TEMPLATE_AURORA_NOCTIS.png")
TEMPLATE_CONFLUENCE_OF_NOTHINGNESS = Template(file="./assets/cn/war_archives/TEMPLATE_CONFLUENCE_OF_NOTHINGNESS.png")
TEMPLATE_COUNTERATTACK_WITHIN_THE_FJORD = Template(
    file="./assets/cn/war_archives/TEMPLATE_COUNTERATTACK_WITHIN_THE_FJORD.png"
)
TEMPLATE_CRESCENDO_OF_POLARIS = Template(file="./assets/cn/war_archives/TEMPLATE_CRESCENDO_OF_POLARIS.png")
TEMPLATE_CRIMSON_ECHOES = Template(file="./assets/cn/war_archives/TEMPLATE_CRIMSON_ECHOES.png")
TEMPLATE_DAEDALIAN_HYMN = Template(file="./assets/cn/war_archives/TEMPLATE_DAEDALIAN_HYMN.png")
TEMPLATE_DIVERGENT_CHESSBOARD = Template(file="./assets/cn/war_archives/TEMPLATE_DIVERGENT_CHESSBOARD.png")
TEMPLATE_DREAMWAKERS_BUTTERFLY = Template(file="./assets/cn/war_archives/TEMPLATE_DREAMWAKERS_BUTTERFLY.png")
TEMPLATE_EMPYREAL_TRAGICOMEDY = Template(file="./assets/cn/war_archives/TEMPLATE_EMPYREAL_TRAGICOMEDY.png")
TEMPLATE_ENCIRCLING_GRAF_SPEE = Template(file="./assets/cn/war_archives/TEMPLATE_ENCIRCLING_GRAF_SPEE.png")
TEMPLATE_FALLEN_WINGS = Template(file="./assets/cn/war_archives/TEMPLATE_FALLEN_WINGS.png")
TEMPLATE_GLORIOUS_BATTLE = Template(file="./assets/cn/war_archives/TEMPLATE_GLORIOUS_BATTLE.png")
TEMPLATE_INK_STAINED_STEEL_SAKURA = Template(file="./assets/cn/war_archives/TEMPLATE_INK_STAINED_STEEL_SAKURA.png")
TEMPLATE_INTERLUDE_OF_ILLUSIONS = Template(file="./assets/cn/war_archives/TEMPLATE_INTERLUDE_OF_ILLUSIONS.png")
TEMPLATE_INVERTED_ORTHANT = Template(file="./assets/cn/war_archives/TEMPLATE_INVERTED_ORTHANT.png")
TEMPLATE_IRIS_OF_LIGHT_AND_DARK = Template(file="./assets/cn/war_archives/TEMPLATE_IRIS_OF_LIGHT_AND_DARK.png")
TEMPLATE_KHOROVOD_OF_DAWNS_RIME = Template(file="./assets/cn/war_archives/TEMPLATE_KHOROVOD_OF_DAWNS_RIME.png")
TEMPLATE_MICROLAYER_MEDLEY = Template(file="./assets/cn/war_archives/TEMPLATE_MICROLAYER_MEDLEY.png")
TEMPLATE_MIRROR_INVOLUTION = Template(file="./assets/cn/war_archives/TEMPLATE_MIRROR_INVOLUTION.png")
TEMPLATE_MOONLIT_OVERTURE = Template(file="./assets/cn/war_archives/TEMPLATE_MOONLIT_OVERTURE.png")
TEMPLATE_NORTHERN_OVERTURE = Template(file="./assets/cn/war_archives/TEMPLATE_NORTHERN_OVERTURE.png")
TEMPLATE_OPERATION_CONVERGENCE = Template(file="./assets/cn/war_archives/TEMPLATE_OPERATION_CONVERGENCE.png")
TEMPLATE_PARALLEL_SUPERIMPOSITION = Template(file="./assets/cn/war_archives/TEMPLATE_PARALLEL_SUPERIMPOSITION.png")
TEMPLATE_PLEDGE_OF_THE_RADIANT_COURT = Template(
    file="./assets/cn/war_archives/TEMPLATE_PLEDGE_OF_THE_RADIANT_COURT.png"
)
TEMPLATE_PRELUDE_UNDER_THE_MOON = Template(file="./assets/cn/war_archives/TEMPLATE_PRELUDE_UNDER_THE_MOON.png")
TEMPLATE_REVELATIONS_OF_DUST = Template(file="./assets/cn/war_archives/TEMPLATE_REVELATIONS_OF_DUST.png")
TEMPLATE_RONDO_AT_RAINBOWS_END = Template(file="./assets/cn/war_archives/TEMPLATE_RONDO_AT_RAINBOWS_END.png")
TEMPLATE_SCHERZO_OF_IRON_AND_BLOOD = Template(file="./assets/cn/war_archives/TEMPLATE_SCHERZO_OF_IRON_AND_BLOOD.png")
TEMPLATE_SKYBOUND_ORATORIO = Template(file="./assets/cn/war_archives/TEMPLATE_SKYBOUND_ORATORIO.png")
TEMPLATE_STARS_OF_THE_SHIMMERING_FJORD = Template(
    file="./assets/cn/war_archives/TEMPLATE_STARS_OF_THE_SHIMMERING_FJORD.png"
)
TEMPLATE_STRIVE_WISH_AND_STRATEGIZE = Template(file="./assets/cn/war_archives/TEMPLATE_STRIVE_WISH_AND_STRATEGIZE.png")
TEMPLATE_SUNDERED_BLUE = Template(file="./assets/cn/war_archives/TEMPLATE_SUNDERED_BLUE.png")
TEMPLATE_SWIRLING_CHERRY_BLOSSOMS = Template(file="./assets/cn/war_archives/TEMPLATE_SWIRLING_CHERRY_BLOSSOMS.png")
TEMPLATE_TEMPESTA_AND_THE_FOUNTAIN_OF_YOUTH = Template(
    file="./assets/cn/war_archives/TEMPLATE_TEMPESTA_AND_THE_FOUNTAIN_OF_YOUTH.png"
)
TEMPLATE_THE_ENIGMA_AND_THE_SHARK = Template(file="./assets/cn/war_archives/TEMPLATE_THE_ENIGMA_AND_THE_SHARK.png")
TEMPLATE_THE_FLAME_TOUCHED_DAGGER = Template(file="./assets/cn/war_archives/TEMPLATE_THE_FLAME_TOUCHED_DAGGER.png")
TEMPLATE_THE_SOLOMON_RANGER = Template(file="./assets/cn/war_archives/TEMPLATE_THE_SOLOMON_RANGER.png")
TEMPLATE_THE_WAY_HOME_IN_THE_NIGHT = Template(file="./assets/cn/war_archives/TEMPLATE_THE_WAY_HOME_IN_THE_NIGHT.png")
TEMPLATE_TOWER_OF_TRANSCENDENCE = Template(file="./assets/cn/war_archives/TEMPLATE_TOWER_OF_TRANSCENDENCE.png")
TEMPLATE_UNIVERSE_IN_UNISON = Template(file="./assets/cn/war_archives/TEMPLATE_UNIVERSE_IN_UNISON.png")
TEMPLATE_UPON_THE_SHIMMERING_BLUE = Template(file="./assets/cn/war_archives/TEMPLATE_UPON_THE_SHIMMERING_BLUE.png")
TEMPLATE_VIOLET_TEMPEST_BLOOMING_LYCORIS = Template(
    file="./assets/cn/war_archives/TEMPLATE_VIOLET_TEMPEST_BLOOMING_LYCORIS.png"
)
TEMPLATE_VIRTUAL_TOWER = Template(file="./assets/cn/war_archives/TEMPLATE_VIRTUAL_TOWER.png")
TEMPLATE_VISITORS_DYED_IN_RED = Template(file="./assets/cn/war_archives/TEMPLATE_VISITORS_DYED_IN_RED.png")
TEMPLATE_WINTERS_CROWN = Template(file="./assets/cn/war_archives/TEMPLATE_WINTERS_CROWN.png")
WAR_ARCHIVES_CAMPAIGN_CHECK = Button(
    area=(1150, 101, 1166, 130),
    color=(134, 175, 207),
    button=(1150, 101, 1166, 130),
    file="./assets/cn/war_archives/WAR_ARCHIVES_CAMPAIGN_CHECK.png",
)
WAR_ARCHIVES_EX_OFF = Button(
    area=(908, 42, 991, 72),
    color=(40, 42, 56),
    button=(908, 42, 991, 72),
    file="./assets/cn/war_archives/WAR_ARCHIVES_EX_OFF.png",
)
WAR_ARCHIVES_EX_ON = Button(
    area=(903, 42, 994, 72),
    color=(75, 93, 151),
    button=(903, 42, 994, 72),
    file="./assets/cn/war_archives/WAR_ARCHIVES_EX_ON.png",
)
WAR_ARCHIVES_SCROLL = Button(
    area=(1253, 130, 1260, 695),
    color=(142, 131, 75),
    button=(1253, 130, 1260, 695),
    file="./assets/cn/war_archives/WAR_ARCHIVES_SCROLL.png",
)
WAR_ARCHIVES_SP_OFF = Button(
    area=(1012, 43, 1095, 71),
    color=(40, 42, 56),
    button=(1012, 43, 1095, 71),
    file="./assets/cn/war_archives/WAR_ARCHIVES_SP_OFF.png",
)
WAR_ARCHIVES_SP_ON = Button(
    area=(1010, 43, 1095, 71),
    color=(77, 95, 152),
    button=(1010, 43, 1095, 71),
    file="./assets/cn/war_archives/WAR_ARCHIVES_SP_ON.png",
)
