from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

AWAKENING = Button(
    area=(803, 282, 893, 304),
    color=(183, 163, 158),
    button=(803, 282, 893, 304),
    file="./assets/cn/awaken/AWAKENING.png",
)
AWAKEN_CANCEL = Button(
    area=(485, 514, 553, 543),
    color=(214, 160, 154),
    button=(485, 514, 553, 543),
    file="./assets/cn/awaken/AWAKEN_CANCEL.png",
)
AWAKEN_CONFIRM = Button(
    area=(727, 513, 795, 542),
    color=(151, 182, 222),
    button=(727, 513, 795, 542),
    file="./assets/cn/awaken/AWAKEN_CONFIRM.png",
)
AWAKEN_FINISH = Button(
    area=(435, 343, 468, 382),
    color=(58, 152, 193),
    button=(218, 561, 548, 630),
    file="./assets/cn/awaken/AWAKEN_FINISH.png",
)
COST_ARRAY = Button(
    area=(720, 374, 780, 434),
    color=(141, 163, 178),
    button=(720, 374, 780, 434),
    file="./assets/cn/awaken/COST_ARRAY.png",
)
COST_CHIP = Button(
    area=(610, 375, 670, 435),
    color=(157, 188, 190),
    button=(610, 375, 670, 435),
    file="./assets/cn/awaken/COST_CHIP.png",
)
COST_COIN = Button(
    area=(499, 373, 559, 433),
    color=(219, 180, 83),
    button=(499, 373, 559, 433),
    file="./assets/cn/awaken/COST_COIN.png",
)
LEVEL_UP = Button(
    area=(804, 282, 897, 304),
    color=(141, 167, 216),
    button=(804, 282, 897, 304),
    file="./assets/cn/awaken/LEVEL_UP.png",
)
OCR_SHIP_LEVEL = Button(
    area=(757, 283, 799, 319),
    color=(115, 130, 142),
    button=(757, 283, 799, 319),
    file="./assets/cn/awaken/OCR_SHIP_LEVEL.png",
)
SHIP_LEVEL_CHECK = Button(
    area=(706, 298, 742, 315),
    color=(171, 162, 193),
    button=(706, 298, 742, 315),
    file="./assets/cn/awaken/SHIP_LEVEL_CHECK.png",
)
