from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

MEOWFFICER_APPLY_LOCK = Button(
    area=(36, 560, 82, 582),
    color=(205, 179, 148),
    button=(36, 560, 82, 582),
    file="./assets/cn/meowfficer/MEOWFFICER_APPLY_LOCK.png",
)
MEOWFFICER_APPLY_UNLOCK = Button(
    area=(35, 559, 83, 582),
    color=(200, 176, 147),
    button=(35, 559, 83, 582),
    file="./assets/cn/meowfficer/MEOWFFICER_APPLY_UNLOCK.png",
)
MEOWFFICER_BUY = Button(
    area=(864, 461, 957, 493),
    color=(241, 217, 105),
    button=(864, 461, 957, 493),
    file="./assets/cn/meowfficer/MEOWFFICER_BUY.png",
)
MEOWFFICER_BUY_ENTER = Button(
    area=(975, 580, 1084, 649),
    color=(206, 177, 135),
    button=(975, 580, 1084, 649),
    file="./assets/cn/meowfficer/MEOWFFICER_BUY_ENTER.png",
)
MEOWFFICER_BUY_NEXT = Button(
    area=(877, 279, 902, 304),
    color=(254, 228, 139),
    button=(877, 279, 902, 304),
    file="./assets/cn/meowfficer/MEOWFFICER_BUY_NEXT.png",
)
MEOWFFICER_BUY_PREV = Button(
    area=(759, 279, 783, 302),
    color=(254, 224, 124),
    button=(759, 279, 783, 302),
    file="./assets/cn/meowfficer/MEOWFFICER_BUY_PREV.png",
)
MEOWFFICER_BUY_SKIP = Button(
    area=(594, 462, 687, 494),
    color=(240, 218, 104),
    button=(594, 462, 687, 494),
    file="./assets/cn/meowfficer/MEOWFFICER_BUY_SKIP.png",
)
MEOWFFICER_CANCEL = Button(
    area=(473, 436, 553, 467),
    color=(234, 210, 104),
    button=(473, 436, 553, 467),
    file="./assets/cn/meowfficer/MEOWFFICER_CANCEL.png",
)
MEOWFFICER_CONFIRM = Button(
    area=(741, 434, 827, 468),
    color=(239, 216, 107),
    button=(741, 434, 827, 468),
    file="./assets/cn/meowfficer/MEOWFFICER_CONFIRM.png",
)
MEOWFFICER_ENHANCE_CONFIRM = Button(
    area=(1135, 627, 1219, 658),
    color=(237, 213, 105),
    button=(1135, 627, 1219, 658),
    file="./assets/cn/meowfficer/MEOWFFICER_ENHANCE_CONFIRM.png",
)
MEOWFFICER_ENHANCE_ENTER = Button(
    area=(27, 208, 77, 259),
    color=(204, 200, 202),
    button=(27, 208, 77, 259),
    file="./assets/cn/meowfficer/MEOWFFICER_ENHANCE_ENTER.png",
)
MEOWFFICER_FEED_CANCEL = Button(
    area=(740, 601, 805, 626),
    color=(223, 199, 97),
    button=(740, 601, 805, 626),
    file="./assets/cn/meowfficer/MEOWFFICER_FEED_CANCEL.png",
)
MEOWFFICER_FEED_CONFIRM = Button(
    area=(1143, 598, 1226, 629),
    color=(237, 215, 103),
    button=(1143, 598, 1226, 629),
    file="./assets/cn/meowfficer/MEOWFFICER_FEED_CONFIRM.png",
)
MEOWFFICER_FEED_ENTER = Button(
    area=(766, 430, 816, 480),
    color=(241, 235, 236),
    button=(766, 430, 816, 480),
    file="./assets/cn/meowfficer/MEOWFFICER_FEED_ENTER.png",
)
MEOWFFICER_FORT_CHECK = Button(
    area=(303, 120, 356, 147),
    color=(194, 189, 190),
    button=(303, 120, 356, 147),
    file="./assets/cn/meowfficer/MEOWFFICER_FORT_CHECK.png",
)
MEOWFFICER_FORT_CHORE = Button(
    area=(441, 181, 468, 206),
    color=(252, 235, 209),
    button=(105, 220, 128, 351),
    file="./assets/cn/meowfficer/MEOWFFICER_FORT_CHORE.png",
)
MEOWFFICER_FORT_ENTER = Button(
    area=(813, 563, 896, 662),
    color=(221, 185, 152),
    button=(813, 563, 896, 662),
    file="./assets/cn/meowfficer/MEOWFFICER_FORT_ENTER.png",
)
MEOWFFICER_FORT_GET_XP_1 = Button(
    area=(371, 198, 453, 278),
    color=(217, 187, 148),
    button=(371, 198, 453, 278),
    file="./assets/cn/meowfficer/MEOWFFICER_FORT_GET_XP_1.png",
)
MEOWFFICER_FORT_GET_XP_2 = Button(
    area=(320, 314, 422, 412),
    color=(221, 189, 148),
    button=(320, 314, 422, 412),
    file="./assets/cn/meowfficer/MEOWFFICER_FORT_GET_XP_2.png",
)
MEOWFFICER_FORT_RED_DOT = Button(
    area=(918, 647, 938, 668),
    color=(243, 132, 118),
    button=(918, 647, 938, 668),
    file="./assets/cn/meowfficer/MEOWFFICER_FORT_RED_DOT.png",
)
MEOWFFICER_GET_CHECK = Button(
    area=(36, 666, 82, 689),
    color=(204, 175, 130),
    button=(36, 666, 82, 689),
    file="./assets/cn/meowfficer/MEOWFFICER_GET_CHECK.png",
)
MEOWFFICER_GOLD_CHECK = Button(
    area=(1117, 242, 1160, 265),
    color=(250, 229, 170),
    button=(1117, 242, 1160, 265),
    file="./assets/cn/meowfficer/MEOWFFICER_GOLD_CHECK.png",
)
MEOWFFICER_PURPLE_CHECK = Button(
    area=(1110, 240, 1148, 265),
    color=(223, 172, 245),
    button=(1110, 240, 1148, 265),
    file="./assets/cn/meowfficer/MEOWFFICER_PURPLE_CHECK.png",
)
MEOWFFICER_TALENT_CLOSE = Button(
    area=(858, 238, 908, 297),
    color=(232, 131, 111),
    button=(858, 238, 908, 297),
    file="./assets/cn/meowfficer/MEOWFFICER_TALENT_CLOSE.png",
)
MEOWFFICER_TRAIN_CLICK_SAFE_AREA = Button(
    area=(224, 184, 242, 347),
    color=(242, 237, 237),
    button=(224, 184, 242, 347),
    file="./assets/cn/meowfficer/MEOWFFICER_TRAIN_CLICK_SAFE_AREA.png",
)
MEOWFFICER_TRAIN_COMPLETE = Button(
    area=(263, 195, 361, 222),
    color=(132, 216, 152),
    button=(263, 195, 361, 222),
    file="./assets/cn/meowfficer/MEOWFFICER_TRAIN_COMPLETE.png",
)
MEOWFFICER_TRAIN_ENTER = Button(
    area=(1123, 573, 1239, 643),
    color=(194, 168, 114),
    button=(1123, 573, 1239, 643),
    file="./assets/cn/meowfficer/MEOWFFICER_TRAIN_ENTER.png",
)
MEOWFFICER_TRAIN_EVALUATE = Button(
    area=(575, 23, 707, 67),
    color=(254, 218, 206),
    button=(575, 23, 707, 67),
    file="./assets/cn/meowfficer/MEOWFFICER_TRAIN_EVALUATE.png",
)
MEOWFFICER_TRAIN_FILL_QUEUE = Button(
    area=(780, 548, 859, 567),
    color=(205, 179, 89),
    button=(780, 548, 859, 567),
    file="./assets/cn/meowfficer/MEOWFFICER_TRAIN_FILL_QUEUE.png",
)
MEOWFFICER_TRAIN_FINISH_ALL = Button(
    area=(784, 551, 870, 576),
    color=(216, 191, 97),
    button=(784, 551, 870, 576),
    file="./assets/cn/meowfficer/MEOWFFICER_TRAIN_FINISH_ALL.png",
)
MEOWFFICER_TRAIN_START = Button(
    area=(937, 553, 1024, 575),
    color=(209, 183, 91),
    button=(937, 553, 1024, 575),
    file="./assets/cn/meowfficer/MEOWFFICER_TRAIN_START.png",
)
OCR_MEOWFFICER = Button(
    area=(1026, 664, 1072, 684),
    color=(215, 201, 189),
    button=(1026, 664, 1072, 684),
    file="./assets/cn/meowfficer/OCR_MEOWFFICER.png",
)
OCR_MEOWFFICER_CAPACITY = Button(
    area=(718, 555, 828, 589),
    color=(229, 227, 227),
    button=(718, 555, 828, 589),
    file="./assets/cn/meowfficer/OCR_MEOWFFICER_CAPACITY.png",
)
OCR_MEOWFFICER_CHOOSE = Button(
    area=(800, 279, 862, 305),
    color=(244, 241, 239),
    button=(800, 279, 862, 305),
    file="./assets/cn/meowfficer/OCR_MEOWFFICER_CHOOSE.png",
)
OCR_MEOWFFICER_COINS = Button(
    area=(1161, 20, 1261, 48),
    color=(200, 198, 192),
    button=(1161, 20, 1261, 48),
    file="./assets/cn/meowfficer/OCR_MEOWFFICER_COINS.png",
)
OCR_MEOWFFICER_ENHANCE_LEVEL = Button(
    area=(374, 599, 434, 621),
    color=(210, 197, 140),
    button=(374, 599, 434, 621),
    file="./assets/cn/meowfficer/OCR_MEOWFFICER_ENHANCE_LEVEL.png",
)
OCR_MEOWFFICER_FEED = Button(
    area=(1046, 599, 1112, 625),
    color=(215, 207, 206),
    button=(1046, 599, 1112, 625),
    file="./assets/cn/meowfficer/OCR_MEOWFFICER_FEED.png",
)
OCR_MEOWFFICER_QUEUE = Button(
    area=(312, 543, 372, 568),
    color=(215, 207, 206),
    button=(312, 543, 372, 568),
    file="./assets/cn/meowfficer/OCR_MEOWFFICER_QUEUE.png",
)
