from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ACTION_POINT_BUY_REMAIN = Button(
    area=(803, 458, 833, 482),
    color=(108, 138, 125),
    button=(803, 458, 833, 482),
    file="./assets/cn/os_handler/ACTION_POINT_BUY_REMAIN.png",
)
ACTION_POINT_CANCEL = Button(
    area=(370, 528, 542, 585),
    color=(167, 168, 171),
    button=(370, 528, 542, 585),
    file="./assets/cn/os_handler/ACTION_POINT_CANCEL.png",
)
ACTION_POINT_REMAIN = Button(
    area=(892, 220, 952, 241),
    color=(124, 127, 113),
    button=(892, 220, 952, 241),
    file="./assets/cn/os_handler/ACTION_POINT_REMAIN.png",
)
ACTION_POINT_REMAIN_OS = Button(
    area=(878, 28, 928, 46),
    color=(78, 89, 100),
    button=(878, 28, 928, 46),
    file="./assets/cn/os_handler/ACTION_POINT_REMAIN_OS.png",
)
ACTION_POINT_USE = Button(
    area=(738, 528, 910, 585),
    color=(93, 142, 203),
    button=(738, 528, 910, 585),
    file="./assets/cn/os_handler/ACTION_POINT_USE.png",
)
ASH_POPUP_CHECK = Button(
    area=(665, 318, 759, 340),
    color=(154, 163, 172),
    button=(665, 318, 759, 340),
    file="./assets/cn/os_handler/ASH_POPUP_CHECK.png",
)
AUTO_SEARCH_OS_MAP_OPTION_OFF = Button(
    area=(1205, 549, 1275, 566),
    color=(196, 169, 169),
    button=(1205, 549, 1275, 566),
    file="./assets/cn/os_handler/AUTO_SEARCH_OS_MAP_OPTION_OFF.png",
)
AUTO_SEARCH_OS_MAP_OPTION_OFF_DISABLED = Button(
    area=(1205, 531, 1275, 547),
    color=(156, 135, 134),
    button=(1205, 531, 1275, 547),
    file="./assets/cn/os_handler/AUTO_SEARCH_OS_MAP_OPTION_OFF_DISABLED.png",
)
AUTO_SEARCH_OS_MAP_OPTION_ON = Button(
    area=(1205, 549, 1275, 566),
    color=(149, 176, 193),
    button=(1205, 549, 1275, 566),
    file="./assets/cn/os_handler/AUTO_SEARCH_OS_MAP_OPTION_ON.png",
)
AUTO_SEARCH_REWARD = Button(
    area=(575, 598, 721, 646),
    color=(169, 168, 170),
    button=(575, 598, 721, 646),
    file="./assets/cn/os_handler/AUTO_SEARCH_REWARD.png",
)
CLICK_SAFE_AREA = Button(
    area=(1104, 169, 1214, 284),
    color=(96, 114, 142),
    button=(1104, 169, 1214, 284),
    file="./assets/cn/os_handler/CLICK_SAFE_AREA.png",
)
CURRENT_AP_CHECK = Button(
    area=(837, 228, 867, 252),
    color=(165, 124, 73),
    button=(837, 228, 867, 252),
    file="./assets/cn/os_handler/CURRENT_AP_CHECK.png",
)
EXCHANGE_CHECK = Button(
    area=(144, 17, 249, 41),
    color=(153, 170, 209),
    button=(144, 17, 249, 41),
    file="./assets/cn/os_handler/EXCHANGE_CHECK.png",
)
EXCHANGE_ENTER = Button(
    area=(195, 629, 344, 693),
    color=(58, 54, 52),
    button=(195, 629, 344, 693),
    file="./assets/cn/os_handler/EXCHANGE_ENTER.png",
)
GET_ADAPTABILITY = Button(
    area=(538, 191, 742, 227),
    color=(166, 195, 246),
    button=(538, 191, 742, 227),
    file="./assets/cn/os_handler/GET_ADAPTABILITY.png",
)
GET_MEOWFFICER_ITEMS_1 = Button(
    area=(558, 211, 730, 242),
    color=(186, 200, 231),
    button=(558, 211, 730, 242),
    file="./assets/cn/os_handler/GET_MEOWFFICER_ITEMS_1.png",
)
GET_MEOWFFICER_ITEMS_2 = Button(
    area=(558, 140, 730, 171),
    color=(186, 200, 231),
    button=(558, 140, 730, 171),
    file="./assets/cn/os_handler/GET_MEOWFFICER_ITEMS_2.png",
)
IN_MAP = Button(
    area=(925, 644, 986, 674),
    color=(244, 212, 159),
    button=(925, 644, 986, 674),
    file="./assets/cn/os_handler/IN_MAP.png",
)
MAP_ARCHIVES = Button(
    area=(1180, 353, 1280, 411),
    color=(134, 255, 255),
    button=(1180, 353, 1280, 411),
    file="./assets/cn/os_handler/MAP_ARCHIVES.png",
)
MAP_WORLD = Button(
    area=(943, 499, 1048, 512),
    color=(71, 74, 83),
    button=(578, 675, 702, 691),
    file="./assets/cn/os_handler/MAP_WORLD.png",
)
MISSION_CHECK = Button(
    area=(120, 122, 229, 148),
    color=(145, 153, 187),
    button=(120, 122, 229, 148),
    file="./assets/cn/os_handler/MISSION_CHECK.png",
)
MISSION_CHECKOUT = Button(
    area=(1026, 204, 1114, 234),
    color=(152, 153, 156),
    button=(1026, 204, 1114, 234),
    file="./assets/cn/os_handler/MISSION_CHECKOUT.png",
)
MISSION_ENTER = Button(
    area=(767, 639, 853, 695),
    color=(230, 185, 113),
    button=(767, 639, 853, 695),
    file="./assets/cn/os_handler/MISSION_ENTER.png",
)
MISSION_FINISH = Button(
    area=(1028, 205, 1112, 232),
    color=(79, 128, 191),
    button=(1028, 205, 1112, 232),
    file="./assets/cn/os_handler/MISSION_FINISH.png",
)
MISSION_MAP_CHECK = Button(
    area=(943, 499, 1048, 512),
    color=(71, 74, 83),
    button=(943, 499, 1048, 512),
    file="./assets/cn/os_handler/MISSION_MAP_CHECK.png",
)
MISSION_MONTHLY_BOSS = Button(
    area=(669, 188, 747, 206),
    color=(121, 130, 154),
    button=(669, 188, 747, 206),
    file="./assets/cn/os_handler/MISSION_MONTHLY_BOSS.png",
)
MISSION_OVERVIEW_ACCEPT = Button(
    area=(1072, 12, 1130, 40),
    color=(230, 193, 168),
    button=(1072, 12, 1130, 40),
    file="./assets/cn/os_handler/MISSION_OVERVIEW_ACCEPT.png",
)
MISSION_OVERVIEW_ACCEPT_SINGLE = Button(
    area=(1066, 121, 1138, 149),
    color=(145, 182, 231),
    button=(1066, 121, 1138, 149),
    file="./assets/cn/os_handler/MISSION_OVERVIEW_ACCEPT_SINGLE.png",
)
MISSION_OVERVIEW_CHECK = Button(
    area=(127, 17, 262, 42),
    color=(148, 165, 209),
    button=(127, 17, 262, 42),
    file="./assets/cn/os_handler/MISSION_OVERVIEW_CHECK.png",
)
MISSION_OVERVIEW_EMPTY = Button(
    area=(1052, 320, 1067, 390),
    color=(144, 91, 99),
    button=(1052, 320, 1067, 390),
    file="./assets/cn/os_handler/MISSION_OVERVIEW_EMPTY.png",
)
MISSION_OVERVIEW_ENTER = Button(
    area=(1111, 672, 1207, 690),
    color=(66, 68, 72),
    button=(1105, 629, 1255, 693),
    file="./assets/cn/os_handler/MISSION_OVERVIEW_ENTER.png",
)
MISSION_QUIT = Button(
    area=(1086, 111, 1152, 155),
    color=(152, 38, 35),
    button=(1086, 111, 1152, 155),
    file="./assets/cn/os_handler/MISSION_QUIT.png",
)
ORDER_CHECK = Button(
    area=(60, 623, 98, 659),
    color=(60, 77, 122),
    button=(106, 77, 224, 94),
    file="./assets/cn/os_handler/ORDER_CHECK.png",
)
ORDER_ENTER = Button(
    area=(1012, 165, 1044, 194),
    color=(95, 114, 137),
    button=(1012, 165, 1044, 194),
    file="./assets/cn/os_handler/ORDER_ENTER.png",
)
ORDER_SCAN = Button(
    area=(993, 391, 1116, 421),
    color=(162, 185, 222),
    button=(920, 375, 1220, 471),
    file="./assets/cn/os_handler/ORDER_SCAN.png",
)
ORDER_SUBMARINE = Button(
    area=(993, 518, 1115, 548),
    color=(167, 188, 223),
    button=(920, 502, 1220, 598),
    file="./assets/cn/os_handler/ORDER_SUBMARINE.png",
)
OS_ADAPTABILITY_ATTACK = Button(
    area=(1162, 230, 1238, 258),
    color=(43, 77, 114),
    button=(1162, 230, 1238, 258),
    file="./assets/cn/os_handler/OS_ADAPTABILITY_ATTACK.png",
)
OS_ADAPTABILITY_DURABILITY = Button(
    area=(1161, 283, 1237, 311),
    color=(47, 75, 108),
    button=(1161, 283, 1237, 311),
    file="./assets/cn/os_handler/OS_ADAPTABILITY_DURABILITY.png",
)
OS_ADAPTABILITY_RECOVER = Button(
    area=(1162, 336, 1238, 364),
    color=(47, 72, 105),
    button=(1162, 336, 1238, 364),
    file="./assets/cn/os_handler/OS_ADAPTABILITY_RECOVER.png",
)
OS_FLEET_LOCKED = Button(
    area=(1187, 531, 1193, 548),
    color=(73, 126, 115),
    button=(1187, 531, 1193, 548),
    file="./assets/cn/os_handler/OS_FLEET_LOCKED.png",
)
OS_FLEET_UNLOCKED = Button(
    area=(1186, 523, 1193, 553),
    color=(88, 77, 90),
    button=(1186, 523, 1193, 553),
    file="./assets/cn/os_handler/OS_FLEET_UNLOCKED.png",
)
OS_GAME_TIPS = Button(
    area=(53, 51, 95, 68),
    color=(71, 50, 67),
    button=(53, 51, 95, 68),
    file="./assets/cn/os_handler/OS_GAME_TIPS.png",
)
OS_MONTHBOSS_HARD = Button(
    area=(564, 183, 662, 209),
    color=(113, 111, 132),
    button=(564, 183, 662, 209),
    file="./assets/cn/os_handler/OS_MONTHBOSS_HARD.png",
)
OS_MONTHBOSS_NORMAL = Button(
    area=(567, 184, 662, 211),
    color=(107, 110, 132),
    button=(567, 184, 662, 211),
    file="./assets/cn/os_handler/OS_MONTHBOSS_NORMAL.png",
)
PORT_DOCK_CHECK = Button(
    area=(182, 645, 364, 697),
    color=(125, 179, 242),
    button=(182, 645, 364, 697),
    file="./assets/cn/os_handler/PORT_DOCK_CHECK.png",
)
PORT_ENTER = Button(
    area=(1148, 640, 1280, 698),
    color=(47, 55, 66),
    button=(1148, 640, 1280, 698),
    file="./assets/cn/os_handler/PORT_ENTER.png",
)
PORT_GOTO_DOCK = Button(
    area=(1069, 640, 1260, 695),
    color=(114, 171, 236),
    button=(1069, 640, 1260, 695),
    file="./assets/cn/os_handler/PORT_GOTO_DOCK.png",
)
PORT_GOTO_MISSION = Button(
    area=(606, 641, 783, 695),
    color=(229, 174, 90),
    button=(606, 641, 783, 695),
    file="./assets/cn/os_handler/PORT_GOTO_MISSION.png",
)
PORT_GOTO_SUPPLY = Button(
    area=(837, 640, 1029, 695),
    color=(110, 167, 233),
    button=(837, 640, 1029, 695),
    file="./assets/cn/os_handler/PORT_GOTO_SUPPLY.png",
)
PORT_MISSION_ACCEPT = Button(
    area=(1132, 147, 1205, 176),
    color=(143, 181, 231),
    button=(1132, 147, 1205, 176),
    file="./assets/cn/os_handler/PORT_MISSION_ACCEPT.png",
)
PORT_MISSION_CHECK = Button(
    area=(127, 17, 179, 42),
    color=(149, 166, 206),
    button=(127, 17, 179, 42),
    file="./assets/cn/os_handler/PORT_MISSION_CHECK.png",
)
PORT_MISSION_RED_DOT = Button(
    area=(791, 639, 799, 647),
    color=(222, 115, 90),
    button=(791, 639, 799, 647),
    file="./assets/cn/os_handler/PORT_MISSION_RED_DOT.png",
)
RESET_FLEET_PREPARATION = Button(
    area=(128, 622, 193, 637),
    color=(46, 83, 36),
    button=(968, 581, 1160, 635),
    file="./assets/cn/os_handler/RESET_FLEET_PREPARATION.png",
)
RESET_TICKET_POPUP = Button(
    area=(363, 240, 455, 258),
    color=(145, 151, 161),
    button=(863, 173, 929, 217),
    file="./assets/cn/os_handler/RESET_TICKET_POPUP.png",
)
STORAGE_CHECK = Button(
    area=(122, 15, 203, 40),
    color=(162, 178, 214),
    button=(122, 15, 203, 40),
    file="./assets/cn/os_handler/STORAGE_CHECK.png",
)
STORAGE_COORDINATE_CHECKOUT = Button(
    area=(554, 493, 726, 550),
    color=(92, 141, 203),
    button=(554, 493, 726, 550),
    file="./assets/cn/os_handler/STORAGE_COORDINATE_CHECKOUT.png",
)
STORAGE_ENTER = Button(
    area=(770, 636, 880, 699),
    color=(240, 199, 121),
    button=(770, 636, 880, 699),
    file="./assets/cn/os_handler/STORAGE_ENTER.png",
)
STORAGE_USE = Button(
    area=(709, 506, 769, 536),
    color=(161, 186, 220),
    button=(687, 493, 860, 550),
    file="./assets/cn/os_handler/STORAGE_USE.png",
)
STORATE_SCROLL = Button(
    area=(1256, 102, 1264, 589),
    color=(119, 109, 60),
    button=(1256, 102, 1264, 589),
    file="./assets/cn/os_handler/STORATE_SCROLL.png",
)
STRATEGIC_SEARCH_DEVICE_CHECK = Button(
    area=(471, 340, 553, 360),
    color=(147, 152, 163),
    button=(471, 340, 553, 360),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_DEVICE_CHECK.png",
)
STRATEGIC_SEARCH_DEVICE_CONTINUE = Button(
    area=(516, 380, 536, 394),
    color=(95, 134, 74),
    button=(516, 380, 536, 394),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_DEVICE_CONTINUE.png",
)
STRATEGIC_SEARCH_DEVICE_STOP = Button(
    area=(443, 380, 463, 394),
    color=(95, 134, 74),
    button=(443, 380, 463, 394),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_DEVICE_STOP.png",
)
STRATEGIC_SEARCH_MAP_OPTION_OFF = Button(
    area=(1178, 576, 1278, 617),
    color=(96, 102, 122),
    button=(1178, 576, 1278, 617),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_MAP_OPTION_OFF.png",
)
STRATEGIC_SEARCH_MERCHANT_CONTINUE = Button(
    area=(516, 443, 536, 457),
    color=(94, 133, 73),
    button=(516, 443, 536, 457),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_MERCHANT_CONTINUE.png",
)
STRATEGIC_SEARCH_MERCHANT_STOP = Button(
    area=(443, 443, 463, 457),
    color=(94, 133, 74),
    button=(443, 443, 463, 457),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_MERCHANT_STOP.png",
)
STRATEGIC_SEARCH_POPUP_CHECK = Button(
    area=(370, 166, 566, 198),
    color=(150, 170, 209),
    button=(370, 166, 566, 198),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_POPUP_CHECK.png",
)
STRATEGIC_SEARCH_SCROLL_AREA = Button(
    area=(902, 277, 910, 470),
    color=(151, 145, 102),
    button=(902, 277, 910, 470),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_SCROLL_AREA.png",
)
STRATEGIC_SEARCH_SUBMIT_CHECK = Button(
    area=(473, 387, 553, 407),
    color=(137, 142, 155),
    button=(473, 387, 553, 407),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_SUBMIT_CHECK.png",
)
STRATEGIC_SEARCH_SUBMIT_OFF = Button(
    area=(443, 427, 463, 441),
    color=(95, 134, 74),
    button=(443, 427, 463, 441),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_SUBMIT_OFF.png",
)
STRATEGIC_SEARCH_SUBMIT_ON = Button(
    area=(516, 427, 536, 441),
    color=(94, 133, 73),
    button=(516, 427, 536, 441),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_SUBMIT_ON.png",
)
STRATEGIC_SEARCH_TAB_SECURED = Button(
    area=(562, 227, 718, 260),
    color=(86, 115, 182),
    button=(562, 227, 718, 260),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_TAB_SECURED.png",
)
STRATEGIC_SEARCH_ZONEMODE_RANDOM = Button(
    area=(747, 335, 767, 349),
    color=(95, 133, 73),
    button=(747, 335, 767, 349),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_ZONEMODE_RANDOM.png",
)
STRATEGIC_SEARCH_ZONEMODE_REPEAT = Button(
    area=(548, 335, 568, 349),
    color=(96, 134, 74),
    button=(548, 335, 568, 349),
    file="./assets/cn/os_handler/STRATEGIC_SEARCH_ZONEMODE_REPEAT.png",
)
TEMPLATE_STORAGE_ABYSSAL = Template(file="./assets/cn/os_handler/TEMPLATE_STORAGE_ABYSSAL.png")
TEMPLATE_STORAGE_COMBAT = Template(file="./assets/cn/os_handler/TEMPLATE_STORAGE_COMBAT.png")
TEMPLATE_STORAGE_LOGGER = Template(file="./assets/cn/os_handler/TEMPLATE_STORAGE_LOGGER.gif")
TEMPLATE_STORAGE_OBSCURE = Template(file="./assets/cn/os_handler/TEMPLATE_STORAGE_OBSCURE.png")
TEMPLATE_STORAGE_OFFENSE = Template(file="./assets/cn/os_handler/TEMPLATE_STORAGE_OFFENSE.png")
TEMPLATE_STORAGE_QUALITY_COMBAT = Template(file="./assets/cn/os_handler/TEMPLATE_STORAGE_QUALITY_COMBAT.png")
TEMPLATE_STORAGE_QUALITY_OFFENSE = Template(file="./assets/cn/os_handler/TEMPLATE_STORAGE_QUALITY_OFFENSE.png")
TEMPLATE_STORAGE_QUALITY_SURVIVAL = Template(file="./assets/cn/os_handler/TEMPLATE_STORAGE_QUALITY_SURVIVAL.png")
TEMPLATE_STORAGE_SURVIVAL = Template(file="./assets/cn/os_handler/TEMPLATE_STORAGE_SURVIVAL.png")
