from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE_STATUS_CF = Button(
    area=(260, 196, 276, 288),
    color=(255, 244, 134),
    button=(1138, 646, 1216, 682),
    file="./assets/cn/guild/BATTLE_STATUS_CF.png",
)
EXP_INFO_CF = Button(
    area=(138, 63, 148, 118),
    color=(255, 244, 134),
    button=(1138, 646, 1216, 682),
    file="./assets/cn/guild/EXP_INFO_CF.png",
)
GUILD_BOSS_AVAILABLE = Button(
    area=(1229, 614, 1242, 632),
    color=(58, 100, 61),
    button=(1229, 614, 1242, 632),
    file="./assets/cn/guild/GUILD_BOSS_AVAILABLE.png",
)
GUILD_BOSS_ENTER = Button(
    area=(1132, 642, 1261, 687),
    color=(71, 156, 246),
    button=(1132, 642, 1261, 687),
    file="./assets/cn/guild/GUILD_BOSS_ENTER.png",
)
GUILD_DISPATCH_CLOSE = Button(
    area=(1236, 102, 1266, 133),
    color=(88, 39, 38),
    button=(1236, 102, 1266, 133),
    file="./assets/cn/guild/GUILD_DISPATCH_CLOSE.png",
)
GUILD_DISPATCH_FLEET = Button(
    area=(982, 645, 1123, 670),
    color=(118, 126, 209),
    button=(982, 645, 1123, 670),
    file="./assets/cn/guild/GUILD_DISPATCH_FLEET.png",
)
GUILD_DISPATCH_FLEET_UNFILLED = Button(
    area=(982, 645, 1122, 670),
    color=(86, 93, 161),
    button=(982, 645, 1122, 670),
    file="./assets/cn/guild/GUILD_DISPATCH_FLEET_UNFILLED.png",
)
GUILD_DISPATCH_IN_PROGRESS = Button(
    area=(1089, 638, 1280, 653),
    color=(228, 163, 74),
    button=(1089, 638, 1280, 653),
    file="./assets/cn/guild/GUILD_DISPATCH_IN_PROGRESS.png",
)
GUILD_DISPATCH_QUICK = Button(
    area=(973, 639, 1113, 664),
    color=(121, 129, 209),
    button=(973, 639, 1113, 664),
    file="./assets/cn/guild/GUILD_DISPATCH_QUICK.png",
)
GUILD_DISPATCH_RECOMMEND = Button(
    area=(1197, 231, 1259, 287),
    color=(78, 112, 187),
    button=(1197, 231, 1259, 287),
    file="./assets/cn/guild/GUILD_DISPATCH_RECOMMEND.png",
)
GUILD_DISPATCH_RECOMMEND_2 = Button(
    area=(140, 432, 193, 488),
    color=(64, 101, 179),
    button=(140, 432, 193, 488),
    file="./assets/cn/guild/GUILD_DISPATCH_RECOMMEND_2.png",
)
GUILD_LOGISTICS_ENSURE_CHECK = Button(
    area=(390, 382, 516, 393),
    color=(155, 87, 90),
    button=(390, 382, 516, 393),
    file="./assets/cn/guild/GUILD_LOGISTICS_ENSURE_CHECK.png",
)
GUILD_MISSION = Button(
    area=(1068, 279, 1224, 320),
    color=(105, 124, 179),
    button=(1068, 279, 1224, 320),
    file="./assets/cn/guild/GUILD_MISSION.png",
)
GUILD_MISSION_CHOOSE = Button(
    area=(406, 194, 565, 235),
    color=(106, 107, 112),
    button=(406, 194, 565, 235),
    file="./assets/cn/guild/GUILD_MISSION_CHOOSE.png",
)
GUILD_MISSION_NEW = Button(
    area=(414, 199, 551, 230),
    color=(127, 128, 132),
    button=(414, 199, 551, 230),
    file="./assets/cn/guild/GUILD_MISSION_NEW.png",
)
GUILD_MISSION_SELECT = Button(
    area=(1023, 131, 1052, 160),
    color=(185, 75, 72),
    button=(912, 532, 975, 565),
    file="./assets/cn/guild/GUILD_MISSION_SELECT.png",
)
GUILD_OPERATIONS_ACTIVE_CHECK = Button(
    area=(967, 640, 1078, 667),
    color=(116, 123, 191),
    button=(967, 640, 1078, 667),
    file="./assets/cn/guild/GUILD_OPERATIONS_ACTIVE_CHECK.png",
)
GUILD_OPERATIONS_CLICK_SAFE_AREA = Button(
    area=(271, 680, 320, 704),
    color=(18, 21, 36),
    button=(271, 680, 320, 704),
    file="./assets/cn/guild/GUILD_OPERATIONS_CLICK_SAFE_AREA.png",
)
GUILD_OPERATIONS_INACTIVE_CHECK = Button(
    area=(192, 119, 240, 141),
    color=(3, 61, 26),
    button=(192, 119, 240, 141),
    file="./assets/cn/guild/GUILD_OPERATIONS_INACTIVE_CHECK.png",
)
GUILD_OPERATIONS_JOIN = Button(
    area=(939, 539, 1121, 579),
    color=(101, 112, 216),
    button=(939, 539, 1121, 579),
    file="./assets/cn/guild/GUILD_OPERATIONS_JOIN.png",
)
GUILD_OPERATIONS_MONTHLY_COUNT = Button(
    area=(1237, 500, 1278, 522),
    color=(74, 63, 77),
    button=(1237, 500, 1278, 522),
    file="./assets/cn/guild/GUILD_OPERATIONS_MONTHLY_COUNT.png",
)
GUILD_OPERATIONS_NEW = Button(
    area=(960, 542, 1036, 576),
    color=(107, 117, 214),
    button=(960, 542, 1036, 576),
    file="./assets/cn/guild/GUILD_OPERATIONS_NEW.png",
)
GUILD_OPERATIONS_SOLOMON = Button(
    area=(1125, 156, 1248, 181),
    color=(101, 102, 107),
    button=(1125, 153, 1280, 535),
    file="./assets/cn/guild/GUILD_OPERATIONS_SOLOMON.png",
)
GUILD_OPERATION_FUND_CHECK = Button(
    area=(1064, 481, 1265, 521),
    color=(64, 59, 75),
    button=(1064, 481, 1265, 521),
    file="./assets/cn/guild/GUILD_OPERATION_FUND_CHECK.png",
)
GUILD_RED_DOT = Button(
    area=(1250, 665, 1273, 688),
    color=(134, 86, 88),
    button=(1250, 665, 1273, 688),
    file="./assets/cn/guild/GUILD_RED_DOT.png",
)
GUILD_REPORT_AVAILABLE = Button(
    area=(117, 607, 435, 713),
    color=(75, 66, 72),
    button=(117, 607, 435, 713),
    file="./assets/cn/guild/GUILD_REPORT_AVAILABLE.png",
)
GUILD_REPORT_CLAIM = Button(
    area=(739, 595, 1078, 637),
    color=(85, 118, 217),
    button=(739, 595, 1078, 637),
    file="./assets/cn/guild/GUILD_REPORT_CLAIM.png",
)
GUILD_REPORT_CLAIMED = Button(
    area=(738, 595, 1078, 637),
    color=(124, 122, 124),
    button=(738, 595, 1078, 637),
    file="./assets/cn/guild/GUILD_REPORT_CLAIMED.png",
)
GUILD_REPORT_CLOSE = Button(
    area=(1059, 93, 1102, 136),
    color=(71, 31, 32),
    button=(1059, 93, 1102, 136),
    file="./assets/cn/guild/GUILD_REPORT_CLOSE.png",
)
GUILD_SUPPLY = Button(
    area=(1077, 617, 1233, 658),
    color=(84, 104, 154),
    button=(1077, 617, 1233, 658),
    file="./assets/cn/guild/GUILD_SUPPLY.png",
)
OCR_GUILD_EXCHANGE_LIMIT = Button(
    area=(960, 383, 975, 403),
    color=(59, 46, 47),
    button=(960, 383, 975, 403),
    file="./assets/cn/guild/OCR_GUILD_EXCHANGE_LIMIT.png",
)
OCR_GUILD_OPERATIONS_PROGRESS = Button(
    area=(1064, 501, 1114, 521),
    color=(89, 94, 107),
    button=(1064, 501, 1114, 521),
    file="./assets/cn/guild/OCR_GUILD_OPERATIONS_PROGRESS.png",
)
