from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ALBION_OCR_PT = Button(
    area=(1166, 604, 1279, 635),
    color=(157, 139, 116),
    button=(1166, 604, 1279, 635),
    file="./assets/cn/raid/ALBION_OCR_PT.png",
)
ALBION_OCR_REMAIN_EASY = Button(
    area=(1147, 505, 1204, 531),
    color=(175, 143, 108),
    button=(1147, 505, 1204, 531),
    file="./assets/cn/raid/ALBION_OCR_REMAIN_EASY.png",
)
ALBION_OCR_REMAIN_HARD = Button(
    area=(1152, 335, 1209, 363),
    color=(177, 146, 108),
    button=(1152, 335, 1209, 363),
    file="./assets/cn/raid/ALBION_OCR_REMAIN_HARD.png",
)
ALBION_OCR_REMAIN_NORMAL = Button(
    area=(1188, 423, 1248, 448),
    color=(175, 144, 107),
    button=(1188, 423, 1248, 448),
    file="./assets/cn/raid/ALBION_OCR_REMAIN_NORMAL.png",
)
ALBION_RAID_EASY = Button(
    area=(1014, 504, 1066, 533),
    color=(190, 166, 135),
    button=(1014, 504, 1066, 533),
    file="./assets/cn/raid/ALBION_RAID_EASY.png",
)
ALBION_RAID_HARD = Button(
    area=(1015, 336, 1072, 363),
    color=(183, 158, 129),
    button=(1015, 336, 1072, 363),
    file="./assets/cn/raid/ALBION_RAID_HARD.png",
)
ALBION_RAID_NORMAL = Button(
    area=(1056, 421, 1109, 451),
    color=(188, 163, 133),
    button=(1056, 421, 1109, 451),
    file="./assets/cn/raid/ALBION_RAID_NORMAL.png",
)
BRISTOL_OCR_REMAIN_EASY = Button(
    area=(1135, 536, 1195, 554),
    color=(89, 137, 227),
    button=(1135, 536, 1195, 554),
    file="./assets/cn/raid/BRISTOL_OCR_REMAIN_EASY.png",
)
BRISTOL_OCR_REMAIN_HARD = Button(
    area=(1163, 292, 1223, 310),
    color=(95, 137, 212),
    button=(1163, 292, 1223, 310),
    file="./assets/cn/raid/BRISTOL_OCR_REMAIN_HARD.png",
)
BRISTOL_OCR_REMAIN_NORMAL = Button(
    area=(1089, 414, 1148, 432),
    color=(93, 138, 222),
    button=(1089, 414, 1148, 432),
    file="./assets/cn/raid/BRISTOL_OCR_REMAIN_NORMAL.png",
)
BRISTOL_RAID_EASY = Button(
    area=(1151, 490, 1203, 528),
    color=(141, 164, 177),
    button=(1151, 490, 1203, 528),
    file="./assets/cn/raid/BRISTOL_RAID_EASY.png",
)
BRISTOL_RAID_HARD = Button(
    area=(1167, 246, 1220, 285),
    color=(136, 160, 173),
    button=(1167, 246, 1220, 285),
    file="./assets/cn/raid/BRISTOL_RAID_HARD.png",
)
BRISTOL_RAID_NORMAL = Button(
    area=(1098, 367, 1150, 404),
    color=(129, 152, 165),
    button=(1098, 367, 1150, 404),
    file="./assets/cn/raid/BRISTOL_RAID_NORMAL.png",
)
CHANGWU_OCR_PT = Button(
    area=(1174, 603, 1280, 632),
    color=(183, 118, 101),
    button=(1174, 603, 1280, 632),
    file="./assets/cn/raid/CHANGWU_OCR_PT.png",
)
CHANGWU_OCR_REMAIN_EASY = Button(
    area=(1057, 565, 1116, 585),
    color=(96, 83, 81),
    button=(1057, 565, 1116, 585),
    file="./assets/cn/raid/CHANGWU_OCR_REMAIN_EASY.png",
)
CHANGWU_OCR_REMAIN_EX = Button(
    area=(1138, 26, 1185, 49),
    color=(213, 128, 103),
    button=(1138, 26, 1185, 49),
    file="./assets/cn/raid/CHANGWU_OCR_REMAIN_EX.png",
)
CHANGWU_OCR_REMAIN_HARD = Button(
    area=(1169, 409, 1229, 429),
    color=(100, 86, 82),
    button=(1169, 409, 1229, 429),
    file="./assets/cn/raid/CHANGWU_OCR_REMAIN_HARD.png",
)
CHANGWU_OCR_REMAIN_NORMAL = Button(
    area=(1112, 487, 1170, 506),
    color=(100, 87, 84),
    button=(1112, 487, 1170, 506),
    file="./assets/cn/raid/CHANGWU_OCR_REMAIN_NORMAL.png",
)
CHANGWU_RAID_EASY = Button(
    area=(976, 559, 1032, 590),
    color=(144, 130, 122),
    button=(976, 559, 1032, 590),
    file="./assets/cn/raid/CHANGWU_RAID_EASY.png",
)
CHANGWU_RAID_EX = Button(
    area=(1135, 296, 1209, 331),
    color=(151, 138, 125),
    button=(1135, 296, 1209, 331),
    file="./assets/cn/raid/CHANGWU_RAID_EX.png",
)
CHANGWU_RAID_HARD = Button(
    area=(1087, 403, 1146, 433),
    color=(154, 139, 130),
    button=(1087, 403, 1146, 433),
    file="./assets/cn/raid/CHANGWU_RAID_HARD.png",
)
CHANGWU_RAID_NORMAL = Button(
    area=(1032, 480, 1091, 511),
    color=(144, 130, 122),
    button=(1032, 480, 1091, 511),
    file="./assets/cn/raid/CHANGWU_RAID_NORMAL.png",
)
CHIENWU_OCR_PT = Button(
    area=(1166, 604, 1279, 632),
    color=(126, 40, 47),
    button=(1166, 604, 1279, 632),
    file="./assets/cn/raid/CHIENWU_OCR_PT.png",
)
CHIENWU_OCR_REMAIN_EASY = Button(
    area=(1111, 528, 1163, 549),
    color=(174, 153, 133),
    button=(1111, 528, 1163, 549),
    file="./assets/cn/raid/CHIENWU_OCR_REMAIN_EASY.png",
)
CHIENWU_OCR_REMAIN_EX = Button(
    area=(1086, 16, 1152, 44),
    color=(90, 39, 34),
    button=(1086, 16, 1152, 44),
    file="./assets/cn/raid/CHIENWU_OCR_REMAIN_EX.png",
)
CHIENWU_OCR_REMAIN_HARD = Button(
    area=(1106, 390, 1158, 411),
    color=(174, 153, 133),
    button=(1106, 390, 1158, 411),
    file="./assets/cn/raid/CHIENWU_OCR_REMAIN_HARD.png",
)
CHIENWU_OCR_REMAIN_NORMAL = Button(
    area=(1144, 459, 1196, 480),
    color=(174, 153, 133),
    button=(1144, 459, 1196, 480),
    file="./assets/cn/raid/CHIENWU_OCR_REMAIN_NORMAL.png",
)
CHIENWU_RAID_EASY = Button(
    area=(1056, 528, 1095, 550),
    color=(221, 142, 125),
    button=(1056, 528, 1095, 550),
    file="./assets/cn/raid/CHIENWU_RAID_EASY.png",
)
CHIENWU_RAID_EX = Button(
    area=(1068, 251, 1125, 286),
    color=(199, 97, 95),
    button=(1068, 251, 1125, 286),
    file="./assets/cn/raid/CHIENWU_RAID_EX.png",
)
CHIENWU_RAID_HARD = Button(
    area=(1049, 390, 1091, 411),
    color=(219, 135, 119),
    button=(1049, 390, 1091, 411),
    file="./assets/cn/raid/CHIENWU_RAID_HARD.png",
)
CHIENWU_RAID_NORMAL = Button(
    area=(1087, 459, 1129, 481),
    color=(221, 143, 126),
    button=(1087, 459, 1129, 481),
    file="./assets/cn/raid/CHIENWU_RAID_NORMAL.png",
)
ESSEX_OCR_REMAIN_EASY = Button(
    area=(1071, 503, 1121, 518),
    color=(97, 130, 255),
    button=(1071, 503, 1121, 518),
    file="./assets/cn/raid/ESSEX_OCR_REMAIN_EASY.png",
)
ESSEX_OCR_REMAIN_HARD = Button(
    area=(1088, 273, 1138, 287),
    color=(96, 126, 255),
    button=(1088, 273, 1138, 287),
    file="./assets/cn/raid/ESSEX_OCR_REMAIN_HARD.png",
)
ESSEX_OCR_REMAIN_NORMAL = Button(
    area=(1049, 387, 1099, 402),
    color=(97, 129, 255),
    button=(1049, 387, 1099, 402),
    file="./assets/cn/raid/ESSEX_OCR_REMAIN_NORMAL.png",
)
ESSEX_RAID_EASY = Button(
    area=(1136, 501, 1199, 544),
    color=(127, 177, 243),
    button=(1136, 501, 1199, 544),
    file="./assets/cn/raid/ESSEX_RAID_EASY.png",
)
ESSEX_RAID_HARD = Button(
    area=(1155, 271, 1215, 313),
    color=(131, 179, 241),
    button=(1155, 271, 1215, 313),
    file="./assets/cn/raid/ESSEX_RAID_HARD.png",
)
ESSEX_RAID_NORMAL = Button(
    area=(1111, 385, 1176, 428),
    color=(123, 173, 242),
    button=(1111, 385, 1176, 428),
    file="./assets/cn/raid/ESSEX_RAID_NORMAL.png",
)
GORIZIA_OCR_PT = Button(
    area=(1160, 605, 1280, 637),
    color=(216, 220, 171),
    button=(1160, 605, 1280, 637),
    file="./assets/cn/raid/GORIZIA_OCR_PT.png",
)
GORIZIA_OCR_REMAIN_EASY = Button(
    area=(1138, 513, 1194, 539),
    color=(205, 208, 201),
    button=(1138, 513, 1194, 539),
    file="./assets/cn/raid/GORIZIA_OCR_REMAIN_EASY.png",
)
GORIZIA_OCR_REMAIN_EX = Button(
    area=(1082, 16, 1151, 42),
    color=(80, 93, 94),
    button=(1082, 16, 1151, 42),
    file="./assets/cn/raid/GORIZIA_OCR_REMAIN_EX.png",
)
GORIZIA_OCR_REMAIN_HARD = Button(
    area=(1138, 346, 1195, 372),
    color=(206, 208, 202),
    button=(1138, 346, 1195, 372),
    file="./assets/cn/raid/GORIZIA_OCR_REMAIN_HARD.png",
)
GORIZIA_OCR_REMAIN_NORMAL = Button(
    area=(1174, 428, 1231, 455),
    color=(208, 210, 204),
    button=(1174, 428, 1231, 455),
    file="./assets/cn/raid/GORIZIA_OCR_REMAIN_NORMAL.png",
)
GORIZIA_RAID_EASY = Button(
    area=(1071, 515, 1118, 538),
    color=(183, 185, 177),
    button=(1071, 515, 1118, 538),
    file="./assets/cn/raid/GORIZIA_RAID_EASY.png",
)
GORIZIA_RAID_EX = Button(
    area=(978, 210, 1050, 242),
    color=(166, 186, 137),
    button=(978, 210, 1050, 242),
    file="./assets/cn/raid/GORIZIA_RAID_EX.png",
)
GORIZIA_RAID_HARD = Button(
    area=(1072, 348, 1118, 370),
    color=(169, 172, 162),
    button=(1072, 348, 1118, 370),
    file="./assets/cn/raid/GORIZIA_RAID_HARD.png",
)
GORIZIA_RAID_NORMAL = Button(
    area=(1108, 430, 1153, 453),
    color=(177, 179, 171),
    button=(1108, 430, 1153, 453),
    file="./assets/cn/raid/GORIZIA_RAID_NORMAL.png",
)
HUANCHANG_OCR_PT = Button(
    area=(1166, 604, 1279, 635),
    color=(143, 143, 144),
    button=(1166, 604, 1279, 635),
    file="./assets/cn/raid/HUANCHANG_OCR_PT.png",
)
HUANCHANG_OCR_REMAIN_EASY = Button(
    area=(961, 548, 983, 567),
    color=(136, 134, 134),
    button=(961, 548, 983, 567),
    file="./assets/cn/raid/HUANCHANG_OCR_REMAIN_EASY.png",
)
HUANCHANG_OCR_REMAIN_EX = Button(
    area=(1082, 16, 1151, 42),
    color=(54, 54, 54),
    button=(1082, 16, 1151, 42),
    file="./assets/cn/raid/HUANCHANG_OCR_REMAIN_EX.png",
)
HUANCHANG_OCR_REMAIN_HARD = Button(
    area=(1146, 548, 1168, 567),
    color=(159, 157, 158),
    button=(1146, 548, 1168, 567),
    file="./assets/cn/raid/HUANCHANG_OCR_REMAIN_HARD.png",
)
HUANCHANG_OCR_REMAIN_NORMAL = Button(
    area=(1054, 548, 1076, 567),
    color=(136, 136, 135),
    button=(1054, 548, 1076, 567),
    file="./assets/cn/raid/HUANCHANG_OCR_REMAIN_NORMAL.png",
)
HUANCHANG_RAID_EASY = Button(
    area=(951, 487, 995, 536),
    color=(100, 100, 99),
    button=(951, 487, 995, 536),
    file="./assets/cn/raid/HUANCHANG_RAID_EASY.png",
)
HUANCHANG_RAID_EX = Button(
    area=(1111, 352, 1170, 381),
    color=(126, 160, 161),
    button=(1111, 352, 1170, 381),
    file="./assets/cn/raid/HUANCHANG_RAID_EX.png",
)
HUANCHANG_RAID_HARD = Button(
    area=(1135, 487, 1178, 536),
    color=(118, 118, 119),
    button=(1135, 487, 1178, 536),
    file="./assets/cn/raid/HUANCHANG_RAID_HARD.png",
)
HUANCHANG_RAID_NORMAL = Button(
    area=(1044, 487, 1088, 536),
    color=(106, 108, 108),
    button=(1044, 487, 1088, 536),
    file="./assets/cn/raid/HUANCHANG_RAID_NORMAL.png",
)
IRIS_OCR_PT = Button(
    area=(1140, 607, 1280, 641),
    color=(40, 43, 36),
    button=(1140, 607, 1280, 641),
    file="./assets/cn/raid/IRIS_OCR_PT.png",
)
IRIS_OCR_REMAIN_EASY = Button(
    area=(1047, 514, 1103, 534),
    color=(50, 49, 44),
    button=(1047, 514, 1103, 534),
    file="./assets/cn/raid/IRIS_OCR_REMAIN_EASY.png",
)
IRIS_OCR_REMAIN_HARD = Button(
    area=(1166, 312, 1221, 332),
    color=(48, 44, 38),
    button=(1166, 312, 1221, 332),
    file="./assets/cn/raid/IRIS_OCR_REMAIN_HARD.png",
)
IRIS_OCR_REMAIN_NORMAL = Button(
    area=(1130, 413, 1185, 433),
    color=(45, 44, 38),
    button=(1130, 413, 1185, 433),
    file="./assets/cn/raid/IRIS_OCR_REMAIN_NORMAL.png",
)
IRIS_RAID_EASY = Button(
    area=(968, 504, 1023, 531),
    color=(95, 95, 91),
    button=(968, 504, 1023, 531),
    file="./assets/cn/raid/IRIS_RAID_EASY.png",
)
IRIS_RAID_HARD = Button(
    area=(1089, 302, 1143, 329),
    color=(106, 105, 101),
    button=(1089, 302, 1143, 329),
    file="./assets/cn/raid/IRIS_RAID_HARD.png",
)
IRIS_RAID_NORMAL = Button(
    area=(1052, 403, 1107, 430),
    color=(101, 100, 97),
    button=(1052, 403, 1107, 430),
    file="./assets/cn/raid/IRIS_RAID_NORMAL.png",
)
KUYBYSHEY_OCR_PT = Button(
    area=(1180, 606, 1280, 634),
    color=(120, 140, 155),
    button=(1180, 606, 1280, 634),
    file="./assets/cn/raid/KUYBYSHEY_OCR_PT.png",
)
KUYBYSHEY_OCR_REMAIN_EASY = Button(
    area=(1138, 504, 1198, 528),
    color=(82, 91, 105),
    button=(1138, 504, 1198, 528),
    file="./assets/cn/raid/KUYBYSHEY_OCR_REMAIN_EASY.png",
)
KUYBYSHEY_OCR_REMAIN_EX = Button(
    area=(1103, 17, 1151, 41),
    color=(53, 59, 71),
    button=(1103, 17, 1151, 41),
    file="./assets/cn/raid/KUYBYSHEY_OCR_REMAIN_EX.png",
)
KUYBYSHEY_OCR_REMAIN_HARD = Button(
    area=(1138, 347, 1198, 371),
    color=(82, 91, 105),
    button=(1138, 347, 1198, 371),
    file="./assets/cn/raid/KUYBYSHEY_OCR_REMAIN_HARD.png",
)
KUYBYSHEY_OCR_REMAIN_NORMAL = Button(
    area=(1107, 426, 1167, 450),
    color=(82, 91, 105),
    button=(1107, 426, 1167, 450),
    file="./assets/cn/raid/KUYBYSHEY_OCR_REMAIN_NORMAL.png",
)
KUYBYSHEY_RAID_EASY = Button(
    area=(1073, 503, 1124, 529),
    color=(84, 93, 107),
    button=(1073, 503, 1124, 529),
    file="./assets/cn/raid/KUYBYSHEY_RAID_EASY.png",
)
KUYBYSHEY_RAID_EX = Button(
    area=(1082, 189, 1146, 217),
    color=(160, 174, 191),
    button=(1082, 189, 1146, 217),
    file="./assets/cn/raid/KUYBYSHEY_RAID_EX.png",
)
KUYBYSHEY_RAID_HARD = Button(
    area=(1073, 345, 1125, 371),
    color=(91, 100, 114),
    button=(1073, 345, 1125, 371),
    file="./assets/cn/raid/KUYBYSHEY_RAID_HARD.png",
)
KUYBYSHEY_RAID_NORMAL = Button(
    area=(1045, 423, 1097, 451),
    color=(86, 95, 109),
    button=(1045, 423, 1097, 451),
    file="./assets/cn/raid/KUYBYSHEY_RAID_NORMAL.png",
)
RAID_FLEET_PREPARATION = Button(
    area=(983, 577, 1181, 638),
    color=(236, 188, 115),
    button=(983, 577, 1181, 638),
    file="./assets/cn/raid/RAID_FLEET_PREPARATION.png",
)
RAID_REWARDS = Button(
    area=(836, 127, 900, 169),
    color=(217, 103, 98),
    button=(836, 127, 900, 169),
    file="./assets/cn/raid/RAID_REWARDS.png",
)
RPG_BACK = Button(
    area=(40, 30, 59, 57),
    color=(154, 127, 105),
    button=(40, 30, 59, 57),
    file="./assets/cn/raid/RPG_BACK.png",
)
RPG_GOTO_STAGE = Button(
    area=(55, 495, 80, 520),
    color=(174, 168, 160),
    button=(55, 495, 80, 520),
    file="./assets/cn/raid/RPG_GOTO_STAGE.png",
)
RPG_GOTO_STORY = Button(
    area=(59, 491, 84, 516),
    color=(182, 122, 105),
    button=(59, 491, 84, 516),
    file="./assets/cn/raid/RPG_GOTO_STORY.png",
)
RPG_HOME = Button(
    area=(1222, 29, 1240, 51),
    color=(197, 181, 158),
    button=(1222, 29, 1240, 51),
    file="./assets/cn/raid/RPG_HOME.png",
)
RPG_LEAVE_CITY = Button(
    area=(688, 642, 711, 664),
    color=(158, 130, 109),
    button=(688, 642, 711, 664),
    file="./assets/cn/raid/RPG_LEAVE_CITY.png",
)
RPG_RAID_EASY = Button(
    area=(149, 561, 179, 591),
    color=(152, 57, 59),
    button=(149, 561, 179, 591),
    file="./assets/cn/raid/RPG_RAID_EASY.png",
)
RPG_RAID_EX = Button(
    area=(979, 223, 999, 258),
    color=(231, 198, 84),
    button=(979, 223, 999, 258),
    file="./assets/cn/raid/RPG_RAID_EX.png",
)
RPG_RAID_HARD = Button(
    area=(475, 108, 505, 138),
    color=(97, 59, 59),
    button=(475, 108, 505, 138),
    file="./assets/cn/raid/RPG_RAID_HARD.png",
)
RPG_RAID_NORMAL = Button(
    area=(313, 259, 343, 289),
    color=(147, 61, 62),
    button=(313, 259, 343, 289),
    file="./assets/cn/raid/RPG_RAID_NORMAL.png",
)
RPG_STATUS_POPUP = Button(
    area=(1120, 97, 1144, 121),
    color=(158, 165, 176),
    button=(1120, 97, 1144, 121),
    file="./assets/cn/raid/RPG_STATUS_POPUP.png",
)
SURUGA_OCR_REMAIN_EASY = Button(
    area=(1093, 549, 1141, 563),
    color=(161, 161, 161),
    button=(1093, 549, 1141, 563),
    file="./assets/cn/raid/SURUGA_OCR_REMAIN_EASY.png",
)
SURUGA_OCR_REMAIN_HARD = Button(
    area=(1071, 318, 1118, 332),
    color=(158, 158, 159),
    button=(1071, 318, 1118, 332),
    file="./assets/cn/raid/SURUGA_OCR_REMAIN_HARD.png",
)
SURUGA_OCR_REMAIN_NORMAL = Button(
    area=(1137, 426, 1185, 439),
    color=(164, 164, 164),
    button=(1137, 426, 1185, 439),
    file="./assets/cn/raid/SURUGA_OCR_REMAIN_NORMAL.png",
)
SURUGA_RAID_EASY = Button(
    area=(1143, 536, 1194, 580),
    color=(88, 88, 89),
    button=(1143, 536, 1194, 580),
    file="./assets/cn/raid/SURUGA_RAID_EASY.png",
)
SURUGA_RAID_HARD = Button(
    area=(1120, 304, 1171, 349),
    color=(87, 88, 88),
    button=(1120, 304, 1171, 349),
    file="./assets/cn/raid/SURUGA_RAID_HARD.png",
)
SURUGA_RAID_NORMAL = Button(
    area=(1187, 411, 1238, 457),
    color=(89, 89, 89),
    button=(1187, 411, 1238, 457),
    file="./assets/cn/raid/SURUGA_RAID_NORMAL.png",
)
TICKET_USE_CANCEL = Button(
    area=(404, 483, 576, 539),
    color=(169, 171, 174),
    button=(404, 483, 576, 539),
    file="./assets/cn/raid/TICKET_USE_CANCEL.png",
)
TICKET_USE_CONFIRM = Button(
    area=(739, 514, 802, 546),
    color=(153, 182, 218),
    button=(704, 483, 876, 540),
    file="./assets/cn/raid/TICKET_USE_CONFIRM.png",
)
