from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

MAIN_OCR_COIN = Button(
    area=(716, 24, 780, 49),
    color=(119, 126, 145),
    button=(716, 24, 780, 49),
    file="./assets/cn/shipyard/MAIN_OCR_COIN.png",
)
SHIPYARD_CONFIRM_DEV = Button(
    area=(1074, 497, 1152, 524),
    color=(106, 144, 211),
    button=(1074, 497, 1152, 524),
    file="./assets/cn/shipyard/SHIPYARD_CONFIRM_DEV.png",
)
SHIPYARD_CONFIRM_FATE = Button(
    area=(1145, 523, 1221, 558),
    color=(109, 149, 203),
    button=(1145, 523, 1221, 558),
    file="./assets/cn/shipyard/SHIPYARD_CONFIRM_FATE.png",
)
SHIPYARD_GO_FATE = Button(
    area=(943, 508, 1031, 531),
    color=(169, 165, 54),
    button=(1080, 415, 1147, 505),
    file="./assets/cn/shipyard/SHIPYARD_GO_FATE.png",
)
SHIPYARD_IN_DEV = Button(
    area=(5, 118, 90, 151),
    color=(111, 131, 185),
    button=(5, 118, 90, 151),
    file="./assets/cn/shipyard/SHIPYARD_IN_DEV.png",
)
SHIPYARD_IN_FATE = Button(
    area=(924, 122, 1025, 146),
    color=(186, 181, 81),
    button=(924, 122, 1025, 146),
    file="./assets/cn/shipyard/SHIPYARD_IN_FATE.png",
)
SHIPYARD_LEVEL_NOT_ENOUGH_DEV = Button(
    area=(1230, 155, 1273, 171),
    color=(125, 142, 174),
    button=(1230, 155, 1273, 171),
    file="./assets/cn/shipyard/SHIPYARD_LEVEL_NOT_ENOUGH_DEV.png",
)
SHIPYARD_LEVEL_NOT_ENOUGH_FATE = Button(
    area=(1040, 160, 1147, 174),
    color=(97, 96, 97),
    button=(1040, 160, 1147, 174),
    file="./assets/cn/shipyard/SHIPYARD_LEVEL_NOT_ENOUGH_FATE.png",
)
SHIPYARD_MINUS_DEV = Button(
    area=(1049, 429, 1084, 463),
    color=(73, 126, 194),
    button=(1049, 429, 1084, 463),
    file="./assets/cn/shipyard/SHIPYARD_MINUS_DEV.png",
)
SHIPYARD_MINUS_FATE = Button(
    area=(1028, 453, 1063, 487),
    color=(72, 125, 193),
    button=(1028, 453, 1063, 487),
    file="./assets/cn/shipyard/SHIPYARD_MINUS_FATE.png",
)
SHIPYARD_PLUS_DEV = Button(
    area=(1149, 429, 1184, 462),
    color=(79, 130, 197),
    button=(1149, 429, 1184, 462),
    file="./assets/cn/shipyard/SHIPYARD_PLUS_DEV.png",
)
SHIPYARD_PLUS_FATE = Button(
    area=(1129, 453, 1164, 487),
    color=(80, 130, 198),
    button=(1129, 453, 1164, 487),
    file="./assets/cn/shipyard/SHIPYARD_PLUS_FATE.png",
)
SHIPYARD_PROGRESS_DEV = Button(
    area=(1184, 145, 1273, 175),
    color=(80, 97, 142),
    button=(1184, 145, 1273, 175),
    file="./assets/cn/shipyard/SHIPYARD_PROGRESS_DEV.png",
)
SHIPYARD_PROGRESS_FATE = Button(
    area=(1141, 153, 1278, 190),
    color=(82, 85, 89),
    button=(1141, 153, 1278, 190),
    file="./assets/cn/shipyard/SHIPYARD_PROGRESS_FATE.png",
)
SHIPYARD_RESEARCH_COMPLETE = Button(
    area=(548, 498, 740, 531),
    color=(214, 142, 124),
    button=(548, 498, 740, 531),
    file="./assets/cn/shipyard/SHIPYARD_RESEARCH_COMPLETE.png",
)
SHIPYARD_RESEARCH_INCOMPLETE = Button(
    area=(616, 490, 740, 531),
    color=(229, 192, 121),
    button=(616, 490, 740, 531),
    file="./assets/cn/shipyard/SHIPYARD_RESEARCH_INCOMPLETE.png",
)
SHIPYARD_RESEARCH_IN_PROGRESS = Button(
    area=(465, 479, 482, 501),
    color=(105, 135, 173),
    button=(465, 479, 482, 501),
    file="./assets/cn/shipyard/SHIPYARD_RESEARCH_IN_PROGRESS.png",
)
SHIPYARD_SERIES_SELECT_CHECK = Button(
    area=(32, 62, 53, 100),
    color=(9, 61, 190),
    button=(32, 62, 53, 100),
    file="./assets/cn/shipyard/SHIPYARD_SERIES_SELECT_CHECK.png",
)
SHIPYARD_SERIES_SELECT_ENTER = Button(
    area=(33, 659, 161, 701),
    color=(91, 110, 155),
    button=(33, 659, 161, 701),
    file="./assets/cn/shipyard/SHIPYARD_SERIES_SELECT_ENTER.png",
)
SHIPYARD_TOTAL_DEV = Button(
    area=(1086, 429, 1147, 463),
    color=(39, 46, 55),
    button=(1086, 429, 1147, 463),
    file="./assets/cn/shipyard/SHIPYARD_TOTAL_DEV.png",
)
SHIPYARD_TOTAL_FATE = Button(
    area=(1067, 457, 1126, 484),
    color=(43, 50, 59),
    button=(1067, 457, 1126, 484),
    file="./assets/cn/shipyard/SHIPYARD_TOTAL_FATE.png",
)
