from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DAILY_ACTIVE = Button(
    area=(673, 357, 705, 396),
    color=(5, 9, 10),
    button=(673, 357, 705, 396),
    file="./assets/cn/daily/DAILY_ACTIVE.png",
)
DAILY_ENTER = Button(
    area=(534, 118, 744, 645),
    color=(136, 166, 185),
    button=(534, 118, 744, 645),
    file="./assets/cn/daily/DAILY_ENTER.png",
)
DAILY_ENTER_CHECK = Button(
    area=(1222, 141, 1229, 150),
    color=(247, 209, 66),
    button=(1222, 141, 1229, 150),
    file="./assets/cn/daily/DAILY_ENTER_CHECK.png",
)
DAILY_FLEET_NEXT = Button(
    area=(914, 325, 931, 354),
    color=(86, 115, 149),
    button=(914, 325, 931, 354),
    file="./assets/cn/daily/DAILY_FLEET_NEXT.png",
)
DAILY_FLEET_PREV = Button(
    area=(36, 325, 53, 354),
    color=(103, 130, 163),
    button=(36, 325, 53, 354),
    file="./assets/cn/daily/DAILY_FLEET_PREV.png",
)
DAILY_LOCKED = Button(
    area=(710, 359, 748, 409),
    color=(24, 29, 29),
    button=(710, 359, 748, 409),
    file="./assets/cn/daily/DAILY_LOCKED.png",
)
DAILY_MISSION_1 = Button(
    area=(482, 140, 701, 255),
    color=(58, 80, 123),
    button=(482, 140, 701, 255),
    file="./assets/cn/daily/DAILY_MISSION_1.png",
)
DAILY_MISSION_2 = Button(
    area=(482, 300, 701, 415),
    color=(61, 84, 128),
    button=(482, 300, 701, 415),
    file="./assets/cn/daily/DAILY_MISSION_2.png",
)
DAILY_MISSION_3 = Button(
    area=(482, 460, 701, 575),
    color=(75, 106, 146),
    button=(482, 460, 701, 575),
    file="./assets/cn/daily/DAILY_MISSION_3.png",
)
DAILY_NEXT = Button(
    area=(821, 161, 996, 604),
    color=(71, 48, 43),
    button=(821, 161, 996, 604),
    file="./assets/cn/daily/DAILY_NEXT.png",
)
DAILY_NORMAL_RUN = Button(
    area=(409, 295, 560, 349),
    color=(244, 180, 106),
    button=(409, 295, 560, 349),
    file="./assets/cn/daily/DAILY_NORMAL_RUN.png",
)
DAILY_PREV = Button(
    area=(282, 163, 456, 600),
    color=(60, 73, 71),
    button=(282, 163, 456, 600),
    file="./assets/cn/daily/DAILY_PREV.png",
)
DAILY_SKIP = Button(
    area=(1003, 295, 1102, 349),
    color=(123, 160, 209),
    button=(1003, 295, 1102, 349),
    file="./assets/cn/daily/DAILY_SKIP.png",
)
ENTRANCE_EMERGENCY_MODULE_DEVELOPMENT = Button(
    area=(606, 246, 673, 293),
    color=(198, 178, 199),
    button=(606, 246, 673, 293),
    file="./assets/cn/daily/ENTRANCE_EMERGENCY_MODULE_DEVELOPMENT.png",
)
OCR_DAILY_FLEET_INDEX = Button(
    area=(525, 605, 561, 667),
    color=(60, 90, 139),
    button=(525, 605, 561, 667),
    file="./assets/cn/daily/OCR_DAILY_FLEET_INDEX.png",
)
OCR_REMAIN = Button(
    area=(526, 114, 546, 144),
    color=(94, 132, 164),
    button=(526, 114, 546, 144),
    file="./assets/cn/daily/OCR_REMAIN.png",
)
