from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ESCORT_CHECK = Button(
    area=(118, 15, 227, 40),
    color=(155, 171, 209),
    button=(118, 15, 227, 40),
    file="./assets/cn/event/ESCORT_CHECK.png",
)
ESCORT_HARD_ENTRANCE = Button(
    area=(118, 15, 227, 40),
    color=(155, 171, 209),
    button=(745, 284, 886, 392),
    file="./assets/cn/event/ESCORT_HARD_ENTRANCE.png",
)
ESCORT_REMAIN = Button(
    area=(55, 673, 135, 694),
    color=(68, 96, 85),
    button=(55, 673, 135, 694),
    file="./assets/cn/event/ESCORT_REMAIN.png",
)
MAIN_GOTO_ESCORT = Button(
    area=(609, 265, 654, 307),
    color=(216, 184, 171),
    button=(609, 265, 654, 307),
    file="./assets/cn/event/MAIN_GOTO_ESCORT.png",
)
