from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

OS_SHOP_CHECK = Button(
    area=(346, 160, 361, 183),
    color=(22, 50, 117),
    button=(346, 160, 361, 183),
    file="./assets/cn/os_shop/OS_SHOP_CHECK.png",
)
OS_SHOP_PURPLE_COINS = Button(
    area=(1043, 155, 1178, 189),
    color=(28, 45, 96),
    button=(1043, 155, 1178, 189),
    file="./assets/cn/os_shop/OS_SHOP_PURPLE_COINS.png",
)
OS_SHOP_SAFE_AREA = Button(
    area=(1130, 196, 1172, 488),
    color=(20, 42, 102),
    button=(1130, 196, 1172, 488),
    file="./assets/cn/os_shop/OS_SHOP_SAFE_AREA.png",
)
OS_SHOP_SCROLL_AREA = Button(
    area=(1176, 210, 1180, 720),
    color=(255, 255, 255),
    button=(1176, 210, 1180, 720),
    file="./assets/cn/os_shop/OS_SHOP_SCROLL_AREA.png",
)
PORT_SUPPLY_CHECK = Button(
    area=(127, 16, 180, 41),
    color=(146, 163, 202),
    button=(127, 16, 180, 41),
    file="./assets/cn/os_shop/PORT_SUPPLY_CHECK.png",
)
SHOP_BUY_CONFIRM = Button(
    area=(704, 483, 876, 540),
    color=(93, 142, 204),
    button=(704, 483, 876, 540),
    file="./assets/cn/os_shop/SHOP_BUY_CONFIRM.png",
)
SHOP_PURPLE_COINS = Button(
    area=(325, 110, 415, 133),
    color=(97, 100, 108),
    button=(325, 110, 415, 133),
    file="./assets/cn/os_shop/SHOP_PURPLE_COINS.png",
)
SHOP_YELLOW_COINS = Button(
    area=(1038, 27, 1128, 48),
    color=(71, 74, 76),
    button=(1038, 27, 1128, 48),
    file="./assets/cn/os_shop/SHOP_YELLOW_COINS.png",
)
