from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

DOSSIER_REWARD_CHECK = Button(
    area=(120, 14, 231, 40),
    color=(176, 159, 160),
    button=(120, 14, 231, 40),
    file="./assets/cn/meta_reward/DOSSIER_REWARD_CHECK.png",
)
DOSSIER_REWARD_ENTER = Button(
    area=(244, 645, 404, 709),
    color=(104, 87, 80),
    button=(244, 645, 404, 709),
    file="./assets/cn/meta_reward/DOSSIER_REWARD_ENTER.png",
)
DOSSIER_REWARD_RECEIVE = Button(
    area=(426, 617, 432, 628),
    color=(214, 117, 103),
    button=(320, 622, 428, 651),
    file="./assets/cn/meta_reward/DOSSIER_REWARD_RECEIVE.png",
)
META_REWARD_NOTICE = Button(
    area=(1070, 508, 1075, 523),
    color=(249, 182, 57),
    button=(1070, 508, 1075, 523),
    file="./assets/cn/meta_reward/META_REWARD_NOTICE.png",
)
REWARD_CHECK = Button(
    area=(31, 486, 64, 543),
    color=(199, 164, 165),
    button=(31, 486, 64, 543),
    file="./assets/cn/meta_reward/REWARD_CHECK.png",
)
REWARD_ENTER = Button(
    area=(1109, 535, 1187, 554),
    color=(199, 195, 201),
    button=(1109, 535, 1187, 554),
    file="./assets/cn/meta_reward/REWARD_ENTER.png",
)
REWARD_RECEIVE = Button(
    area=(1031, 601, 1215, 638),
    color=(149, 62, 62),
    button=(1031, 601, 1215, 638),
    file="./assets/cn/meta_reward/REWARD_RECEIVE.png",
)
SYNC_ENTER = Button(
    area=(866, 351, 944, 370),
    color=(185, 176, 179),
    button=(866, 351, 944, 370),
    file="./assets/cn/meta_reward/SYNC_ENTER.png",
)
SYNC_ENTER2 = Button(
    area=(866, 351, 943, 370),
    color=(132, 117, 119),
    button=(866, 351, 943, 370),
    file="./assets/cn/meta_reward/SYNC_ENTER2.png",
)
SYNC_REWARD_NOTICE = Button(
    area=(977, 337, 981, 352),
    color=(250, 182, 57),
    button=(977, 337, 981, 352),
    file="./assets/cn/meta_reward/SYNC_REWARD_NOTICE.png",
)
SYNC_TAP = Button(
    area=(581, 339, 707, 377),
    color=(168, 112, 111),
    button=(581, 339, 707, 377),
    file="./assets/cn/meta_reward/SYNC_TAP.png",
)
