from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

CAMPAIGN_BONUS = Button(
    area=(404, 149, 439, 166),
    color=(188, 195, 207),
    button=(404, 149, 439, 166),
    file="./assets/cn/statistics/CAMPAIGN_BONUS.png",
)
ENEMY_NAME = Button(
    area=(781, 283, 965, 322),
    color=(92, 102, 119),
    button=(781, 283, 965, 322),
    file="./assets/cn/statistics/ENEMY_NAME.png",
)
GET_ITEMS_ODD = Button(
    area=(628, 294, 653, 397),
    color=(98, 103, 121),
    button=(628, 294, 653, 397),
    file="./assets/cn/statistics/GET_ITEMS_ODD.png",
)
