from module.base.button import Button

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ASH_COLLECT_STATUS = Button(
    area=(640, 27, 720, 49),
    color=(82, 92, 99),
    button=(640, 27, 720, 49),
    file="./assets/cn/os_ash/ASH_COLLECT_STATUS.png",
)
ASH_DAILY_STATUS = Button(
    area=(637, 0, 741, 19),
    color=(104, 112, 121),
    button=(637, 0, 741, 19),
    file="./assets/cn/os_ash/ASH_DAILY_STATUS.png",
)
ASH_QUIT = Button(
    area=(29, 25, 59, 49),
    color=(115, 63, 68),
    button=(29, 25, 59, 49),
    file="./assets/cn/os_ash/ASH_QUIT.png",
)
ASH_SHOWDOWN = Button(
    area=(120, 14, 262, 38),
    color=(153, 131, 131),
    button=(120, 14, 262, 38),
    file="./assets/cn/os_ash/ASH_SHOWDOWN.png",
)
ASH_START = Button(
    area=(1061, 635, 1259, 695),
    color=(236, 187, 115),
    button=(1061, 635, 1259, 695),
    file="./assets/cn/os_ash/ASH_START.png",
)
BATTLE_STATUS = Button(
    area=(1051, 644, 1123, 675),
    color=(247, 199, 137),
    button=(1051, 644, 1123, 675),
    file="./assets/cn/os_ash/BATTLE_STATUS.png",
)
BEACON_EMPTY = Button(
    area=(535, 288, 647, 316),
    color=(126, 129, 134),
    button=(535, 288, 647, 316),
    file="./assets/cn/os_ash/BEACON_EMPTY.png",
)
BEACON_LIST = Button(
    area=(26, 649, 218, 703),
    color=(135, 105, 122),
    button=(26, 649, 218, 703),
    file="./assets/cn/os_ash/BEACON_LIST.gif",
)
BEACON_MY = Button(
    area=(25, 647, 218, 702),
    color=(106, 84, 86),
    button=(25, 647, 218, 702),
    file="./assets/cn/os_ash/BEACON_MY.png",
)
BEACON_NEXT = Button(
    area=(129, 369, 440, 439),
    color=(51, 52, 48),
    button=(129, 369, 440, 439),
    file="./assets/cn/os_ash/BEACON_NEXT.png",
)
BEACON_REMAIN = Button(
    area=(1014, 25, 1073, 48),
    color=(48, 51, 48),
    button=(1014, 25, 1073, 48),
    file="./assets/cn/os_ash/BEACON_REMAIN.png",
)
BEACON_REWARD = Button(
    area=(1051, 643, 1179, 674),
    color=(162, 196, 239),
    button=(1049, 640, 1239, 695),
    file="./assets/cn/os_ash/BEACON_REWARD.png",
)
BEACON_TIER = Button(
    area=(100, 562, 200, 637),
    color=(82, 83, 79),
    button=(100, 562, 200, 637),
    file="./assets/cn/os_ash/BEACON_TIER.png",
)
DOSSIER_LIST = Button(
    area=(22, 646, 221, 706),
    color=(116, 89, 77),
    button=(22, 646, 221, 706),
    file="./assets/cn/os_ash/DOSSIER_LIST.png",
)
HELP_1 = Button(
    area=(391, 270, 557, 439),
    color=(83, 95, 118),
    button=(391, 270, 557, 439),
    file="./assets/cn/os_ash/HELP_1.png",
)
HELP_2 = Button(
    area=(584, 270, 750, 439),
    color=(82, 95, 119),
    button=(584, 270, 750, 439),
    file="./assets/cn/os_ash/HELP_2.png",
)
HELP_3 = Button(
    area=(778, 271, 941, 438),
    color=(83, 96, 118),
    button=(778, 271, 941, 438),
    file="./assets/cn/os_ash/HELP_3.png",
)
HELP_CONFIRM = Button(
    area=(742, 500, 914, 557),
    color=(94, 143, 203),
    button=(742, 500, 914, 557),
    file="./assets/cn/os_ash/HELP_CONFIRM.png",
)
HELP_ENTER = Button(
    area=(894, 635, 1013, 699),
    color=(210, 130, 130),
    button=(894, 635, 1013, 699),
    file="./assets/cn/os_ash/HELP_ENTER.png",
)
META_AUTO_ATTACKING = Button(
    area=(746, 649, 778, 680),
    color=(111, 95, 93),
    button=(746, 649, 778, 680),
    file="./assets/cn/os_ash/META_AUTO_ATTACKING.png",
)
META_AUTO_ATTACK_CONFIRM = Button(
    area=(717, 493, 884, 547),
    color=(185, 98, 88),
    button=(717, 493, 884, 547),
    file="./assets/cn/os_ash/META_AUTO_ATTACK_CONFIRM.png",
)
META_AUTO_ATTACK_START = Button(
    area=(746, 648, 777, 683),
    color=(77, 63, 61),
    button=(746, 648, 777, 683),
    file="./assets/cn/os_ash/META_AUTO_ATTACK_START.png",
)
META_AUTO_CONFIRM = Button(
    area=(608, 506, 674, 535),
    color=(208, 148, 141),
    button=(608, 506, 674, 535),
    file="./assets/cn/os_ash/META_AUTO_CONFIRM.png",
)
META_BEACON_DATA = Button(
    area=(840, 22, 951, 45),
    color=(49, 53, 52),
    button=(840, 22, 951, 45),
    file="./assets/cn/os_ash/META_BEACON_DATA.png",
)
META_BEACON_FLAG = Button(
    area=(788, 22, 811, 45),
    color=(48, 111, 134),
    button=(788, 22, 811, 45),
    file="./assets/cn/os_ash/META_BEACON_FLAG.png",
)
META_BEGIN_ENTRANCE = Button(
    area=(651, 348, 706, 372),
    color=(99, 99, 98),
    button=(546, 115, 748, 503),
    file="./assets/cn/os_ash/META_BEGIN_ENTRANCE.png",
)
META_DAMAGE = Button(
    area=(1196, 380, 1276, 416),
    color=(58, 59, 58),
    button=(1196, 380, 1276, 416),
    file="./assets/cn/os_ash/META_DAMAGE.png",
)
META_DOSSIER_DATA = Button(
    area=(1050, 22, 1161, 46),
    color=(53, 56, 56),
    button=(1050, 22, 1161, 46),
    file="./assets/cn/os_ash/META_DOSSIER_DATA.png",
)
META_DOSSIER_FLAG = Button(
    area=(999, 22, 1022, 45),
    color=(123, 70, 44),
    button=(999, 22, 1022, 45),
    file="./assets/cn/os_ash/META_DOSSIER_FLAG.png",
)
META_ENTRANCE = Button(
    area=(578, 463, 623, 493),
    color=(106, 134, 169),
    button=(578, 463, 623, 493),
    file="./assets/cn/os_ash/META_ENTRANCE.png",
)
META_INNER_PAGE_DAMAGE = Button(
    area=(936, 105, 1029, 128),
    color=(148, 105, 105),
    button=(936, 105, 1029, 128),
    file="./assets/cn/os_ash/META_INNER_PAGE_DAMAGE.png",
)
META_INNER_PAGE_NOT_DAMAGE = Button(
    area=(936, 105, 1029, 128),
    color=(68, 71, 72),
    button=(936, 105, 1029, 128),
    file="./assets/cn/os_ash/META_INNER_PAGE_NOT_DAMAGE.png",
)
META_MAIN_BEACON_ENTRANCE = Button(
    area=(275, 162, 567, 557),
    color=(68, 56, 52),
    button=(275, 162, 567, 557),
    file="./assets/cn/os_ash/META_MAIN_BEACON_ENTRANCE.png",
)
META_MAIN_DOSSIER_ENTRANCE = Button(
    area=(900, 526, 925, 539),
    color=(203, 146, 117),
    button=(706, 163, 998, 557),
    file="./assets/cn/os_ash/META_MAIN_DOSSIER_ENTRANCE.png",
)
